{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-samples",
    "version": "1.2.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material-samples-1.2.0-beta01.aar",
          "url": "material-samples-1.2.0-beta01.aar",
          "size": 879814,
          "sha512": "3f1bf76434d648979b67a6eda121358a93132aad5da05eaa10d420586ad8f02f84b5f892a75aa083e37c5706523e5500c665e65507502bdb7d09604bde6c772e",
          "sha256": "baa865e8c93633e6893fff5f588fc27e62e53b40e691b6aced5088cb35a79583",
          "sha1": "13b1e5f2c3a41e7d1c396b6316182c87ac790b9e",
          "md5": "52b0981559b567c2be06458b5c3a1f52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "material-samples-1.2.0-beta01.aar",
          "url": "material-samples-1.2.0-beta01.aar",
          "size": 879814,
          "sha512": "3f1bf76434d648979b67a6eda121358a93132aad5da05eaa10d420586ad8f02f84b5f892a75aa083e37c5706523e5500c665e65507502bdb7d09604bde6c772e",
          "sha256": "baa865e8c93633e6893fff5f588fc27e62e53b40e691b6aced5088cb35a79583",
          "sha1": "13b1e5f2c3a41e7d1c396b6316182c87ac790b9e",
          "md5": "52b0981559b567c2be06458b5c3a1f52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-samples-1.2.0-beta01-sources.jar",
          "url": "material-samples-1.2.0-beta01-sources.jar",
          "size": 40770,
          "sha512": "03837fdceb2a60f54589e1092bb3cd99ceda297388fad48dd99485d1252464c7e163ca0c482304d1edc96c3ad6db77f9f161af6e77ec644dac73737dfe02e52b",
          "sha256": "36183ceb964f565c28f52ab73429314e177d19b14777bd40559a733f63e40634",
          "sha1": "908e3537dbc9267469a3d5d9c85d50b135f86b24",
          "md5": "0d72925a26371f46f73f3547e05e0556"
        }
      ]
    }
  ]
}