{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent-testing/1.0.0-alpha09/navigationevent-testing-1.0.0-alpha09.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent-testing",
    "version": "1.0.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14134477"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-testing-watchosArm32Main-1.0.0-alpha09.klib",
          "url": "navigationevent-testing-watchosarm32-1.0.0-alpha09.klib",
          "size": 19172,
          "sha512": "5d59509afc05074ab04349430ceaad901575ba269f7ec03ad6a7327ebd9f38428e6647dcc6dad177ecdd61be712e2735ed6a71da7bf30156350e1f02223868e2",
          "sha256": "c8246879b9f5a7eb49720e7d302a42ef7b148fb19d709b124b304265a547dd17",
          "sha1": "8b856808038463f0dcf30f4ee88ab098c8065710",
          "md5": "7a4745ca172a342f4342cc8f8292aad0"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-testing-watchosarm32-1.0.0-alpha09-sources.jar",
          "url": "navigationevent-testing-watchosarm32-1.0.0-alpha09-sources.jar",
          "size": 8239,
          "sha512": "af0752f291dcc732ce524e30957606b808501f27b9fb324bc37bdd27b7fe8507dc6b03a64fb93c80ca6686f4ac9adc79e1fb3b7c72b0558222d509874e394258",
          "sha256": "91dd00cdf90bf628aa0f2ee5b69a56d07ebb47ecf7d94ebb8861fbb94a9a34f1",
          "sha1": "dd137cdbcd9d0d3f76d9c7e988e8c99a2826b011",
          "md5": "a41c8701e4c9ba8bb4eeb638222b821c"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-testing-watchosarm32-1.0.0-alpha09-metadata.jar",
          "url": "navigationevent-testing-watchosarm32-1.0.0-alpha09-metadata.jar",
          "size": 4492,
          "sha512": "91283f18e42ae1010235d92f0e6ee6a3d75d042016bab6ce3f865a8d227b878f0f5cccd509fd548212ab38a8c6ef08b3a544842ef712e919509b2a0e8174f0f4",
          "sha256": "cc5823c9a2ad647bf1516894700150a96098b4829eb63879321ea325c2cfb1f9",
          "sha1": "fbb199e3028e86b256edc61d6c1b1c985d15c94d",
          "md5": "e464537f68712b5c60430de859958eb1"
        }
      ]
    }
  ]
}