{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-android-stubs",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-android-stubs-1.0.0.aar",
          "url": "ui-android-stubs-1.0.0.aar",
          "size": 4230,
          "sha512": "a05c87c840e57fc9cc251ea2d5959087ff9f30756d743390796dda20dcc05822ae1778738b4d6d2e481c3be64ff7baca973d4a5878ac1a6a781a230bbd27a23e",
          "sha256": "46e0e8429662990a09998aede92e0d9833fb7815e870707a2b789fac737d7858",
          "sha1": "3c99aa5a3fdaa55e00f62a64295297f47f810788",
          "md5": "536e19bfb7ee720fc130febfed917cf7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-android-stubs-1.0.0.aar",
          "url": "ui-android-stubs-1.0.0.aar",
          "size": 4230,
          "sha512": "a05c87c840e57fc9cc251ea2d5959087ff9f30756d743390796dda20dcc05822ae1778738b4d6d2e481c3be64ff7baca973d4a5878ac1a6a781a230bbd27a23e",
          "sha256": "46e0e8429662990a09998aede92e0d9833fb7815e870707a2b789fac737d7858",
          "sha1": "3c99aa5a3fdaa55e00f62a64295297f47f810788",
          "md5": "536e19bfb7ee720fc130febfed917cf7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-android-stubs-1.0.0-sources.jar",
          "url": "ui-android-stubs-1.0.0-sources.jar",
          "size": 2552,
          "sha512": "792d13ab946ea59400a50d6dac00e00baa0469d55a784014f287e66da600870ad5c3aa646176338143df81f0a1f0abcfc7ead039f62715db23df698b63e868f3",
          "sha256": "eda5dd0818f9c8c8b47ee0b512c611594d8c056b3cc7774b3ebd1edc4be477ac",
          "sha1": "764db175795d30d374c695bb03b6c2228131698e",
          "md5": "e5583ff53b021fc8ba7695cd46ecc75b"
        }
      ]
    }
  ]
}
