{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.4.0/collection-1.4.0.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection.klib",
          "url": "collection-macosarm64-1.4.0.klib",
          "size": 774561,
          "sha512": "921faa5da3846542a8198e081bb6b301fdaa30fd141160cd4f6a9dddb7b717a10a14b45c67e245ba3901884e437bfd7d358231939eae09a3e31362c6f9cc48b5",
          "sha256": "c230f3d00d9c3980a79b3bbe8bbb7f0fdac30fb79740feaaebfa5d2d270815d0",
          "sha1": "80c4e2ef088c08739643242e8053508a01974e19",
          "md5": "8b75451e3028a64f8ac5522992f7ef04"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-macosarm64-1.4.0-sources.jar",
          "url": "collection-macosarm64-1.4.0-sources.jar",
          "size": 227470,
          "sha512": "553cde9e639dc90a80d9734ba667196e2b1c3a1106a02c7264f05d6621ac1f4cff676d671246c5d95f66e05d61919a7355d218d60a195e5f3a4112cbb5dd9a67",
          "sha256": "70970198f2409eafc694482c8d20117d00c8758d3430140b92219bfe7a3f8d7f",
          "sha1": "302d6bdc80fe280f69b5b53e9316603d1876b475",
          "md5": "2f7ca82cb0c497d4dbb5d92e2f7405d8"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-macosarm64-1.4.0-metadata.jar",
          "url": "collection-macosarm64-1.4.0-metadata.jar",
          "size": 3792,
          "sha512": "da7cde9a50f1600dfa645777df6844f2caf692116c6c97868e04e7b96a3c85a1293aedb541616b586ae40d65bb78ce5d7841d66cabaed7f7b89ce2d5ec1d7c16",
          "sha256": "d1a4bc5f34b8c6e363bf91a7074eb53a0bf6f28d37bb092bbba2aae0e0c2fd9d",
          "sha1": "483d10483cb43984f76fcccb8522b2afedcbfcce",
          "md5": "7f5822425472bbea2d39cd881efe5cb4"
        }
      ]
    }
  ]
}