{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-ui-tooling",
    "version": "1.6.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14122922"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-ui-tooling-1.6.0-alpha02-sources.jar",
          "url": "compose-ui-tooling-1.6.0-alpha02-sources.jar",
          "size": 9835,
          "sha512": "284a6d3b611ff196b68c4b4eac614371f0311cdd5fa3ec2d44ff0aef2b456207a30827807cd445a5d607d52d38ecdcfd5f10f7cf1561b043ae8a2092120a1b62",
          "sha256": "3fc792c83ac831f56f80d4f26e093f17af60c60fbfc171107c88ccc3cd31ed3d",
          "sha1": "8b65cbe14d29ba5bf0af20a1fc3ee873579bc3d8",
          "md5": "cd869d1eecd199f16df401d6fc5bde07"
        },
        {
          "name": "compose-ui-tooling-1.6.0-alpha02-samples-sources.jar",
          "url": "compose-ui-tooling-1.6.0-alpha02-samples-sources.jar",
          "size": 36664,
          "sha512": "d3090f174fb4651d894de116bfed6d33403daa213ba4e3b84f9c5f34cf45da2943282f310554c1ed220a23b148b90405bf8b0b953d3002c5f0461db634ea2b51",
          "sha256": "b772c455c5b1bdffe8881919c77997e882b2099d8575f5115d3cdc11b5e7c965",
          "sha1": "69ad02e5948d82fc42fc5c722605a8968cdc703f",
          "md5": "0f8a359ebcc0f17737574d854b41d805"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-ui-tooling-1.6.0-alpha02.aar",
          "url": "compose-ui-tooling-1.6.0-alpha02.aar",
          "size": 9089,
          "sha512": "bb2c0f8c9efbd92459414ff880514269c1982c936048ea78babd125d3d914c2fc92da6fc1cd5d684716c6a5b5d5b6729bbf0b5bb86f7e05d37bd8cd00dd1838f",
          "sha256": "eb372fb0575d8516394533bb12d882d4415e6e9b89098f04bef8c3cc96d973eb",
          "sha1": "ccdbf0317c6c6ded967a8180e58c3d693f1dd55a",
          "md5": "f7a8a35f2a22b2cb9f81817cfffc366f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear-tooling-preview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-ui-tooling-1.6.0-alpha02.aar",
          "url": "compose-ui-tooling-1.6.0-alpha02.aar",
          "size": 9089,
          "sha512": "bb2c0f8c9efbd92459414ff880514269c1982c936048ea78babd125d3d914c2fc92da6fc1cd5d684716c6a5b5d5b6729bbf0b5bb86f7e05d37bd8cd00dd1838f",
          "sha256": "eb372fb0575d8516394533bb12d882d4415e6e9b89098f04bef8c3cc96d973eb",
          "sha1": "ccdbf0317c6c6ded967a8180e58c3d693f1dd55a",
          "md5": "f7a8a35f2a22b2cb9f81817cfffc366f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "compose-ui-tooling is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-ui-tooling-1.6.0-alpha02-versionMetadata.json",
          "url": "compose-ui-tooling-1.6.0-alpha02-versionMetadata.json",
          "size": 688,
          "sha512": "24719befd4ff645b21e7ff118d96c35d867f2c99e3de22e4bfd4ef0df154d54610d362b58165760860155bf925ab2e7295554efc26a2764f749ad8d6e0760124",
          "sha256": "4c5952e96a8c9576289a5a861c61a1b4a9491bc7310b11aaa86f5e96538038f3",
          "sha1": "a2433718f69d1b661ef83a1996e7ac134624b3df",
          "md5": "a55c64f947e23bfa9a8af0bead0af5e5"
        }
      ]
    }
  ]
}