{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-common/1.0.0-alpha01/material3-common-1.0.0-alpha01.module",
    "group": "androidx.compose.material3",
    "module": "material3-common",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13699310"
    }
  },
  "variants": [
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "material3-common-linuxx64StubsMain-1.0.0-alpha01.klib",
          "url": "material3-common-linuxx64stubs-1.0.0-alpha01.klib",
          "size": 64854,
          "sha512": "a3e99cb387c2f953606c3520984c229cf4ecb9462b44702ee7ca4abeee9cbf454a34fce256e063748dcd26b106c065145427d3e682ddeb1862c2580a4583de4f",
          "sha256": "2dd5c58d0a0e5e7101dc8d90c98d7ddcdf8245c33d9013ebadb1b61b46c8c4d4",
          "sha1": "1e8082af4588f51d740596d0de07f3f8689c598d",
          "md5": "630af379d01a8ed1f3d544376db292ae"
        }
      ]
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "material3-common-linuxx64stubs-1.0.0-alpha01-sources.jar",
          "url": "material3-common-linuxx64stubs-1.0.0-alpha01-sources.jar",
          "size": 18297,
          "sha512": "0d16d4740e99842144c7ded4dae9725b1391a69a75a05cf6a34c9e7a016d1bbc3db6ff14b3d29ce024336bd46b8362e1522f03079bc3c29d6f3bcc16c2d170d2",
          "sha256": "55869395b929719a53ea7e5f68ea668c0b6522236e1280540d654b124f6cab33",
          "sha1": "ea1002a1c4c8d0e29253da2ee6b526cb36d7e460",
          "md5": "5c57e4c1980515b67b797279eb75dab3"
        }
      ]
    }
  ]
}