{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-testing",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7276851"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "room-testing-2.3.0.aar",
          "url": "room-testing-2.3.0.aar",
          "size": 12182,
          "sha512": "f09447426c1124aed133f5ee001661dc2c0507cd71ea8e3902e409a57ca5492df4d288f9a9df9eb80e140995aa52864314374b130436f4f433084d1011373111",
          "sha256": "de9cfefb7046454714de33d5cd87d6416365d0b151a1c9ff886725b47ec1a9da",
          "sha1": "08eb65988682d56336a9354f755303b97044204c",
          "md5": "49f5864165c85b0267b4adb016b7d9f8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "room-testing-2.3.0.aar",
          "url": "room-testing-2.3.0.aar",
          "size": 12182,
          "sha512": "f09447426c1124aed133f5ee001661dc2c0507cd71ea8e3902e409a57ca5492df4d288f9a9df9eb80e140995aa52864314374b130436f4f433084d1011373111",
          "sha256": "de9cfefb7046454714de33d5cd87d6416365d0b151a1c9ff886725b47ec1a9da",
          "sha1": "08eb65988682d56336a9354f755303b97044204c",
          "md5": "49f5864165c85b0267b4adb016b7d9f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-testing-2.3.0-sources.jar",
          "url": "room-testing-2.3.0-sources.jar",
          "size": 6048,
          "sha512": "10a5560b3125217164040100487c13740fdcd582b6cc71c06c39ed688b19e22ab39ca83ace56bea230c54d909da429712b6c9210bff0b9a8bcbc8e1d130a558d",
          "sha256": "7d07c0892a965abe5c487b7bc60b2d1ae3ca9498b4381a5086cbe8598b804aee",
          "sha1": "ef0953091956b2a9b110ccd07b4dd77a6671a64c",
          "md5": "c409c8587684a0c30942882a5916bba8"
        }
      ]
    }
  ]
}
