{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-dynamic-features-runtime",
    "version": "2.5.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "core",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.5.0-rc02.aar",
          "url": "navigation-dynamic-features-runtime-2.5.0-rc02.aar",
          "size": 47496,
          "sha512": "fc6cda92a471d8bf2494a2b3604aca7c3d6de586523d8bca6252ca61c486943dcb98bbe974256787eab4c061fee74722028e04c42839ba68596335fb3f381d93",
          "sha256": "d09f239b7993043d93f32dca5bf12fde797171a7fc125c2cd0b5c1f8cf2b9d51",
          "sha1": "f10440ee9ca3c2b9905bb408321b28fa728f599e",
          "md5": "dd6698611563a865bcea6eb291a57ad2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.0-rc02"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "core",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.5.0-rc02.aar",
          "url": "navigation-dynamic-features-runtime-2.5.0-rc02.aar",
          "size": 47496,
          "sha512": "fc6cda92a471d8bf2494a2b3604aca7c3d6de586523d8bca6252ca61c486943dcb98bbe974256787eab4c061fee74722028e04c42839ba68596335fb3f381d93",
          "sha256": "d09f239b7993043d93f32dca5bf12fde797171a7fc125c2cd0b5c1f8cf2b9d51",
          "sha1": "f10440ee9ca3c2b9905bb408321b28fa728f599e",
          "md5": "dd6698611563a865bcea6eb291a57ad2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.5.0-rc02-sources.jar",
          "url": "navigation-dynamic-features-runtime-2.5.0-rc02-sources.jar",
          "size": 20078,
          "sha512": "ca6645107a63df90f94444f675e7b37ab9bf74a6634b58d3318a93b986fc702478a006cb8e079845372c81546148683f4c6b19fc21978d7f5224f69cd67eb4be",
          "sha256": "1e8d77af9e28d424a4eab29b7b93d5f2b32d54e60c845e9fd5edb4f1bcb3d31b",
          "sha1": "252c7ac65f7d5056f3a89e50f420148ee5c8b8c0",
          "md5": "33f044854cde21683953826a66d588f3"
        }
      ]
    }
  ]
}