{
  "formatVersion": "1.1",
  "component": {
    "url": "../../room-common/2.8.0/room-common-2.8.0.module",
    "group": "androidx.room",
    "module": "room-common",
    "version": "2.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14041852"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-tvosArm64Main-2.8.0.klib",
          "url": "room-common-tvosarm64-2.8.0.klib",
          "size": 79795,
          "sha512": "72efcf6478648b1a43eb1307702f3450b7e3440da09db9f2dd749a88ed83f6d9e5a43816de52b4fec5650c607eea85aaf4997a2cb006b7fe8b96952c6b23d2bc",
          "sha256": "db8d9327d08de3846e1f71d02834b4ad88a6d285edf629ac9c790acdf914a625",
          "sha1": "c118d12949ff0a0321f6ae32a141ff8deb038ee0",
          "md5": "92095c2fa1bf4de53de8c3003933f068"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-common-tvosarm64-2.8.0-sources.jar",
          "url": "room-common-tvosarm64-2.8.0-sources.jar",
          "size": 68824,
          "sha512": "948f934c6afbc8476a8025c14e035c6d1b7a07deda0444c42c717e7e506f867fea141d8a96c5e4ba525792c015b9735ccfcf9217e16a453ce7406b91f923aae3",
          "sha256": "ee211a93d3171ed950fe2a3a4f1baca7552bde2756b63f55ace49debc5f07bef",
          "sha1": "c197e6448c938e3bdc2ce1c7dce2be82a57f7ab3",
          "md5": "a055e0a810a20a6efa280fc00376bf85"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.0"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-tvosarm64-2.8.0-metadata.jar",
          "url": "room-common-tvosarm64-2.8.0-metadata.jar",
          "size": 4378,
          "sha512": "c177d50b7b6bbadf181993874026bb7a649b9e85e2590d0e3891b6443a5b5307734580dfe209e5fe4b3751795040714183994c9f94376189e30041a4f014ea32",
          "sha256": "50846f019b40e2fbd7ac96e5263459ff073049b7d909404f9bf798a2ac7bd672",
          "sha1": "27fbdf8b72bb7599559991da88f02407fd56df46",
          "md5": "3b9aaf682a0c435fe863790e88139056"
        }
      ]
    }
  ]
}