{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.3.0-alpha02.aar",
          "url": "recyclerview-1.3.0-alpha02.aar",
          "size": 401492,
          "sha512": "7fac42a895cb69c65738f7c5e8838187ddab645620491c3baf5f175f90d32b76c879ef2fbabec92a2d7f14acb40ee58c98af913f9213ae981354e1dcc8aa6019",
          "sha256": "bb8b0cac5ef9c99a6db6286e6643eb0cb22e46b61a895679c4f278095384c1e2",
          "sha1": "6b854c8ff11d2676c5dcdea88100417f7b84d380",
          "md5": "607562741458082837ceffc3b707742a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.3.0-alpha02.aar",
          "url": "recyclerview-1.3.0-alpha02.aar",
          "size": 401492,
          "sha512": "7fac42a895cb69c65738f7c5e8838187ddab645620491c3baf5f175f90d32b76c879ef2fbabec92a2d7f14acb40ee58c98af913f9213ae981354e1dcc8aa6019",
          "sha256": "bb8b0cac5ef9c99a6db6286e6643eb0cb22e46b61a895679c4f278095384c1e2",
          "sha1": "6b854c8ff11d2676c5dcdea88100417f7b84d380",
          "md5": "607562741458082837ceffc3b707742a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.3.0-alpha02-sources.jar",
          "url": "recyclerview-1.3.0-alpha02-sources.jar",
          "size": 324309,
          "sha512": "3f7c7864e11286d31e61a5da1550faf8eb3e21657c1c6e7a0ad260ca735fec75b1f4300505d0306cdb1aae5484bf5d6a952044c867f614d4d028bfd3a64ccf94",
          "sha256": "d3b4f9c17c3bb8428f5db7e80617f462b6a4959f80b0bd581a6882cfd13a28e4",
          "sha1": "a77dec232b359d38cfceeb2fe7c3c83fa8fdbdbe",
          "md5": "d4e565552d8951c90bddd9f17a1e5e48"
        }
      ]
    }
  ]
}