{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout-samples",
    "version": "1.1.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "foundation-layout-samples-1.1.0-rc01.aar",
          "url": "foundation-layout-samples-1.1.0-rc01.aar",
          "size": 112976,
          "sha512": "1705575bb4a7119303c63c9e48f1ad9268f6489cd8af1fe273232e90bc0a0f42debab957c52051d7658d9380c05df3fe268efe8c8e450533364d7905f71a992b",
          "sha256": "9343d6168d1e7bf0655b0077a04863baed6bae4c8edf45aef2efb80dcab63b2c",
          "sha1": "f8c294dd06b4da9bff0289d61600a527e8e0060f",
          "md5": "f809b3bba470c52e364ca7482e5639dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.1.0-rc01.aar",
          "url": "foundation-layout-samples-1.1.0-rc01.aar",
          "size": 112976,
          "sha512": "1705575bb4a7119303c63c9e48f1ad9268f6489cd8af1fe273232e90bc0a0f42debab957c52051d7658d9380c05df3fe268efe8c8e450533364d7905f71a992b",
          "sha256": "9343d6168d1e7bf0655b0077a04863baed6bae4c8edf45aef2efb80dcab63b2c",
          "sha1": "f8c294dd06b4da9bff0289d61600a527e8e0060f",
          "md5": "f809b3bba470c52e364ca7482e5639dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-layout-samples-1.1.0-rc01-sources.jar",
          "url": "foundation-layout-samples-1.1.0-rc01-sources.jar",
          "size": 14233,
          "sha512": "d1fbd2a3976eb4bfa9393a6a0ca09205c3d54388ca48405dc838bbaf31de4b563ee941f7267208ad3e66e7aefc843addc79ef58b99be8c2af4875f9b937d051e",
          "sha256": "cc405f3834ca191fef01b9d532bdef8581d588d868bad0ea246c3a65ab11753d",
          "sha1": "7f256935449991ed7f0115a376e460fbde15bac9",
          "md5": "14d808b1c5a43ae119d325681fb9a1c0"
        }
      ]
    }
  ]
}
