{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-style",
    "version": "1.2.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-style-1.2.0-beta02.aar",
          "url": "watchface-style-1.2.0-beta02.aar",
          "size": 195349,
          "sha512": "a8903097cc11ce31cefe5a703e626dd998aea13d756561e3214c4e5413b675749b3b57a6d00d737b74571155e5972546016a40db3338022ff02b20776a6e2ddc",
          "sha256": "f3af48aa030254dbccfca24341dcffb6e18086d9a3745c049562ca1748d9b794",
          "sha1": "2155f716f1d9d0ccc4d4f8ba221c40395f11fca4",
          "md5": "4de270fb7384c6a7f020ab7871a7ffcc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-style-1.2.0-beta02.aar",
          "url": "watchface-style-1.2.0-beta02.aar",
          "size": 195349,
          "sha512": "a8903097cc11ce31cefe5a703e626dd998aea13d756561e3214c4e5413b675749b3b57a6d00d737b74571155e5972546016a40db3338022ff02b20776a6e2ddc",
          "sha256": "f3af48aa030254dbccfca24341dcffb6e18086d9a3745c049562ca1748d9b794",
          "sha1": "2155f716f1d9d0ccc4d4f8ba221c40395f11fca4",
          "md5": "4de270fb7384c6a7f020ab7871a7ffcc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-style-1.2.0-beta02-sources.jar",
          "url": "watchface-style-1.2.0-beta02-sources.jar",
          "size": 31331,
          "sha512": "331056d73f366041c289e6eb96bb65c4ab0084dbf2e2b693a1ff1eb172ecd16db806cd8b2df7d5c8ca37fd6b3f6dd1d19db09d8cd91793542b21e5a8487d7e2d",
          "sha256": "6196df8832567c6b8712f35625e76ed4b4b811f5b09f8920164adb05fdeac23e",
          "sha1": "3597949bafab3f749bf41a9975637a5a3dd3db4e",
          "md5": "3b667f74bd1ec1a82e675f766085aa69"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-beta02"
          },
          "reason": "watchface-style is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-style-1.2.0-beta02-versionMetadata.json",
          "url": "watchface-style-1.2.0-beta02-versionMetadata.json",
          "size": 23012,
          "sha512": "9366fc2372fca51ec929c5f64df7fa9b7da53b533e4761b1072b1145700f32377453954a5311da5525b78c8599f5a61f9863e6a53efb0e64cc4888a07177eab3",
          "sha256": "b8fae8d60f1fcb4fcd83ffbd8e2718738b22c0df5f7b4a793f7642e6de324565",
          "sha1": "4c4a6ecb672802c6494d7951a7cf4f45f8bda46c",
          "md5": "792188bd8e52840b67285573eb31c77e"
        }
      ]
    }
  ]
}