{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive-layout/1.1.0-alpha02/adaptive-layout-1.1.0-alpha02.module",
    "group": "androidx.compose.material3.adaptive",
    "module": "adaptive-layout",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha02"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-alpha02"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-layout-release.aar",
          "url": "adaptive-layout-android-1.1.0-alpha02.aar",
          "size": 273860,
          "sha512": "061e9038e401596c99dc79d4c2063e66a31bf9b3a2ed7de3647e6487c1ce443689c9c9920a96375edc8bd80d93e0f2b0c5489152a3a7c20c3b49466c31976e63",
          "sha256": "a17161bfd246b64530637182b63bd0adcd10d834537778a34ba78c9d4443433b",
          "sha1": "254229d2418d3ee7276dcbe89ebaca441d634c7f",
          "md5": "230c4bc194e5450b5b68763d57c2de1e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha02"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha02"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-alpha02"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-layout-release.aar",
          "url": "adaptive-layout-android-1.1.0-alpha02.aar",
          "size": 273860,
          "sha512": "061e9038e401596c99dc79d4c2063e66a31bf9b3a2ed7de3647e6487c1ce443689c9c9920a96375edc8bd80d93e0f2b0c5489152a3a7c20c3b49466c31976e63",
          "sha256": "a17161bfd246b64530637182b63bd0adcd10d834537778a34ba78c9d4443433b",
          "sha1": "254229d2418d3ee7276dcbe89ebaca441d634c7f",
          "md5": "230c4bc194e5450b5b68763d57c2de1e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha02"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-alpha02"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-layout-1.1.0-alpha02-samples-sources.jar",
          "url": "adaptive-layout-android-1.1.0-alpha02-samples-sources.jar",
          "size": 8990,
          "sha512": "3295968fdbe8155c029330d3d567ea0f2c410c56dffd4a9a54926e26e868508569ee31dc11354235957a84f61249bc5080418cd5268cb65fa8049658e68c876e",
          "sha256": "0de5d01d202fa28b2440faa8028be031fd45fe24e94038ffcf50dbbb056d7554",
          "sha1": "8acfbeb27d1444fa37d9eb9c451775b164c6509a",
          "md5": "a1b09eec3c4644e02b225f5268dc2fa3"
        },
        {
          "name": "adaptive-layout-android-1.1.0-alpha02-sources.jar",
          "url": "adaptive-layout-android-1.1.0-alpha02-sources.jar",
          "size": 57233,
          "sha512": "e55cc0476bd325ab7d5c344f8939a1a8a9e363456394f18fc39b5929a46e066f239b00e8b98a9de04ee12ecb098ea363fce84de6452afd7be08fa5249c24e117",
          "sha256": "08983009b796c6cdc3acc22e8c830d136b61c4e599aba393811e75f112122037",
          "sha1": "c55a4de7eed99919b1c703e14b86e77bae134d45",
          "md5": "deda71648e2b337677d63e9943af8ade"
        }
      ]
    }
  ]
}