{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.8.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.8.0-alpha04.aar",
          "url": "activity-ktx-1.8.0-alpha04.aar",
          "size": 26423,
          "sha512": "f09e9cf17da46b98fa9f5e340ac9e0e0e4222779e52768a228fc599bd02ef3d71afc76f598b47c2bd7e28872af46f945ffecd035160b8eece619ad542ce2f72f",
          "sha256": "aa736d7287575ea3774b9401b083bf7254cc2d249a257903d632726ce7265cf3",
          "sha1": "1c7d06b4236312fc98c664594b56b4e1c300a361",
          "md5": "fc4bf6801e1cdc027e8d1bc535d1f901"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.8.0-alpha04.aar",
          "url": "activity-ktx-1.8.0-alpha04.aar",
          "size": 26423,
          "sha512": "f09e9cf17da46b98fa9f5e340ac9e0e0e4222779e52768a228fc599bd02ef3d71afc76f598b47c2bd7e28872af46f945ffecd035160b8eece619ad542ce2f72f",
          "sha256": "aa736d7287575ea3774b9401b083bf7254cc2d249a257903d632726ce7265cf3",
          "sha1": "1c7d06b4236312fc98c664594b56b4e1c300a361",
          "md5": "fc4bf6801e1cdc027e8d1bc535d1f901"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.8.0-alpha04-sources.jar",
          "url": "activity-ktx-1.8.0-alpha04-sources.jar",
          "size": 5873,
          "sha512": "bb4498b5dbf5e75607297db8d7f84719e31f0c72936a7b84865716df44ed16ce86d4a97891e41fbdcc8f26325468c9418ce1bbca722321e71805ecb82dbad898",
          "sha256": "83f9f1ba40e16ccb95308a52bb220351a7350a55a47a6a1d2c2df5fe947cbadb",
          "sha1": "1d3d2690e12555f90e977b470043ee92b69122f6",
          "md5": "2d9d2fe16dc709509cc4856d400c0ab0"
        }
      ]
    }
  ]
}