{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.4.aar",
          "url": "ui-1.0.4.aar",
          "size": 3838575,
          "sha512": "8f78cbb6efd7d16d5a24a6a957e5f7e90bd14720543bdac3e355ca5a601ecf7b49c024ee3eae8259592d052af71014e7e3e09589326cb382d714169583756be7",
          "sha256": "07b8db2265ffc7608a83766e346062b4ca56f0380a52238198d7798a8d4b2107",
          "sha1": "95e5ca88afdcf77950da600d722623d237dee199",
          "md5": "3fe98bd1c4a1e77add39da65e3e7cd99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.4.aar",
          "url": "ui-1.0.4.aar",
          "size": 3838575,
          "sha512": "8f78cbb6efd7d16d5a24a6a957e5f7e90bd14720543bdac3e355ca5a601ecf7b49c024ee3eae8259592d052af71014e7e3e09589326cb382d714169583756be7",
          "sha256": "07b8db2265ffc7608a83766e346062b4ca56f0380a52238198d7798a8d4b2107",
          "sha1": "95e5ca88afdcf77950da600d722623d237dee199",
          "md5": "3fe98bd1c4a1e77add39da65e3e7cd99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-1.0.4-sources.jar",
          "url": "ui-1.0.4-sources.jar",
          "size": 425905,
          "sha512": "4ee07bc3f0f16a48281dee3f3228dabedc1a87564c4ab5c426333174fc1b1bcd7371ddace8e98758083bf314e465aa1b1eb82d95a2d1b5d5942a778c39c294d4",
          "sha256": "cc9b2586ff30c98e2c114b27dd690aaaa6991a0c78dc807d09fcfb2ee6fcff2b",
          "sha1": "d4fb7a366b91a61db992d026fafc8f2b035fbead",
          "md5": "120459d3d0aec78a6e349398d6541e9b"
        }
      ]
    }
  ]
}
