{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core-okio/1.1.0-alpha01/datastore-core-okio-1.1.0-alpha01.module",
    "group": "androidx.datastore",
    "module": "datastore-core-okio",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.1.0-alpha01.jar",
          "url": "datastore-core-okio-jvm-1.1.0-alpha01.jar",
          "size": 26089,
          "sha512": "71cf3fcf38fbb3c25b2f89924457d809ffa70c3b942ea7065ee43a665feccd93ea9a9f2bdb47cce18470f350a0efb27b44958aa83c2be01254a12a112ef5f454",
          "sha256": "db02f0e0db6715309c76e4c711e40783bda4082680a2953a76bdbc3c832109e1",
          "sha1": "b83989100f2af401d3aef20f9b82273f17244d78",
          "md5": "cc53bc99a9080854bd06c34ef51ca6f9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.1.0-alpha01.jar",
          "url": "datastore-core-okio-jvm-1.1.0-alpha01.jar",
          "size": 26089,
          "sha512": "71cf3fcf38fbb3c25b2f89924457d809ffa70c3b942ea7065ee43a665feccd93ea9a9f2bdb47cce18470f350a0efb27b44958aa83c2be01254a12a112ef5f454",
          "sha256": "db02f0e0db6715309c76e4c711e40783bda4082680a2953a76bdbc3c832109e1",
          "sha1": "b83989100f2af401d3aef20f9b82273f17244d78",
          "md5": "cc53bc99a9080854bd06c34ef51ca6f9"
        }
      ]
    }
  ]
}