{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.health.connect",
    "module": "connect-client-samples",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "connect-client-samples-1.0.0-alpha08.aar",
          "url": "connect-client-samples-1.0.0-alpha08.aar",
          "size": 22078,
          "sha512": "ec79e5059917fcd9fd5661c1eb84d68bf00101be49dc968a9cbba86c61b1ed7e95559baea8aef5c27df4c99a659aafccd48292953ae28c7ac446c2d478550603",
          "sha256": "6d370c0dd070bae53809cbe4bb37bb57e8130fea331980874f5a76189afb59b9",
          "sha1": "6b01bbe75b2783cca64a2ff0d4e5fe65f2780112",
          "md5": "725924512388ceb9983f697fa2b77dc3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0-rc01"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "connect-client-samples-1.0.0-alpha08.aar",
          "url": "connect-client-samples-1.0.0-alpha08.aar",
          "size": 22078,
          "sha512": "ec79e5059917fcd9fd5661c1eb84d68bf00101be49dc968a9cbba86c61b1ed7e95559baea8aef5c27df4c99a659aafccd48292953ae28c7ac446c2d478550603",
          "sha256": "6d370c0dd070bae53809cbe4bb37bb57e8130fea331980874f5a76189afb59b9",
          "sha1": "6b01bbe75b2783cca64a2ff0d4e5fe65f2780112",
          "md5": "725924512388ceb9983f697fa2b77dc3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "connect-client-samples-1.0.0-alpha08-sources.jar",
          "url": "connect-client-samples-1.0.0-alpha08-sources.jar",
          "size": 7309,
          "sha512": "e9d3fd9f6ec09552f899f3d0367d7944be62aada03d80ebc6f1721a4d2cf114fce0665327fdb9f27a9821a1f8b06d9c7f535ac33c2ee0737ee9c2084416978f3",
          "sha256": "70c91cccb413883a32c04b882fc717f4aea3f6f6327e3fbbb878a68b29fe1f86",
          "sha1": "ffd7c8dd85bc46b05e2e6c190a42854bd7f41f5a",
          "md5": "2ed68d6f4fdf094e453bb549bb5fba64"
        }
      ]
    }
  ]
}