{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials.providerevents",
    "module": "providerevents",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14278171"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials.providerevents",
          "module": "providerevents-play-services",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "providerevents is in atomic group androidx.credentials.providerevents"
        }
      ],
      "files": [
        {
          "name": "providerevents-1.0.0-alpha03-sources.jar",
          "url": "providerevents-1.0.0-alpha03-sources.jar",
          "size": 91996,
          "sha512": "8dcd2007fdd911ed3e18839e844cc33cb7d6268dd4a3eba80e26b1ad3b6308c0256b73dd23c4f2cbd443ca7aea44f14ad33f5f248aba51b5a9ae0fc4b81165fd",
          "sha256": "6dd05d9662cf985b2cf66a8166f403d74154aa764878cd2108e65d5a92a4af3f",
          "sha1": "e285e462533addfacdd44c7fe5ffeb287e3aa11c",
          "md5": "9d804622bc598c77a145381c357fee88"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials.providerevents",
          "module": "providerevents-play-services",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "providerevents is in atomic group androidx.credentials.providerevents"
        }
      ],
      "files": [
        {
          "name": "providerevents-1.0.0-alpha03.aar",
          "url": "providerevents-1.0.0-alpha03.aar",
          "size": 134782,
          "sha512": "8d5602564a3c7d5bd5fb6539300ca2c12be88ce6fcd498133621f6b276484489b3f60892f90e15bb0c5097089e51db67a0c3d499025a66438c5a259ffc44aa16",
          "sha256": "8cf496cd9cb4875062b39862cb6fb923ee06f0051655b484dce19878409e7d2c",
          "sha1": "18a07fe27bfc0792da3997d510e3ad0691183acf",
          "md5": "cc2e2a41f64120dc6695d129a5472f5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0-beta03"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "rules",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials.providerevents",
          "module": "providerevents-play-services",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "providerevents is in atomic group androidx.credentials.providerevents"
        }
      ],
      "files": [
        {
          "name": "providerevents-1.0.0-alpha03.aar",
          "url": "providerevents-1.0.0-alpha03.aar",
          "size": 134782,
          "sha512": "8d5602564a3c7d5bd5fb6539300ca2c12be88ce6fcd498133621f6b276484489b3f60892f90e15bb0c5097089e51db67a0c3d499025a66438c5a259ffc44aa16",
          "sha256": "8cf496cd9cb4875062b39862cb6fb923ee06f0051655b484dce19878409e7d2c",
          "sha1": "18a07fe27bfc0792da3997d510e3ad0691183acf",
          "md5": "cc2e2a41f64120dc6695d129a5472f5b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials.providerevents",
          "module": "providerevents-play-services",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "providerevents is in atomic group androidx.credentials.providerevents"
        }
      ],
      "files": [
        {
          "name": "providerevents-1.0.0-alpha03-versionMetadata.json",
          "url": "providerevents-1.0.0-alpha03-versionMetadata.json",
          "size": 24476,
          "sha512": "3116e082216d026f27b4395f37acbf2e5274b421ef7c21f25be5da18f6aaf488dd749ea62f294ba9a9cab1f16c7c76494dbc0528ea67eb7b77c8c8dd3cccd4ae",
          "sha256": "8e95a53b87a92f12527f67a0116e4a46d916efe10b93822e780d8f935e94bcab",
          "sha1": "0d012d12733e27fe338a62a7cbf4712f1093fe29",
          "md5": "8cb5927d3779e8615fea13b8cd8765fb"
        }
      ]
    }
  ]
}