{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-test-accessibility/1.10.0-beta01/ui-test-accessibility-1.10.0-beta01.module",
    "group": "androidx.compose.ui",
    "module": "ui-test-accessibility",
    "version": "1.10.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14298655"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "com.google.android.apps.common.testing.accessibility.framework",
          "module": "accessibility-test-framework",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-accessibility.aar",
          "url": "ui-test-accessibility-android-1.10.0-beta01.aar",
          "size": 7983,
          "sha512": "37a1ca184029b7b6243b91446c9c7c1b5c7a130168ceb0cbf0d5d661c4b21e6021f36ce5b7d68a64be3c8f5a97ca380caefddb9f41b74f145c194bd6b8ec5379",
          "sha256": "32bf804871c5e825476f38235d111d2ce7e4903f3c054097e4a943fef15c9784",
          "sha1": "f24498a01097427d2713da0d82d444e1021aa391",
          "md5": "0212058e530995ee8237bb2a35ec5e25"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-beta01"
          }
        },
        {
          "group": "com.google.android.apps.common.testing.accessibility.framework",
          "module": "accessibility-test-framework",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-accessibility.aar",
          "url": "ui-test-accessibility-android-1.10.0-beta01.aar",
          "size": 7983,
          "sha512": "37a1ca184029b7b6243b91446c9c7c1b5c7a130168ceb0cbf0d5d661c4b21e6021f36ce5b7d68a64be3c8f5a97ca380caefddb9f41b74f145c194bd6b8ec5379",
          "sha256": "32bf804871c5e825476f38235d111d2ce7e4903f3c054097e4a943fef15c9784",
          "sha1": "f24498a01097427d2713da0d82d444e1021aa391",
          "md5": "0212058e530995ee8237bb2a35ec5e25"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "ui-test-accessibility is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-accessibility-android-1.10.0-beta01-sources.jar",
          "url": "ui-test-accessibility-android-1.10.0-beta01-sources.jar",
          "size": 6809,
          "sha512": "13c210a034a3c0fca852327f35e03bcdc07614f95a2d377ce462bcbad4ebe2c30cb62e9e8ca62485ba9c9b475e2f7b46f6126003c1c8b5652f2808244cb9190c",
          "sha256": "daafe3fb33e5a85b1f212534e382c472225ba3cdd3c2f4779d7c372de187a159",
          "sha1": "d2a9c214e72f22076b3e18125bc743afb65922a9",
          "md5": "b56166db3c472a174393441621ade16f"
        },
        {
          "name": "ui-test-accessibility-1.10.0-beta01-samples-sources.jar",
          "url": "ui-test-accessibility-android-1.10.0-beta01-samples-sources.jar",
          "size": 6758,
          "sha512": "923fbf70e766f029ccdafc1abaf2e8bb706dd1a9874280a529dc51f88398a4925a7a083eaf3f245f38a592a70edfe2e7b3f4aeecbbb989e09860863e72989bcf",
          "sha256": "cc6b9da33f34ad7b1992d5fa30db2fa56eb4736215906b684daea05fd0b682b4",
          "sha1": "a67685163fc7468bc0a180dc943cb0c3966225cc",
          "md5": "7eec8bccec0bb28bee2ec3c45a21d357"
        }
      ]
    }
  ]
}