{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-runtime/2.9.1/lifecycle-runtime-2.9.1.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime",
    "version": "2.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13557335"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-iosArm64Main-2.9.1.klib",
          "url": "lifecycle-runtime-iosarm64-2.9.1.klib",
          "size": 41843,
          "sha512": "1786acb88bb12280224961c80857003e628638d0cb9a3224c9abaf94d7c6029a633d6c0c7634e5ccc3d150b34c261401643eb8ff074fb8d840495ecca4824cac",
          "sha256": "fe20c9ed0e5d35fc895e879632f9b472782bd36d9f5161c1066ab3988fdd3e1d",
          "sha1": "cdd2649ce7ad90b1036084aaf46054f1ae896174",
          "md5": "7011de28bb7e30340b98b83b49ee7bac"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-iosarm64-2.9.1-sources.jar",
          "url": "lifecycle-runtime-iosarm64-2.9.1-sources.jar",
          "size": 20367,
          "sha512": "547fbf6ecd73cd64d96909c1bc605f589d6a2df01118c8322502b1470dbc1aa033229156fd45b017fe00e7077788b0e09a085831e593d7a5709753639dfa3f9b",
          "sha256": "5483e87ba3a8141f2ce63ecf89504a8dcc966fa59f97671561dc3de0980cd844",
          "sha1": "e94e230e9c63c48adcf7f009975acce0420774ca",
          "md5": "e9572a336e1a2839f4befa01091bc9d2"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.1"
          },
          "reason": "lifecycle-runtime is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-iosarm64-2.9.1-metadata.jar",
          "url": "lifecycle-runtime-iosarm64-2.9.1-metadata.jar",
          "size": 4432,
          "sha512": "519a83a736f0824c5a73df3598a6885244e3504973256c172762d9b9056468f2a9753356f56a096f97f03c564c2984e98abf964d82520d5e99c9edc58c981296",
          "sha256": "424f7d6e3e2e3fc3f8b45e07ede1e9a44f90dcfb8b88cd9dabd89d30665216e7",
          "sha1": "3504b894a82bf3ecb1ff47e5876d5662e21eee08",
          "md5": "36d1e0b75b809fdee9975b908c57bc0f"
        }
      ]
    }
  ]
}