{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.12.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14134477"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha09"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.0-alpha09"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.12.0-alpha09-sources.jar",
          "url": "activity-compose-1.12.0-alpha09-sources.jar",
          "size": 16845,
          "sha512": "6096f0cc90b4f409f6def5ceb2627e234b7271511ea81e37a939393c9ae5bddf54da43bd1695f006f3a191f3558ab01a80ea5b1fcea98486c34384fde6cf9aa2",
          "sha256": "fd0d35164272f1c45a56d93a7e17168003c130bf2a0e18b1d95d77feadee40bd",
          "sha1": "083c18d50b0699f32026ee19451f32f7288d649a",
          "md5": "41e4744c056266a91c4c0cd66080405d"
        },
        {
          "name": "activity-compose-1.12.0-alpha09-samples-sources.jar",
          "url": "activity-compose-1.12.0-alpha09-samples-sources.jar",
          "size": 7851,
          "sha512": "9a989c99452f247373f0dd6350ad8f0feb2ff47d438df2c24a85340a5cca7ee3385fe7254c0ef621133e5e746e13c4796e2853b884c868cd2b142abd730afd8b",
          "sha256": "95289ac1dcb6073b439d440fe43935ad8e4a513a5511b66a647e678142dd45f0",
          "sha1": "09d83336b437e0d661e0925d0e84383bb9c19f65",
          "md5": "04d92c9bd78b5f89b85bed0e36326e08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha09"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha09"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.0-alpha09"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.12.0-alpha09.aar",
          "url": "activity-compose-1.12.0-alpha09.aar",
          "size": 1082886,
          "sha512": "8f446f3ba526f17c9b41251329a64b22671d0c52d3b1c4be29a17e80c51b0b3b5adff4f1734333209c35fdf91136ce1598524d5bcb37caa858877573cef128b1",
          "sha256": "75c040306ae1cef865a4f43a576f09903aee0b9ca67a8b9ffb5aff6fe74d30f6",
          "sha1": "b76a87acdea199229da1b7ab6d76a60ca6e20980",
          "md5": "81952cfba755d1376f16f5db9847880b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha09"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha09"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.0-alpha09"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.12.0-alpha09.aar",
          "url": "activity-compose-1.12.0-alpha09.aar",
          "size": 1082886,
          "sha512": "8f446f3ba526f17c9b41251329a64b22671d0c52d3b1c4be29a17e80c51b0b3b5adff4f1734333209c35fdf91136ce1598524d5bcb37caa858877573cef128b1",
          "sha256": "75c040306ae1cef865a4f43a576f09903aee0b9ca67a8b9ffb5aff6fe74d30f6",
          "sha1": "b76a87acdea199229da1b7ab6d76a60ca6e20980",
          "md5": "81952cfba755d1376f16f5db9847880b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha09"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.0-alpha09"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.12.0-alpha09-versionMetadata.json",
          "url": "activity-compose-1.12.0-alpha09-versionMetadata.json",
          "size": 4988,
          "sha512": "882aedff7a434a45cb7ba13f3830fb239bec5cbd4a867ff2bc8bb91cd7f62192c875b9dfe096f11100ab4ebc2abeffb0925c16bc7162d15a1a28d1ea6dd87f66",
          "sha256": "414941304bf307e6ada955a3dcf41ec5328b9727c8c7c7f141052587c10c028e",
          "sha1": "f3b6c81bee360f2895c70c2d39d82ec928f1caea",
          "md5": "aad2a5422a5fb6ac6e7d847ea6db4f92"
        }
      ]
    }
  ]
}