{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-rxjava2",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-rxjava2-3.3.2.aar",
          "url": "paging-rxjava2-3.3.2.aar",
          "size": 37093,
          "sha512": "f1370c9b0845b7d310672ea4dee420b8bf57cd0778226c5c6d86f3408e541311d3b99cf557354399c9ec7d25b96973b9569f0079aa32c4728abd79951c862605",
          "sha256": "70252cfe944a9f7c641a4c6eb275af984c0b3dd88aac072d8256cfa2211a5d74",
          "sha1": "0dca8018deca019bdebc18e2068aa4db5faa12f8",
          "md5": "b43f42ca2224942ff13c8fdcedad3fab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.2"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-rxjava2-3.3.2.aar",
          "url": "paging-rxjava2-3.3.2.aar",
          "size": 37093,
          "sha512": "f1370c9b0845b7d310672ea4dee420b8bf57cd0778226c5c6d86f3408e541311d3b99cf557354399c9ec7d25b96973b9569f0079aa32c4728abd79951c862605",
          "sha256": "70252cfe944a9f7c641a4c6eb275af984c0b3dd88aac072d8256cfa2211a5d74",
          "sha1": "0dca8018deca019bdebc18e2068aa4db5faa12f8",
          "md5": "b43f42ca2224942ff13c8fdcedad3fab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-rxjava2-3.3.2-sources.jar",
          "url": "paging-rxjava2-3.3.2-sources.jar",
          "size": 12924,
          "sha512": "317c7c490d958f24ce485c316aed5814bfd6c3c08614151787850b515d2f7be60583f6f356fe0b5e27716c9562d55925d59c8294807087e93bf65a3ab5455b9c",
          "sha256": "5acd2a9b03d124f557d4b59e6cc6856dad2ca70ad0d2ee2ebefcb67045273924",
          "sha1": "995a8f575748a91536429ca1b8183b23c8478a1f",
          "md5": "7020d3bcfa1a7f209657af4bea1f3fd8"
        },
        {
          "name": "paging-rxjava2-3.3.2-samples-sources.jar",
          "url": "paging-rxjava2-3.3.2-samples-sources.jar",
          "size": 40591,
          "sha512": "cbdd887c89003f6b02e6d351773c1559a0dbef7b10cbe911b23cca6356a342b14e594999a9760eee35148e941d87f9005d86db0f299f9a5c4c5201f2e6219625",
          "sha256": "e38a380af1a161410207cb358cb5fcf1ec844432d92a5c9a741524a4767ef970",
          "sha1": "a577b372155d466531746351cd9d1dfb4812d0d5",
          "md5": "6a209d35769c6bb11bbca1bcbcd5b8ad"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.2"
          },
          "reason": "paging-rxjava2 is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-rxjava2-3.3.2-versionMetadata.json",
          "url": "paging-rxjava2-3.3.2-versionMetadata.json",
          "size": 5834,
          "sha512": "25053f301f47c1d95df1401c13214b692adb747333d6c8349d100ebcfc8b4a8ae9beb9506e51c00658d2fcd2b776c27d70cc6924ddecdc4d78ec381d3465a9fe",
          "sha256": "8884bb82c8b05529941e23798e543fb7ba0a6c687c5c42d78eb2443bcf812313",
          "sha1": "ea9a68c75b7c1ad5c99e297134f2ab48d08a790b",
          "md5": "9f9ecb75edb6cf3e7edd63d537e72235"
        }
      ]
    }
  ]
}