{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-testing",
    "version": "1.13.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-testing-1.13.0-alpha01.aar",
          "url": "core-testing-1.13.0-alpha01.aar",
          "size": 3829,
          "sha512": "cffd5ff44bd6490e2deefda5432e6284bb99cf27aa6b861e4287fee612cf7222b283e1131834593bb8089d63d51dc24a7dc748d4936e79b80f92f8d6099e8683",
          "sha256": "e1d8de770ad81a550bedea4906be905b7d5cdc41534a17dbc3e568e8d60b8981",
          "sha1": "b92e4c73f73d09fef4919a62193465a3a84c64db",
          "md5": "50ff77b2806d89f2ccf30f269a4c626b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-testing-1.13.0-alpha01.aar",
          "url": "core-testing-1.13.0-alpha01.aar",
          "size": 3829,
          "sha512": "cffd5ff44bd6490e2deefda5432e6284bb99cf27aa6b861e4287fee612cf7222b283e1131834593bb8089d63d51dc24a7dc748d4936e79b80f92f8d6099e8683",
          "sha256": "e1d8de770ad81a550bedea4906be905b7d5cdc41534a17dbc3e568e8d60b8981",
          "sha1": "b92e4c73f73d09fef4919a62193465a3a84c64db",
          "md5": "50ff77b2806d89f2ccf30f269a4c626b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-testing-1.13.0-alpha01-sources.jar",
          "url": "core-testing-1.13.0-alpha01-sources.jar",
          "size": 1761,
          "sha512": "122c34ef92d4be822e60cb1a9aa95f3bdaf96390114750c147e48a0dc85c9edba7ece31234b67fa8582df35f4686f8afd707a1f4f52c2412c5bbfe370d7cc77c",
          "sha256": "eecd1df4942bdd46bc3e5fe0246b6e320a24bf4e3478040cefb867cfddf27271",
          "sha1": "b3e85fe9c3221df242e3ed1117bd74a387453413",
          "md5": "48ff55a248d4b0d25ac16742ff16b1f4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-testing-1.13.0-alpha01-versionMetadata.json",
          "url": "core-testing-1.13.0-alpha01-versionMetadata.json",
          "size": 259,
          "sha512": "772ac310a85a3a2ea497bedba01209997e7462a8186f9189c715115d4747381bbe21def613f3d7db1e26277ff17b01b26a1271ab4f975661479d71e608172af2",
          "sha256": "3ec0967f9b4ca4bf319450ee16c9b0ac4782c9e9c40c6a019714c4d9e9e3c280",
          "sha1": "e40073082cdff30ec1c846bdb5133e8828e66705",
          "md5": "d378661ee88517b578aa919c986c8625"
        }
      ]
    }
  ]
}