{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-1.0.0-rc02.aar",
          "url": "ui-test-1.0.0-rc02.aar",
          "size": 197894,
          "sha512": "0b9d4437f8abe9807c267e597c7a17d4c9074fc10db9486d06e9b9c48a939bd193bb20da9768cde8bfb3a433b76ea9b90a3adf351a5c27ce685e4030dc9eecdb",
          "sha256": "cd855fcd183ea5038367771f0c090cf132962ab58887d5a1568c70c54cc2e3ca",
          "sha1": "0307ffba9c01ca26aef86ef8186fd9e44ca0d1ed",
          "md5": "aab31e8a347d26cf5d3d534913846389"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-rc02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-1.0.0-rc02.aar",
          "url": "ui-test-1.0.0-rc02.aar",
          "size": 197894,
          "sha512": "0b9d4437f8abe9807c267e597c7a17d4c9074fc10db9486d06e9b9c48a939bd193bb20da9768cde8bfb3a433b76ea9b90a3adf351a5c27ce685e4030dc9eecdb",
          "sha256": "cd855fcd183ea5038367771f0c090cf132962ab58887d5a1568c70c54cc2e3ca",
          "sha1": "0307ffba9c01ca26aef86ef8186fd9e44ca0d1ed",
          "md5": "aab31e8a347d26cf5d3d534913846389"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-1.0.0-rc02-sources.jar",
          "url": "ui-test-1.0.0-rc02-sources.jar",
          "size": 60320,
          "sha512": "e9a825cb3075d1a0b907a7b4d45bf999e0902dc711c4159543ed8225cc3930f4bdd8d75a82a6ebb06eb3f376de45a5c0d1309ec2e700c69fe9f68a4d4f1c036e",
          "sha256": "6b257b3885911a0ad1f248e5b17094794ad3f8a7cb381bbf98eeadaacd366d09",
          "sha1": "a1d0dfdbffcb39c75cb7857b119d12a9315455ea",
          "md5": "5679e1657e48ce1dbdd4fa70433f1d80"
        }
      ]
    }
  ]
}
