{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-java",
    "version": "1.4.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.4.0-alpha04-sources.jar",
          "url": "window-java-1.4.0-alpha04-sources.jar",
          "size": 13535,
          "sha512": "313318200fe09b9c5a5e251d4a56eec43ebac06df476b773019c68a410b9007341f3844d6767cc6e379063971d90eb31179bce84f5a5ab7d28430c9631f84a71",
          "sha256": "a7b11bd9bdd34ddb2ef4a8ee46825f55c39b9f1ccdffc5bc4576f64408771227",
          "sha1": "b0b550475920026e390fa67fffb35f0655c9d826",
          "md5": "f25566260460e05aa8e6f12328d9b149"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.4.0-alpha04.aar",
          "url": "window-java-1.4.0-alpha04.aar",
          "size": 18034,
          "sha512": "52dd85f8e8f3b82b73169f2fc5744474068f912822201e0778a2580aae56c027dc1c54ce4e94a7d0bf8ba296af5808e0cd8e57816f82d7f9615e45650dbe249c",
          "sha256": "8502faaa0c76b0b95067a3ed97b431da7230c1ec7658e08dc30a747f74d9961e",
          "sha1": "261e3d0999f38c986daff06b90d9496016df13c8",
          "md5": "05250fd187643d8da371f753437ff5b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.4.0-alpha04.aar",
          "url": "window-java-1.4.0-alpha04.aar",
          "size": 18034,
          "sha512": "52dd85f8e8f3b82b73169f2fc5744474068f912822201e0778a2580aae56c027dc1c54ce4e94a7d0bf8ba296af5808e0cd8e57816f82d7f9615e45650dbe249c",
          "sha256": "8502faaa0c76b0b95067a3ed97b431da7230c1ec7658e08dc30a747f74d9961e",
          "sha1": "261e3d0999f38c986daff06b90d9496016df13c8",
          "md5": "05250fd187643d8da371f753437ff5b2"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.4.0-alpha04-versionMetadata.json",
          "url": "window-java-1.4.0-alpha04-versionMetadata.json",
          "size": 3437,
          "sha512": "bfe7f2f6c0437c509cfaf271fb928793e25030289a73bdaa663cfa966bb9293e40c39968d85c08d2a61edd69cc0ee03ff5a2b953d10a125428b88f7bc6e27af7",
          "sha256": "aae68ae9cda7c31570f78b6723b1487876f94b0cca51109d8731120668f2c458",
          "sha1": "edc71911b5c8809c704d3a80d318c87d491b9ca2",
          "md5": "9e8544daa49761664db967eb5fc8c23b"
        }
      ]
    }
  ]
}