{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.1.0-alpha04.jar",
          "url": "paging-common-3.1.0-alpha04.jar",
          "size": 697441,
          "sha512": "2004db4e6d991f8ef86514076fa35a1fb70ecc865efcacc4bae68599c00196a352dc5c640b91d63d1559b9e5a41624c7be1ae14ddbf12ec95e62c9f025a11a58",
          "sha256": "09219cb1f293355e9ad45b2fff38344c5c2285a88a7195a67e2644b4d91beffb",
          "sha1": "5ca3dc585f0aff238ac4a6665942ced4c7c5ea5c",
          "md5": "37a347c972ee37daa1fa8d358849d2b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.1.0-alpha04.jar",
          "url": "paging-common-3.1.0-alpha04.jar",
          "size": 697441,
          "sha512": "2004db4e6d991f8ef86514076fa35a1fb70ecc865efcacc4bae68599c00196a352dc5c640b91d63d1559b9e5a41624c7be1ae14ddbf12ec95e62c9f025a11a58",
          "sha256": "09219cb1f293355e9ad45b2fff38344c5c2285a88a7195a67e2644b4d91beffb",
          "sha1": "5ca3dc585f0aff238ac4a6665942ced4c7c5ea5c",
          "md5": "37a347c972ee37daa1fa8d358849d2b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-common-3.1.0-alpha04-sources.jar",
          "url": "paging-common-3.1.0-alpha04-sources.jar",
          "size": 139799,
          "sha512": "e9390e842f5a1c76f83f5df506a4c0e5177d304dfe8e22044d8b89a48a3ad3de7cab85f02c30fb1a7de8bb66f8bf95f53a8ea4d4217d733086fd2663e3551407",
          "sha256": "21c5b0dfb6d9007dcdcb2c534ff5711bdfeb57610f9bd02d76ed0cb690550ac5",
          "sha1": "eddb01f48b688d14b2d190ef992919d0d2079970",
          "md5": "595f675acf66c39588d8d678d44ed6a5"
        }
      ]
    }
  ]
}
