{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ink-authoring-compose/1.0.0-beta01/ink-authoring-compose-1.0.0-beta01.module",
    "group": "androidx.ink",
    "module": "ink-authoring-compose",
    "version": "1.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14278171"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-authoring-compose.aar",
          "url": "ink-authoring-compose-android-1.0.0-beta01.aar",
          "size": 34131,
          "sha512": "15c833e29381d9ffee90750a91c08d1cadd6495bd7f8e9013e543a6b0422a338d35fbfe1fd37ff5d0beef3f11d2cbdf58a0b23b863253b5a1dea425b3cd1b0a6",
          "sha256": "4e37a1db5e5a9a0793d8b7b11551ae928ae5b83bf8fc8088f9de61fbd8811e12",
          "sha1": "1de84aaa6cd50c0e6711b369abead946d64a2601",
          "md5": "a13c75bdd30ae921b41eac179928663c"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.input",
          "module": "input-motionprediction",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-authoring-compose.aar",
          "url": "ink-authoring-compose-android-1.0.0-beta01.aar",
          "size": 34131,
          "sha512": "15c833e29381d9ffee90750a91c08d1cadd6495bd7f8e9013e543a6b0422a338d35fbfe1fd37ff5d0beef3f11d2cbdf58a0b23b863253b5a1dea425b3cd1b0a6",
          "sha256": "4e37a1db5e5a9a0793d8b7b11551ae928ae5b83bf8fc8088f9de61fbd8811e12",
          "sha1": "1de84aaa6cd50c0e6711b369abead946d64a2601",
          "md5": "a13c75bdd30ae921b41eac179928663c"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "ink-authoring-compose is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-authoring-compose-android-1.0.0-beta01-sources.jar",
          "url": "ink-authoring-compose-android-1.0.0-beta01-sources.jar",
          "size": 13095,
          "sha512": "cdb19e393765c375e6865696f5e2460e337dfc2f64ee31f5929e20c0e5c1c20e42186e7e6d8f58b08fc6332cbd1f712e4e975e8f2aaf28653db2cad58944335d",
          "sha256": "26634102142174c35efed075cbccb6b38f50db009ef6b995472289c06e489ed4",
          "sha1": "c22d69da694e9cc3f769dd867b0b97896c0b2a87",
          "md5": "ff4e585b33e3c206f158cee3d8c41540"
        }
      ]
    }
  ]
}