{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.asynclayoutinflater",
    "module": "asynclayoutinflater",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "asynclayoutinflater-1.1.0-alpha01.aar",
          "url": "asynclayoutinflater-1.1.0-alpha01.aar",
          "size": 9358,
          "sha512": "79c3be338f1895a9d7bfbfcc47d57e0b29def77c3ac3638e767c255fd2765d59492c38c5ec94f35a5c87cf5b260809508ab2e3f6456eaa72ea87615b033f0e14",
          "sha256": "d9f2c72c6b38e1ddfff2c2782746a257f05d0668e1bdee632d74b86c4b339dba",
          "sha1": "81cb7f320bb6fabb9e08c7301214adf417f256cc",
          "md5": "54325249bb5fc0731d53abba5bba8824"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "asynclayoutinflater-1.1.0-alpha01.aar",
          "url": "asynclayoutinflater-1.1.0-alpha01.aar",
          "size": 9358,
          "sha512": "79c3be338f1895a9d7bfbfcc47d57e0b29def77c3ac3638e767c255fd2765d59492c38c5ec94f35a5c87cf5b260809508ab2e3f6456eaa72ea87615b033f0e14",
          "sha256": "d9f2c72c6b38e1ddfff2c2782746a257f05d0668e1bdee632d74b86c4b339dba",
          "sha1": "81cb7f320bb6fabb9e08c7301214adf417f256cc",
          "md5": "54325249bb5fc0731d53abba5bba8824"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "asynclayoutinflater-1.1.0-alpha01-sources.jar",
          "url": "asynclayoutinflater-1.1.0-alpha01-sources.jar",
          "size": 4506,
          "sha512": "13d42352178926fc7334392c1c260a74c47fde5dde8c5750a7a94fea1292b89d4e448ec72e40ea34755bca5a7d3bfc0c327675cb23ab86cf4dbf54a1fe444505",
          "sha256": "301ba28f1bf8abc609e0c243b1b7276f4c53e59d6b9bb01cefd1c3043d33d3ce",
          "sha1": "c3865e93edc905d2b36dfb2bff6aa2cdf0150675",
          "md5": "231bbda4328b589b0b74b9daa79db1a1"
        }
      ]
    }
  ]
}