{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-rxjava3",
    "version": "3.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13972835"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-rxjava3-3.4.0-alpha03-sources.jar",
          "url": "paging-rxjava3-3.4.0-alpha03-sources.jar",
          "size": 17322,
          "sha512": "9812a953b564e00bc784a109937c87aa47d1a02cf2c0922854d870b336e87cc54b88b387e503e584f45b565f8d25213837d601e62b29cfa3fc723c189a7d025e",
          "sha256": "fb13d0ed2c910ffd5f8b58756dfb5ec17153fbaefa5d302e0fcd58b8743975f7",
          "sha1": "60e812e204cae0da8920104ac7bc13d813451817",
          "md5": "c12ab2816e1679d8879fd86577987e71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha03"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-rxjava3-3.4.0-alpha03.aar",
          "url": "paging-rxjava3-3.4.0-alpha03.aar",
          "size": 37483,
          "sha512": "79a234df859e50326a696ae9bafe3551baa4a90710ae447521110b27712921f06421107c3abf13f1cad325cd861b37621c45246ae0a3d1e53b8638946ead8096",
          "sha256": "8f22184f5558ab037d13bb2604b3c47f5970f8d178c7fa810ff6b827cd19645d",
          "sha1": "9d5efe041617c8b752ad38ddf81a51dba3cb4018",
          "md5": "07db2954e52319134c7f6c449d3a561e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha03"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx3",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "paging-rxjava3-3.4.0-alpha03.aar",
          "url": "paging-rxjava3-3.4.0-alpha03.aar",
          "size": 37483,
          "sha512": "79a234df859e50326a696ae9bafe3551baa4a90710ae447521110b27712921f06421107c3abf13f1cad325cd861b37621c45246ae0a3d1e53b8638946ead8096",
          "sha256": "8f22184f5558ab037d13bb2604b3c47f5970f8d178c7fa810ff6b827cd19645d",
          "sha1": "9d5efe041617c8b752ad38ddf81a51dba3cb4018",
          "md5": "07db2954e52319134c7f6c449d3a561e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.4.0-alpha03"
          },
          "reason": "paging-rxjava3 is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-rxjava3-3.4.0-alpha03-versionMetadata.json",
          "url": "paging-rxjava3-3.4.0-alpha03-versionMetadata.json",
          "size": 6227,
          "sha512": "e64c5d359b94d25b22d5077aa87cc0933b1c0478cb5d1337fb0b9cc6bbb8209f8bb7148625ce8e5e3e2d82e7ef567ef796a54579478641089145532570471ea3",
          "sha256": "a7511125b7cf8d18cc888838f8cdef669400e109c306309a33e2388a7145632b",
          "sha1": "2d00de6bc8a745b81261905ec7bbe3a9370456ca",
          "md5": "35572ac895aa808e590d49c5e61f352a"
        }
      ]
    }
  ]
}