{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.7.0-alpha08/runtime-saveable-1.7.0-alpha08.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.7.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha08"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-desktop-1.7.0-alpha08.jar",
          "url": "runtime-saveable-desktop-1.7.0-alpha08.jar",
          "size": 54966,
          "sha512": "e8aa5399aabdd5700efdf581c459db7741580007cb945e1abddc2631cc33e4b120dbe6f005191b145a574ba18cf959f829cf03c8698c6ecf147af49a0d33df73",
          "sha256": "65bfa3d18537e7fca4f9e3587e47d1e3fc92cf7a4af78a445d6b3ae93530f06e",
          "sha1": "3efb202eed26f52b6b4bd8edf5a284a6bee2f3f7",
          "md5": "cdbdca85bf832345e3f2f24cae87e34c"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-desktop-1.7.0-alpha08.jar",
          "url": "runtime-saveable-desktop-1.7.0-alpha08.jar",
          "size": 54966,
          "sha512": "e8aa5399aabdd5700efdf581c459db7741580007cb945e1abddc2631cc33e4b120dbe6f005191b145a574ba18cf959f829cf03c8698c6ecf147af49a0d33df73",
          "sha256": "65bfa3d18537e7fca4f9e3587e47d1e3fc92cf7a4af78a445d6b3ae93530f06e",
          "sha1": "3efb202eed26f52b6b4bd8edf5a284a6bee2f3f7",
          "md5": "cdbdca85bf832345e3f2f24cae87e34c"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha08"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-desktop-1.7.0-alpha08-sources.jar",
          "url": "runtime-saveable-desktop-1.7.0-alpha08-sources.jar",
          "size": 11712,
          "sha512": "ba1621eac8c4452f36a8024a3019b05a547a0943414f56ccf9edcae0601a7beca3c8f8258734f92a7f0f7075c1e6cb2cd65a7ff1d184ab9b3103bb7eb7c3d0af",
          "sha256": "d4a91889cf76b4a39015f254af70ba95e3bdc6cc2b09377257c99a784ba21c72",
          "sha1": "a69d1bd090dd923851ff99f2e973d7a1e5314d91",
          "md5": "17a130013d5888fccf05b316e617c16c"
        }
      ]
    }
  ]
}