{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout-samples",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "foundation-layout-samples-1.4.0-alpha03.aar",
          "url": "foundation-layout-samples-1.4.0-alpha03.aar",
          "size": 243276,
          "sha512": "3e74d266c288b98752670ac2dbb93158a1eeee38c38c899a7b5b8fc1f7c6109c28b9d90a826ada65cfae4bf25a62c72969fd5aa907e8f71942c6c8e59003e980",
          "sha256": "4e14c9b98415c6b550148ab53a83fd9bc84bb37c8a508ce7004820f0e0c7ca05",
          "sha1": "ec127135876552be77126e4bfdcb1166104d3e5d",
          "md5": "9694996b538c75ac95c85d2faa72bb5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.4.0-alpha03.aar",
          "url": "foundation-layout-samples-1.4.0-alpha03.aar",
          "size": 243276,
          "sha512": "3e74d266c288b98752670ac2dbb93158a1eeee38c38c899a7b5b8fc1f7c6109c28b9d90a826ada65cfae4bf25a62c72969fd5aa907e8f71942c6c8e59003e980",
          "sha256": "4e14c9b98415c6b550148ab53a83fd9bc84bb37c8a508ce7004820f0e0c7ca05",
          "sha1": "ec127135876552be77126e4bfdcb1166104d3e5d",
          "md5": "9694996b538c75ac95c85d2faa72bb5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-layout-samples-1.4.0-alpha03-sources.jar",
          "url": "foundation-layout-samples-1.4.0-alpha03-sources.jar",
          "size": 18310,
          "sha512": "4ad635aebe0aaf1d739abc0535fdf1b56539607b67081d7409e4629f0f9e7102fa3b642f6a3f204dce7e0b6b933983fe63e3a8463b743fb058c11823c9df9da3",
          "sha256": "c7294c9cebe66861c491f1a60f80f3c4c93b2311f3fad3449dc773cf0c97cdc9",
          "sha1": "921322bc1bc1571b9b0a8d554d717a4c8631a982",
          "md5": "d78b0a4ea05634a9711ec9ea7c5bbcdf"
        }
      ]
    }
  ]
}