{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.7.0-alpha03/runtime-saveable-1.7.0-alpha03.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-desktop-1.7.0-alpha03.jar",
          "url": "runtime-saveable-desktop-1.7.0-alpha03.jar",
          "size": 54690,
          "sha512": "cb2c9c0f9eadd06465157aa30bd9d2b9c2a076824934a0dbe8a05d36f53c5085c1807a86f6006faf2380662e4a2a6a5b2c9f566c96eb519e1d00fb7ee641bb69",
          "sha256": "2a941b13c7d7a6e1c1ebf9d773b407b6c3fd30874ff5b34ea6d5ee163169c807",
          "sha1": "286c22076c3186a6794e713ccea5604eb7b32426",
          "md5": "58244b3651dccd72eb6ca24e9ad868ab"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-desktop-1.7.0-alpha03.jar",
          "url": "runtime-saveable-desktop-1.7.0-alpha03.jar",
          "size": 54690,
          "sha512": "cb2c9c0f9eadd06465157aa30bd9d2b9c2a076824934a0dbe8a05d36f53c5085c1807a86f6006faf2380662e4a2a6a5b2c9f566c96eb519e1d00fb7ee641bb69",
          "sha256": "2a941b13c7d7a6e1c1ebf9d773b407b6c3fd30874ff5b34ea6d5ee163169c807",
          "sha1": "286c22076c3186a6794e713ccea5604eb7b32426",
          "md5": "58244b3651dccd72eb6ca24e9ad868ab"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-desktop-1.7.0-alpha03-sources.jar",
          "url": "runtime-saveable-desktop-1.7.0-alpha03-sources.jar",
          "size": 11663,
          "sha512": "326baea73bb95d4df655daa5b2b8f44613671b930581886d54885fc55955ca5feb72aecdd55922847c444861600de704d9f04e896d1e857bafd328977fd60c35",
          "sha256": "c1730d3a69eb62ad819b12835591d0a8d7676de0b6d4257a38fa28daebbb8399",
          "sha1": "f4b8bdb1cd75cb3c61bc1a3996fe6eff4382e836",
          "md5": "084246caa2aa3053867c6bf8c5b79b6d"
        }
      ]
    }
  ]
}