{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class-samples",
    "version": "1.4.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13958485"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-samples-1.4.0-beta03-sources.jar",
          "url": "material3-window-size-class-samples-1.4.0-beta03-sources.jar",
          "size": 6513,
          "sha512": "69547dd36fa8f2bcca298c97383d4b3f488404fd3579fbabec0d68f4af515d39d83ac8a2282874de93e2c1e0b7ab64e845b7e1d906b3c6f4b1d9047fdcdc1884",
          "sha256": "b319045da15bf9ed8003d4636702cf83fd322e1ee164955d28b2cffb3a591818",
          "sha1": "0eda4b3d6cc1b0383cc1379a157d7c19eb462c20",
          "md5": "aa6a2af64c7d4a06d0cea72d570dcd0c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-samples-1.4.0-beta03.aar",
          "url": "material3-window-size-class-samples-1.4.0-beta03.aar",
          "size": 10482,
          "sha512": "2b00bccf3a54800050e25e8cf3ef0e628b0f80883e97b8c4dd33655bc3e8eff6107731dff14461e29ce27afb44c54e80106dd2f5b1567768171112c5234dd5e3",
          "sha256": "0327be69219074de6d2da04a672fffe9ee43ab629492bd9a260caf1d506b08e7",
          "sha1": "f2d07bb5f9a6492659c4d19b282aa7905704f366",
          "md5": "ff1b1d4a1df555f8dc7e1905e813177b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.4.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-samples-1.4.0-beta03.aar",
          "url": "material3-window-size-class-samples-1.4.0-beta03.aar",
          "size": 10482,
          "sha512": "2b00bccf3a54800050e25e8cf3ef0e628b0f80883e97b8c4dd33655bc3e8eff6107731dff14461e29ce27afb44c54e80106dd2f5b1567768171112c5234dd5e3",
          "sha256": "0327be69219074de6d2da04a672fffe9ee43ab629492bd9a260caf1d506b08e7",
          "sha1": "f2d07bb5f9a6492659c4d19b282aa7905704f366",
          "md5": "ff1b1d4a1df555f8dc7e1905e813177b"
        }
      ]
    }
  ]
}