{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent-testing/1.0.0-alpha08/navigationevent-testing-1.0.0-alpha08.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent-testing",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14046583"
    }
  },
  "variants": [
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-testing-watchosSimulatorArm64Main-1.0.0-alpha08.klib",
          "url": "navigationevent-testing-watchossimulatorarm64-1.0.0-alpha08.klib",
          "size": 19131,
          "sha512": "d10625f5c1ad0acbba0a951fc7b9d18a56b5e95bb380b8881426cf52666d339bfd3b3807c43d3c22c3af0ac09c9fe31c09c12543137c4affd927c4b7c87a5909",
          "sha256": "d2483ccd7e95093dbbd3e525063f9d34a4652b5c101241e3790d2dc0cd1e4dd8",
          "sha1": "21f152e769adfc3a96a52443110afdab3ae208a2",
          "md5": "ca6fa5b36bc753155dce90086cf0fd31"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-testing-watchossimulatorarm64-1.0.0-alpha08-sources.jar",
          "url": "navigationevent-testing-watchossimulatorarm64-1.0.0-alpha08-sources.jar",
          "size": 8080,
          "sha512": "1e1803bb2752cc1a4d80579d468b937861f208626d8979bc017667818ab6f9cc352556b70fad63cc61290db283f323cb260ea03d4cc1ef1e39e18bde09b7afb4",
          "sha256": "0bf8e988b2663f8442b613abe0c188ceadf7d4fc18a410d62128bfd02eaa2b25",
          "sha1": "b38a5a6719148a240a771728b52fb6aafa404d29",
          "md5": "e9d58fda27477fa3a8f58b1f4c0866a5"
        }
      ]
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-testing-watchossimulatorarm64-1.0.0-alpha08-metadata.jar",
          "url": "navigationevent-testing-watchossimulatorarm64-1.0.0-alpha08-metadata.jar",
          "size": 4492,
          "sha512": "91283f18e42ae1010235d92f0e6ee6a3d75d042016bab6ce3f865a8d227b878f0f5cccd509fd548212ab38a8c6ef08b3a544842ef712e919509b2a0e8174f0f4",
          "sha256": "cc5823c9a2ad647bf1516894700150a96098b4829eb63879321ea325c2cfb1f9",
          "sha1": "fbb199e3028e86b256edc61d6c1b1c985d15c94d",
          "md5": "e464537f68712b5c60430de859958eb1"
        }
      ]
    }
  ]
}