{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive/1.2.0-alpha11/adaptive-1.2.0-alpha11.module",
    "group": "androidx.compose.material3.adaptive",
    "module": "adaptive",
    "version": "1.2.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13969651"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha11"
          },
          "reason": "adaptive is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.2.0-alpha11"
          },
          "reason": "adaptive is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive.aar",
          "url": "adaptive-android-1.2.0-alpha11.aar",
          "size": 32640,
          "sha512": "954901acd7c711dc9e8e08b8501c428884a01f36fdd18686b980bd27320a2f32953a3084f1966db808ab67b1cf2a0d0526d4be8d27528c7d3f07a425f80fa265",
          "sha256": "8c74437fe81d9dd3cf2439e38731e71e36c8c052d09fb83358cabd385fd8d016",
          "sha1": "57a31709bdd83a17287d7df16e8703b909154e74",
          "md5": "e603df8465d6b7dd0890e6e3909d5ab7"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha11"
          },
          "reason": "adaptive is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.2.0-alpha11"
          },
          "reason": "adaptive is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive.aar",
          "url": "adaptive-android-1.2.0-alpha11.aar",
          "size": 32640,
          "sha512": "954901acd7c711dc9e8e08b8501c428884a01f36fdd18686b980bd27320a2f32953a3084f1966db808ab67b1cf2a0d0526d4be8d27528c7d3f07a425f80fa265",
          "sha256": "8c74437fe81d9dd3cf2439e38731e71e36c8c052d09fb83358cabd385fd8d016",
          "sha1": "57a31709bdd83a17287d7df16e8703b909154e74",
          "md5": "e603df8465d6b7dd0890e6e3909d5ab7"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha11"
          },
          "reason": "adaptive is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.2.0-alpha11"
          },
          "reason": "adaptive is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-android-1.2.0-alpha11-sources.jar",
          "url": "adaptive-android-1.2.0-alpha11-sources.jar",
          "size": 16269,
          "sha512": "f55d6a36c675d3d200b4acd96140c569a66a67902704a621a6bdfd723c892afbc99407b0a66493d6d0970d235a5c373ac39776b567753b6be47b986c919db473",
          "sha256": "c07b985393a7b26f7eef9af12ada662a6faea61c079f36af6bd1bd5c17a5a2a5",
          "sha1": "e8ba480d18afd879907fbfd7a35a5731174942d7",
          "md5": "5dbf49af4a0d32d2e8a8dfebd8ed59fa"
        }
      ]
    }
  ]
}