{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material-samples",
    "version": "1.5.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13092615"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-samples-1.5.0-alpha10-sources.jar",
          "url": "compose-material-samples-1.5.0-alpha10-sources.jar",
          "size": 36690,
          "sha512": "9dd98986e224a2a662d85dc8ccc544a73296d979dff8683c7824bcc646de23e6c0312e750d601cf5ca1f2ff3fcfd3ded05132aa049ab874549b2dcc10a38b066",
          "sha256": "35fbeaa1b0f3b1e1cf26102f643a636b1d17a4c2f2f1966195d5786a2b775339",
          "sha1": "f52c084273532fd4c98565a2af00761763285d23",
          "md5": "42cd363100ee613946683a94307d7f09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-samples-1.5.0-alpha10.aar",
          "url": "compose-material-samples-1.5.0-alpha10.aar",
          "size": 753498,
          "sha512": "1f7b0a914f383aad2d37bc58841b38b6f70a7236a1f2baa6f06f1a009a49c66596b5edd982ac4a20f11fdca2c0b1428f8ad0f5aae2cf3a3a6208605536a6f57b",
          "sha256": "bbb38cddb6cb32bd9d3e5f20ccfc89a781991ece538c72e92ae0b3c8ab296b50",
          "sha1": "bc23a9b4543aaad5a423c9c8867ea8614dda8d7f",
          "md5": "12f069ded13764c5e24dd4d645c04c03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha10"
          },
          "reason": "compose-material-samples is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-samples-1.5.0-alpha10.aar",
          "url": "compose-material-samples-1.5.0-alpha10.aar",
          "size": 753498,
          "sha512": "1f7b0a914f383aad2d37bc58841b38b6f70a7236a1f2baa6f06f1a009a49c66596b5edd982ac4a20f11fdca2c0b1428f8ad0f5aae2cf3a3a6208605536a6f57b",
          "sha256": "bbb38cddb6cb32bd9d3e5f20ccfc89a781991ece538c72e92ae0b3c8ab296b50",
          "sha1": "bc23a9b4543aaad5a423c9c8867ea8614dda8d7f",
          "md5": "12f069ded13764c5e24dd4d645c04c03"
        }
      ]
    }
  ]
}