{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.webkit",
    "module": "webkit",
    "version": "1.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.9.0-alpha01.aar",
          "url": "webkit-1.9.0-alpha01.aar",
          "size": 154436,
          "sha512": "2190b158491df7820496bb64c3b31b7db1523a42be112eb9fcd048112fad1b4dd7c8f8cf1966c9f93211c78ea6cac6f3a812e76d58e6443804dbe120cd5ae21b",
          "sha256": "4f6e3cbf91edf6018ef00d9b560dc363ee648dec789adcdf3508058180fa25b8",
          "sha1": "1aec518d556b1e26e124686079978b964f980cde",
          "md5": "0b97300da23dfd35c1a7505a4a40dc45"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.9.0-alpha01.aar",
          "url": "webkit-1.9.0-alpha01.aar",
          "size": 154436,
          "sha512": "2190b158491df7820496bb64c3b31b7db1523a42be112eb9fcd048112fad1b4dd7c8f8cf1966c9f93211c78ea6cac6f3a812e76d58e6443804dbe120cd5ae21b",
          "sha256": "4f6e3cbf91edf6018ef00d9b560dc363ee648dec789adcdf3508058180fa25b8",
          "sha1": "1aec518d556b1e26e124686079978b964f980cde",
          "md5": "0b97300da23dfd35c1a7505a4a40dc45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webkit-1.9.0-alpha01-sources.jar",
          "url": "webkit-1.9.0-alpha01-sources.jar",
          "size": 172445,
          "sha512": "0df67923666067b036d263b2f5cb9d62b97ed0555393a17b1af2b437b1dc9461b37c3aadeb4b03d07e57bac6aa6ffb46e07567794b50e6dc25996519f382a544",
          "sha256": "659050edc1d635f376a2a115bf34cad8959a6b20c7722e259779a125d744cc87",
          "sha1": "770ea343bbfa1a0c5b9d83de587ab42566384439",
          "md5": "5146d9aa535a5b506b8f63b382ee6aad"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "webkit-1.9.0-alpha01-versionMetadata.json",
          "url": "webkit-1.9.0-alpha01-versionMetadata.json",
          "size": 23424,
          "sha512": "bb0b2104787b0f691bccc133f6d7fab7f0076f4a9cc6c2a9283288f76fcec9b0586058559c3c59db0c1d2600185975fa2e35b2075e38bde0112f8b311d210fab",
          "sha256": "452dd60e91a294ee524e7b32a6cc84c946d42b87bfb5a11b7d6f147783834958",
          "sha1": "cad6d72daff9ed8b28ccfed45f15a5323ca282b1",
          "md5": "f925326121aed247e84c3ccb1794bfe2"
        }
      ]
    }
  ]
}