{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing-testing",
    "version": "2.7.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha11"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-testing-2.7.0-alpha11.jar",
          "url": "room-compiler-processing-testing-2.7.0-alpha11.jar",
          "size": 264424,
          "sha512": "a7de69aa6e41b41748bd244f172e28c0b8e4f7d5668c5204c821f20877b71c6f9d411a35e4257a14f355b119c7c29cbd377a02809168e04324a32fa34ac5d779",
          "sha256": "86f6347d85cccc6827ffd774e98c999f94e04b1108661a503558dbec4a9fffa7",
          "sha1": "709061e79dcf497231c742626abf8f963a58b4ea",
          "md5": "fa7e17673a9dd5830fb9b40e3715d8b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha11"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing",
          "version": {
            "requires": "2.1.0-Beta1-1.0.25"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-aa-embeddable",
          "version": {
            "requires": "2.1.0-Beta1-1.0.25"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.1.0-Beta1-1.0.25"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-common-deps",
          "version": {
            "requires": "2.1.0-Beta1-1.0.25"
          }
        },
        {
          "group": "com.google.testing.compile",
          "module": "compile-testing",
          "version": {
            "requires": "0.18"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-annotation-processing-embeddable",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler-embeddable",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-daemon-embeddable",
          "version": {
            "requires": "2.1.0-Beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-testing-2.7.0-alpha11.jar",
          "url": "room-compiler-processing-testing-2.7.0-alpha11.jar",
          "size": 264424,
          "sha512": "a7de69aa6e41b41748bd244f172e28c0b8e4f7d5668c5204c821f20877b71c6f9d411a35e4257a14f355b119c7c29cbd377a02809168e04324a32fa34ac5d779",
          "sha256": "86f6347d85cccc6827ffd774e98c999f94e04b1108661a503558dbec4a9fffa7",
          "sha1": "709061e79dcf497231c742626abf8f963a58b4ea",
          "md5": "fa7e17673a9dd5830fb9b40e3715d8b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha11"
          },
          "reason": "room-compiler-processing-testing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-testing-2.7.0-alpha11-sources.jar",
          "url": "room-compiler-processing-testing-2.7.0-alpha11-sources.jar",
          "size": 64128,
          "sha512": "a1ef4a35689b6be97e33df7aece74dc4b63e4d323e219794fca72227da29a9a6c8f24be851ebbdfe828b8f203230460576b770eaada5bc0f8957e331c30d9d9a",
          "sha256": "3ef32d213e845ffb59d5e4462ce5625110cf018d8134ca53e1ba6b2d96292bbb",
          "sha1": "c267057baa4c6f0c75d674481bf65890d941b5e0",
          "md5": "ef980bf116855f3fc62a24d4685bc6ae"
        }
      ]
    }
  ]
}