{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core-samples",
    "version": "1.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.4.0-rc01.aar",
          "url": "animation-core-samples-1.4.0-rc01.aar",
          "size": 151502,
          "sha512": "8616155e7b80d9c08e6083934fb9424537bee8e7396a5faaa4359d15488adf15548fc055e72699fd78024bd2edce1f649c7a8afa27183069aea1b0feab0f9e55",
          "sha256": "dc9b362388ac339ebeefd7b91c5c1ea1a4df709f9c3c510b3da3fa9be5780e27",
          "sha1": "5ffe955ce27f5f03314d7be0710ef1725ce1e22c",
          "md5": "5f5cb5cf3450a9780ff2366fec98fb22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.4.0-rc01.aar",
          "url": "animation-core-samples-1.4.0-rc01.aar",
          "size": 151502,
          "sha512": "8616155e7b80d9c08e6083934fb9424537bee8e7396a5faaa4359d15488adf15548fc055e72699fd78024bd2edce1f649c7a8afa27183069aea1b0feab0f9e55",
          "sha256": "dc9b362388ac339ebeefd7b91c5c1ea1a4df709f9c3c510b3da3fa9be5780e27",
          "sha1": "5ffe955ce27f5f03314d7be0710ef1725ce1e22c",
          "md5": "5f5cb5cf3450a9780ff2366fec98fb22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.4.0-rc01-sources.jar",
          "url": "animation-core-samples-1.4.0-rc01-sources.jar",
          "size": 16170,
          "sha512": "f11bc397c6c11acb4ad672cbb428248cf367929175ddfc4d94fab11f05989fb2c0c513f7ea921a5a33d19e924633794e4ac5124e8e5104312310490608aabd47",
          "sha256": "b8aa24f61b3d6d6b766cc9d59dccbdd1792f61c694735dde7104c4be6698c5b6",
          "sha1": "ad087ed4bf49b32c7e4d2af4a22ea6f7ff39fee4",
          "md5": "79e46cb7f12fb5198c142071bf9ec245"
        }
      ]
    }
  ]
}