{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-samples",
    "version": "1.7.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-samples-1.7.0-alpha05.aar",
          "url": "ui-samples-1.7.0-alpha05.aar",
          "size": 897444,
          "sha512": "1b20da0bbff742c3aab65ebb1c042dd8d0b0fbc8216875a1bf8fad0e94afc3fc9a01cbc4d6b35f69b8252786839c7cc706db634be2529c2ac0175655598dac88",
          "sha256": "714a07e2407ccce3a1322966b5c0320a710b1dfed0943bc8d8a0f3369c216c47",
          "sha1": "8ab30a122006d4b7926ba91134fd8d6547eb7390",
          "md5": "2d49f5f89b25093a2cab74b493260c67"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha05"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-samples-1.7.0-alpha05.aar",
          "url": "ui-samples-1.7.0-alpha05.aar",
          "size": 897444,
          "sha512": "1b20da0bbff742c3aab65ebb1c042dd8d0b0fbc8216875a1bf8fad0e94afc3fc9a01cbc4d6b35f69b8252786839c7cc706db634be2529c2ac0175655598dac88",
          "sha256": "714a07e2407ccce3a1322966b5c0320a710b1dfed0943bc8d8a0f3369c216c47",
          "sha1": "8ab30a122006d4b7926ba91134fd8d6547eb7390",
          "md5": "2d49f5f89b25093a2cab74b493260c67"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "ui-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-samples-1.7.0-alpha05-sources.jar",
          "url": "ui-samples-1.7.0-alpha05-sources.jar",
          "size": 56331,
          "sha512": "c800b4911eaab6b1b80240816ce09bdbe68cddf4a47605b22b5a0bc9149f9461f764827e4119bc8a584c7472076e75a60e5f14f9697e7f77fb7268d902671785",
          "sha256": "2fc1d93c71bfef7e9aba9f336d0476fe839d764d71bd18416804484efac67794",
          "sha1": "ae9b56f08d47ebedc31bc08a237d06079be21a67",
          "md5": "8ffcdca159d642142d5fe235aa31af9d"
        }
      ]
    }
  ]
}