{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core-okio/1.1.0-alpha05/datastore-core-okio-1.1.0-alpha05.module",
    "group": "androidx.datastore",
    "module": "datastore-core-okio",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.1.0-alpha05.jar",
          "url": "datastore-core-okio-jvm-1.1.0-alpha05.jar",
          "size": 28959,
          "sha512": "f457757430537cf6a5e695115446d09c435fdc6a57e892cfc3b6e79bdfe45574fc906e491865ba3f12cfb9e46022e1db8188e815175b750332e3305fa31c9984",
          "sha256": "75c270e17e07412029e8656e08d5d9cd89aa8dbc47fcdfc1917861475c2699bb",
          "sha1": "e9510c9555680b6565cb376e6b905f4485dd36ea",
          "md5": "2cf0b21e043ae2c288b6c6cf63ea616b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.1.0-alpha05.jar",
          "url": "datastore-core-okio-jvm-1.1.0-alpha05.jar",
          "size": 28959,
          "sha512": "f457757430537cf6a5e695115446d09c435fdc6a57e892cfc3b6e79bdfe45574fc906e491865ba3f12cfb9e46022e1db8188e815175b750332e3305fa31c9984",
          "sha256": "75c270e17e07412029e8656e08d5d9cd89aa8dbc47fcdfc1917861475c2699bb",
          "sha1": "e9510c9555680b6565cb376e6b905f4485dd36ea",
          "md5": "2cf0b21e043ae2c288b6c6cf63ea616b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-alpha05"
          },
          "reason": "datastore-core-okio is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-okio-jvm-1.1.0-alpha05-sources.jar",
          "url": "datastore-core-okio-jvm-1.1.0-alpha05-sources.jar",
          "size": 6637,
          "sha512": "c4d6b05d31b1e2b6e0d879c799c66879831e9241b872d5724b115ace6937ffd3addb279699382a942bfe6a27792ec225c6e6bae37be30199665754036fc09389",
          "sha256": "99d423f4d9f1143acd78306b5b4048231ec6c68049f3de4d01b8646cc7bdc8cd",
          "sha1": "8c0c5963396154a5d27ba8f07404fb65296176ae",
          "md5": "fa1fae17acc597174f957ccefba690e9"
        }
      ]
    }
  ]
}