{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-client-guava",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-client-guava-1.2.0.aar",
          "url": "watchface-client-guava-1.2.0.aar",
          "size": 25364,
          "sha512": "4bd099cef30601978d2df03a64dcc64a27707783287ceb8a97e64a36af15ec0353ecef0e9a66349368a05e7eff1c92b1970eff48cd2a8253cf961479fc59095c",
          "sha256": "b244487bbcd13744bea1c4ba089cb013e22d794a89be13ebc14ad62d035c7268",
          "sha1": "99505b2224f154cef49431e27ccd7310856e465d",
          "md5": "2151d80246162f1ea3360b4764ef34e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-client-guava-1.2.0.aar",
          "url": "watchface-client-guava-1.2.0.aar",
          "size": 25364,
          "sha512": "4bd099cef30601978d2df03a64dcc64a27707783287ceb8a97e64a36af15ec0353ecef0e9a66349368a05e7eff1c92b1970eff48cd2a8253cf961479fc59095c",
          "sha256": "b244487bbcd13744bea1c4ba089cb013e22d794a89be13ebc14ad62d035c7268",
          "sha1": "99505b2224f154cef49431e27ccd7310856e465d",
          "md5": "2151d80246162f1ea3360b4764ef34e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-client-guava-1.2.0-sources.jar",
          "url": "watchface-client-guava-1.2.0-sources.jar",
          "size": 5723,
          "sha512": "fec441868f206194e94fe8ee401bbb62e58efaebe526d42b90d6e6d91810e79e8c6437d55a76074eed26886224d3f08c46e67163510968f4d27b592c4decbefa",
          "sha256": "f1e9b305025e9f1e72fb94a7fb673b3dd98201b4d8364ec5d5246c881dbe8661",
          "sha1": "a4faa2253352e427e0b652cf71de88215f8d32d5",
          "md5": "0a4823b2117aeab0dc4ad2927c70bd42"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-client-guava-1.2.0-versionMetadata.json",
          "url": "watchface-client-guava-1.2.0-versionMetadata.json",
          "size": 4248,
          "sha512": "c4a699e2f078adcd495bf5234f3c0694a4ea1ece64059b709b5abf22dbf94cc51a714f136e80915f1358bf6cdb8a5fe35bdc4b66577007d44a50082391afcfb4",
          "sha256": "70562caf9d38b7a7676f4f991f09b122593f4cfcccbc2f3c3b9fb8bf8412d0fe",
          "sha1": "64bf0ec5f4735da207efc934c3025e574c18beb5",
          "md5": "800e6ac3a92d15eee94f4f2b0212f10f"
        }
      ]
    }
  ]
}