{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.1.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-1.1.0-rc01.aar",
          "url": "material-ripple-1.1.0-rc01.aar",
          "size": 72619,
          "sha512": "95edb1e6dd830668fb722343404c406c200a1728128c4f1b9eb6e89e906d23fefde1c323ae498bbb72eed7537a57767def4cde97153b3b508f8b0bc9e66e40cc",
          "sha256": "02b430f8aecc46d7c11b5407c82866f2314793ad472ba5aaec3177ebd56670b1",
          "sha1": "c9eba74a7786925a94022c63709d85bc98a23306",
          "md5": "9c13e76e2d2c2eb06e53229343ac880c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-1.1.0-rc01.aar",
          "url": "material-ripple-1.1.0-rc01.aar",
          "size": 72619,
          "sha512": "95edb1e6dd830668fb722343404c406c200a1728128c4f1b9eb6e89e906d23fefde1c323ae498bbb72eed7537a57767def4cde97153b3b508f8b0bc9e66e40cc",
          "sha256": "02b430f8aecc46d7c11b5407c82866f2314793ad472ba5aaec3177ebd56670b1",
          "sha1": "c9eba74a7786925a94022c63709d85bc98a23306",
          "md5": "9c13e76e2d2c2eb06e53229343ac880c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-ripple-1.1.0-rc01-sources.jar",
          "url": "material-ripple-1.1.0-rc01-sources.jar",
          "size": 21691,
          "sha512": "1b90df22733378bbf14bf73f1e44954476a67b9fbd22ad2d14e57f4970e2c06bc85a1a70d4b9ae85b83e7eb760ce9ba9fc13a5c61f68ce60afb64335b97022fa",
          "sha256": "ed1dc4e848d69095c883c2e02a0794f0adf34b021762895f5ac010dc74a67e15",
          "sha1": "17dc970b3b9979e18c1401c0d30c381a1d4eeff1",
          "md5": "3829807753b151eda51c1840b346b97e"
        }
      ]
    }
  ]
}
