{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-tooling",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-1.2.0-alpha01.aar",
          "url": "ui-tooling-1.2.0-alpha01.aar",
          "size": 102420,
          "sha512": "43ef9b1b0e323d65d45062009b1b58cc1abf4579de12e8e98060630253f3b70aed598ff2ae27532f9db4037d674f06c444eade1b3450a8e72b5e73c6b7a3d2e0",
          "sha256": "b4b85fba984c88449b7760545be2ba5b83a588d6a98bb21c7a3cc08075459e20",
          "sha1": "350efe5c9c8beccc5ea678c89d77b6562754e4fa",
          "md5": "2b67e4a1bc7f10d6f9ee6fa2990369fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-1.2.0-alpha01.aar",
          "url": "ui-tooling-1.2.0-alpha01.aar",
          "size": 102420,
          "sha512": "43ef9b1b0e323d65d45062009b1b58cc1abf4579de12e8e98060630253f3b70aed598ff2ae27532f9db4037d674f06c444eade1b3450a8e72b5e73c6b7a3d2e0",
          "sha256": "b4b85fba984c88449b7760545be2ba5b83a588d6a98bb21c7a3cc08075459e20",
          "sha1": "350efe5c9c8beccc5ea678c89d77b6562754e4fa",
          "md5": "2b67e4a1bc7f10d6f9ee6fa2990369fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-tooling-1.2.0-alpha01-sources.jar",
          "url": "ui-tooling-1.2.0-alpha01-sources.jar",
          "size": 22991,
          "sha512": "87e31b01b645719428a618608639d040f62638ffc02362608b47a35f014c212633c7e3a3557e4b52a58ee57d5aefe9f49c8c5a9cbd1a413b4b6895ca445bd754",
          "sha256": "dc4d3b7fe13aebe0a1578d2365841bad42c4dc788b29289f7ca0a0e0bbe25632",
          "sha1": "a17b4de28a84db168aa508cb7ba88ff3ff9f9715",
          "md5": "62a7fa3b3d12ba232a34290734f28a2e"
        }
      ]
    }
  ]
}
