{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text-google-fonts",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13900193"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-google-fonts-1.9.0-sources.jar",
          "url": "ui-text-google-fonts-1.9.0-sources.jar",
          "size": 13136,
          "sha512": "ee2963c40b772065e6e7cf358b2cf7797a8f8cc9e2fed892f00cb60995382b673eaa4ad456eb85493205485dc778103a7df719c63cad0c607782dcec00656bde",
          "sha256": "b98932d6c8f7c1643c88e1abe217168d321269fc5060f06fd6222f35503bea8f",
          "sha1": "cc4d8498b2711d81b735a22ac5436e1e124881f5",
          "md5": "53a9ce18abb3ce75f75dff15d5a082e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-google-fonts-1.9.0.aar",
          "url": "ui-text-google-fonts-1.9.0.aar",
          "size": 29028,
          "sha512": "c3b0c2d72259c61a7be7e6a5f4703a99a92a6744ff686165e87f55d76d47b23771aeb9cd8f92f032e488f660b8c75fcd1d56275fbb45c31199ee2d39e253109f",
          "sha256": "cfe5911cf4ae9b52ca038e5cd5a9402fa0f8dfbbbe7e8ac87214f6ae26eb3ffb",
          "sha1": "aaa301faf87096ebe1d0b3f61a9f36cab074bda4",
          "md5": "baa6809993e7382d320fe7876832d935"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-google-fonts-1.9.0.aar",
          "url": "ui-text-google-fonts-1.9.0.aar",
          "size": 29028,
          "sha512": "c3b0c2d72259c61a7be7e6a5f4703a99a92a6744ff686165e87f55d76d47b23771aeb9cd8f92f032e488f660b8c75fcd1d56275fbb45c31199ee2d39e253109f",
          "sha256": "cfe5911cf4ae9b52ca038e5cd5a9402fa0f8dfbbbe7e8ac87214f6ae26eb3ffb",
          "sha1": "aaa301faf87096ebe1d0b3f61a9f36cab074bda4",
          "md5": "baa6809993e7382d320fe7876832d935"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.0"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-google-fonts-1.9.0-versionMetadata.json",
          "url": "ui-text-google-fonts-1.9.0-versionMetadata.json",
          "size": 1691,
          "sha512": "b6ea914fd61e15e19759748eb2d415335143d5e8959ff50f2a06931eb477dd791ead144987ea9c3cb617b4041856fcea6cd1db4795d29ca162f5beac9af3d13f",
          "sha256": "9c6596140e53c60c3a4cce15c4b4c99f40950a2f530a637436fddc6b326784dd",
          "sha1": "719290fe59612e1c3b7ff40c0565ce67ea0bfc96",
          "md5": "bf42bb2c3388e4f071a6ef9f74a58a3f"
        }
      ]
    }
  ]
}