{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3-samples",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "material3-samples-1.2.0-alpha02.aar",
          "url": "material3-samples-1.2.0-alpha02.aar",
          "size": 1283908,
          "sha512": "b2403217520f799f7c4bf80eabc7e1e52779e534c1fd642d50c20ed87de6a48d99deaecb6bdf9e235860976b2062731cd3d5da5ac83d95a1bf977faa9fc9b62b",
          "sha256": "9bb940ca53272eeead354a8eeae65f91a96c1293a2e2a4b198f840a19862f8ad",
          "sha1": "cc856e5d973f55a3d7340878beed480cdccb45de",
          "md5": "2db4ce1a9443024ba45889d9f94e6541"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "material3-samples-1.2.0-alpha02.aar",
          "url": "material3-samples-1.2.0-alpha02.aar",
          "size": 1283908,
          "sha512": "b2403217520f799f7c4bf80eabc7e1e52779e534c1fd642d50c20ed87de6a48d99deaecb6bdf9e235860976b2062731cd3d5da5ac83d95a1bf977faa9fc9b62b",
          "sha256": "9bb940ca53272eeead354a8eeae65f91a96c1293a2e2a4b198f840a19862f8ad",
          "sha1": "cc856e5d973f55a3d7340878beed480cdccb45de",
          "md5": "2db4ce1a9443024ba45889d9f94e6541"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "material3-samples-1.2.0-alpha02-sources.jar",
          "url": "material3-samples-1.2.0-alpha02-sources.jar",
          "size": 46765,
          "sha512": "550ca676adb4124f8d9475f166553cf54242ea05bbf57cd33d527cf2f69bf27494039402efd728df6ddef26391fcdba59cd3d7ae891d8e621f7ae47af4ccb375",
          "sha256": "ca2e9ccd199bd78db9b3106a9a8d995d0a416aa8e8ceb77a23194f357057d377",
          "sha1": "e80925b0e741f5ecfa533eea1aee9fb7dfe8d75b",
          "md5": "62f7e3ac1174a7dfbe7d6d7e0deeac35"
        }
      ]
    }
  ]
}