{
  "formatVersion": "1.1",
  "component": {
    "url": "../../paging-testing/3.4.0-alpha01/paging-testing-3.4.0-alpha01.module",
    "group": "androidx.paging",
    "module": "paging-testing",
    "version": "3.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13699310"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "paging-testing-watchosDeviceArm64Main-3.4.0-alpha01.klib",
          "url": "paging-testing-watchosdevicearm64-3.4.0-alpha01.klib",
          "size": 59172,
          "sha512": "156409fbab6db32e7f0ee1ce03eeaa3690eaa0be112d9f8dccf4b9b3a95ebe51f7752ef3978abc03c6483f3042ad1e7ac920e37fd075ec60feca3fb971fc5d11",
          "sha256": "6cd6eff4765c79af1d68dd6ba69b16cd21efe0aa33dcbb0df1ec2f56cbc3b885",
          "sha1": "d5fc3d0360ca6e8b4de5db279e9c9699b7c5d097",
          "md5": "fec9274351d15f99a73e82f990836dd6"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-testing-watchosdevicearm64-3.4.0-alpha01-sources.jar",
          "url": "paging-testing-watchosdevicearm64-3.4.0-alpha01-sources.jar",
          "size": 25054,
          "sha512": "cb831e14a5fabfa2e4c26d7d931a288a0ef218134adfba15f867e070f9c0d1ada8a6725eb67f3b7b53ed16f0e253fd075cf50b3712a686991164da25fda8a8ee",
          "sha256": "67750dcbebc44c8ce3034ad62404a49dca52170998fd81474738503d7b3a8bc0",
          "sha1": "9459efeac2eacc2144ba76e0dc12e233836f073a",
          "md5": "80251fedf10a8e0536efa00fb644d808"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-testing is in atomic group androidx.paging"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "paging-testing-watchosdevicearm64-3.4.0-alpha01-metadata.jar",
          "url": "paging-testing-watchosdevicearm64-3.4.0-alpha01-metadata.jar",
          "size": 4402,
          "sha512": "55bfca7e65650181e4459140760f4322244ac17ff2d3a8e4bd9c08d1b00aaa344dde0e9ca6527a475132c07e2c28c96566ed58068b1b52a24a33a66bd2b01afb",
          "sha256": "f69734c9b965c1b462f9b2d6ca64fe5e38163a958c5c0c413576064904850eca",
          "sha1": "30258be0072efb77c454e76058a47044f0554c89",
          "md5": "ee7302068951ca82973710df9e257c57"
        }
      ]
    }
  ]
}