{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.2.0-alpha02.aar",
          "url": "runtime-1.2.0-alpha02.aar",
          "size": 1913000,
          "sha512": "32d37ecb84072a9b12f1e148f8a856c0f699a8193d2657c8156c8c1cbdadcdddb9cd659c5ce5cf0c5866aa4e217058a601d84a0bdd6d6f1ea03bdad116162df5",
          "sha256": "993bccb97c5c20ae0b5f71663d329c35cb9b5ff5378910d0f2e6f7477219f4d2",
          "sha1": "14ab334f08186419e94ef7aaa7d8810310fbfdda",
          "md5": "0e5d489fa138b37d3ad0cf9c89b7f2dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.2.0-alpha02.aar",
          "url": "runtime-1.2.0-alpha02.aar",
          "size": 1913000,
          "sha512": "32d37ecb84072a9b12f1e148f8a856c0f699a8193d2657c8156c8c1cbdadcdddb9cd659c5ce5cf0c5866aa4e217058a601d84a0bdd6d6f1ea03bdad116162df5",
          "sha256": "993bccb97c5c20ae0b5f71663d329c35cb9b5ff5378910d0f2e6f7477219f4d2",
          "sha1": "14ab334f08186419e94ef7aaa7d8810310fbfdda",
          "md5": "0e5d489fa138b37d3ad0cf9c89b7f2dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-1.2.0-alpha02-sources.jar",
          "url": "runtime-1.2.0-alpha02-sources.jar",
          "size": 267722,
          "sha512": "135784e562d7bcd8f52bb37e0be9a9a2afe25f4b93c39ce3ba76da56bd3414c75104d2adc03d990406a035a2b4030b8ad65d22412197c2e82086d3b3bd59c73b",
          "sha256": "18ceba31b6edc3fdd3e22e37d21453acc2732796e0b00c5e6fc40125ee0abee0",
          "sha1": "e0654297f771550568ecffd692133b19c1117fbd",
          "md5": "9ba783151530a16ce45ab06705a1921b"
        }
      ]
    }
  ]
}
