{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ink",
    "module": "ink-nativeloader",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13020744"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-nativeloader-1.0.0-alpha03-multiplatform-sources.jar",
          "url": "ink-nativeloader-1.0.0-alpha03-multiplatform-sources.jar",
          "size": 9642,
          "sha512": "db4741ff20d9b12fb9037f4c1f5baa5783ef38b1911bb422bfc36bf2a15dd6766bcd1383efec9c7b60d3a2cc3d42fbf66efbb711bffefec6863f666c2bce9eff",
          "sha256": "20c7c61545841286eda5204acf2dbcb95726c488b951f3f8b62017ec2ce13847",
          "sha1": "3bf5c7c35b0a918cc6482969538710639a92f57a",
          "md5": "eff8be1e448558bdbb7def861210ed51"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ink-nativeloader-1.0.0-alpha03-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-nativeloader-metadata-1.0.0-alpha03.jar",
          "url": "ink-nativeloader-1.0.0-alpha03.jar",
          "size": 4812,
          "sha512": "d9374c7a65fa9be59c74330e4a66aad5f93d0e4607fe1b1308f6588c69cfde148d31d4dd30a57befcaba1979b1632e72692b64b5e5adb0fdd545a72b0825edbd",
          "sha256": "e10e59d1e064a8c9e102476ec64cb490fd2134d003284971d93b9aeaa0f26fc4",
          "sha1": "c3370bed48de89e94165435501fc95b71588889d",
          "md5": "450fb68bb247ca8c47b9a4d7db76876f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "ink-nativeloader is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-nativeloader-kotlin-1.0.0-alpha03-sources.jar",
          "url": "ink-nativeloader-1.0.0-alpha03-sources.jar",
          "size": 6387,
          "sha512": "0ac43c82c6982e3f57898d9d4fe0a7af3b0cd00d97fb2f75023a2f9aa3dcfdadfaea69b384d9757832b4a7b8b3bf085b60f34419e7384641d61f633cdac52168",
          "sha256": "3b4929a31dd34ded123ab06a0dec76c44817f19888d59d4708252a5d6f2ec092",
          "sha1": "55fbf89c31a14667dc08ced957353a61ba2385bd",
          "md5": "e3c30cd3f1047b1b790565298dff349c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ink-nativeloader-android/1.0.0-alpha03/ink-nativeloader-android-1.0.0-alpha03.module",
        "group": "androidx.ink",
        "module": "ink-nativeloader-android",
        "version": "1.0.0-alpha03"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ink-nativeloader-android/1.0.0-alpha03/ink-nativeloader-android-1.0.0-alpha03.module",
        "group": "androidx.ink",
        "module": "ink-nativeloader-android",
        "version": "1.0.0-alpha03"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ink-nativeloader-android/1.0.0-alpha03/ink-nativeloader-android-1.0.0-alpha03.module",
        "group": "androidx.ink",
        "module": "ink-nativeloader-android",
        "version": "1.0.0-alpha03"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-nativeloader-jvm/1.0.0-alpha03/ink-nativeloader-jvm-1.0.0-alpha03.module",
        "group": "androidx.ink",
        "module": "ink-nativeloader-jvm",
        "version": "1.0.0-alpha03"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-nativeloader-jvm/1.0.0-alpha03/ink-nativeloader-jvm-1.0.0-alpha03.module",
        "group": "androidx.ink",
        "module": "ink-nativeloader-jvm",
        "version": "1.0.0-alpha03"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-nativeloader-jvm/1.0.0-alpha03/ink-nativeloader-jvm-1.0.0-alpha03.module",
        "group": "androidx.ink",
        "module": "ink-nativeloader-jvm",
        "version": "1.0.0-alpha03"
      }
    }
  ]
}