{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-effects",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-effects-1.4.0-beta01-sources.jar",
          "url": "camera-effects-1.4.0-beta01-sources.jar",
          "size": 31868,
          "sha512": "77430ca79ffae75f548976bd7245bf350121a98e1b678043535fae3fc4d43c86d50f97e290caa835d7a0ce5da0843a673f90279c79a65e3f7edd4b29a39c3335",
          "sha256": "dfa884db1e7ffdd9a47a1683971271055a2348ecf284c3f782b8854f068757b7",
          "sha1": "5b295cdd537770437d493863485e4cde74a3272f",
          "md5": "d021bcc4bccaa75920de919b35aa3237"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-effects-1.4.0-beta01.aar",
          "url": "camera-effects-1.4.0-beta01.aar",
          "size": 35463,
          "sha512": "2837d8fd47c0160efd0f0e930b9c43b753149a239e20e3ad8c9789c9e5fc0eae1190fed697de2039926163f3adb94ebc79c2c6de7e1f58c6b6e46734ff7779df",
          "sha256": "8cb376ab46d9987d9d880c49cdb179831a3aa6c316760f67a86d66f777f315e5",
          "sha1": "62272dd754f977c0be561a080230b74e6387b3fa",
          "md5": "77868295e670988ab231981fa0dbbbaa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-effects-1.4.0-beta01.aar",
          "url": "camera-effects-1.4.0-beta01.aar",
          "size": 35463,
          "sha512": "2837d8fd47c0160efd0f0e930b9c43b753149a239e20e3ad8c9789c9e5fc0eae1190fed697de2039926163f3adb94ebc79c2c6de7e1f58c6b6e46734ff7779df",
          "sha256": "8cb376ab46d9987d9d880c49cdb179831a3aa6c316760f67a86d66f777f315e5",
          "sha1": "62272dd754f977c0be561a080230b74e6387b3fa",
          "md5": "77868295e670988ab231981fa0dbbbaa"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-effects is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-effects-1.4.0-beta01-versionMetadata.json",
          "url": "camera-effects-1.4.0-beta01-versionMetadata.json",
          "size": 1403,
          "sha512": "5391e5fafa486420fb5b59a4cbdaf7303c4fed8eb0c50aa1552161d7ed1b923587c85594f823a45562507cf971065da4d16f410209bd867b483d3ac9e71db63a",
          "sha256": "77bc192ea2593572295e0a8dbbbb0814a0b6ea3744fae252c865490b673f28e6",
          "sha1": "8a348c68b0eeeda4dcef54c78bca17716685ae73",
          "md5": "c1b8646d93fc9a2f4727f6d4f86a0106"
        }
      ]
    }
  ]
}