{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-navigation-samples",
    "version": "1.10.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14128725"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-navigation-samples-1.10.0-alpha04-sources.jar",
          "url": "material-navigation-samples-1.10.0-alpha04-sources.jar",
          "size": 6644,
          "sha512": "76aa69a0bc6a2172d69c3f5fa9e71c5547f01cc576d14fb6e5ad8dfc0e974bce1c2a32a6260544f5c4ff5a649cf22d4f0c73ecb9501a74eccde2d2d77acd9512",
          "sha256": "a6a86355843f0a8fea11de1a9b0b2a178ade062152eed667653656873ab7567a",
          "sha1": "b14ba3fde28abd6695f2c91516f32440228925bc",
          "md5": "d0ff613c8d6d62fba90eec427d0aedf7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material-navigation-samples-1.10.0-alpha04.aar",
          "url": "material-navigation-samples-1.10.0-alpha04.aar",
          "size": 19783,
          "sha512": "3dcf34d1ffeefe4ccd1cf6eae2ddbcc3a3771e3a030d465092f5f0ab896f551ffb67cd3f5148e777a919cbeae8bcac4c8dfa9392b345183957749524bf289199",
          "sha256": "1e35702ffb371514e6a1c00036c54ad883a08c5832336ae92e7f6a460004b99b",
          "sha1": "f6f486eb3b4c1d2e58f8787924ed15e327f0c082",
          "md5": "9fc169025fbc665042f06df721e63d54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-navigation",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "material-navigation-samples-1.10.0-alpha04.aar",
          "url": "material-navigation-samples-1.10.0-alpha04.aar",
          "size": 19783,
          "sha512": "3dcf34d1ffeefe4ccd1cf6eae2ddbcc3a3771e3a030d465092f5f0ab896f551ffb67cd3f5148e777a919cbeae8bcac4c8dfa9392b345183957749524bf289199",
          "sha256": "1e35702ffb371514e6a1c00036c54ad883a08c5832336ae92e7f6a460004b99b",
          "sha1": "f6f486eb3b4c1d2e58f8787924ed15e327f0c082",
          "md5": "9fc169025fbc665042f06df721e63d54"
        }
      ]
    }
  ]
}