{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-extensions",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6759487"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-beta08"
          }
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.0.0-alpha15.aar",
          "url": "camera-extensions-1.0.0-alpha15.aar",
          "size": 60463,
          "sha512": "95ea3735d94443b3a81c695822160219bb1d44a2b23788eb087682495d136ac086ea31f46d860c6fc83a25a5e7e98480720f185b6a0ac8fe030bc8c8ce379482",
          "sha256": "797cb25add82940c5bef71c01933714054a8b9d0e897acb333897434dba88838",
          "sha1": "7e686acfb1e1fedb4f5cd5050d50a6e850a0ef2f",
          "md5": "8e87330b3e4fb1fb1d65fb4341992ca9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-beta08"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-beta08"
          }
        }
      ],
      "files": [
        {
          "name": "camera-extensions-1.0.0-alpha15.aar",
          "url": "camera-extensions-1.0.0-alpha15.aar",
          "size": 60463,
          "sha512": "95ea3735d94443b3a81c695822160219bb1d44a2b23788eb087682495d136ac086ea31f46d860c6fc83a25a5e7e98480720f185b6a0ac8fe030bc8c8ce379482",
          "sha256": "797cb25add82940c5bef71c01933714054a8b9d0e897acb333897434dba88838",
          "sha1": "7e686acfb1e1fedb4f5cd5050d50a6e850a0ef2f",
          "md5": "8e87330b3e4fb1fb1d65fb4341992ca9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-extensions-1.0.0-alpha15-sources.jar",
          "url": "camera-extensions-1.0.0-alpha15-sources.jar",
          "size": 36890,
          "sha512": "c943897ec1e63af70688d2a41721400247b7b1dc4aea1f4a6ea88fa8265ed8f6068a243f570c1d65b15b91ff55a444b37ed1d2f2dae82d331f2d51abfffea515",
          "sha256": "44f903f1df89cc09f8c6765397adf4dabfca250336df8201dc89e785f8e5b044",
          "sha1": "29233a5ebae0eda30bacbffda2ca2d733c1afa72",
          "md5": "a24abd15443dcc10f3fee9f5c0629616"
        }
      ]
    }
  ]
}
