{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.xr.scenecore",
    "module": "scenecore-testing",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12754188"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.xr.scenecore",
          "module": "scenecore",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "scenecore-testing is in atomic group androidx.xr.scenecore"
        }
      ],
      "files": [
        {
          "name": "scenecore-testing-1.0.0-alpha01-sources.jar",
          "url": "scenecore-testing-1.0.0-alpha01-sources.jar",
          "size": 19011,
          "sha512": "4692bb7f8eb7970c44f3ff30bb1a37ad65a2b38c7fb0d371f0fed01397a3239c5bfcd8919209648cfdf30aa10eb2db22de707f77819f293497b2baaa88853168",
          "sha256": "e66c353f4061e36751a4d6e9ea61dae63502db53169e3697a0b5dc922d28ea5a",
          "sha1": "4fc6c835f7483e6520b24fededf96e64edfb50c2",
          "md5": "0d705efd0eaa1469a1d1fe2067384342"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.xr.scenecore",
          "module": "scenecore",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.xr.scenecore",
          "module": "scenecore",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "scenecore-testing is in atomic group androidx.xr.scenecore"
        }
      ],
      "files": [
        {
          "name": "scenecore-testing-1.0.0-alpha01.aar",
          "url": "scenecore-testing-1.0.0-alpha01.aar",
          "size": 46587,
          "sha512": "704fbf0c99ac8f4f791d4002559cde7b28ab42a7cfbb99633cff35826d0da8672e223bf7df28714c8249ef3c17c4127f8f573c9a43e9608fcdae09230f00230a",
          "sha256": "4841d743f4ffb21acb4934cccfe672fd974b2142f2984d6d815a3e8441533cb3",
          "sha1": "e5e9d89e4ddf2e367999611ce3038e7859366d35",
          "md5": "ff8a0b64459f874cabcdaf25ee717833"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "truth",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.xr.scenecore",
          "module": "scenecore",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "com.google.ar",
          "module": "impress",
          "version": {
            "requires": "0.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.xr.scenecore",
          "module": "scenecore",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "scenecore-testing is in atomic group androidx.xr.scenecore"
        }
      ],
      "files": [
        {
          "name": "scenecore-testing-1.0.0-alpha01.aar",
          "url": "scenecore-testing-1.0.0-alpha01.aar",
          "size": 46587,
          "sha512": "704fbf0c99ac8f4f791d4002559cde7b28ab42a7cfbb99633cff35826d0da8672e223bf7df28714c8249ef3c17c4127f8f573c9a43e9608fcdae09230f00230a",
          "sha256": "4841d743f4ffb21acb4934cccfe672fd974b2142f2984d6d815a3e8441533cb3",
          "sha1": "e5e9d89e4ddf2e367999611ce3038e7859366d35",
          "md5": "ff8a0b64459f874cabcdaf25ee717833"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.xr.scenecore",
          "module": "scenecore",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "scenecore-testing is in atomic group androidx.xr.scenecore"
        }
      ],
      "files": [
        {
          "name": "scenecore-testing-1.0.0-alpha01-versionMetadata.json",
          "url": "scenecore-testing-1.0.0-alpha01-versionMetadata.json",
          "size": 29519,
          "sha512": "658d9516f3218f31d7c995c10fe96bc7d865b3a60be1e2181af873cda1a14c0ff157fabc4520bb00fef098fe153b368a71b8b4a310321f09f48ac37e7f7493a3",
          "sha256": "d40b62c8bc91fae02a236e41b217f9d32dd7579e7f05f8564388cf593d40651f",
          "sha1": "196e6ee2db1165d66905a73a4a6bda17b0439c0d",
          "md5": "6e98f7a217dd9bfe427e4225c0ae59b1"
        }
      ]
    }
  ]
}