{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-compose-samples",
    "version": "2.8.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.8.0-beta01.aar",
          "url": "lifecycle-runtime-compose-samples-2.8.0-beta01.aar",
          "size": 29456,
          "sha512": "0fc1aafda774042bfb13723b64627a2d33276a42b5432555a9a6f615495db5d74c03fc21a5a1cc852d29459279b8a37ba4c55909e401cddebfa0a9def4b93e93",
          "sha256": "36eaf1dcdfa8f674a0ce747c5a46aea338119795535706ef47ebe7d19206f17a",
          "sha1": "f3ea2aa45992c392f82a76f9e2a7718350e35c62",
          "md5": "05b1cf325e7517fa1a639f2bfdea1591"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.8.0-beta01.aar",
          "url": "lifecycle-runtime-compose-samples-2.8.0-beta01.aar",
          "size": 29456,
          "sha512": "0fc1aafda774042bfb13723b64627a2d33276a42b5432555a9a6f615495db5d74c03fc21a5a1cc852d29459279b8a37ba4c55909e401cddebfa0a9def4b93e93",
          "sha256": "36eaf1dcdfa8f674a0ce747c5a46aea338119795535706ef47ebe7d19206f17a",
          "sha1": "f3ea2aa45992c392f82a76f9e2a7718350e35c62",
          "md5": "05b1cf325e7517fa1a639f2bfdea1591"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.0-beta01"
          },
          "reason": "lifecycle-runtime-compose-samples is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-compose-samples-2.8.0-beta01-sources.jar",
          "url": "lifecycle-runtime-compose-samples-2.8.0-beta01-sources.jar",
          "size": 2798,
          "sha512": "cbf1343692fbbb0ae6be6349e1e112e89ea98715015def740025c5b5ae155110bc8a8dcccb7462d5b320fc39c3129d5c531892762cbaf625fd05fc6fd86ec5b4",
          "sha256": "c9722f19c81a97b7c63bb9806a068191df6ffa1586803359551ba2da2a32371c",
          "sha1": "f5d7e9e3a63f480e6c86da0e50035dab77b8ce8b",
          "md5": "449617061481013c2b5274eb4c39f38d"
        }
      ]
    }
  ]
}