{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout-samples",
    "version": "1.6.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.6.0-alpha07.aar",
          "url": "foundation-layout-samples-1.6.0-alpha07.aar",
          "size": 257067,
          "sha512": "0e3edee8c53297543532915ddd08d7c924658077409f14467c6368cc89c7942b539828635ec135a6c6a694b612692008d66454adfacef0731cb52bc6db09254c",
          "sha256": "8697a10f96c738675471eca46a251d423fffc3779b693ac19b66cce6ee379b87",
          "sha1": "c8cda834e74485ad45830510f3f268eecb34fce3",
          "md5": "6a086cabfed5138e19238c41163eb343"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.6.0-alpha07.aar",
          "url": "foundation-layout-samples-1.6.0-alpha07.aar",
          "size": 257067,
          "sha512": "0e3edee8c53297543532915ddd08d7c924658077409f14467c6368cc89c7942b539828635ec135a6c6a694b612692008d66454adfacef0731cb52bc6db09254c",
          "sha256": "8697a10f96c738675471eca46a251d423fffc3779b693ac19b66cce6ee379b87",
          "sha1": "c8cda834e74485ad45830510f3f268eecb34fce3",
          "md5": "6a086cabfed5138e19238c41163eb343"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.6.0-alpha07-sources.jar",
          "url": "foundation-layout-samples-1.6.0-alpha07-sources.jar",
          "size": 20582,
          "sha512": "22b28ba20491fcfe4133543189bd5d1ad15f9bd852973349a0a0f50fc7258d554f5f3acae043cbc722ea51536c314f998ad398f7c86d0e958d023bd531fcda5c",
          "sha256": "4b996e56356b78feb0de2c1a8ebcbc91ffa88661cb4c28282303802defcf1313",
          "sha1": "a07777feeee1ff82025db91100ea5a47013913fc",
          "md5": "9ce66bd652d7cc98e832360f519f1df6"
        }
      ]
    }
  ]
}