{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6983882"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.2.aar",
          "url": "navigation-runtime-ktx-2.3.2.aar",
          "size": 13227,
          "sha512": "0dba137d874ef0e5656a4f9d3b50831bccf3f9f7143eb9343f7c25076f630a782092cdf726cc9632c52bc188d5431a29b31be8e3e4855107171537237e55a1f1",
          "sha256": "8183bbeef707d05816526f72e6d05306333d5ecc2d0706cf29abca9e348e6296",
          "sha1": "9c1b102f024007133e982d99efd63cacf9e271ed",
          "md5": "907809e9ce84b0c1173542bf1c217a1d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.2.aar",
          "url": "navigation-runtime-ktx-2.3.2.aar",
          "size": 13227,
          "sha512": "0dba137d874ef0e5656a4f9d3b50831bccf3f9f7143eb9343f7c25076f630a782092cdf726cc9632c52bc188d5431a29b31be8e3e4855107171537237e55a1f1",
          "sha256": "8183bbeef707d05816526f72e6d05306333d5ecc2d0706cf29abca9e348e6296",
          "sha1": "9c1b102f024007133e982d99efd63cacf9e271ed",
          "md5": "907809e9ce84b0c1173542bf1c217a1d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.2-sources.jar",
          "url": "navigation-runtime-ktx-2.3.2-sources.jar",
          "size": 6128,
          "sha512": "f976814e20f825b4f16bf017c59918c3eb42304e8cb934b491431d2cf1e280bceea3a63b255a8ebbfcbb3886fdf26bd2a258e41928747b90eb04075e421ef4df",
          "sha256": "17df0a9cfd3b645ce58d9716f293ffdcfd8f30b60b87dab2a3cf099dddc1e70a",
          "sha1": "4d2da12a557444e5706dd6ca99f059ec099a45de",
          "md5": "fe0b36da8a72a76b3f3e34d30eebbcb2"
        }
      ]
    }
  ]
}
