{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel/2.10.0-alpha03/lifecycle-viewmodel-2.10.0-alpha03.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.10.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13969651"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-linuxX64Main-2.10.0-alpha03.klib",
          "url": "lifecycle-viewmodel-linuxx64-2.10.0-alpha03.klib",
          "size": 56703,
          "sha512": "8bcaa672bb7235f1289e0aa42ebb0d163a5b9af589727183ef979e05a9d9ad394167830e28e384f7a41af14717b777d88bb25d04729c1239b309876a28ca0dcf",
          "sha256": "e01d66f25f19f325c4a927035c4acab25834ca3b73a33e50a53bd55a79ab70ff",
          "sha1": "d4f88300a9f3caf5f30f5544de4d3c4dc2b2e027",
          "md5": "561f96551304f0aaf0bebc851a11ecd8"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-linuxx64-2.10.0-alpha03-sources.jar",
          "url": "lifecycle-viewmodel-linuxx64-2.10.0-alpha03-sources.jar",
          "size": 38770,
          "sha512": "07c0d9c9647363d030f982071d9f6da661292ad1917cb3f7b9399799b5dedc7f5ae73b4933619731e2fea8b5a0437d4352fa5a4bdd213505a53806a711be77d8",
          "sha256": "566894a840d87fc2e9dd22fba9085e5709a8d4f8a439e01e6000714afab1615e",
          "sha1": "ab549ee198efb5ca3c06a14d3030fd63f1a2cdc8",
          "md5": "b6a983c6d4d48e03761c7eb8b5772110"
        }
      ]
    }
  ]
}