{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.2.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.2.0-beta01.aar",
          "url": "camera-core-1.2.0-beta01.aar",
          "size": 1146028,
          "sha512": "6d48b19b5a85f99622de2810e34f05b853330c167925ba5d3113add725dbeaceab0918b595647eaad0a8f66ec507049540d3276c0c4950074ae8c3ea5640018f",
          "sha256": "cb2a4d1b1ec04575e3d78e3ca11e9910e78ed661e7b8071b890b1f1d21393614",
          "sha1": "5f8443fa8457e984dbdf39cd25bce7c4ed660725",
          "md5": "9e7cedeaaeb18822f9f7e2b55fe31119"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "camera-core-1.2.0-beta01.aar",
          "url": "camera-core-1.2.0-beta01.aar",
          "size": 1146028,
          "sha512": "6d48b19b5a85f99622de2810e34f05b853330c167925ba5d3113add725dbeaceab0918b595647eaad0a8f66ec507049540d3276c0c4950074ae8c3ea5640018f",
          "sha256": "cb2a4d1b1ec04575e3d78e3ca11e9910e78ed661e7b8071b890b1f1d21393614",
          "sha1": "5f8443fa8457e984dbdf39cd25bce7c4ed660725",
          "md5": "9e7cedeaaeb18822f9f7e2b55fe31119"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-core-1.2.0-beta01-sources.jar",
          "url": "camera-core-1.2.0-beta01-sources.jar",
          "size": 483208,
          "sha512": "492b48d11ed7437abe01901d886f45c15d730ddcb76aaac4375d8f73f901dde5c93f19b34a0fa5851874a0331b0fdf256a7161d4944791428ee04f0a0edbb9b0",
          "sha256": "074e836b7a213704c63249bd344344ff5afb17a2194f64c060f102e45b0cdaa0",
          "sha1": "1af823b080da4ff82cb6ae86e81a8f4822191897",
          "md5": "ffcad6dcbfb16483cfe8ccdc2d567047"
        }
      ]
    }
  ]
}