{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-samples",
    "version": "1.1.0-rc03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-samples-1.1.0-rc03.aar",
          "url": "ui-samples-1.1.0-rc03.aar",
          "size": 455339,
          "sha512": "cab6047691280e081fb5efb0fcd7e5cab47900886079a791b5d4f17e6b8e59f0819ab44e2c047068f5d6d373dce8fc9329eb7ad0ba42829675b9924c6975741e",
          "sha256": "ea497ee50c0d421a0908d29695e216939f3476db92d08d42cdd894ddd80d296b",
          "sha1": "09e5ad3845ec25e0569c42229eff7f6aa3b3b9e3",
          "md5": "00091c00afe985ccf977f750152adf2a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.1.0-rc03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-rc03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-rc03"
          }
        }
      ],
      "files": [
        {
          "name": "ui-samples-1.1.0-rc03.aar",
          "url": "ui-samples-1.1.0-rc03.aar",
          "size": 455339,
          "sha512": "cab6047691280e081fb5efb0fcd7e5cab47900886079a791b5d4f17e6b8e59f0819ab44e2c047068f5d6d373dce8fc9329eb7ad0ba42829675b9924c6975741e",
          "sha256": "ea497ee50c0d421a0908d29695e216939f3476db92d08d42cdd894ddd80d296b",
          "sha1": "09e5ad3845ec25e0569c42229eff7f6aa3b3b9e3",
          "md5": "00091c00afe985ccf977f750152adf2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-samples-1.1.0-rc03-sources.jar",
          "url": "ui-samples-1.1.0-rc03-sources.jar",
          "size": 31426,
          "sha512": "2eb958678b4ac1e9587c15c6f37e36e4cb35aa43d96bd43de9733ef4525bb15665176c59684e9782ce2089761a33038c4d73f6df62a662ca44ace1f08c3ae5b1",
          "sha256": "4d65c63a803dcbd0b4f3dfbe70fc0ff2d84755c49c9dd909a3154573edbf04d0",
          "sha1": "f3855b95e5c94a4d1eec7bfffd998717d13315ae",
          "md5": "3523ac661254b29cdf45923a279f7b31"
        }
      ]
    }
  ]
}
