{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-guava",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-guava-2.5.0-alpha01.aar",
          "url": "room-guava-2.5.0-alpha01.aar",
          "size": 6198,
          "sha512": "867a6f47339a8d88f6f083a5d7be6e251e95730a28ece65f8f5cbddf97efbf791769fe2a8a2ddd18c0d757900e9610fb5d54831bc6bfc80136285b4b0319736f",
          "sha256": "f92577d78a9ce2f5037f6f08dc36cb9f4ddab76e653482572fa2839b08cd71e6",
          "sha1": "49f8dabd1db551429502e9cb45efd2e7e6bf917d",
          "md5": "7729506430b230930c40c67f95aef01d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.0-alpha01"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.0-alpha01"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-guava-2.5.0-alpha01.aar",
          "url": "room-guava-2.5.0-alpha01.aar",
          "size": 6198,
          "sha512": "867a6f47339a8d88f6f083a5d7be6e251e95730a28ece65f8f5cbddf97efbf791769fe2a8a2ddd18c0d757900e9610fb5d54831bc6bfc80136285b4b0319736f",
          "sha256": "f92577d78a9ce2f5037f6f08dc36cb9f4ddab76e653482572fa2839b08cd71e6",
          "sha1": "49f8dabd1db551429502e9cb45efd2e7e6bf917d",
          "md5": "7729506430b230930c40c67f95aef01d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-guava-2.5.0-alpha01-sources.jar",
          "url": "room-guava-2.5.0-alpha01-sources.jar",
          "size": 2352,
          "sha512": "abdd7f024522351117f3779136dce6599d50b29d8d55c4936a7d3bdda1051bf4d3317c30ab49be5696d9c03417d87b67f02686855ece96ca2e037306aebaf993",
          "sha256": "b84007f0038e5d98afc06d3f56e09153ddc5915f50f258e0c55b9db500b808f9",
          "sha1": "0f03ce251b30ddba68d30350993f4b1c6596a2bf",
          "md5": "391aa4a05808342ecabc73a28d9b981a"
        }
      ]
    }
  ]
}
