{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material3-samples",
    "version": "1.2.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-samples-1.2.0-alpha10.aar",
          "url": "compose-material3-samples-1.2.0-alpha10.aar",
          "size": 2142,
          "sha512": "ce31f64c28c0b376f6538053f1018414d7364ce160989664b26b16a3df30ef7d43b09b14fdc10585f55704b875084663728d45e5a47c5b85f66d3f36032df5ee",
          "sha256": "58cabbe6514363cb78bf30ed27e93fec8950ad2f02a0acf07f9119e0ed7412aa",
          "sha1": "b3dc64bdc1818902f0a39515016cd455a7b978f8",
          "md5": "95b929787126840c40ed6108526647d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-samples-1.2.0-alpha10.aar",
          "url": "compose-material3-samples-1.2.0-alpha10.aar",
          "size": 2142,
          "sha512": "ce31f64c28c0b376f6538053f1018414d7364ce160989664b26b16a3df30ef7d43b09b14fdc10585f55704b875084663728d45e5a47c5b85f66d3f36032df5ee",
          "sha256": "58cabbe6514363cb78bf30ed27e93fec8950ad2f02a0acf07f9119e0ed7412aa",
          "sha1": "b3dc64bdc1818902f0a39515016cd455a7b978f8",
          "md5": "95b929787126840c40ed6108526647d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-alpha10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-samples-1.2.0-alpha10-sources.jar",
          "url": "compose-material3-samples-1.2.0-alpha10-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}