{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-material",
    "version": "1.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-material-1.3.0-alpha02-sources.jar",
          "url": "protolayout-material-1.3.0-alpha02-sources.jar",
          "size": 63225,
          "sha512": "aa9b17fe7f7d58352b418a8bca83116441c044cc18b308b046e1828e897ab924ef281621c382056169b16aff74473a1e7ccf9055986b2ebb627d6d528cb8a082",
          "sha256": "7cdcb2e79f3bb79eea387990f0afe986a0b8d79661326c1ddaf17bf7c3df4d8f",
          "sha1": "576e8070e73bd4bf6d9b44d1d952d7ec2739cae0",
          "md5": "9a2a42d96277832566890b62b0a4a41f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-material-1.3.0-alpha02.aar",
          "url": "protolayout-material-1.3.0-alpha02.aar",
          "size": 94855,
          "sha512": "31d9c5f4bac9d0d761b6dcc31b3331e00ea36d7ab90d732bab15b1fc0e8fdf045b8645d3829d92e7c8d2bbed08f1470a8b6c5d9e1b182b490f1d3b9a4f594ac3",
          "sha256": "94914f86aaf7b2c33708c79125e343d05140e4a22eed773a3117022411b690e5",
          "sha1": "17bc869439350799f06b1faeb00c3639e865e904",
          "md5": "0377d8865153d576735da657ef9aac8d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-material-1.3.0-alpha02.aar",
          "url": "protolayout-material-1.3.0-alpha02.aar",
          "size": 94855,
          "sha512": "31d9c5f4bac9d0d761b6dcc31b3331e00ea36d7ab90d732bab15b1fc0e8fdf045b8645d3829d92e7c8d2bbed08f1470a8b6c5d9e1b182b490f1d3b9a4f594ac3",
          "sha256": "94914f86aaf7b2c33708c79125e343d05140e4a22eed773a3117022411b690e5",
          "sha1": "17bc869439350799f06b1faeb00c3639e865e904",
          "md5": "0377d8865153d576735da657ef9aac8d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "protolayout-material is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-material-1.3.0-alpha02-versionMetadata.json",
          "url": "protolayout-material-1.3.0-alpha02-versionMetadata.json",
          "size": 20064,
          "sha512": "d674d6c708ed539904814e6ea2d2c61028d029600d1ba77b402e1dcf9ba48640c4fb5a10a9f2c88f040a95c63086098abf644ca822d207057317838f85492cf4",
          "sha256": "909236d5a74894776b3a61da2d0c3af282507b8a8f524cf65de16c894219ab0f",
          "sha1": "8452c185344e4430c6b3a3080571fee131d11227",
          "md5": "07bcb25de380846e4c688c92f8cdcf0c"
        }
      ]
    }
  ]
}