{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive-navigation/1.2.0-alpha02/adaptive-navigation-1.2.0-alpha02.module",
    "group": "androidx.compose.material3.adaptive",
    "module": "adaptive-navigation",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13243833"
    }
  },
  "variants": [
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation-jvmstubs-1.2.0-alpha02.jar",
          "url": "adaptive-navigation-jvmstubs-1.2.0-alpha02.jar",
          "size": 32849,
          "sha512": "1df0ce4a543745eeca7d161dc43712eebaea6ebcf1e64cccdf5b409e9543067b4efc8d10fed49a5f3c1b10d8ab4c3921370930ef1af1ac75ad2bca193858ae33",
          "sha256": "6fd2795c6f54a77f060b7867c4ddfff519e0c520b5f55107d4e12c2e8ded29dd",
          "sha1": "13ccec69fc263268d137fbcaf7fce67d2b1518b7",
          "md5": "0bc30c37cc8782c418b4c210ad678b8c"
        }
      ]
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation-jvmstubs-1.2.0-alpha02.jar",
          "url": "adaptive-navigation-jvmstubs-1.2.0-alpha02.jar",
          "size": 32849,
          "sha512": "1df0ce4a543745eeca7d161dc43712eebaea6ebcf1e64cccdf5b409e9543067b4efc8d10fed49a5f3c1b10d8ab4c3921370930ef1af1ac75ad2bca193858ae33",
          "sha256": "6fd2795c6f54a77f060b7867c4ddfff519e0c520b5f55107d4e12c2e8ded29dd",
          "sha1": "13ccec69fc263268d137fbcaf7fce67d2b1518b7",
          "md5": "0bc30c37cc8782c418b4c210ad678b8c"
        }
      ]
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation-jvmstubs-1.2.0-alpha02-sources.jar",
          "url": "adaptive-navigation-jvmstubs-1.2.0-alpha02-sources.jar",
          "size": 11548,
          "sha512": "9bfe6cd99bdc9cb8968ab76cd41ea1a91b668744b42e8a6bfad687b189ed9ddf360f971a44b800a3b673427ccac1338ca6d5946661b5c8143a9cbe4df82bee78",
          "sha256": "bfb1fd4e430f7aaf302d5997e0fc50f74d31ece0a61530dd3aa5b6342908a231",
          "sha1": "aa4e8c125bdda71bd2ce6d3646216792372e44cb",
          "md5": "a262fe30b1f42ccf23665e60a2faf746"
        }
      ]
    }
  ]
}