{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe-integration",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-1.0.0-alpha01.aar",
          "size": 962411,
          "sha512": "749911e085b1916e6d17ee342d379271be71a04065cc5d2df6e44e4d6f3abfe55c2404a3227e9acd6f6c50d8777cebc072b1935442387ebc279a872a34609836",
          "sha256": "27364db78aa26317bcfb1c28f7820dbc5fb19d1fec688ecf7cb7609661463d8d",
          "sha1": "3f9e5e606d8d095de00d4fa1c498c032168df16b",
          "md5": "6094847b5cc445c2803b4277d104dad6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe-integration",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-1.0.0-alpha01.aar",
          "size": 962411,
          "sha512": "749911e085b1916e6d17ee342d379271be71a04065cc5d2df6e44e4d6f3abfe55c2404a3227e9acd6f6c50d8777cebc072b1935442387ebc279a872a34609836",
          "sha256": "27364db78aa26317bcfb1c28f7820dbc5fb19d1fec688ecf7cb7609661463d8d",
          "sha1": "3f9e5e606d8d095de00d4fa1c498c032168df16b",
          "md5": "6094847b5cc445c2803b4277d104dad6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe-integration",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-1.0.0-alpha01-sources.jar",
          "size": 226439,
          "sha512": "a6fd409d157cb8d79f0c1236c1381b3529344a563a971b8fd5ab52fbe3b3e5217d1ff37ffaa79792621eda05271b6a48fcc8df39e494f614b6c441fa4c5ee583",
          "sha256": "7ca8d11e50ada0d48fda0fbc7f5821b9611decde9e7c9188fad9b8ddbaae9316",
          "sha1": "e1a8c5db7ff5956de96014220714dce25539a8c5",
          "md5": "012b22a9c3a130641629dafc9fc8e3d1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe-integration",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder-compose",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-1.0.0-alpha01-versionMetadata.json",
          "url": "camera-camera2-pipe-1.0.0-alpha01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}