{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.13.1"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-1.0.0-alpha01.aar",
          "size": 491920,
          "sha512": "141c8e76e0c59d26993d66dff6525f1f6644b985fec796634c88d2490cc8072555b6bd52be43bcf3b7278be4070ed6981a8c0263353c5804caf977c68b853600",
          "sha256": "ad83858789a522b1291aae85b7f9d4dcf8bd1cd98f23971694540b36e0c18163",
          "sha1": "054f723d17a553ffb64a5b18cbb5e2b41b31d2e5",
          "md5": "bde29fbeeaabf93285a3143a8b367028"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.13.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.40.1"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-1.0.0-alpha01.aar",
          "size": 491920,
          "sha512": "141c8e76e0c59d26993d66dff6525f1f6644b985fec796634c88d2490cc8072555b6bd52be43bcf3b7278be4070ed6981a8c0263353c5804caf977c68b853600",
          "sha256": "ad83858789a522b1291aae85b7f9d4dcf8bd1cd98f23971694540b36e0c18163",
          "sha1": "054f723d17a553ffb64a5b18cbb5e2b41b31d2e5",
          "md5": "bde29fbeeaabf93285a3143a8b367028"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-camera2-pipe-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-1.0.0-alpha01-sources.jar",
          "size": 115026,
          "sha512": "5a806b7454d4adcda8a24536b964cd4d1b2b73e4e1cbed047848058492f9df337ced8ddb2c9edda0f7a8cb30d7d9236635ce2e2d2b8f8c805b7c12ff79948c5b",
          "sha256": "c76ea1524eea71a3f0837fbadea564bfc2aff81d7dbcc0a27a949841c7c809fd",
          "sha1": "166527f93d4b2081b3b7348dbdde90c16cda7d14",
          "md5": "c1b4fbcb011809a6a09461dbc815b0cf"
        }
      ]
    }
  ]
}
