{
  "formatVersion": "1.1",
  "component": {
    "url": "../../room-common/2.7.2/room-common-2.7.2.module",
    "group": "androidx.room",
    "module": "room-common",
    "version": "2.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13652230"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-wasm-js-2.7.2.klib",
          "url": "room-common-wasm-js-2.7.2.klib",
          "size": 80804,
          "sha512": "d2edc530fc95bea648c5af4ec49f4a8055c3ba3f0f4abc1c5caf31fb7d9b582414ef32a4eafc5309c5f13adc0658329a007c5b658f22e72583125eeacd72e3db",
          "sha256": "24d444581703d7672a638b1035353bdab6d737fe42eaa4197debb24a8f702435",
          "sha1": "b9c63722cc355fff6d6f3de7aa7cbbc148b74717",
          "md5": "48cb013735d68089a70c5bcafb1e946d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-wasm-js-2.7.2.klib",
          "url": "room-common-wasm-js-2.7.2.klib",
          "size": 80804,
          "sha512": "d2edc530fc95bea648c5af4ec49f4a8055c3ba3f0f4abc1c5caf31fb7d9b582414ef32a4eafc5309c5f13adc0658329a007c5b658f22e72583125eeacd72e3db",
          "sha256": "24d444581703d7672a638b1035353bdab6d737fe42eaa4197debb24a8f702435",
          "sha1": "b9c63722cc355fff6d6f3de7aa7cbbc148b74717",
          "md5": "48cb013735d68089a70c5bcafb1e946d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.2"
          },
          "reason": "room-common is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-common-wasm-js-2.7.2-sources.jar",
          "url": "room-common-wasm-js-2.7.2-sources.jar",
          "size": 68795,
          "sha512": "7fdaee5eba994465d223f3e86b62c28add19c08097ecc7439dcbe1b3a02d6232f805671c430222a8aa138dcfe74188a4d168b348fb2cbebd5ba30e71f552da1a",
          "sha256": "75398063fd989c428603921d06c84f186ebd12c5b096586fb4cdfa82293f4d70",
          "sha1": "b4e131cf46285b0f206381f39771718063624463",
          "md5": "b65818bf9f528bf365700e06381be806"
        }
      ]
    }
  ]
}