{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-graphics-samples",
    "version": "1.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.4.0-rc01.aar",
          "url": "animation-graphics-samples-1.4.0-rc01.aar",
          "size": 7918,
          "sha512": "e91b6ec3b7c033df684b3775d4ba545c8767e5310a26c6161a1f5ed0d2952644a3d5b74382d786694aab1f7f62f3c00cea49d8409c67087ff278376b3ef0b5fe",
          "sha256": "fdedd96d5481367f29be3d5030db30b70ce27fbda1d74ae45a69b9bbd323a2f4",
          "sha1": "4e6b79a870f42639504d7d376cb8e79576e008fd",
          "md5": "0c03915e94fed64c6eca6835601acc7a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.4.0-rc01.aar",
          "url": "animation-graphics-samples-1.4.0-rc01.aar",
          "size": 7918,
          "sha512": "e91b6ec3b7c033df684b3775d4ba545c8767e5310a26c6161a1f5ed0d2952644a3d5b74382d786694aab1f7f62f3c00cea49d8409c67087ff278376b3ef0b5fe",
          "sha256": "fdedd96d5481367f29be3d5030db30b70ce27fbda1d74ae45a69b9bbd323a2f4",
          "sha1": "4e6b79a870f42639504d7d376cb8e79576e008fd",
          "md5": "0c03915e94fed64c6eca6835601acc7a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-samples",
          "version": {
            "requires": "1.4.0-rc01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.4.0-rc01-sources.jar",
          "url": "animation-graphics-samples-1.4.0-rc01-sources.jar",
          "size": 1904,
          "sha512": "c18fad718bdf26fb40230ba195b9cd5efdea14d7f6ed255a25872a79bfce4e3ad285d4e94cd93d1f980de8e7a0d6d3a56dc270933a228adff36ab3ab37e615dd",
          "sha256": "8c3fe29b648846f8e535d42e0c84f87e6328479569fc26125385ff82eb487039",
          "sha1": "eaaf8cde7045c83b9c0f1ebb4726f70e24b15c4b",
          "md5": "982acda41e185e887d60862f0bb2273a"
        }
      ]
    }
  ]
}