{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-samples",
    "version": "1.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-samples-1.3.0-alpha02.aar",
          "url": "window-samples-1.3.0-alpha02.aar",
          "size": 13120,
          "sha512": "3ad1a59a81156b84beb1f02d98451116da40970f80a4aa6a8622ba59e7d86d49a822d733ee68726ada524e8e533d0c6f6fe283d92f37b5487530058e8078a4f1",
          "sha256": "83f56f164c74e873335d0b6126b42af5127c5458437460fb2d80616ec0164beb",
          "sha1": "bf876bc52d7a20c7e04cf9753986d798ce1dd519",
          "md5": "75345ce5ecf781881a403416ca456a87"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-samples-1.3.0-alpha02.aar",
          "url": "window-samples-1.3.0-alpha02.aar",
          "size": 13120,
          "sha512": "3ad1a59a81156b84beb1f02d98451116da40970f80a4aa6a8622ba59e7d86d49a822d733ee68726ada524e8e533d0c6f6fe283d92f37b5487530058e8078a4f1",
          "sha256": "83f56f164c74e873335d0b6126b42af5127c5458437460fb2d80616ec0164beb",
          "sha1": "bf876bc52d7a20c7e04cf9753986d798ce1dd519",
          "md5": "75345ce5ecf781881a403416ca456a87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "window-samples is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-samples-1.3.0-alpha02-sources.jar",
          "url": "window-samples-1.3.0-alpha02-sources.jar",
          "size": 3568,
          "sha512": "f92fca2c8173093a6669f284fb473bc11fb18bf4fc20a30740875655608a18f80a669772366052c8dc0cf57ead7403faf056e5d0b288bae2f2b74d37077c54cb",
          "sha256": "1b6a0669243bff243293e002934c340253b79229ab9ed0201ed2ed9a4e476fc8",
          "sha1": "4e5745950262dc6ea4d0cb50a16ce298d9467bce",
          "md5": "4f1f601dca2a7ecbff673f7254406738"
        }
      ]
    }
  ]
}