{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.0.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.0-alpha05.aar",
          "url": "material3-1.0.0-alpha05.aar",
          "size": 856512,
          "sha512": "58fffa5424ab094d5bb44739d8b2ce77dca600056b62ba5de734206e89444c249210b88997143a1e2e8d855e39a26e6da8b582594c11a4f05e8b33e66940837c",
          "sha256": "78881f88df85c29300c9a156eaf5a98a49880810b4f81523eba67f87b03ab22d",
          "sha1": "360326ed3c3643fc2b84d840b0bdd437df09bce0",
          "md5": "725056a4a7a823f727f597ec1288e755"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.0-alpha05.aar",
          "url": "material3-1.0.0-alpha05.aar",
          "size": 856512,
          "sha512": "58fffa5424ab094d5bb44739d8b2ce77dca600056b62ba5de734206e89444c249210b88997143a1e2e8d855e39a26e6da8b582594c11a4f05e8b33e66940837c",
          "sha256": "78881f88df85c29300c9a156eaf5a98a49880810b4f81523eba67f87b03ab22d",
          "sha1": "360326ed3c3643fc2b84d840b0bdd437df09bce0",
          "md5": "725056a4a7a823f727f597ec1288e755"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-1.0.0-alpha05-sources.jar",
          "url": "material3-1.0.0-alpha05-sources.jar",
          "size": 149457,
          "sha512": "b7c159a7a6b491c8ed37f3934721d928d1798099ffcd3089ed2bb85393ceef4ea66d4a3d1241f8bac506e486d136de8e1f70656d360b777597d38838f1743836",
          "sha256": "ae87cd10efbde798eb10c31662414d3af677169dd2810d78882a77c52170f704",
          "sha1": "0b0e66dcf675460cca55c72238d0a729b00e6cf5",
          "md5": "7b15f328d5136b26de9529c5880320d4"
        }
      ]
    }
  ]
}
