{
  "formatVersion": "1.1",
  "component": {
    "url": "../../window-core/1.4.0/window-core-1.4.0.module",
    "group": "androidx.window",
    "module": "window-core",
    "version": "1.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13448509"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "window-core-watchosArm32Main-1.4.0.klib",
          "url": "window-core-watchosarm32-1.4.0.klib",
          "size": 24509,
          "sha512": "d54df03f98bca2c64e78a5df7e0ce9f534837dbd602df08f6e902efbe08099130786f02fb63312550bd17c025f2ad83b34341cdc563fb97fc43407b32bb13910",
          "sha256": "498da2a4de113c8cb8cc598f39d16c97a3225aeb61d22e370285daa51fba2fb5",
          "sha1": "c0352628e54f6bf25b532d3d73fca3449cd7817f",
          "md5": "02b4f085fbaf17840665f701d5c063cf"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-watchosarm32-1.4.0-sources.jar",
          "url": "window-core-watchosarm32-1.4.0-sources.jar",
          "size": 12953,
          "sha512": "c35902f42f9d1a7ee6d9c08324aefbb36718bb03e6e412001128d77c99420a026ba781ef45b9c748b0003e0352c1ed5d41dc6fbff585aa5243ba168f2c6e0f44",
          "sha256": "53b920de7d6c889ec6596954689eadade4a5c181389463915af4a5780d355cae",
          "sha1": "8c396877b4d6a2b1d832233414a705480a080652",
          "md5": "521531ec496ce00e1ca37aee63c35e64"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "window-core-watchosarm32-1.4.0-metadata.jar",
          "url": "window-core-watchosarm32-1.4.0-metadata.jar",
          "size": 4390,
          "sha512": "06fb4eb320d1ad7818b505b2e1d1b6008d1731e421c57051cc538d6cbb1df1da665ffaed565c25236a2b8e7dc4bc0b2045552eaed7981fe28563a6963e097bf9",
          "sha256": "496ef4be6ca3b32b4f403e710302ed53822d019c7c02b5ccd2f95659b2641c58",
          "sha1": "ad421d4ff46e452f0d861da4c02545571dd88efa",
          "md5": "0075fef7d2a08d3ad4c80acc2596d09c"
        }
      ]
    }
  ]
}