{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-graphics-samples",
    "version": "1.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "animation-graphics-samples-1.4.0-alpha02.aar",
          "url": "animation-graphics-samples-1.4.0-alpha02.aar",
          "size": 7852,
          "sha512": "d59dba817a01f3a9afd5751231d0d349603c96865d082723d79b589a99229ea3b0130783c6e791e41985bdd59408905d505a7764ca0350079969d5f54bc94b5c",
          "sha256": "3b609738da9929286b01297bd396a860a48a0977116eaff277f67fc32bb41755",
          "sha1": "31444b33bef47ba8a650d7fce4b24826eb367f6e",
          "md5": "41447f828791f5e823064c325c377d5d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.4.0-alpha02.aar",
          "url": "animation-graphics-samples-1.4.0-alpha02.aar",
          "size": 7852,
          "sha512": "d59dba817a01f3a9afd5751231d0d349603c96865d082723d79b589a99229ea3b0130783c6e791e41985bdd59408905d505a7764ca0350079969d5f54bc94b5c",
          "sha256": "3b609738da9929286b01297bd396a860a48a0977116eaff277f67fc32bb41755",
          "sha1": "31444b33bef47ba8a650d7fce4b24826eb367f6e",
          "md5": "41447f828791f5e823064c325c377d5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-graphics-samples-1.4.0-alpha02-sources.jar",
          "url": "animation-graphics-samples-1.4.0-alpha02-sources.jar",
          "size": 1904,
          "sha512": "0aec20e4f374d3648d4a2c73b661cad97f48b486602b3bdcf2e960de55da9622607d8c2f3261f51de1d8f3274b1763175244225ebefaf385d2dbe9780994dae0",
          "sha256": "e2dc36ca592625ef764a49cd98b2358640ec77b561b0f6e846b9992683dfda6d",
          "sha1": "8775918be2aa2ed655a0dc7c97297e3862936d7e",
          "md5": "a63329e9ed44a4f4af70b3fb6dc53f52"
        }
      ]
    }
  ]
}