{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-ima",
    "version": "1.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.35.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.6.0-alpha01.aar",
          "url": "media3-exoplayer-ima-1.6.0-alpha01.aar",
          "size": 113109,
          "sha512": "765b4982bc15403338faf768bae8d40285e6b159b708195c35ff2bfd49946fe8b0ca6b08471121f7300f83dd0a57f49c84915123b340edd634b39851c93d8074",
          "sha256": "4dec924cb6cc539a333b938cbad7275e1fa251fee9a42d7035821923bd1c5429",
          "sha1": "6b8c5f97bfe17c029e25cfe7344a6f40f1638ed7",
          "md5": "1194ae2918e41b24f98cfeabe3122f45"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.ads.interactivemedia.v3",
          "module": "interactivemedia",
          "version": {
            "requires": "3.35.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-ima-1.6.0-alpha01.aar",
          "url": "media3-exoplayer-ima-1.6.0-alpha01.aar",
          "size": 113109,
          "sha512": "765b4982bc15403338faf768bae8d40285e6b159b708195c35ff2bfd49946fe8b0ca6b08471121f7300f83dd0a57f49c84915123b340edd634b39851c93d8074",
          "sha256": "4dec924cb6cc539a333b938cbad7275e1fa251fee9a42d7035821923bd1c5429",
          "sha1": "6b8c5f97bfe17c029e25cfe7344a6f40f1638ed7",
          "md5": "1194ae2918e41b24f98cfeabe3122f45"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-ima-1.6.0-alpha01-sources.jar",
          "url": "media3-exoplayer-ima-1.6.0-alpha01-sources.jar",
          "size": 50362,
          "sha512": "4717fed9428913b60366e70841446324bd08899c15ac2e29df1818781cfbaeee69ec2aa20b9cbdfba597132192c820797a0084bdbc199492d122cb7ff2f45ac5",
          "sha256": "84ad81648aec3c473acf77ec3fb0a7dbc55fc56586515e436f531c8f0bf2108f",
          "sha1": "cd38ba8164951e116b35409ecbce9648d6c88a9b",
          "md5": "0bd7e2f14f41bcf84d0103405e0da8ff"
        }
      ]
    }
  ]
}
