{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-graphics/1.7.0-beta06/animation-graphics-1.7.0-beta06.module",
    "group": "androidx.compose.animation",
    "module": "animation-graphics",
    "version": "1.7.0-beta06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta06"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta06"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-beta06"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0-beta06"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-desktop-1.7.0-beta06.jar",
          "url": "animation-graphics-desktop-1.7.0-beta06.jar",
          "size": 74761,
          "sha512": "c122f0c11395cd1c6196bb7cbc9683a3a6ce6e73e91640f005854bed68bd2c285484c9bca792bbc98fb00e46dee04408c756441678c48f05886180b1b91a17f9",
          "sha256": "f90536e13664e8a47c2216333399e2253f9a4d67cfa4e87427c26e376080aeb2",
          "sha1": "d4d2ce011135258dc50e8eab69b111a22a456b9a",
          "md5": "1565909f0649844ffeab643d5508914f"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta06"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-beta06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta06"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-beta06"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0-beta06"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-desktop-1.7.0-beta06.jar",
          "url": "animation-graphics-desktop-1.7.0-beta06.jar",
          "size": 74761,
          "sha512": "c122f0c11395cd1c6196bb7cbc9683a3a6ce6e73e91640f005854bed68bd2c285484c9bca792bbc98fb00e46dee04408c756441678c48f05886180b1b91a17f9",
          "sha256": "f90536e13664e8a47c2216333399e2253f9a4d67cfa4e87427c26e376080aeb2",
          "sha1": "d4d2ce011135258dc50e8eab69b111a22a456b9a",
          "md5": "1565909f0649844ffeab643d5508914f"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-beta06"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-beta06"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0-beta06"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-desktop-1.7.0-beta06-sources.jar",
          "url": "animation-graphics-desktop-1.7.0-beta06-sources.jar",
          "size": 9754,
          "sha512": "048b43e30c0f5c8cdfa2611f47b0016fa06db81b89a0b7d2005b3d206e3eda33f615c39ae6a599234fa85698cb9ce39f8cc455d9e2aa6c84ada3e2a039ee7e31",
          "sha256": "afaea3a24880b501cdff4b952370eb4702284750d9e4e052bc14306aa31bc873",
          "sha1": "b3e27f47d4c2a170e3b5b817233e628d0b003908",
          "md5": "cfb4758416c535853ea39c1f65d08b8b"
        }
      ]
    }
  ]
}