{
  "formatVersion": "1.1",
  "component": {
    "url": "../../window-core/1.5.0-rc01/window-core-1.5.0-rc01.module",
    "group": "androidx.window",
    "module": "window-core",
    "version": "1.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13953699"
    }
  },
  "variants": [
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-core-mingwX64Main-1.5.0-rc01.klib",
          "url": "window-core-mingwx64-1.5.0-rc01.klib",
          "size": 25750,
          "sha512": "32046185d1fc3ade9bee0b80ab34e116b0d5f552725700302c181d5a48cb776c50377b5c5d30a58e05cac71a7bbf9e4b22fd5abd9d6eeb2961ff49b74f12e363",
          "sha256": "316bfaf3ef7e65024c69413b5ed76826bab595707d8e9bf07f7e33af5138aed1",
          "sha1": "1c8c2b46fa6bdb1b8ce0d0fa142e1857e20572e7",
          "md5": "b10cdb6dbf40a8e4cb3e5a61fc52d1ab"
        }
      ]
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-mingwx64-1.5.0-rc01-sources.jar",
          "url": "window-core-mingwx64-1.5.0-rc01-sources.jar",
          "size": 13190,
          "sha512": "c0f2a079dc7d7f759d456b17a609e4520b5a126e7a21fa330fda5df48675cac7d6f35c332a7434f96f61d810c49fb9c9bfe7fe1101b35d66b53657f1218330db",
          "sha256": "84310e2892f4a174f74607eacbb7342b8bff23197495db4557938aa553aa510e",
          "sha1": "d4743b9b2b7773360048f68369e2612675c28176",
          "md5": "bcb367569a180dc39e4ccd12074b3785"
        }
      ]
    }
  ]
}