{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava3",
    "version": "1.0.0-beta05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7285231"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava3-1.0.0-beta05.aar",
          "url": "runtime-rxjava3-1.0.0-beta05.aar",
          "size": 25074,
          "sha512": "7395f0db240614b32e580fe14c3249a93fe0aa0a48d84f571a401720f0029f11f9994908d56f4fefb5ba7a9829445a6efe12fb2add78a450c9d030be71c86c6c",
          "sha256": "ecc8ceb4b1f94efff09630d99e4eba4cada5fd787cc39c967f1dc2d6ddc54fa4",
          "sha1": "f53828bb3d3cf73e5c83363863f9f1da23afe821",
          "md5": "cebf5a78ff3750bb397d50946268c5d4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava3-1.0.0-beta05.aar",
          "url": "runtime-rxjava3-1.0.0-beta05.aar",
          "size": 25074,
          "sha512": "7395f0db240614b32e580fe14c3249a93fe0aa0a48d84f571a401720f0029f11f9994908d56f4fefb5ba7a9829445a6efe12fb2add78a450c9d030be71c86c6c",
          "sha256": "ecc8ceb4b1f94efff09630d99e4eba4cada5fd787cc39c967f1dc2d6ddc54fa4",
          "sha1": "f53828bb3d3cf73e5c83363863f9f1da23afe821",
          "md5": "cebf5a78ff3750bb397d50946268c5d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-rxjava3-1.0.0-beta05-sources.jar",
          "url": "runtime-rxjava3-1.0.0-beta05-sources.jar",
          "size": 2234,
          "sha512": "cb08a0d39fde12fe624d93f2e09c94cbe881f8b113df257744acc349138b04c6e7f6e8344cc659d878da9e4d0aeab34a58fd05d8be09eaaa18a8249e3336e372",
          "sha256": "e2d577605af518c7ef2b1dd8f91739602d6562ced82bdcd13cb6347c9f9cae54",
          "sha1": "6a81e97b8e1b3320b53e65ef75b07d2793bc99f4",
          "md5": "5b6eba3aa3b922dfd848803b0ea1a746"
        }
      ]
    }
  ]
}
