{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-foundation-samples",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-samples-1.4.0-beta01-sources.jar",
          "url": "compose-foundation-samples-1.4.0-beta01-sources.jar",
          "size": 13024,
          "sha512": "9f31ade1bb3e1851f2244cd160859bcb30417298c65a8f851581fcd77099e4ef1abf625de126fef048652e8eda205a6f2e9c5ea3ed31f812a62e401c888a9ce6",
          "sha256": "94c289f365ad0b6eaf02aca05dc28a71da4bce37927c377c1604e800b0f94391",
          "sha1": "0d5be6f1675f7fc4117e118c9c2cae60abe500e7",
          "md5": "8bb6cab16f4e606d8058ba3fc325f348"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-samples-1.4.0-beta01.aar",
          "url": "compose-foundation-samples-1.4.0-beta01.aar",
          "size": 304979,
          "sha512": "d3ebca479e024c9490f85731cb16627a44d3980cd26c22ec0a0afcfff37b88bc6f27fe914e15282d6ba3c8d9c7d13ae68ba010d7632c7c0329eee0df48244a23",
          "sha256": "6b46569f445b728ed68355b38028affcbe3c29104b92f3461becfe421209a56e",
          "sha1": "574b051d0cbd018e6f4ddb9469fb445c440c568f",
          "md5": "78f62ab43ededf9279986c3d70406e5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "compose-foundation-samples is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-samples-1.4.0-beta01.aar",
          "url": "compose-foundation-samples-1.4.0-beta01.aar",
          "size": 304979,
          "sha512": "d3ebca479e024c9490f85731cb16627a44d3980cd26c22ec0a0afcfff37b88bc6f27fe914e15282d6ba3c8d9c7d13ae68ba010d7632c7c0329eee0df48244a23",
          "sha256": "6b46569f445b728ed68355b38028affcbe3c29104b92f3461becfe421209a56e",
          "sha1": "574b051d0cbd018e6f4ddb9469fb445c440c568f",
          "md5": "78f62ab43ededf9279986c3d70406e5a"
        }
      ]
    }
  ]
}