{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core-samples",
    "version": "1.6.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-samples-1.6.0-alpha08.aar",
          "url": "material-icons-core-samples-1.6.0-alpha08.aar",
          "size": 8214,
          "sha512": "5b800f4f953ec7f3eb6256d1b1e8d1437cd9748bc81a9bcf06e5d5991b5ac418dee9bea0a3279859d49143eb2c3c3ecec300c9414143ffb307d9a4118317ca90",
          "sha256": "1dfccf3422d6d7a4a65de2707a4ed56fe2233117a7e12daec56059d3b5652dfa",
          "sha1": "7d2551f2a07d3f343558104bb93f2819e8fc2a33",
          "md5": "4adb85e55f61b7fffedf503f86a1b692"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-samples-1.6.0-alpha08.aar",
          "url": "material-icons-core-samples-1.6.0-alpha08.aar",
          "size": 8214,
          "sha512": "5b800f4f953ec7f3eb6256d1b1e8d1437cd9748bc81a9bcf06e5d5991b5ac418dee9bea0a3279859d49143eb2c3c3ecec300c9414143ffb307d9a4118317ca90",
          "sha256": "1dfccf3422d6d7a4a65de2707a4ed56fe2233117a7e12daec56059d3b5652dfa",
          "sha1": "7d2551f2a07d3f343558104bb93f2819e8fc2a33",
          "md5": "4adb85e55f61b7fffedf503f86a1b692"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha08"
          },
          "reason": "material-icons-core-samples is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-samples-1.6.0-alpha08-sources.jar",
          "url": "material-icons-core-samples-1.6.0-alpha08-sources.jar",
          "size": 1849,
          "sha512": "5e82b6fc611569270b0a77b159588b3d249a31627630b5e8a1eeb18b462eca347a9a9dfd07bac984a4b1b3df6d71fd490fda7a6f07995b5fcaaee4c2f038ec6c",
          "sha256": "262d79cf95faf69f89988b01d568d48b69742a95b0959b9238e2e797457938fa",
          "sha1": "578ff7394b718fb34c333c24bcfade35ccba41c5",
          "md5": "6dfd44933714f319df97b87cf801f994"
        }
      ]
    }
  ]
}