{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.heifwriter",
    "module": "heifwriter",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14278171"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "heifwriter-1.2.0-alpha01-sources.jar",
          "url": "heifwriter-1.2.0-alpha01-sources.jar",
          "size": 44446,
          "sha512": "08757559249e43144f1ee773cb06f8cee99ec3dfbda0801fe49acca23e79e6d07c6395ec37afb5bab6f6f96e5cc7f3aec49c211c51246b7cc991a8ade92e3316",
          "sha256": "00c07d7aab13ee448a8ae12f7b0cdefe49901236056a0d313b30dab1650d5709",
          "sha1": "ae48a3ead57a60b681a3bdb443ddbcda9201ab7d",
          "md5": "bd9c5442af99493f835c9b9696dbf091"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "heifwriter-1.2.0-alpha01.aar",
          "url": "heifwriter-1.2.0-alpha01.aar",
          "size": 56416,
          "sha512": "fb51942f4b498c994a084c41282debec60fe37c5a77d563422e4846d50913fb9d9d3ab1c458abf62c881c0eef712a9633e513373af7592cddd601c36de9b5793",
          "sha256": "0d70e41a1d6eed7ebaa189ed6530c161771621aa0edecf668c83f628886b4d1a",
          "sha1": "09fe5c8816dc7256ea1a32852f21ae23e8dd0a01",
          "md5": "e85bd9cc42bbdcaf55086faef48b15c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "heifwriter-1.2.0-alpha01.aar",
          "url": "heifwriter-1.2.0-alpha01.aar",
          "size": 56416,
          "sha512": "fb51942f4b498c994a084c41282debec60fe37c5a77d563422e4846d50913fb9d9d3ab1c458abf62c881c0eef712a9633e513373af7592cddd601c36de9b5793",
          "sha256": "0d70e41a1d6eed7ebaa189ed6530c161771621aa0edecf668c83f628886b4d1a",
          "sha1": "09fe5c8816dc7256ea1a32852f21ae23e8dd0a01",
          "md5": "e85bd9cc42bbdcaf55086faef48b15c8"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "heifwriter-1.2.0-alpha01-versionMetadata.json",
          "url": "heifwriter-1.2.0-alpha01-versionMetadata.json",
          "size": 4569,
          "sha512": "b49abdd88a6da8cab2bb56a3de3c82e3b2a14bf192ffe4bbcb529df28867a7f2bc18926f7fdcf70db24e686422cbd598a0918e911b32d36363c2a9064c03d55f",
          "sha256": "55b08b460a3ddac76350570f365596898c7f1711759ee892336b023b063f84d2",
          "sha1": "8d82723fbbf919a00e3eb234de02f08c19bc60ee",
          "md5": "5858afa8ddc20718805fceb09cbd9d3b"
        }
      ]
    }
  ]
}