{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-performance",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-performance-1.0.0-alpha03.aar",
          "url": "core-performance-1.0.0-alpha03.aar",
          "size": 7301,
          "sha512": "c1b67ed7f91b4aab1f53f0e2b5ceb3cf37ffc19fc50a12006e572494cc0b338647f2632099d8808c0e5aa11bdd2d884399041eacf3236ad04fbd13e5adc91cc7",
          "sha256": "8920da65c0d645a0d458b3249cac3ecc81c4d46e3fd0fefe630bc86d8dcaec23",
          "sha1": "47731c0415d721a33a7ecf3a47c4fb0459393067",
          "md5": "ddc90522176c102797f7f781481e4ae2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "core-performance-1.0.0-alpha03.aar",
          "url": "core-performance-1.0.0-alpha03.aar",
          "size": 7301,
          "sha512": "c1b67ed7f91b4aab1f53f0e2b5ceb3cf37ffc19fc50a12006e572494cc0b338647f2632099d8808c0e5aa11bdd2d884399041eacf3236ad04fbd13e5adc91cc7",
          "sha256": "8920da65c0d645a0d458b3249cac3ecc81c4d46e3fd0fefe630bc86d8dcaec23",
          "sha1": "47731c0415d721a33a7ecf3a47c4fb0459393067",
          "md5": "ddc90522176c102797f7f781481e4ae2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-performance-1.0.0-alpha03-sources.jar",
          "url": "core-performance-1.0.0-alpha03-sources.jar",
          "size": 2941,
          "sha512": "6c8e20687cd53b52d89ab44144904ec29b2c67202188b48c9530172536a2a63f5739ad1d3887614d2ef148d36abd29f9035ad5e7a1f6b7fdc499d738a8f01f3c",
          "sha256": "b8df3012fb6d2e57b0f3468bae246b155461dee122f5a16e249761c07d42ace3",
          "sha1": "a594cddd59c07bed6a89e71a33d8672276707608",
          "md5": "adfb08739385a87f5ba16c73124a8d78"
        }
      ]
    }
  ]
}