{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.startup",
    "module": "startup-runtime",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "startup-runtime-1.2.0-alpha02.aar",
          "url": "startup-runtime-1.2.0-alpha02.aar",
          "size": 20274,
          "sha512": "0cc05bdde0ca30a53d09d6bfee04e593461e1d7d98ca6e972316587bd981c39b250c2c5b30fd3b72d19421c259b142f58cfe51262a8c53622aa5f5b5392bde3c",
          "sha256": "9c45c97abe1141894f625f4182623f8647a50cf06c1651e86bf5f31ff19a6d6e",
          "sha1": "8a3aa132063185faaeb775558a9a4c59ba11d120",
          "md5": "8c63cde21cabad0be1a5d0c57b35e7c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "startup-runtime-1.2.0-alpha02.aar",
          "url": "startup-runtime-1.2.0-alpha02.aar",
          "size": 20274,
          "sha512": "0cc05bdde0ca30a53d09d6bfee04e593461e1d7d98ca6e972316587bd981c39b250c2c5b30fd3b72d19421c259b142f58cfe51262a8c53622aa5f5b5392bde3c",
          "sha256": "9c45c97abe1141894f625f4182623f8647a50cf06c1651e86bf5f31ff19a6d6e",
          "sha1": "8a3aa132063185faaeb775558a9a4c59ba11d120",
          "md5": "8c63cde21cabad0be1a5d0c57b35e7c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "startup-runtime-1.2.0-alpha02-sources.jar",
          "url": "startup-runtime-1.2.0-alpha02-sources.jar",
          "size": 6957,
          "sha512": "4841017712daa8e8cbb54c1b03a118fce0445d1f60a6699d77b223dd3397543ca24b269fe91e05d143659a0cade40873c1e4c40be71beabc0916be5c4ef0b505",
          "sha256": "6a3a0749b8e6037a8ef7cf977ee18298f4eb471def461fc3ba55ea5258527737",
          "sha1": "76558a92d9a945a5f5880a06e8ba58cd542e12aa",
          "md5": "e0bb69cb0059c194ec261877447466c5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "startup-runtime-1.2.0-alpha02-versionMetadata.json",
          "url": "startup-runtime-1.2.0-alpha02-versionMetadata.json"
        }
      ]
    }
  ]
}