{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.8.0-alpha03/runtime-saveable-1.8.0-alpha03.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.8.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable.klib",
          "url": "runtime-saveable-linuxx64stubs-1.8.0-alpha03.klib",
          "size": 44681,
          "sha512": "e6cf5798bef4a71bc4b5b17e2d173164f376b2f593095491e12aa1de6de136af5ad963a8c75863de6461dd1746624b188092ae1f239eaa65e9f651239b48619b",
          "sha256": "ac1a772707f7491dee989b9e0bd0748d17108e77fca3488757d332004a275270",
          "sha1": "e325298ea4576e59597fcf06a817066d948ef12e",
          "md5": "829ed70605ea2fafd5cf7ffa247a2a8d"
        }
      ]
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-linuxx64stubs-1.8.0-alpha03-sources.jar",
          "url": "runtime-saveable-linuxx64stubs-1.8.0-alpha03-sources.jar",
          "size": 16244,
          "sha512": "2b09b948b548c02b7cbfd21ddb4f44acbc0a50da30d411f5987e99727f316a1ab0abbcd015d2fdc786565a59daa167c986dec5c2593ed6c1514d34875f17fa46",
          "sha256": "ae70add17dd2954c10d21545f3f7e4ec6018e4f8b94ddabca0754fabe4f8d583",
          "sha1": "21a62ad898d445c6d84dc78d172336032ebfe0cc",
          "md5": "19abfecd1e4af393c36242ccaf7d634a"
        }
      ]
    }
  ]
}