{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media2",
    "module": "media2-common",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "7079094"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "media2-common-1.1.2.aar",
          "url": "media2-common-1.1.2.aar",
          "size": 50357,
          "sha512": "e044b1ad3785d314ae66f0a7736341921cb4668fb908f925ef7d6b63a140dc26737c810f27811ef145c8840c538f6382b07df29e580dca7d555394d28411cccd",
          "sha256": "5d286be71e9176b163275024a40b8ef0b0791cca79f2e07c73bb56e15492edc8",
          "sha1": "659368a5f45ab57c2fd164ed80cff24509c875cc",
          "md5": "382fdf20a5650df9d36dfa5973685d06"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "media2-common-1.1.2.aar",
          "url": "media2-common-1.1.2.aar",
          "size": 50357,
          "sha512": "e044b1ad3785d314ae66f0a7736341921cb4668fb908f925ef7d6b63a140dc26737c810f27811ef145c8840c538f6382b07df29e580dca7d555394d28411cccd",
          "sha256": "5d286be71e9176b163275024a40b8ef0b0791cca79f2e07c73bb56e15492edc8",
          "sha1": "659368a5f45ab57c2fd164ed80cff24509c875cc",
          "md5": "382fdf20a5650df9d36dfa5973685d06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media2-common-1.1.2-sources.jar",
          "url": "media2-common-1.1.2-sources.jar",
          "size": 40693,
          "sha512": "e41a398511c437c65a154aa99f353961aaf31f93c28966426b4aa0886df859ac5f7c6bb07116ebbbe1d65e1895cd58344ffbf5568ef82d8fefad16b07454cb8b",
          "sha256": "466a1017e4b389bdc2323dad3f10f0b2f1a6ee8faa4de0574270d0acb6c92319",
          "sha1": "8c5e2a32a5ed53f6d0d45cc355f0e8b6d8a3c4ea",
          "md5": "220c612640340f9508f6345fc06986b3"
        }
      ]
    }
  ]
}
