{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core-samples",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material-icons-core-samples-1.2.0-alpha03.aar",
          "url": "material-icons-core-samples-1.2.0-alpha03.aar",
          "size": 6458,
          "sha512": "8191f6c3eb8e6a796428c0cfa8684ab8ada0cba97ffb0317b8eac7f259b1252a4d1cb6aaf8cc1a13de7ebc581adca3da8561d57a2b655df46fa77e89224fa5e1",
          "sha256": "531e505807d8f25d611455381d0c64cb7d662681bbfbe02667bd98d1d91c7f69",
          "sha1": "822a35e5e61f9676b8408533d5732e34bca0d8a6",
          "md5": "04598aa76d63f2e63a16a21021988167"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-samples-1.2.0-alpha03.aar",
          "url": "material-icons-core-samples-1.2.0-alpha03.aar",
          "size": 6458,
          "sha512": "8191f6c3eb8e6a796428c0cfa8684ab8ada0cba97ffb0317b8eac7f259b1252a4d1cb6aaf8cc1a13de7ebc581adca3da8561d57a2b655df46fa77e89224fa5e1",
          "sha256": "531e505807d8f25d611455381d0c64cb7d662681bbfbe02667bd98d1d91c7f69",
          "sha1": "822a35e5e61f9676b8408533d5732e34bca0d8a6",
          "md5": "04598aa76d63f2e63a16a21021988167"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-core-samples-1.2.0-alpha03-sources.jar",
          "url": "material-icons-core-samples-1.2.0-alpha03-sources.jar",
          "size": 1766,
          "sha512": "9af01cbd272d59183f057711ecb3d1815afe46d28712c6425f61265b394c184bf2dc7419ab6f7ced8b9a85d7be5ffc354744b1c0a356f8fa1ca151e38f28e107",
          "sha256": "a8b20c285a14ba89883d5f50e8d29804b0660a5fb5fe63ab6542b62306fc3832",
          "sha1": "fdcdcc37a0964ac7056aa4566a52fe2f9cb3c4f2",
          "md5": "d39e231a67cc1cf1ef4fbe133163c263"
        }
      ]
    }
  ]
}
