{
  "formatVersion": "1.1",
  "component": {
    "url": "../../performance-annotation/1.0.0-alpha01/performance-annotation-1.0.0-alpha01.module",
    "group": "androidx.performance",
    "module": "performance-annotation",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12891226"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.performance",
          "module": "performance-unsafe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "performance-annotation is in atomic group androidx.performance"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "performance-annotation-watchosArm32Main-1.0.0-alpha01.klib",
          "url": "performance-annotation-watchosarm32-1.0.0-alpha01.klib",
          "size": 9706,
          "sha512": "5b7f108a593dc9b20f93cd7d82164407a651c2e65a00b118522dd926f721cf339975af33a052011182d6acfbd538fce3d8edbeb9916e784fdb441079d67e7829",
          "sha256": "052ef309b916ee3dbad9a16004f4f68cb0b7bb949275a17ab6eef46ecad71846",
          "sha1": "f940e4cf9ebd06eb3a2a78da9767f18e2d3acd17",
          "md5": "b20f928450353d58d8a6a54eb7c91f32"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.performance",
          "module": "performance-unsafe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "performance-annotation is in atomic group androidx.performance"
        }
      ],
      "files": [
        {
          "name": "performance-annotation-watchosarm32-1.0.0-alpha01-sources.jar",
          "url": "performance-annotation-watchosarm32-1.0.0-alpha01-sources.jar",
          "size": 5989,
          "sha512": "884060442eaf56306b1fc31fb24b6e8ef898210f37fcc5506c422d8e8f894206bbb94a818ae3e89207183ec5378bdde4e59456a5f9f9f5dacd7f91b6e295a8b9",
          "sha256": "8ae9442e4c57ca5d8bdd4c2c722444caf9163d23ebb49cb452a61b20dee72f6f",
          "sha1": "30961ced12992f4aaee7c1bb1701778d30a53459",
          "md5": "361d1825e8c616c81a31135208df7006"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.performance",
          "module": "performance-unsafe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "performance-annotation is in atomic group androidx.performance"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "performance-annotation-watchosarm32-1.0.0-alpha01-metadata.jar",
          "url": "performance-annotation-watchosarm32-1.0.0-alpha01-metadata.jar",
          "size": 4464,
          "sha512": "aa6df945874a996af8a4ed7c3e97dea0113c80394e0a87e6998cfe2f5886f29800d408c9cae0f2cbfabfb15f1a2fe874550b408dec842022019d0bc1c4d85b83",
          "sha256": "dd04d811b79ce36ed6135b386fd19712bafd2371d94b1ad1893b257def9333d4",
          "sha1": "4a87a36be9c7d38576221a704dd55a199ff18767",
          "md5": "c94bae4242897acc1aa2fb5ac88b609f"
        }
      ]
    }
  ]
}