{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.health.connect",
    "module": "connect-client-samples",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13169740"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "connect-client-samples is in atomic group androidx.health.connect"
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client-proto",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "connect-client-samples is in atomic group androidx.health.connect"
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client-external-protobuf",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "connect-client-samples is in atomic group androidx.health.connect"
        }
      ],
      "files": [
        {
          "name": "connect-client-samples-1.1.0-beta01-sources.jar",
          "url": "connect-client-samples-1.1.0-beta01-sources.jar",
          "size": 13378,
          "sha512": "65bc95741a70f3aec5f63b3898189d85ca06afa9ffdf17275396ac6bdcab07050a525446895ed69c525f2dc20e3c1ad9d89fd6ca6da2f012a971fa25d9b4642a",
          "sha256": "5184f07712f8dd4d3a98fd1a1eb2009e5145d77bcf0e2d27b685c490ea8b6543",
          "sha1": "59606f3b75459ddbb8dd454a2c0d18188f1de06a",
          "md5": "65c98fd40b29a390c29557edc4be07f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "connect-client-samples is in atomic group androidx.health.connect"
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client-proto",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "connect-client-samples is in atomic group androidx.health.connect"
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client-external-protobuf",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "connect-client-samples is in atomic group androidx.health.connect"
        }
      ],
      "files": [
        {
          "name": "connect-client-samples-1.1.0-beta01.aar",
          "url": "connect-client-samples-1.1.0-beta01.aar",
          "size": 36549,
          "sha512": "1f7d8d001b5d242cac0f26ad8ef249c927a9c397b7b140c91cf11a1d36f5490c0a22188621b1d16946514bd9a7dd60f91bc7920147e12cbabf17b2cdaccb2427",
          "sha256": "af4059e4dcb83688b0cd2f790c2537007ec409efd49db25b420c94cfe4287e02",
          "sha1": "5e9f39437fc142fd0a7d0fc2139d01dbbb5f063f",
          "md5": "3185b53c14f47ebd375d228d0aa6091a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "connect-client-samples is in atomic group androidx.health.connect"
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client-proto",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "connect-client-samples is in atomic group androidx.health.connect"
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client-external-protobuf",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "connect-client-samples is in atomic group androidx.health.connect"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "connect-client-samples-1.1.0-beta01.aar",
          "url": "connect-client-samples-1.1.0-beta01.aar",
          "size": 36549,
          "sha512": "1f7d8d001b5d242cac0f26ad8ef249c927a9c397b7b140c91cf11a1d36f5490c0a22188621b1d16946514bd9a7dd60f91bc7920147e12cbabf17b2cdaccb2427",
          "sha256": "af4059e4dcb83688b0cd2f790c2537007ec409efd49db25b420c94cfe4287e02",
          "sha1": "5e9f39437fc142fd0a7d0fc2139d01dbbb5f063f",
          "md5": "3185b53c14f47ebd375d228d0aa6091a"
        }
      ]
    }
  ]
}