{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core-samples",
    "version": "1.2.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "animation-core-samples-1.2.0-alpha08.aar",
          "url": "animation-core-samples-1.2.0-alpha08.aar",
          "size": 142525,
          "sha512": "8b750088876d8ba9bab05d59419ab0b906ccf39125df767ed4ceffd9599875a4ed333f4dabf4ec5e023de2e2ea05d72e8dc0a1c0042c6012bdaffecd1362aa6b",
          "sha256": "1cb10d5013532174d9d5d38b22c1d7733e4a09a9e248dbdaf94bfe5d68ac9aeb",
          "sha1": "8b190963ee3538f34cd85a4bb921de9eee4bd9e5",
          "md5": "9ef3aa5b336d42174f2d51043e9fafed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.2.0-alpha08.aar",
          "url": "animation-core-samples-1.2.0-alpha08.aar",
          "size": 142525,
          "sha512": "8b750088876d8ba9bab05d59419ab0b906ccf39125df767ed4ceffd9599875a4ed333f4dabf4ec5e023de2e2ea05d72e8dc0a1c0042c6012bdaffecd1362aa6b",
          "sha256": "1cb10d5013532174d9d5d38b22c1d7733e4a09a9e248dbdaf94bfe5d68ac9aeb",
          "sha1": "8b190963ee3538f34cd85a4bb921de9eee4bd9e5",
          "md5": "9ef3aa5b336d42174f2d51043e9fafed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-samples-1.2.0-alpha08-sources.jar",
          "url": "animation-core-samples-1.2.0-alpha08-sources.jar",
          "size": 16170,
          "sha512": "5c70e3b0ec6e46d316767929753ef790088fda06dae6ada30908816f46f0150587802312da8b46ef666443970ccdcab5bb02a34d8c320780aded2f908be9d2fd",
          "sha256": "adf21cbfbeebf807c918ec1e2d839b2d4d182497dc71607f26cfd7863c6a49bb",
          "sha1": "b8d0480b0af6fc7d8aa32526989e4489f6aa3037",
          "md5": "44452c0d018a153c340c66c3af8c5dcd"
        }
      ]
    }
  ]
}