{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core/1.1.2/datastore-core-1.1.2.module",
    "group": "androidx.datastore",
    "module": "datastore-core",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-release.aar",
          "url": "datastore-core-android-1.1.2.aar",
          "size": 198997,
          "sha512": "742ca8c8a732926245fed90f74ec1a97fcb771016c7c1b44673482137e585d4000761d128daf59033c14277a737756802810d6c01f9ca68bc4f6672252bedcd0",
          "sha256": "0d59326c89da3f404f9ea801b55f250b5c66211875914538a53c1daa0c6f39f7",
          "sha1": "66c188fa1253fcd9cfb2dfc3d161ddeec5987259",
          "md5": "ac01d9e0062c8a03a728312bafddb425"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.9.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-release.aar",
          "url": "datastore-core-android-1.1.2.aar",
          "size": 198997,
          "sha512": "742ca8c8a732926245fed90f74ec1a97fcb771016c7c1b44673482137e585d4000761d128daf59033c14277a737756802810d6c01f9ca68bc4f6672252bedcd0",
          "sha256": "0d59326c89da3f404f9ea801b55f250b5c66211875914538a53c1daa0c6f39f7",
          "sha1": "66c188fa1253fcd9cfb2dfc3d161ddeec5987259",
          "md5": "ac01d9e0062c8a03a728312bafddb425"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.2"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-android-1.1.2-sources.jar",
          "url": "datastore-core-android-1.1.2-sources.jar",
          "size": 50290,
          "sha512": "34f50cb01deb6f4070b4d5b32881a248fc52dd7fc0f077035fa542f9cdd6ff8ece9d5ac67e5197859007434434a23a8d8def2a36ae987d9a154b00ab5ca87542",
          "sha256": "0450c809f780beb2627ffdb43fbc5cdccf29284cf4c06e42488c28d1155b9697",
          "sha1": "b97b8d7afa5020ee10f7bf2e7ed68beeadfcfc93",
          "md5": "f19d42afdefcfdb57399ed49616f2c0b"
        }
      ]
    }
  ]
}