{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7001724"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-alpha08.aar",
          "url": "ui-unit-1.0.0-alpha08.aar",
          "size": 79024,
          "sha512": "d7928b7e1d2afa4f67ecbd9aabcb2f82132740dc20407c54b92daadd6ba98e66013108cfa874314bc6855425f89d638e594fd19534a2418190c3fbc8d519dc71",
          "sha256": "8cfa7bea83c85b060be0ccde36dfe21d30372bbf91db25845f8cf09bada47a1b",
          "sha1": "577aa2d5b90d92e35c7caa9d94dae8fc74117213",
          "md5": "326d8fc5c568cacb8c5c702fa19a9de1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.20"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-alpha08.aar",
          "url": "ui-unit-1.0.0-alpha08.aar",
          "size": 79024,
          "sha512": "d7928b7e1d2afa4f67ecbd9aabcb2f82132740dc20407c54b92daadd6ba98e66013108cfa874314bc6855425f89d638e594fd19534a2418190c3fbc8d519dc71",
          "sha256": "8cfa7bea83c85b060be0ccde36dfe21d30372bbf91db25845f8cf09bada47a1b",
          "sha1": "577aa2d5b90d92e35c7caa9d94dae8fc74117213",
          "md5": "326d8fc5c568cacb8c5c702fa19a9de1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-1.0.0-alpha08-sources.jar",
          "url": "ui-unit-1.0.0-alpha08-sources.jar",
          "size": 25704,
          "sha512": "e6ecdee32b5eedcae6d75646464771dc0688d111f97e73c941c395328b42e1d4cdbad0715a487513b864635353c93d338a5bf9dc5b59a39f040c0f19384f82c7",
          "sha256": "d020586e2cd18a3a8c9706dcb9c847883dc1c0ee37ab411855509c261e7e344a",
          "sha1": "47b25069000bb43b0a7554251e672a23fa1c8096",
          "md5": "4fd2b7f3927ee1ac38f0ab122f6ee48e"
        }
      ]
    }
  ]
}
