{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit-samples",
    "version": "1.8.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-unit-samples-1.8.0-alpha04-sources.jar",
          "url": "ui-unit-samples-1.8.0-alpha04-sources.jar",
          "size": 6730,
          "sha512": "bb4d7f85932494534ca278a02f58a62fa1c96812da503cfc08748a67ac014bfc9a00b5e6f2c7d5ddcdf27a1766897dc3d6dd81c2ff0ecc57712ee73c76211270",
          "sha256": "1b2424a27627c8073d4a253b1a33c4078f8afa26c116e3b544a023794e01dbd8",
          "sha1": "945c3e336baa7d3c4389d8a5d581056773eb170a",
          "md5": "fa83a021efb8e31c87343ae15f9a1331"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-unit-samples-1.8.0-alpha04.aar",
          "url": "ui-unit-samples-1.8.0-alpha04.aar",
          "size": 14301,
          "sha512": "f5f4b84d010b3a46b95347cb01b20d8614984a2dd6b51de31597cdabc05a5e2cc27c9c65ab94dfb2210e382f593d6716558f732dc1df8a8ef184b2ad0a4d624e",
          "sha256": "fd893c34608ca70ec62a48e67c0d092d762f1f8b93eb2cbf2b199e3964c0a338",
          "sha1": "8baf8a4a5dbc5dec7dff072062670ce26936a8ef",
          "md5": "e6616beedaf75d39c37d9fe38d54392a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha04"
          },
          "reason": "ui-unit-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-unit-samples-1.8.0-alpha04.aar",
          "url": "ui-unit-samples-1.8.0-alpha04.aar",
          "size": 14301,
          "sha512": "f5f4b84d010b3a46b95347cb01b20d8614984a2dd6b51de31597cdabc05a5e2cc27c9c65ab94dfb2210e382f593d6716558f732dc1df8a8ef184b2ad0a4d624e",
          "sha256": "fd893c34608ca70ec62a48e67c0d092d762f1f8b93eb2cbf2b199e3964c0a338",
          "sha1": "8baf8a4a5dbc5dec7dff072062670ce26936a8ef",
          "md5": "e6616beedaf75d39c37d9fe38d54392a"
        }
      ]
    }
  ]
}