{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.webkit",
    "module": "webkit",
    "version": "1.13.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12891226"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "webkit-1.13.0-alpha03-sources.jar",
          "url": "webkit-1.13.0-alpha03-sources.jar",
          "size": 215295,
          "sha512": "04b9495f875f21798bef2010c884b517091d5d0c06456dbfbd0fdd1425ff4ecf5c4295af4041d0c9eafa7bf26dd8bc493b8e48493c5f5d21f2d8f1d4cf48e1a8",
          "sha256": "1472d264864fb5572a09241d9abda8f839d68944df8397f92c45c175869402ee",
          "sha1": "5b7c738d4f89f62083bdd7cbc636872176f09755",
          "md5": "128d7006813afa9c89c147068aa07d8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.13.0-alpha03.aar",
          "url": "webkit-1.13.0-alpha03.aar",
          "size": 203915,
          "sha512": "ba0812e60078fc270b7134eeec33f224233a1b2ec2994c23273ea055727298bfa16ad7810c3638a6ecd1c8d29a51658d0e2986c6d08b03507861a72bdb79ef5c",
          "sha256": "6d4612e60d7d076bb563f149fe4bdc23881d14255fc29ac9225348e78ab594cf",
          "sha1": "26ff9710e7063f03ed4f448bd6eac9953589dad4",
          "md5": "6d6ddbfff7479c6b328ecf7586dc28ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "webkit-1.13.0-alpha03.aar",
          "url": "webkit-1.13.0-alpha03.aar",
          "size": 203915,
          "sha512": "ba0812e60078fc270b7134eeec33f224233a1b2ec2994c23273ea055727298bfa16ad7810c3638a6ecd1c8d29a51658d0e2986c6d08b03507861a72bdb79ef5c",
          "sha256": "6d4612e60d7d076bb563f149fe4bdc23881d14255fc29ac9225348e78ab594cf",
          "sha1": "26ff9710e7063f03ed4f448bd6eac9953589dad4",
          "md5": "6d6ddbfff7479c6b328ecf7586dc28ae"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "webkit-1.13.0-alpha03-versionMetadata.json",
          "url": "webkit-1.13.0-alpha03-versionMetadata.json",
          "size": 32304,
          "sha512": "82a3f9b9f0cbac553b5cd979627b6f9ad38136812105fd9127d09b1b657b11bb0ba436103b6cd60b736ac7472fefdd37a8e08780f430c9b35009e2a7621c55d9",
          "sha256": "4555ad1e32f83af1781369057aa42bf556ff293a196fa40aa0a8bcb1cd599f62",
          "sha1": "fb2ecf529018a1fa61ac8fc7f97913592cdba43f",
          "md5": "32852d5860eccee3b0eff085ebd28797"
        }
      ]
    }
  ]
}