{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava2-samples",
    "version": "1.0.0-beta06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7321851"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.0.0-beta06.aar",
          "url": "runtime-rxjava2-samples-1.0.0-beta06.aar",
          "size": 10474,
          "sha512": "132d234b9d46c8f54031ad322559209899428444e4a5957fbaef27a05bf73d15c7e36a4b834d3b32766e5736ab96d4f4d2b6709ecc1cd125be59cb47d5f32290",
          "sha256": "4cd9be91d690c222ee21a8316c0809fc37d6b4bccfc9de48abca96010683375a",
          "sha1": "528a385a63452d49faf55e4a1de3352262503096",
          "md5": "95bd0e52584807cb3fc2985cec98965e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-beta06"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0-beta06"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.0.0-beta06"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.0.0-beta06.aar",
          "url": "runtime-rxjava2-samples-1.0.0-beta06.aar",
          "size": 10474,
          "sha512": "132d234b9d46c8f54031ad322559209899428444e4a5957fbaef27a05bf73d15c7e36a4b834d3b32766e5736ab96d4f4d2b6709ecc1cd125be59cb47d5f32290",
          "sha256": "4cd9be91d690c222ee21a8316c0809fc37d6b4bccfc9de48abca96010683375a",
          "sha1": "528a385a63452d49faf55e4a1de3352262503096",
          "md5": "95bd0e52584807cb3fc2985cec98965e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.0.0-beta06-sources.jar",
          "url": "runtime-rxjava2-samples-1.0.0-beta06-sources.jar",
          "size": 1747,
          "sha512": "a08d4e95552c2cebc0b12252dd8e92565f8dd628057f6763622f78b3c5a89d8905be477146474ecd210ccb392a34625e2a49578bad2af7c067db00b5a19f4e3d",
          "sha256": "0989f77f4130ca4ddb4a74173b051b4ec120f7dc52bb6690e93086b67186896d",
          "sha1": "5b71b7363219375ff52e3f6a799fe295d73134a6",
          "md5": "fec176d1c82b6fb1cab031f458465d9e"
        }
      ]
    }
  ]
}
