{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-guava",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7546089"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "paging-guava-3.0.1.aar",
          "url": "paging-guava-3.0.1.aar",
          "size": 20766,
          "sha512": "b8d3a7231c758e68bfbfaf424ad38d780a8a741af32df686c69279934495693dc940b3cedbeafa9b82c397bc1ec8e2ac1ef4d6498e7e0b706e6b927fab0552ce",
          "sha256": "9e75c7e15ad1ef8870e9d3a6bb17633e9e430a414a2536f4cc000489ce2cd93a",
          "sha1": "820cde5c5da36691c3f517073ef836c7c192b085",
          "md5": "ddb51f5474b5ebd7e6165f9e355e2cbe"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "paging-guava-3.0.1.aar",
          "url": "paging-guava-3.0.1.aar",
          "size": 20766,
          "sha512": "b8d3a7231c758e68bfbfaf424ad38d780a8a741af32df686c69279934495693dc940b3cedbeafa9b82c397bc1ec8e2ac1ef4d6498e7e0b706e6b927fab0552ce",
          "sha256": "9e75c7e15ad1ef8870e9d3a6bb17633e9e430a414a2536f4cc000489ce2cd93a",
          "sha1": "820cde5c5da36691c3f517073ef836c7c192b085",
          "md5": "ddb51f5474b5ebd7e6165f9e355e2cbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-guava-3.0.1-sources.jar",
          "url": "paging-guava-3.0.1-sources.jar",
          "size": 4782,
          "sha512": "8fc0f498cb309315546049c3b8d6259c4f53224252126b3562286e74ee8dac4deb9c549eca37bb8d8907800386800cdc11613823632a061b095622394b5d275e",
          "sha256": "b493a6ff80a46b7786e0dd57269b148e64d2ca8fe7b4e965464cdd62c0b431af",
          "sha1": "54a3751815014aae94b6403f89fbdbeca7cb7fb4",
          "md5": "aa573d5d66dd4b0e9e4a68ee8dc91d22"
        }
      ]
    }
  ]
}
