{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment",
    "version": "1.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.6-sources.jar",
          "url": "fragment-1.8.6-sources.jar",
          "size": 200947,
          "sha512": "1014061ddf02476f15843766c73bc6e309bebfdd426ccad2b8a2259d05b3108de11ae145f7aadfc91930e41acb8b1bf2444294fb97f9bc9916f6352d186267ee",
          "sha256": "bb152086ddddb6eedb31fdc1cb9da825ad317223520a7bd6755d722ff3789126",
          "sha1": "f028494dcc7ceac0a250522b38a8a093772f10db",
          "md5": "6bc9bf895d069fbc36dc1a18a61dcc61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.6.aar",
          "url": "fragment-1.8.6.aar",
          "size": 382526,
          "sha512": "26a9c5828fa2ae03a70e82685417f751c6961f1d3b47be2a21d4b23c952488288115ca5a63f0e097e47b81210ae98098920c84f38997462d1f6624d1bd91d643",
          "sha256": "6d5aa4c135247a7f8b59ef5d0bb2990f3a8d6502f02c763c8d34df8a410a3731",
          "sha1": "d440d8c0da33f552d24f5646202e732252868332",
          "md5": "2e351dc25160a2d7157522d16a85c86f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.6.aar",
          "url": "fragment-1.8.6.aar",
          "size": 382526,
          "sha512": "26a9c5828fa2ae03a70e82685417f751c6961f1d3b47be2a21d4b23c952488288115ca5a63f0e097e47b81210ae98098920c84f38997462d1f6624d1bd91d643",
          "sha256": "6d5aa4c135247a7f8b59ef5d0bb2990f3a8d6502f02c763c8d34df8a410a3731",
          "sha1": "d440d8c0da33f552d24f5646202e732252868332",
          "md5": "2e351dc25160a2d7157522d16a85c86f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.6"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.6-versionMetadata.json",
          "url": "fragment-1.8.6-versionMetadata.json",
          "size": 37214,
          "sha512": "8091dc4641cf1e8d08c895e19150cba5b6aa900c0848ab8a580d51cce261caa67d78610e6cf47c906bb95a8c2e23544476940477ffc26634117e205310c8a608",
          "sha256": "7f8a28c400645b4175bd7c392ac0ad91d782155ef5989759a601191027dcd58f",
          "sha1": "091fa5aaa74874b5681847d5914a7b68331f7593",
          "md5": "ec893e4da7ae0d7b7e9625150a73ad2d"
        }
      ]
    }
  ]
}