{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-testing",
    "version": "2.9.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-testing-2.9.0-alpha06-multiplatform-sources.jar",
          "url": "lifecycle-viewmodel-testing-2.9.0-alpha06-multiplatform-sources.jar",
          "size": 12727,
          "sha512": "676f3f501652b3a17f3f5d800ba84b907275721935c7df115204ef11eb957e923491ac67d05bc687adb1f380330a35a1633b694e48ed14a210a9c6dd5a119664",
          "sha256": "280fb8bb06da4f47a3f5b1bede254ab035dcbaf3155c2ed950f5f02f33cbe972",
          "sha1": "d4a9380eec987086eef2f49c01f1c249a1e27497",
          "md5": "25a7308a7dcfc8501965bbacc95dc248"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "lifecycle-viewmodel-testing-2.9.0-alpha06-versionMetadata.json",
          "size": 1048,
          "sha512": "73782f7b0b1aea046e0436514bd3fcd569e5a3414af1e2cea868b4977d8558240cbe97a408a24485067db185dc01e757fe307da11bb6672da5dc41fe56382343",
          "sha256": "27d5af1c0232c3c93df0c5c6063eaf4bdc8b8559d6d38c468ab2e28fa4e180dd",
          "sha1": "f699940058612e7a3579a228ab3b51d234a23dbf",
          "md5": "985e7869391a63353130c1a656184cb5"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-testing-metadata-2.9.0-alpha06.jar",
          "url": "lifecycle-viewmodel-testing-2.9.0-alpha06.jar",
          "size": 13544,
          "sha512": "ad0cfd011997f6aa9dd1a3a0c4dc2d52342bfd4c9d6679dba9440d068ec82a98df637e2b1180d1426d7002c2df78d1e268bdfee95083016823ff6e9c1f26b316",
          "sha256": "09b2dfef55324f4805b7f4fec35c040ff5a1f2c65bea5cd8311785fdd372727a",
          "sha1": "95648a014c7e4996cd223b25c3013e091e38e771",
          "md5": "cdba0d82d16581541f668dac9077f957"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-testing-kotlin-2.9.0-alpha06-sources.jar",
          "url": "lifecycle-viewmodel-testing-2.9.0-alpha06-sources.jar",
          "size": 8841,
          "sha512": "b3baa6d63a279ee945cfa0d4081473faf155f4132d4d6c31b0da2f940420c38837b11943e9d1d5584ae4dc6654b17b5780bb70d306d58e924594e45379a2bfb8",
          "sha256": "320724c958c7f0daf323775613af9c158f80a22c28cc400284b9a730c6188687",
          "sha1": "d3eacd819f7588e33a32c5a1103d2d926b480ae3",
          "md5": "2f72c8c18ea4ef65841cf9193d2a100d"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-android/2.9.0-alpha06/lifecycle-viewmodel-testing-android-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-android",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-android/2.9.0-alpha06/lifecycle-viewmodel-testing-android-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-android",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-android/2.9.0-alpha06/lifecycle-viewmodel-testing-android-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-android",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-desktop/2.9.0-alpha06/lifecycle-viewmodel-testing-desktop-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-desktop",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-desktop/2.9.0-alpha06/lifecycle-viewmodel-testing-desktop-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-desktop",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-desktop/2.9.0-alpha06/lifecycle-viewmodel-testing-desktop-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-desktop",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-iosarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-iosarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-iosarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-iosarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-iosarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-iosarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-iosarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-iosarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-iosarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-iossimulatorarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-iossimulatorarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-iossimulatorarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-iossimulatorarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-iossimulatorarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-iossimulatorarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-iossimulatorarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-iossimulatorarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-iossimulatorarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-iosx64/2.9.0-alpha06/lifecycle-viewmodel-testing-iosx64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-iosx64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-iosx64/2.9.0-alpha06/lifecycle-viewmodel-testing-iosx64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-iosx64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-iosx64/2.9.0-alpha06/lifecycle-viewmodel-testing-iosx64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-iosx64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-linuxarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-linuxarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-linuxarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-linuxarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-linuxarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-linuxarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-linuxx64/2.9.0-alpha06/lifecycle-viewmodel-testing-linuxx64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-linuxx64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-linuxx64/2.9.0-alpha06/lifecycle-viewmodel-testing-linuxx64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-linuxx64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-macosarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-macosarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-macosarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-macosarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-macosarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-macosarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-macosarm64/2.9.0-alpha06/lifecycle-viewmodel-testing-macosarm64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-macosarm64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-macosx64/2.9.0-alpha06/lifecycle-viewmodel-testing-macosx64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-macosx64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-macosx64/2.9.0-alpha06/lifecycle-viewmodel-testing-macosx64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-macosx64",
        "version": "2.9.0-alpha06"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lifecycle-viewmodel-testing-macosx64/2.9.0-alpha06/lifecycle-viewmodel-testing-macosx64-2.9.0-alpha06.module",
        "group": "androidx.lifecycle",
        "module": "lifecycle-viewmodel-testing-macosx64",
        "version": "2.9.0-alpha06"
      }
    }
  ]
}