{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-rxjava3",
    "version": "1.0.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava3-1.0.0-rc01.aar",
          "url": "datastore-preferences-rxjava3-1.0.0-rc01.aar",
          "size": 14280,
          "sha512": "1f25e2f77529ce9fdefd9e428eb3595f16557646c6c5ebfb974f1fa5b76829f60286ee5a411d72e28c3a25421c2d404706db1aca9a017070b6ef2607f3d371b3",
          "sha256": "8e44cff01672ad81e782b23886a644790796976d214b53b74f913463b5910032",
          "sha1": "c9532465b572e56f608e4e22c352edee5bcd3c1e",
          "md5": "aff7456a442b7f1ce2be636f4f7a2803"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx3",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava3-1.0.0-rc01.aar",
          "url": "datastore-preferences-rxjava3-1.0.0-rc01.aar",
          "size": 14280,
          "sha512": "1f25e2f77529ce9fdefd9e428eb3595f16557646c6c5ebfb974f1fa5b76829f60286ee5a411d72e28c3a25421c2d404706db1aca9a017070b6ef2607f3d371b3",
          "sha256": "8e44cff01672ad81e782b23886a644790796976d214b53b74f913463b5910032",
          "sha1": "c9532465b572e56f608e4e22c352edee5bcd3c1e",
          "md5": "aff7456a442b7f1ce2be636f4f7a2803"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datastore-preferences-rxjava3-1.0.0-rc01-sources.jar",
          "url": "datastore-preferences-rxjava3-1.0.0-rc01-sources.jar",
          "size": 5021,
          "sha512": "fc41cfa721f9e82281c7af64d51aa4b46b7561c82e35129f7116d05831ce063724a79836de1e5e7fa5deeb6fd705e604240f4d5abf24fe934526c01a23a05e39",
          "sha256": "a42fe7a579627ddad83bd773f3646fc449195d3534394bd95b7963d1fb842bf7",
          "sha1": "b49378a8921d6fc006d3b44cedf106399be61305",
          "md5": "d2d14997f1146ec82f6a3f663429a67a"
        }
      ]
    }
  ]
}
