{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles-tooling",
    "version": "1.6.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14278171"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-tooling-1.6.0-alpha02-sources.jar",
          "url": "tiles-tooling-1.6.0-alpha02-sources.jar",
          "size": 8954,
          "sha512": "e283c02d19446d26f639d3c6e8cd0f6c0e62246785914b08da313b56144bf2a8bc78acff97d8b918f6839e7a4bd556b1fd1ebcab1968b6763e3625419676c3d1",
          "sha256": "033fafd59c4215beddc8f9df921c065afc64f39e63e38e50c3c75367c3ac64ae",
          "sha1": "ec6772186ae0524df9a1fb99acf8eeb64b15c2a4",
          "md5": "e50ed2bd21f1fb69ae86384875a247ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-tooling-1.6.0-alpha02.aar",
          "url": "tiles-tooling-1.6.0-alpha02.aar",
          "size": 18990,
          "sha512": "7063befabb13cbd538948c781dcc6d3bee044e36fbfa5241ae0176e970d55c907b725ce9e8878f42998b960ef08fdc935d4e96a5b64adf9c41b2e28f2d3d933f",
          "sha256": "cc7cca45474eed18820605b0c3a791ebd0a5d61832683c71392e73d93a68815e",
          "sha1": "8ac121e6ace5db1971f1a97432ba8c613a560f20",
          "md5": "b3d90d7c98a5859ead8a6ef55374f840"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.6.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.6.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-tooling-1.6.0-alpha02.aar",
          "url": "tiles-tooling-1.6.0-alpha02.aar",
          "size": 18990,
          "sha512": "7063befabb13cbd538948c781dcc6d3bee044e36fbfa5241ae0176e970d55c907b725ce9e8878f42998b960ef08fdc935d4e96a5b64adf9c41b2e28f2d3d933f",
          "sha256": "cc7cca45474eed18820605b0c3a791ebd0a5d61832683c71392e73d93a68815e",
          "sha1": "8ac121e6ace5db1971f1a97432ba8c613a560f20",
          "md5": "b3d90d7c98a5859ead8a6ef55374f840"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "tiles-tooling is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-tooling-1.6.0-alpha02-versionMetadata.json",
          "url": "tiles-tooling-1.6.0-alpha02-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}