{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test",
    "version": "1.2.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-1.2.0-beta02.aar",
          "url": "ui-test-1.2.0-beta02.aar",
          "size": 302608,
          "sha512": "5427fd4732cf0e92df50eb3affc97fd845ed19d9cd48478dc732d3989672811d0784b40b7686ac454e9fd0b649b246b9ba61bc05320516eeb257afbab5fc7817",
          "sha256": "8a0215b308af8ae2d526aa6abd6d04e42cd8d533c30ff9c95bcf8e5d44520dc0",
          "sha1": "2508173afb815d4da3ef77ae3f47688db13e7dfb",
          "md5": "2407d6be42154f4f8fed9780764cac2e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-1.2.0-beta02.aar",
          "url": "ui-test-1.2.0-beta02.aar",
          "size": 302608,
          "sha512": "5427fd4732cf0e92df50eb3affc97fd845ed19d9cd48478dc732d3989672811d0784b40b7686ac454e9fd0b649b246b9ba61bc05320516eeb257afbab5fc7817",
          "sha256": "8a0215b308af8ae2d526aa6abd6d04e42cd8d533c30ff9c95bcf8e5d44520dc0",
          "sha1": "2508173afb815d4da3ef77ae3f47688db13e7dfb",
          "md5": "2407d6be42154f4f8fed9780764cac2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-1.2.0-beta02-sources.jar",
          "url": "ui-test-1.2.0-beta02-sources.jar",
          "size": 89734,
          "sha512": "aa36c4c21b7646d5bd515d7af4142c7ae368f79875c71a4952dcc0cd2a8f48f1b448df84f15a490517e0c0dd5b3ee19ba6a68f2e9aeb21bf8597ae57891adeca",
          "sha256": "ee8a1d2cf7c6fa7385b53eec32ccb20757bbcfc89720c3a08b82ec5e5ef0f74e",
          "sha1": "2e101ceae2a3ab2bc56866767bf17870d0f6e4b4",
          "md5": "cb29b8b1b484c438dc4e79135a757579"
        }
      ]
    }
  ]
}