{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core-samples",
    "version": "1.10.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14128725"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.10.0-alpha04-sources.jar",
          "url": "animation-core-samples-1.10.0-alpha04-sources.jar",
          "size": 25951,
          "sha512": "c47d7caa2fa6ea92a57a886adecc37494bae8712706a45067ac3c1eed8dc599c9cfc258959cb4e73c3c00309f49a6867347f7f39f9a71fde8028324df6353ddf",
          "sha256": "cbd4b9814d7e2af91b3a22f554e75281beaf23c3f47016f98a79b1ac0f3cb6b2",
          "sha1": "ae139cc0ab318b5bb8cf986e43f25356bfc126c8",
          "md5": "a46005f614a432aa11f427df6ba5e618"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.10.0-alpha04.aar",
          "url": "animation-core-samples-1.10.0-alpha04.aar",
          "size": 215633,
          "sha512": "abb48b2254deefb294e44f6df8fb7370303fa3f824eab8acf960974571845752295a1ca762fc7dfc169d020580e1dd54d926fffe997f18dce0bebf7e4a0442e3",
          "sha256": "bd9aea67be993cdf5c1f67f986d675315620cc6fbead2ab69c98ee310d443729",
          "sha1": "a94d57a8e7ad6274384c8b945ab8619b3a491a41",
          "md5": "e6c27adaa9e7299f9b7b795b84672f42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.10.0-alpha04.aar",
          "url": "animation-core-samples-1.10.0-alpha04.aar",
          "size": 215633,
          "sha512": "abb48b2254deefb294e44f6df8fb7370303fa3f824eab8acf960974571845752295a1ca762fc7dfc169d020580e1dd54d926fffe997f18dce0bebf7e4a0442e3",
          "sha256": "bd9aea67be993cdf5c1f67f986d675315620cc6fbead2ab69c98ee310d443729",
          "sha1": "a94d57a8e7ad6274384c8b945ab8619b3a491a41",
          "md5": "e6c27adaa9e7299f9b7b795b84672f42"
        }
      ]
    }
  ]
}