{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-samples",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "animation-samples-1.0.0-beta03.aar",
          "url": "animation-samples-1.0.0-beta03.aar",
          "size": 103973,
          "sha512": "5799018408b7c6eae0df99261040b7fad36178cd064976e1ad7bda7d59fda3664faa3e7eff3afc293700f5856c5b54bf93b826bf4301f5a3d78e0f48f7b7d82e",
          "sha256": "13531618fd02cd440d1f2d522cc8482ec971ec528f69dcf974d0fc908b6c8c42",
          "sha1": "1e568be3624842ac723625a5eb79ce087896e708",
          "md5": "c3075d7faec8f9c99aad727dfc70e084"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.0.0-beta03.aar",
          "url": "animation-samples-1.0.0-beta03.aar",
          "size": 103973,
          "sha512": "5799018408b7c6eae0df99261040b7fad36178cd064976e1ad7bda7d59fda3664faa3e7eff3afc293700f5856c5b54bf93b826bf4301f5a3d78e0f48f7b7d82e",
          "sha256": "13531618fd02cd440d1f2d522cc8482ec971ec528f69dcf974d0fc908b6c8c42",
          "sha1": "1e568be3624842ac723625a5eb79ce087896e708",
          "md5": "c3075d7faec8f9c99aad727dfc70e084"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-samples-1.0.0-beta03-sources.jar",
          "url": "animation-samples-1.0.0-beta03-sources.jar",
          "size": 9038,
          "sha512": "fda2c0f7bd054b25d50439c3b626fcd9086f203d9e05c0908edd1b80483cc384df6181e2cc4b0f70dae1966dddc376da71739e0046683df06ce04a946e068ded",
          "sha256": "0699888659b5a90ceedcbf4a76c4f3a3b93cee73a5e682aae8fa480d1822d92e",
          "sha1": "c0addf658c9d864f704e20343207711fafe22bef",
          "md5": "8d626cdeb6105cc45423303019ac823c"
        }
      ]
    }
  ]
}
