{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-samples",
    "version": "1.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-samples-1.7.4-sources.jar",
          "url": "material-samples-1.7.4-sources.jar",
          "size": 45207,
          "sha512": "a04b759ccfaba8c3cbf2d322b8799e17a04731c570c61627fa3c0d353ba8794d4a28b8c12b96100d3b5cf35e6083dce85749eff12f78b0f56c169d5f217344ce",
          "sha256": "650bfced6e90fba241db7884bf3785482f41c0ae5ce4f68a7d66039e1d16339b",
          "sha1": "6ebb29bfb19a8ee27431234559e62b4c84103b07",
          "md5": "f555171c43ba4e2c91d5c46f826a3e18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.7"
          }
        }
      ],
      "files": [
        {
          "name": "material-samples-1.7.4.aar",
          "url": "material-samples-1.7.4.aar",
          "size": 1061757,
          "sha512": "7ab4581802bfab48bbc0becce03b5f5a47c2e157b912004f2a2b0dfeb0f872787797f0d87072c983d0378367b01f3990d8635160180189f30002fc5d471ec0b7",
          "sha256": "dd75fc4bec37e99ba0acbe0f669a7b9209f3fc9ad44d9033d9c8dc8294f6e2f1",
          "sha1": "8e3778ab4fbc3210ae595afda70460280c1679ac",
          "md5": "3a8c5447cb3fd770738330b03fae3791"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-samples-1.7.4.aar",
          "url": "material-samples-1.7.4.aar",
          "size": 1061757,
          "sha512": "7ab4581802bfab48bbc0becce03b5f5a47c2e157b912004f2a2b0dfeb0f872787797f0d87072c983d0378367b01f3990d8635160180189f30002fc5d471ec0b7",
          "sha256": "dd75fc4bec37e99ba0acbe0f669a7b9209f3fc9ad44d9033d9c8dc8294f6e2f1",
          "sha1": "8e3778ab4fbc3210ae595afda70460280c1679ac",
          "md5": "3a8c5447cb3fd770738330b03fae3791"
        }
      ]
    }
  ]
}