{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text-samples",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-text-samples-1.2.0-alpha04.aar",
          "url": "ui-text-samples-1.2.0-alpha04.aar",
          "size": 46040,
          "sha512": "d2c7df7d5911b6d47367776eac1cd970ff3adeeccf3fe66a66baff64242cd6a39c3e063feda03651552817459606807c57b4b42aeb3d2e06df4e8e77ff7bda77",
          "sha256": "7deb6c5fc2de4b68b66c6e9e047b093c7b4d6067b4b422c2242e7bb9e3278aca",
          "sha1": "a90ca822d3f95d81861fc360b2af507dffb3c23b",
          "md5": "ddc8a6e56a274c7557a5914f4d1dc3fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-samples-1.2.0-alpha04.aar",
          "url": "ui-text-samples-1.2.0-alpha04.aar",
          "size": 46040,
          "sha512": "d2c7df7d5911b6d47367776eac1cd970ff3adeeccf3fe66a66baff64242cd6a39c3e063feda03651552817459606807c57b4b42aeb3d2e06df4e8e77ff7bda77",
          "sha256": "7deb6c5fc2de4b68b66c6e9e047b093c7b4d6067b4b422c2242e7bb9e3278aca",
          "sha1": "a90ca822d3f95d81861fc360b2af507dffb3c23b",
          "md5": "ddc8a6e56a274c7557a5914f4d1dc3fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-samples-1.2.0-alpha04-sources.jar",
          "url": "ui-text-samples-1.2.0-alpha04-sources.jar",
          "size": 10198,
          "sha512": "f269bde2eba4b308d3c240d5fb5f4a4c04034e4d36ec7a8dd1f3ca1c43d35ed40c605207a16bfad7f2bff4348bb4cc24afc1f7baff1ebba3e3dbfa4be2168a17",
          "sha256": "4997ab99f6c31de97fe3538144e2896d71d95aba6ae2d0b0c40c58d145e39a0c",
          "sha1": "86b69e3622a7f5aa3ed86f591d8af9386874e68c",
          "md5": "3881982861f968b7bded29308c09394d"
        }
      ]
    }
  ]
}
