{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-bundled/2.5.2/sqlite-bundled-2.5.2.module",
    "group": "androidx.sqlite",
    "module": "sqlite-bundled",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13624135"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-iosArm64Main-2.5.2.klib",
          "url": "sqlite-bundled-iosarm64-2.5.2.klib",
          "size": 13703,
          "sha512": "dcaac073cae1fc8a0596b473fa0c27847cfebb8de901a685b322bac7879b0f56a956f0798e1718529672fc836ef3a1c8c895e68122da67231da42a2c6ffa08e1",
          "sha256": "74bc8f48d7b8d83ef72a713eb3095da28b940d4a5b9e00e4d92055c0601d913f",
          "sha1": "f366d641e272fede4687a0cac2018d293f852469",
          "md5": "030d83ee4c5ebd213ca6b49042f366b7"
        },
        {
          "name": "sqlite-bundled-iosArm64Cinterop-androidXBundledSqliteMain-2.5.2.klib",
          "url": "sqlite-bundled-iosarm64-2.5.2-cinterop-androidXBundledSqlite.klib",
          "size": 1004508,
          "sha512": "f3960e5ae58f0bb8539bd4111f1e91b63732b32e548f8077c0b62adf6a758f675667fa74e5704513be34eb8300a82742abb8fc4537b3bc014f22310bc62f4115",
          "sha256": "ae68e9298490128021d9dfa7c652a094ed4fd037545f6be38b770d3614c97ca7",
          "sha1": "c8fa765fff7f143c5fc34f0de1f1fa07ab53a87a",
          "md5": "e85cb0feb204fb492b5ffd6fa03b7836"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-iosarm64-2.5.2-sources.jar",
          "url": "sqlite-bundled-iosarm64-2.5.2-sources.jar",
          "size": 13905,
          "sha512": "ea1584b460c631e9cc57b14b3119e806863779851f1eb52eb808f33177ab4783b250c884c2a03a21f62aee27e30f84a534e06aa74348b7a05e1d25e5bae9f995",
          "sha256": "553da10c55efb3f2c0d678e99ca45b07e9de25159d2bc766103e541d4aeefc1a",
          "sha1": "c1f7e1597613d53c4711592317c99cc2424f2035",
          "md5": "52f628c7a2cc75ebcb47fb4acd1939b0"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-iosarm64-2.5.2-metadata.jar",
          "url": "sqlite-bundled-iosarm64-2.5.2-metadata.jar",
          "size": 4402,
          "sha512": "4590a8fc13a784d8eb37eb5593332dc6cde3c688221ea4376106638f7b684f2e52890b62d14b87f18c77b60bb28f4f36d4e9bbd0102e7ab93bafa35cf182e385",
          "sha256": "f1b1d37ec015031be6ad73b47af370a0aa91915509566ab7afbc6255caa22796",
          "sha1": "a810273062dde533c9c2c61d85785b94e5f4a158",
          "md5": "11a07c1e3be434f977552166cc203d2f"
        }
      ]
    }
  ]
}