{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-samples",
    "version": "1.6.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.6.0-rc01.aar",
          "url": "animation-samples-1.6.0-rc01.aar",
          "size": 248953,
          "sha512": "ecee969f864b7272a0af7575289238735b4aa525d80d2064ae3ddc8d553380518719a92e0b49757927599f700c7f1a196abfb79fa8a6c7493294bf1873804183",
          "sha256": "0badc29d9fda625f9863f090c8554e2289fc9578fc1b243a8f45b7e5d0f83036",
          "sha1": "057c83c31c7fa4128b4daaf05ea83660f8f72e3e",
          "md5": "cfe1ccf8805bf1bce37d79a8ad5529bc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.6.0-rc01.aar",
          "url": "animation-samples-1.6.0-rc01.aar",
          "size": 248953,
          "sha512": "ecee969f864b7272a0af7575289238735b4aa525d80d2064ae3ddc8d553380518719a92e0b49757927599f700c7f1a196abfb79fa8a6c7493294bf1873804183",
          "sha256": "0badc29d9fda625f9863f090c8554e2289fc9578fc1b243a8f45b7e5d0f83036",
          "sha1": "057c83c31c7fa4128b4daaf05ea83660f8f72e3e",
          "md5": "cfe1ccf8805bf1bce37d79a8ad5529bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0-rc01"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.6.0-rc01-sources.jar",
          "url": "animation-samples-1.6.0-rc01-sources.jar",
          "size": 17099,
          "sha512": "3eefa156e4379adc9c9dfd8f0ceaed8210e213760bbbb23ea691e54bb80d29b34f18da29ce102dbde63ee513a75e36ebffee37d5415a368d0d17daa1e1d628b1",
          "sha256": "107c0fd66a740599562dfe2c7e632ead8674acb02f15d3039d6d608e660d4d10",
          "sha1": "92f05b8d3e98440f5462f3e330fe0def1cfe36bc",
          "md5": "5458180812163feddeed212ccb6c9cb3"
        }
      ]
    }
  ]
}