{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-framework/2.5.0-alpha08/sqlite-framework-2.5.0-alpha08.module",
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.5.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework.klib",
          "url": "sqlite-framework-iosx64-2.5.0-alpha08.klib",
          "size": 26377,
          "sha512": "3c5c05681aeea5da97f853ba761d1e6c8babd20724f752439e20ed2c4d24bb6d6a04ac59dc1d9cd46d588128b9cba4e9ef1c892de7d805ef678a0d317e08643f",
          "sha256": "3c66517ae0c97ca4cf57bcb242f58b992ff43ac8eb2d796abd7decb06d4671c1",
          "sha1": "4d9d6d6a131162b590bc7b948a5abd34b46e7940",
          "md5": "a028946bf6c36aecbe3b35dffb57c26f"
        },
        {
          "name": "sqlite-framework-cinterop-sqlite3.klib",
          "url": "sqlite-framework-iosx64-2.5.0-alpha08-cinterop-sqlite3.klib",
          "size": 67129,
          "sha512": "1be0d57b5c20cff48a6c6ad792f1544ee273837d29dc645fe76cbe357922f48acd948d67add66e7a2e131e3580ecebcd4ee70c82fccea1d2ac0570b31cf7ebfc",
          "sha256": "440c83678bba9d15df2e3bb2a2d0079dde3069cc6552378caa7953c9be784fd1",
          "sha1": "a42a0ed1a87cef629be525667bdc14bbca473674",
          "md5": "fff193c24fa90a14a01cd4ca0e5c6309"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-iosx64-2.5.0-alpha08-sources.jar",
          "url": "sqlite-framework-iosx64-2.5.0-alpha08-sources.jar",
          "size": 10553,
          "sha512": "454676d8094c4005e298b80988618f01b41c8652ca4ce6b5dc8b3f4563f53b3812f0efb142b9ede13a416baefc040105b1336f26e85ae4d84f7657bd0c5aed76",
          "sha256": "d80a2f621c8afa5e0f3301c5caf3f93f422ead1af2df32b533cae25d2a2b3530",
          "sha1": "e46feae1e866a14543fbad899b7b047ad1df2457",
          "md5": "294299af010fc75d367fc145f51169cd"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-iosx64-2.5.0-alpha08-metadata.jar",
          "url": "sqlite-framework-iosx64-2.5.0-alpha08-metadata.jar",
          "size": 4410,
          "sha512": "8a1dad28d8f0d29f274c988e1a7148c09ed9d4ecd45478639880bcba187912e129f9facb6125401ea05111d74fb0cc233d54f3a3f2ede532995fc33a73eb6dd5",
          "sha256": "009b67f8ad4ce8bfb48d7315e4883cd1b39e82bd9caece95a12ba6b7da46e4c3",
          "sha1": "b8eff1a3305e8d209805c9f38543d55f90f938e7",
          "md5": "edd9c586c0f4762042a6f92d03946e16"
        }
      ]
    }
  ]
}