{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-bundled",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-bundled-1.5.0-alpha01.aar",
          "url": "emoji2-bundled-1.5.0-alpha01.aar",
          "size": 9873562,
          "sha512": "71e0a4f38884de5cd858907fc24e8611db484b851eb2d4cef0a0eb7dd4850c22bd54cb36a15f85261afb7e1cd3688d40c1c70c688d6a0572847aafb362551906",
          "sha256": "e141658e07abed53d3951c65059275062a7407bb5d7d724d49135582ca2d99f5",
          "sha1": "9b14e333b57a3a01df61921da6bb5d8a0058b83e",
          "md5": "3a8baa94f538d4d750a900f35ec1281e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-bundled-1.5.0-alpha01.aar",
          "url": "emoji2-bundled-1.5.0-alpha01.aar",
          "size": 9873562,
          "sha512": "71e0a4f38884de5cd858907fc24e8611db484b851eb2d4cef0a0eb7dd4850c22bd54cb36a15f85261afb7e1cd3688d40c1c70c688d6a0572847aafb362551906",
          "sha256": "e141658e07abed53d3951c65059275062a7407bb5d7d724d49135582ca2d99f5",
          "sha1": "9b14e333b57a3a01df61921da6bb5d8a0058b83e",
          "md5": "3a8baa94f538d4d750a900f35ec1281e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-bundled-1.5.0-alpha01-sources.jar",
          "url": "emoji2-bundled-1.5.0-alpha01-sources.jar",
          "size": 2179,
          "sha512": "088763e1b48f341a8ea50345b301967f813548ab7c8ac1b1537343b2a60130ab1974893c5f2b13cc2c5087b4b07f99067f957e19e8981b63496cd9a5bc920e63",
          "sha256": "f8641f66e5f935c01c3a1f814eb88418388db42c2a1d5ffffb7ba88df17a1a54",
          "sha1": "a7cbe8a6bec66db8f10133f7ed5eda64516633c3",
          "md5": "db8ff7ce5fb184aebe4d1424ba440e2f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-bundled is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-bundled-1.5.0-alpha01-versionMetadata.json",
          "url": "emoji2-bundled-1.5.0-alpha01-versionMetadata.json",
          "size": 335,
          "sha512": "e45772eb86c721bc4e6b1118a39859bfffa4723d8aa7d1843905355da6af5f065cc846ea9f3be05cccef311195ab44473efaa2b73b8bc1cba3c50206d3b53569",
          "sha256": "44353d235a8495b6cc5e6252f02f8a5577976be4a069677c2f4c3a7b5e20b657",
          "sha1": "d2b336333ff4dbe33775ab9909432045ef9b5816",
          "md5": "d396f35b20709f3e5c80102de9eda8da"
        }
      ]
    }
  ]
}