{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation",
    "version": "1.8.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12750671"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-1.8.0-alpha07-multiplatform-sources.jar",
          "url": "animation-1.8.0-alpha07-multiplatform-sources.jar",
          "size": 80628,
          "sha512": "2e1365308f69959739ed570fcc00d0ae2169956881652a55e400afc99a0eecb98332959eda21c8e4f75e8df045f1eb35ad21d3ddafa77eea314995c239f1046c",
          "sha256": "3a291f66c79a258fc6bb8563a8a61aa9ecb52ba122cafa3729846a2b92642618",
          "sha1": "703450a2095b4bbea39446985498851e545e217f",
          "md5": "414c4d8ecf2ff255ebf46f3ea73635d5"
        },
        {
          "name": "animation-1.8.0-alpha07-samples-sources.jar",
          "url": "animation-1.8.0-alpha07-samples-sources.jar",
          "size": 29600,
          "sha512": "601ac79771ddc26bb1314fbd0e18478fcfa47628ebcec7314eebd7fbfa1d56a48b16e9ad99eeeba6c7b0fcb27e4b7867d2c7f434bfa337afb2fb436106328751",
          "sha256": "43c34f29475a01ffdad25f3c0bfdd130f1dee8d5718992263562dfd130ef772c",
          "sha1": "fd04d34c483dc99377b6199c1461d8649ff3deee",
          "md5": "2e8b15c19b23bf42d542835e6b19e822"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "animation-1.8.0-alpha07-versionMetadata.json",
          "size": 30707,
          "sha512": "a973a5cfac8533ce953782f7ccae437d7fad081393cbc9954637ec1d8c244cb444903c131e7931fcb283a7ee98da73c446ef051537dd1a40a81d17f152f749ac",
          "sha256": "1d621b5c1569dd42f5f05e929201d0bb1fa5fbab4a6c618fbc6b014ba7f11234",
          "sha1": "5b8fdffe1fdb30b973f5d8fa132906d01026e2fa",
          "md5": "6e3ea656780eb8fba8b1193bc9d77ab2"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha07"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-metadata-1.8.0-alpha07.jar",
          "url": "animation-1.8.0-alpha07.jar",
          "size": 26843,
          "sha512": "e7c901ba35f20f50e6d35762f5da5e7f4b5cc5b8feaeab7c2c971a2163855e55335e62129b0e177780c059d765aa9165c1bba733ca93227371c8203ab902df67",
          "sha256": "57ef7dccaf1d83bb600118a134e8f9c44b81390aaed8ae171450fa9a354aae94",
          "sha1": "3975afb109c0728b88a971ad66c8c52fb7ab8411",
          "md5": "56f99348f9bb16d4b58efd3cc5e82883"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha07"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-kotlin-1.8.0-alpha07-sources.jar",
          "url": "animation-1.8.0-alpha07-sources.jar",
          "size": 80247,
          "sha512": "d4bb806573458ea82a353bab3177997f44165334cc2cb4dc25bdb1aad75bda3d48fb2665a13200877fe8576e7abcfd8d0aab6e58fe69f3ad8bf5d01e6cf0eae7",
          "sha256": "6ad319d8613b4dea0c6436fb9c0ad3a447767d1adde9d7a8ebab36174062ac11",
          "sha1": "d8ed6701e2b44ac7cf2b95c6f33cf68677a53961",
          "md5": "e299fbba9641f0fbb8bf13ebf1ae25f5"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-android/1.8.0-alpha07/animation-android-1.8.0-alpha07.module",
        "group": "androidx.compose.animation",
        "module": "animation-android",
        "version": "1.8.0-alpha07"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-android/1.8.0-alpha07/animation-android-1.8.0-alpha07.module",
        "group": "androidx.compose.animation",
        "module": "animation-android",
        "version": "1.8.0-alpha07"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-android/1.8.0-alpha07/animation-android-1.8.0-alpha07.module",
        "group": "androidx.compose.animation",
        "module": "animation-android",
        "version": "1.8.0-alpha07"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-jvmstubs/1.8.0-alpha07/animation-jvmstubs-1.8.0-alpha07.module",
        "group": "androidx.compose.animation",
        "module": "animation-jvmstubs",
        "version": "1.8.0-alpha07"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-jvmstubs/1.8.0-alpha07/animation-jvmstubs-1.8.0-alpha07.module",
        "group": "androidx.compose.animation",
        "module": "animation-jvmstubs",
        "version": "1.8.0-alpha07"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../animation-jvmstubs/1.8.0-alpha07/animation-jvmstubs-1.8.0-alpha07.module",
        "group": "androidx.compose.animation",
        "module": "animation-jvmstubs",
        "version": "1.8.0-alpha07"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../animation-linuxx64stubs/1.8.0-alpha07/animation-linuxx64stubs-1.8.0-alpha07.module",
        "group": "androidx.compose.animation",
        "module": "animation-linuxx64stubs",
        "version": "1.8.0-alpha07"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../animation-linuxx64stubs/1.8.0-alpha07/animation-linuxx64stubs-1.8.0-alpha07.module",
        "group": "androidx.compose.animation",
        "module": "animation-linuxx64stubs",
        "version": "1.8.0-alpha07"
      }
    }
  ]
}