{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core-samples",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "6953474"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "animation-core-samples-1.0.0-alpha07.aar",
          "url": "animation-core-samples-1.0.0-alpha07.aar",
          "size": 20171,
          "sha512": "5cfeba4b58f09a084e532b01554185eb822e225b7cc1b73f54df8ca938d7c9b7691ae0aa4f6d023af82be92ccbc1d82084e0a8a046124b510dbf91e7b480f97e",
          "sha256": "43fd21b29199f3f1066dfdf3f475073e03a13d10a350ec4024345341983eaa3d",
          "sha1": "7612793539a04d3750e90e12f075b8e2b76914be",
          "md5": "e7fd0da362b819f72913ead09ae137bf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.0.0-alpha07.aar",
          "url": "animation-core-samples-1.0.0-alpha07.aar",
          "size": 20171,
          "sha512": "5cfeba4b58f09a084e532b01554185eb822e225b7cc1b73f54df8ca938d7c9b7691ae0aa4f6d023af82be92ccbc1d82084e0a8a046124b510dbf91e7b480f97e",
          "sha256": "43fd21b29199f3f1066dfdf3f475073e03a13d10a350ec4024345341983eaa3d",
          "sha1": "7612793539a04d3750e90e12f075b8e2b76914be",
          "md5": "e7fd0da362b819f72913ead09ae137bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-samples-1.0.0-alpha07-sources.jar",
          "url": "animation-core-samples-1.0.0-alpha07-sources.jar",
          "size": 3992,
          "sha512": "2ac5f1adcbcf3f905abce8922e0ba40931421bfb2297eb61f91dc20c26db6c7f828c53047b04bfb8bd45753a0a8af3be5959ec388432fd6acfdb91c6388bff10",
          "sha256": "8948d9e106ccf62259d0af355da2c7a525715205122a95eeaa427eb53015e694",
          "sha1": "c9a9c3e3b2d7adc38c65c67c5e97d491f5fa79a8",
          "md5": "7b01266f8135891fddc522e9a756f9af"
        }
      ]
    }
  ]
}
