{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-runtime-testing/2.10.0-rc01/lifecycle-runtime-testing-2.10.0-rc01.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.10.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14366034"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-linuxArm64Main-2.10.0-rc01.klib",
          "url": "lifecycle-runtime-testing-linuxarm64-2.10.0-rc01.klib",
          "size": 12998,
          "sha512": "aebe4e82906bb9c53e641234dbf5686e3bcad4a97af373addcf5dc8e24cd59cb1638138f16289d8e18eeaf75e1b0f6d3e60534451a276d5f18230edc90fed124",
          "sha256": "548b687f0b812b160b5a8635dffdb77a2928375cfe3e9f055c5a8673384b0859",
          "sha1": "5d434c3d4f6d6e6387ed1581dcfc5eb13bcaed34",
          "md5": "9b73e9988afabda95ee7640e17463bdc"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0-rc01"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-linuxarm64-2.10.0-rc01-sources.jar",
          "url": "lifecycle-runtime-testing-linuxarm64-2.10.0-rc01-sources.jar",
          "size": 7892,
          "sha512": "5d8d8bb91924dd51695e5442d02d6ff8318a06a125f7fca244fd8d3f11b09f93131b755b36891f80a2e481d83f74bb0de513ecb913fa0b02958fc6d151fe522d",
          "sha256": "32681b0459ad2fdf6e93eb251023e625d38e84c948218e9054da9ba31595460b",
          "sha1": "ecc753308dee449f9b6d79ef7e05dfb68f7f55b9",
          "md5": "5d734f9a21e3f3e500ef2ee8dd1d233c"
        }
      ]
    }
  ]
}