{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource-rtmp",
    "version": "1.8.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.8.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-rtmp-1.8.0-rc02.aar",
          "url": "media3-datasource-rtmp-1.8.0-rc02.aar",
          "size": 4150,
          "sha512": "a65805b72cec558e31112da8252ea94d746c7dae94744c8be851fd0a1bc2f0be94d73eda79029acf4ee1626daf705e0fe0a2cae33734077e6263086f247900cb",
          "sha256": "cce107775d908fd52c5f0a5f9d0cc361116d5be784e4c6f5fe1549badcdc6739",
          "sha1": "cf7d6164c4416692f3715434a2de3aa5fb3de6a2",
          "md5": "88875e0f3b6f2bbd0a6842e063487fc4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.antmedia",
          "module": "rtmp-client",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.8.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-rtmp-1.8.0-rc02.aar",
          "url": "media3-datasource-rtmp-1.8.0-rc02.aar",
          "size": 4150,
          "sha512": "a65805b72cec558e31112da8252ea94d746c7dae94744c8be851fd0a1bc2f0be94d73eda79029acf4ee1626daf705e0fe0a2cae33734077e6263086f247900cb",
          "sha256": "cce107775d908fd52c5f0a5f9d0cc361116d5be784e4c6f5fe1549badcdc6739",
          "sha1": "cf7d6164c4416692f3715434a2de3aa5fb3de6a2",
          "md5": "88875e0f3b6f2bbd0a6842e063487fc4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-rtmp-1.8.0-rc02-sources.jar",
          "url": "media3-datasource-rtmp-1.8.0-rc02-sources.jar",
          "size": 3739,
          "sha512": "48d7c738e9ec5a208d0706cae094d73eb2573230ef7b0685fe24d39b335c69a399ed8454e38982b4987e4cd4831a2113ba1bca139e1c1bdfd6e32bc984bff6f4",
          "sha256": "d68022028d2b1a5957c9e19763cd9e5a279f84e6b9bec47e99136c1461266304",
          "sha1": "624eaabddabc0b81233625b159304a1419c9030e",
          "md5": "861d377be76386d77a2b99893ddd9273"
        }
      ]
    }
  ]
}
