{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout-samples",
    "version": "1.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.7.0-alpha03.aar",
          "url": "foundation-layout-samples-1.7.0-alpha03.aar",
          "size": 383417,
          "sha512": "97e447de50bb8e38534eeffa9eedb89f69febe31250091eb3b1d9323b2cc202a2477333ed39482b659d52d07db590f0887534cee224d22a50194196f915e61a8",
          "sha256": "c58199540cef93e1ca3d07048c977c3018de1f80ee5204da2d4bbf10a0433011",
          "sha1": "bc7b3e77d83490b7fb82ef22d2fab305572e7a1c",
          "md5": "3f0ee3568af71140a58f8f91dd9aa1a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.7.0-alpha03.aar",
          "url": "foundation-layout-samples-1.7.0-alpha03.aar",
          "size": 383417,
          "sha512": "97e447de50bb8e38534eeffa9eedb89f69febe31250091eb3b1d9323b2cc202a2477333ed39482b659d52d07db590f0887534cee224d22a50194196f915e61a8",
          "sha256": "c58199540cef93e1ca3d07048c977c3018de1f80ee5204da2d4bbf10a0433011",
          "sha1": "bc7b3e77d83490b7fb82ef22d2fab305572e7a1c",
          "md5": "3f0ee3568af71140a58f8f91dd9aa1a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha03"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.7.0-alpha03-sources.jar",
          "url": "foundation-layout-samples-1.7.0-alpha03-sources.jar",
          "size": 25990,
          "sha512": "27e099591f5ff2f9ca673e6fbb209551246ae196e8cdcbcbf3332b87e74c544bf88c56f859168346ac5a69b920920def1185c2f68e1d9f3eaa55f08215c6e555",
          "sha256": "b9bbfc441dbbc857859142408b33e83e0b15e187760e5db05045d2ac17c55989",
          "sha1": "939c51bc57342682aa65f25e34880a00a318b33a",
          "md5": "7175ad6c6415fa6542f33c203d24ec62"
        }
      ]
    }
  ]
}