{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-samples",
    "version": "1.0.0-beta07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runtime-samples-1.0.0-beta07.aar",
          "url": "runtime-samples-1.0.0-beta07.aar",
          "size": 166730,
          "sha512": "e018749d2f978ea0e5751519beb7defc51f2bc140866f66007c8163ce55b24e2c82ec78a8e0afc691aec1ba34b40812b2eb17950bc6e48caac03e07464b19b99",
          "sha256": "5135fe9cfd073e66259629ab9cd4f589de106c0b3062c005e8f17485fc1294db",
          "sha1": "1b25b10687111f146cf5cdbfd44486782deb94f4",
          "md5": "5c476901f75d89fe2786cee2fe229cac"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-beta07"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0-beta07"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta07"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-samples-1.0.0-beta07.aar",
          "url": "runtime-samples-1.0.0-beta07.aar",
          "size": 166730,
          "sha512": "e018749d2f978ea0e5751519beb7defc51f2bc140866f66007c8163ce55b24e2c82ec78a8e0afc691aec1ba34b40812b2eb17950bc6e48caac03e07464b19b99",
          "sha256": "5135fe9cfd073e66259629ab9cd4f589de106c0b3062c005e8f17485fc1294db",
          "sha1": "1b25b10687111f146cf5cdbfd44486782deb94f4",
          "md5": "5c476901f75d89fe2786cee2fe229cac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-samples-1.0.0-beta07-sources.jar",
          "url": "runtime-samples-1.0.0-beta07-sources.jar",
          "size": 16114,
          "sha512": "8f8d9ec50de088a06a0b0a9649d1a623fb372c7672afa5a088a167d668334830d1f6315438928e99b5447fe47b0c55c607b38b320f475314f882e462a9b9373d",
          "sha256": "d707439c7f9818588518e84e33b0be9640279ffe0557e20b53c9ee4cadee69a5",
          "sha1": "11ecbecf261b6e21206500e6928170881859b937",
          "md5": "ca5c9449a26a3ee61ee50e67fae231f3"
        }
      ]
    }
  ]
}
