{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.biometric",
    "module": "biometric",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6759487"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.1.0-alpha02.aar",
          "url": "biometric-1.1.0-alpha02.aar",
          "size": 187802,
          "sha512": "1c3e3ac76c96baa7699c04cf2625eb59b1bad7f67abacb81e049287caebe9e179ceaf9712bdc931c2dd21aa7bd14fa741ccba9e2d0a5ce06423ba7ded81c1b7a",
          "sha256": "ff29111895a8d736c54bd873e979ded2596806acc2cc7ccc71a15e420c1110f1",
          "sha1": "7db431f70bffa6ec2823b0c33441365919cb006f",
          "md5": "579fbad0157c89f4a7b9fe7f66c25d47"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.1.0-alpha02.aar",
          "url": "biometric-1.1.0-alpha02.aar",
          "size": 187802,
          "sha512": "1c3e3ac76c96baa7699c04cf2625eb59b1bad7f67abacb81e049287caebe9e179ceaf9712bdc931c2dd21aa7bd14fa741ccba9e2d0a5ce06423ba7ded81c1b7a",
          "sha256": "ff29111895a8d736c54bd873e979ded2596806acc2cc7ccc71a15e420c1110f1",
          "sha1": "7db431f70bffa6ec2823b0c33441365919cb006f",
          "md5": "579fbad0157c89f4a7b9fe7f66c25d47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biometric-1.1.0-alpha02-sources.jar",
          "url": "biometric-1.1.0-alpha02-sources.jar",
          "size": 46667,
          "sha512": "c79dc26b1d4c00a85487e03b63c0d753c8334f815d31abf70d6d936d6174e6ef4129a7421c203c3f656369562e5318d42620f79426380f743d7ed72abf3a2872",
          "sha256": "2c7e246bc70c6bb54c62c96c8294a0662700d325a5f9b61e286721edba04996c",
          "sha1": "32304565482e6741f77c1ccb9b7554485abfb683",
          "md5": "20240b162cd9ba61d485bbd9a3e758aa"
        }
      ]
    }
  ]
}
