{
  "formatVersion": "1.1",
  "component": {
    "url": "../../window-core/1.5.0-beta02/window-core-1.5.0-beta02.module",
    "group": "androidx.window",
    "module": "window-core",
    "version": "1.5.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13895212"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-core-watchosArm32Main-1.5.0-beta02.klib",
          "url": "window-core-watchosarm32-1.5.0-beta02.klib",
          "size": 25777,
          "sha512": "50d7be71f5f986cc51551f0004d9d44e117e0fd242c50ffaae9e58c611e60842dd49997c2ac247194c3e36a6c86b6668c3ac0ace91cd54a0d09736f2b4188ae8",
          "sha256": "e30f48b4fb87c046bf9a5e4898e158c6603584b4d6c4483db773c9d61445b2e7",
          "sha1": "35a7f64058445f4a2ac4cff4521aa659bc465928",
          "md5": "44090d741bf774571612b8577c7a7b88"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-watchosarm32-1.5.0-beta02-sources.jar",
          "url": "window-core-watchosarm32-1.5.0-beta02-sources.jar",
          "size": 13190,
          "sha512": "c0f2a079dc7d7f759d456b17a609e4520b5a126e7a21fa330fda5df48675cac7d6f35c332a7434f96f61d810c49fb9c9bfe7fe1101b35d66b53657f1218330db",
          "sha256": "84310e2892f4a174f74607eacbb7342b8bff23197495db4557938aa553aa510e",
          "sha1": "d4743b9b2b7773360048f68369e2612675c28176",
          "md5": "bcb367569a180dc39e4ccd12074b3785"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-core-watchosarm32-1.5.0-beta02-metadata.jar",
          "url": "window-core-watchosarm32-1.5.0-beta02-metadata.jar",
          "size": 4390,
          "sha512": "06fb4eb320d1ad7818b505b2e1d1b6008d1731e421c57051cc538d6cbb1df1da665ffaed565c25236a2b8e7dc4bc0b2045552eaed7981fe28563a6963e097bf9",
          "sha256": "496ef4be6ca3b32b4f403e710302ed53822d019c7c02b5ccd2f95659b2641c58",
          "sha1": "ad421d4ff46e452f0d861da4c02545571dd88efa",
          "md5": "0075fef7d2a08d3ad4c80acc2596d09c"
        }
      ]
    }
  ]
}