{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler",
    "version": "1.0.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compiler-1.0.0-rc02.jar",
          "url": "compiler-1.0.0-rc02.jar",
          "size": 609998,
          "sha512": "7f8b59c6c6b533d0ad8861c8011fc46ea3221e53b0b9370fe15d2bb0ff47949f34b76a3f28eaac61bc7dc9497c71aa929d45d7a41bf5de71277839860659dac7",
          "sha256": "581826c62ed33a317088e364f3a51037152d47f7a267830048ffde4220c070d8",
          "sha1": "85b5927d9ba60941f2ce56de894eda2cb6103fbb",
          "md5": "2466d90c8a138110cd7c6f11c3c72607"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-1.0.0-rc02.jar",
          "url": "compiler-1.0.0-rc02.jar",
          "size": 609998,
          "sha512": "7f8b59c6c6b533d0ad8861c8011fc46ea3221e53b0b9370fe15d2bb0ff47949f34b76a3f28eaac61bc7dc9497c71aa929d45d7a41bf5de71277839860659dac7",
          "sha256": "581826c62ed33a317088e364f3a51037152d47f7a267830048ffde4220c070d8",
          "sha1": "85b5927d9ba60941f2ce56de894eda2cb6103fbb",
          "md5": "2466d90c8a138110cd7c6f11c3c72607"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-1.0.0-rc02-sources.jar",
          "url": "compiler-1.0.0-rc02-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
