{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.0-alpha01.aar",
          "url": "fragment-1.8.0-alpha01.aar",
          "size": 381903,
          "sha512": "c28dd2d56901f4a94011748c65bae6db7edbdcc57b5d20cf0bd0713deb3321cc71ea360fa35caf36d06d662fde154384359fe70c4c858936711c32f37755f9e6",
          "sha256": "e385e28504e2ec2ea410c506fb260d7c3b8a2c0131b176d0122e11d73f275758",
          "sha1": "87b91cae7757d184e9c1818df67ff0ffcba89619",
          "md5": "181280356c02fd5bf53eaa8543a0e540"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.0-alpha01.aar",
          "url": "fragment-1.8.0-alpha01.aar",
          "size": 381903,
          "sha512": "c28dd2d56901f4a94011748c65bae6db7edbdcc57b5d20cf0bd0713deb3321cc71ea360fa35caf36d06d662fde154384359fe70c4c858936711c32f37755f9e6",
          "sha256": "e385e28504e2ec2ea410c506fb260d7c3b8a2c0131b176d0122e11d73f275758",
          "sha1": "87b91cae7757d184e9c1818df67ff0ffcba89619",
          "md5": "181280356c02fd5bf53eaa8543a0e540"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.0-alpha01-sources.jar",
          "url": "fragment-1.8.0-alpha01-sources.jar",
          "size": 199477,
          "sha512": "2adca9f11c5a8ff27bb477796f626b755e76bef48246fa33d4c654b57a8c05da7cd41d60ff175bb4cf6244affa672616cb9324cdba8f33abea21ac0345293cb2",
          "sha256": "a59f92f2f231c4e75db440f182b03accba9f49e74eef3c394a68553fc3415268",
          "sha1": "951d045d651b207794780ec0e209b0a96fbfc04a",
          "md5": "41519d4565d3a1be3261c7dcf838f484"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "fragment is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-1.8.0-alpha01-versionMetadata.json",
          "url": "fragment-1.8.0-alpha01-versionMetadata.json",
          "size": 37286,
          "sha512": "2338ac29a28f745d86e064d4bcccec12c49a3c718145fa7a824fe45a085a897addf30575d6e4b5f85dc0a78c3349deff7cc7e3ad2069d448b6b008b519fa3f5b",
          "sha256": "f3ca99bc035cf1e6cc87a3302d0f291335d9ddfa231f3db1eafc0007249ec3b4",
          "sha1": "923697468f7bc80242b395ad7a2e311f5df7247f",
          "md5": "9b01e058d5021484317d390653574bf9"
        }
      ]
    }
  ]
}