{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-junit4-accessibility-samples",
    "version": "1.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13895212"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-accessibility-samples-1.10.0-alpha01-sources.jar",
          "url": "ui-test-junit4-accessibility-samples-1.10.0-alpha01-sources.jar",
          "size": 6927,
          "sha512": "2f094e772f0039b640fc8c11cf6e16581a7eeb7818530ba1051c76bfa4bab539411dac780f1b7339455b393511de4fa866ed00b9b6b873c5a7ad717caea9ac5e",
          "sha256": "532ec3b951667e0cb2f66dc2b35e38a4c2b355f6b0daf8bc3c5c94142986b8b3",
          "sha1": "ca9757d1de0b647eb7bf10d57feb92eb224a4ed9",
          "md5": "9ae9a2164dceed36b9478df18c38f6b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-accessibility-samples-1.10.0-alpha01.aar",
          "url": "ui-test-junit4-accessibility-samples-1.10.0-alpha01.aar",
          "size": 8463,
          "sha512": "df5f24cec2cc23e55e1f8c7e1f363ebe261bd0e4d1f2e023ce58ee0cc55f7297fac2083e785200de75a7aa19beab6daca72785c7e958c8cd8ef0d28c3195f06a",
          "sha256": "b25b16e51bae4c1441632c658e16ed27ecb8bb4cf9c213f1d940eda861a65c2a",
          "sha1": "91a6c94872f3626d769148b205215a01d95136df",
          "md5": "c89287da211d908ad256e04a32846c32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-accessibility",
          "version": {
            "requires": "3.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-test-junit4-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-accessibility-samples-1.10.0-alpha01.aar",
          "url": "ui-test-junit4-accessibility-samples-1.10.0-alpha01.aar",
          "size": 8463,
          "sha512": "df5f24cec2cc23e55e1f8c7e1f363ebe261bd0e4d1f2e023ce58ee0cc55f7297fac2083e785200de75a7aa19beab6daca72785c7e958c8cd8ef0d28c3195f06a",
          "sha256": "b25b16e51bae4c1441632c658e16ed27ecb8bb4cf9c213f1d940eda861a65c2a",
          "sha1": "91a6c94872f3626d769148b205215a01d95136df",
          "md5": "c89287da211d908ad256e04a32846c32"
        }
      ]
    }
  ]
}