{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.8.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13094998"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-beta03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.0-beta03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-1.8.0-beta03-multiplatform-sources.jar",
          "url": "foundation-1.8.0-beta03-multiplatform-sources.jar",
          "size": 951523,
          "sha512": "df0f3e4c55a64910585e3a6227f5b68a7c4957bd9fdfc8dfeb3b2586e76b6e5360800f10f903ba9592944a240d02cbdc4ae95fb3b07e0bcdf73bed3cefa58514",
          "sha256": "396c056518d393eb6d091b7d018757752fdf04412436dfddb34fbea41e5d4241",
          "sha1": "440ffa2bcdd0943c216ee1e3f7ede56602f80ab5",
          "md5": "5716d3fa5541f589ec929aee5f47e686"
        },
        {
          "name": "foundation-1.8.0-beta03-samples-sources.jar",
          "url": "foundation-1.8.0-beta03-samples-sources.jar",
          "size": 81651,
          "sha512": "06f651fb3d451f6251d9a8052766b832f46fb67cbc787e1d7a220dd0b3b7c6dd9740d4c0bce413657f2b261c4b6e75fe2dd842af3cf9ddf89d47a0d9112b3e68",
          "sha256": "72d923f928702f5397ec35d0a1f60d781af07d396bb8f3d3d98d297f4e044ece",
          "sha1": "f591e3faf1365b552e686519613c21693fae79f6",
          "md5": "043af180862e0f5469fc25d387e5817b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-beta03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.0-beta03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-1.8.0-beta03-versionMetadata.json",
          "size": 196485,
          "sha512": "d4e898b2ae6a850d22ce67076bcbc04af6294b72f93b847234f38a119eb96eebe3dc8a6dc4d474483a4c0d56122d03a722e8fd6a45806744ca206cba7ebaaf85",
          "sha256": "9576aab7edff7d86ac6788ed0fb9508c6e2e46afc3049ef1aaddf35ef2096170",
          "sha1": "c90ed8db683f1f24bf8c82d857a4296038caa01e",
          "md5": "29d3cc949ae2877f277c1a2ea18a1498"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-beta03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-beta03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.0-beta03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-metadata-1.8.0-beta03.jar",
          "url": "foundation-1.8.0-beta03.jar",
          "size": 196958,
          "sha512": "39de085e1f7bf32acc00cf81fb388242c53da69287a6d42448aadf924249764c52d0f5ad5a1a3f669161610b23a14d2d72b0cfeb65647372208ed323efb5d573",
          "sha256": "1e7a955b8b337a45b7dc65b31b6b3a998a36e7e0ca790d3c31958ae90b70d594",
          "sha1": "6e0e20a2c2400e75060326b749b2d3ec2f59c582",
          "md5": "4a91c7b459dbda8b76f839708079618c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-beta03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.0-beta03"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-kotlin-1.8.0-beta03-sources.jar",
          "url": "foundation-1.8.0-beta03-sources.jar",
          "size": 831332,
          "sha512": "7d83c7edd6e88a801446f4db1fa8061ea1d89f2a93af0c239d8487007cedcd178d7f91491980d41bb1803a598f9838c98dfae8580630e6e0393d9f0218d24158",
          "sha256": "3e11798a72a6332f525ebb40b9855807e1f1a1084bc5f875faac21532d54a486",
          "sha1": "f352d9cbe726b00ef95e1b484cff01889d69646f",
          "md5": "1688a2da943a0cb4ab9ff6e04f4dad7f"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.8.0-beta03/foundation-android-1.8.0-beta03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.8.0-beta03"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.8.0-beta03/foundation-android-1.8.0-beta03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.8.0-beta03"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-android/1.8.0-beta03/foundation-android-1.8.0-beta03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-android",
        "version": "1.8.0-beta03"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-jvmstubs/1.8.0-beta03/foundation-jvmstubs-1.8.0-beta03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-jvmstubs",
        "version": "1.8.0-beta03"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-jvmstubs/1.8.0-beta03/foundation-jvmstubs-1.8.0-beta03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-jvmstubs",
        "version": "1.8.0-beta03"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-jvmstubs/1.8.0-beta03/foundation-jvmstubs-1.8.0-beta03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-jvmstubs",
        "version": "1.8.0-beta03"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-linuxx64stubs/1.8.0-beta03/foundation-linuxx64stubs-1.8.0-beta03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-linuxx64stubs",
        "version": "1.8.0-beta03"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-linuxx64stubs/1.8.0-beta03/foundation-linuxx64stubs-1.8.0-beta03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-linuxx64stubs",
        "version": "1.8.0-beta03"
      }
    }
  ]
}