{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics-samples",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-samples-1.1.0-alpha05.aar",
          "url": "ui-graphics-samples-1.1.0-alpha05.aar",
          "size": 29785,
          "sha512": "63045c7cbaf02adf15c068b107a454ee66ab373fc139610e1c2438cba20cbf6f4a6ac37a2c36bcb6f95d45188be00196bd5337af27b7f4955c9c9dc9579dcb41",
          "sha256": "7ad2672464439227185b9202dbf50736b05d9b5f335025c5e400c816b286788a",
          "sha1": "10f827a738f07f5290dee62dec8b17d1e69d1ab9",
          "md5": "413258066bad7b62c3bfb9412b47b884"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-samples-1.1.0-alpha05.aar",
          "url": "ui-graphics-samples-1.1.0-alpha05.aar",
          "size": 29785,
          "sha512": "63045c7cbaf02adf15c068b107a454ee66ab373fc139610e1c2438cba20cbf6f4a6ac37a2c36bcb6f95d45188be00196bd5337af27b7f4955c9c9dc9579dcb41",
          "sha256": "7ad2672464439227185b9202dbf50736b05d9b5f335025c5e400c816b286788a",
          "sha1": "10f827a738f07f5290dee62dec8b17d1e69d1ab9",
          "md5": "413258066bad7b62c3bfb9412b47b884"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-samples-1.1.0-alpha05-sources.jar",
          "url": "ui-graphics-samples-1.1.0-alpha05-sources.jar",
          "size": 5963,
          "sha512": "09b7d144c0d3d15971e9e766085acebd41f12bc206e408ff8ad4d753190677beb653619ffb084cee7a90f84bb81bfa1c79b5208b87d8a83df9063c5e683fce11",
          "sha256": "48357f57b5e3aa1a99ee5bdd2ac33d126667022d8130788c6bc3eaca650c6b1f",
          "sha1": "eea990f628d04cd732d614b9800cb0a546fa50ec",
          "md5": "f06d2804c1ade113cea33bef3d866cec"
        }
      ]
    }
  ]
}
