{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-dynamic-features-runtime",
    "version": "2.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "feature-delivery",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.7.5.aar",
          "url": "navigation-dynamic-features-runtime-2.7.5.aar",
          "size": 50703,
          "sha512": "c7acabf1ccd2f498c99eb20b1ddee00085ea83cfa673893deb3a39ec59a39ca73b589fcc12f7e3eda5c9e593f6bb2d353b8b19f3d9df0ea7c1ab900c9c222669",
          "sha256": "beab55246a74df12add34ceec603be56de31abb639ec92ec80004b114ce2f6d2",
          "sha1": "8774ea0e3b866560e94a42bc4fa83b17e6a0de0a",
          "md5": "2f6d4f9b1feafbf56d6b17f32ce3aedc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.5"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "feature-delivery",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.7.5.aar",
          "url": "navigation-dynamic-features-runtime-2.7.5.aar",
          "size": 50703,
          "sha512": "c7acabf1ccd2f498c99eb20b1ddee00085ea83cfa673893deb3a39ec59a39ca73b589fcc12f7e3eda5c9e593f6bb2d353b8b19f3d9df0ea7c1ab900c9c222669",
          "sha256": "beab55246a74df12add34ceec603be56de31abb639ec92ec80004b114ce2f6d2",
          "sha1": "8774ea0e3b866560e94a42bc4fa83b17e6a0de0a",
          "md5": "2f6d4f9b1feafbf56d6b17f32ce3aedc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.7.5-sources.jar",
          "url": "navigation-dynamic-features-runtime-2.7.5-sources.jar",
          "size": 20101,
          "sha512": "c20314d76c6b3f7e886833a8894912b8b7a2a0bc02581f6a86bcd2451f417a3fcd7bc08aa83b44141928967b73ff23c23caa807b0ef57ed501e59717226e290d",
          "sha256": "6ee6a7b1b3a7458497d47e054230dc061a832bc610f91a76449b2cf1aa470125",
          "sha1": "b70e796c54868f4d8aa74462020642a5cd4b3e23",
          "md5": "40bbab7f2b3412c7fd5e0d6d5f262442"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.5"
          },
          "reason": "navigation-dynamic-features-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-runtime-2.7.5-versionMetadata.json",
          "url": "navigation-dynamic-features-runtime-2.7.5-versionMetadata.json",
          "size": 11615,
          "sha512": "120d120fc007547732cbfc6d8a77994e03165c4c417a7cda45b2d0021c8e4a5a540a127be31cbab9dca1d7dec9ae14eeb98888c283eed02f5b7a0e0fcdd8cf65",
          "sha256": "92c64a6473e65e63bff806257d7495aa05badc97e851148861b3434a80c718ba",
          "sha1": "317de64920d243335d2d864f069158818541bfb5",
          "md5": "7f47c0b8f2502d4e4e24e6e933ea217b"
        }
      ]
    }
  ]
}