{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.3.2.aar",
          "url": "runtime-saveable-1.3.2.aar",
          "size": 1086282,
          "sha512": "b5e9ca657192619e3ae47e805143c01d5e1c8ad3092079ab0d2e0708a8365a4735cb66f80730e2b210eb1cc515634c0d26337a0bfc9600551c5ed818d522d739",
          "sha256": "84d4de9262846d4a9d9833bba7714e1c216bba82b66b4ea537e267f0923602c1",
          "sha1": "e8214dbd82f2b9ce85305699019078494d440aa0",
          "md5": "ac60156728fefa81f59ad6105e56626a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.3.2.aar",
          "url": "runtime-saveable-1.3.2.aar",
          "size": 1086282,
          "sha512": "b5e9ca657192619e3ae47e805143c01d5e1c8ad3092079ab0d2e0708a8365a4735cb66f80730e2b210eb1cc515634c0d26337a0bfc9600551c5ed818d522d739",
          "sha256": "84d4de9262846d4a9d9833bba7714e1c216bba82b66b4ea537e267f0923602c1",
          "sha1": "e8214dbd82f2b9ce85305699019078494d440aa0",
          "md5": "ac60156728fefa81f59ad6105e56626a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-saveable-1.3.2-sources.jar",
          "url": "runtime-saveable-1.3.2-sources.jar",
          "size": 10792,
          "sha512": "2a4fd28cfd1e8bc9572cecab3dcc25560efcbf690e104e3b1e7039bd4d9c3bfc28f96e1d996cc2da2fb846b0f279de63a83d9e801867fa275b164a59645c606f",
          "sha256": "a498d31ee590d7b8b4a31021134e3793d6287a08fc0444c99b80020beea432ae",
          "sha1": "dfdc3070b43a1cb2939cc13498dd40988a8d3d93",
          "md5": "55cf532a33cf4313df6415a1342a26a3"
        }
      ]
    }
  ]
}