{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.versionedparcelable",
    "module": "versionedparcelable",
    "version": "1.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "versionedparcelable-1.2.0-rc01.aar",
          "url": "versionedparcelable-1.2.0-rc01.aar",
          "size": 34504,
          "sha512": "cdbe8dcb74b6e1db4715408f668e5af897db2a12c5feace69fc60aad9ffd00905ca3e98b953e91b555034d18ef360a79cfbb77e572bab952bafa7a14b9073564",
          "sha256": "dcc47543e25f0e564a5a2379874e3f9cac331f847b1eb8239a9049cb6c97fbaf",
          "sha1": "8b235c966215a1bb3ba90f1ee3a3632245263e9e",
          "md5": "d490a27071765eba89508bb8215ba44a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "versionedparcelable-1.2.0-rc01.aar",
          "url": "versionedparcelable-1.2.0-rc01.aar",
          "size": 34504,
          "sha512": "cdbe8dcb74b6e1db4715408f668e5af897db2a12c5feace69fc60aad9ffd00905ca3e98b953e91b555034d18ef360a79cfbb77e572bab952bafa7a14b9073564",
          "sha256": "dcc47543e25f0e564a5a2379874e3f9cac331f847b1eb8239a9049cb6c97fbaf",
          "sha1": "8b235c966215a1bb3ba90f1ee3a3632245263e9e",
          "md5": "d490a27071765eba89508bb8215ba44a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "versionedparcelable-1.2.0-rc01-sources.jar",
          "url": "versionedparcelable-1.2.0-rc01-sources.jar",
          "size": 21653,
          "sha512": "e6ddf927423d425b2d2cc594a3620c75fe2a18883e2cd0b2ef3ce66f5aad1cc6ecf4c240d199dbf0e3c3ff63e640a3fde159a3859337af822490d9ffbc7f8e04",
          "sha256": "d28a8320e5e34ab82c47c3425dc23b3b10d77a621c119b7f0a5cb938e6d675eb",
          "sha1": "79c7f863acc00145960a87745c56beda37a8a256",
          "md5": "aa93625825a4e970f21892e7618392a1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "versionedparcelable-1.2.0-rc01-versionMetadata.json",
          "url": "versionedparcelable-1.2.0-rc01-versionMetadata.json",
          "size": 812,
          "sha512": "22a9ed98f02c6fb3b74dd973ccf21bfdb6da82bed4d53f7ef8efdd3c405934e4684f990a2a2c17f55e9c1745ba524a76ece3ed2985d49c635d8d36478c4a55b3",
          "sha256": "e77cb446474ed330703e863d18f15890bc986718b0fb4cbcd90ef1c48b100daa",
          "sha1": "28adf44ff82497f0f7ac082d5dd8f7590dcbb67c",
          "md5": "50ff87e7093a2dc159727e91a0b270bb"
        }
      ]
    }
  ]
}