{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear-watchface-guava",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear",
          "module": "wear-watchface",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-watchface-guava-1.0.0-alpha14.aar",
          "url": "wear-watchface-guava-1.0.0-alpha14.aar",
          "size": 18734,
          "sha512": "b7fb57d541a7ab3b63d62fffc350824d821504a6a398569e5aac648b7ab74fc52cd012a1f5cfac40560ffb597b909527a790390c0e4830ebfc633a27c7e927da",
          "sha256": "d9799c2f4e8cfa03bce89583d78b578cb4275b61d741fd3815ed093ca5df1dcd",
          "sha1": "06c69e538f8867f855156af51ea96ba22bef67cc",
          "md5": "99b9de12fd2979685b9008cb8ec30011"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.wear",
          "module": "wear-watchface",
          "version": {
            "requires": "1.0.0-alpha14"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-watchface-guava-1.0.0-alpha14.aar",
          "url": "wear-watchface-guava-1.0.0-alpha14.aar",
          "size": 18734,
          "sha512": "b7fb57d541a7ab3b63d62fffc350824d821504a6a398569e5aac648b7ab74fc52cd012a1f5cfac40560ffb597b909527a790390c0e4830ebfc633a27c7e927da",
          "sha256": "d9799c2f4e8cfa03bce89583d78b578cb4275b61d741fd3815ed093ca5df1dcd",
          "sha1": "06c69e538f8867f855156af51ea96ba22bef67cc",
          "md5": "99b9de12fd2979685b9008cb8ec30011"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-watchface-guava-1.0.0-alpha14-sources.jar",
          "url": "wear-watchface-guava-1.0.0-alpha14-sources.jar",
          "size": 1536,
          "sha512": "aa686d6e112193b6227becc3a875ef5f36689d0784e3ed0a61cbedf0212e2b979e2e905345466b9d9ff009dcc46c1e6eeaa81f97ac27051bb67ea89065a2da09",
          "sha256": "cf4f3a1584ec6ccaba202ef18d8e680d421686f02ee4d7fc56f60c3bb08686ac",
          "sha1": "3be73ae550983b29e305781421bd0ca5d114f801",
          "md5": "5b818f80fef3961cdf71eebd15c30ebb"
        }
      ]
    }
  ]
}
