{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-core",
    "version": "1.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-1.0.0-beta02.jar",
          "url": "datastore-preferences-core-1.0.0-beta02.jar",
          "size": 744933,
          "sha512": "faed15f44518b3e17dfbe6f9e922cc7e247cd6ba64f264aa213cb6ea48207d484719c9b587fa21cc4f63d836ac01bd4413ab7d9e6c49994a1caa5bce5137da7a",
          "sha256": "d92b470e5a5b0f12b2e1bda13016485a025e9ff372db6d4d4772a44aeb4f1ba0",
          "sha1": "d234cf5560e10a9f4ae43ecc9c13988e58c8b164",
          "md5": "86b8eeef74b5805edb2da403745c5ce5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-1.0.0-beta02.jar",
          "url": "datastore-preferences-core-1.0.0-beta02.jar",
          "size": 744933,
          "sha512": "faed15f44518b3e17dfbe6f9e922cc7e247cd6ba64f264aa213cb6ea48207d484719c9b587fa21cc4f63d836ac01bd4413ab7d9e6c49994a1caa5bce5137da7a",
          "sha256": "d92b470e5a5b0f12b2e1bda13016485a025e9ff372db6d4d4772a44aeb4f1ba0",
          "sha1": "d234cf5560e10a9f4ae43ecc9c13988e58c8b164",
          "md5": "86b8eeef74b5805edb2da403745c5ce5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datastore-preferences-core-1.0.0-beta02-sources.jar",
          "url": "datastore-preferences-core-1.0.0-beta02-sources.jar",
          "size": 9760,
          "sha512": "8e0e0a4143c216abe94644d2c12f38a135cf6fb783a01a786891a88fd6d37a8c5f57362078188c0e0a400bc50d8f1eb40c35a369d31973e612fc14867e13f105",
          "sha256": "15f80c888ffea02d6dd69e2a2638ab1090c87afcb9cae723720c9904eba7b729",
          "sha1": "cd1e6a8b69e3acc3202c00da8ac7d5f625b6ad19",
          "md5": "efa3bf9b8c722419026f5831c4406357"
        }
      ]
    }
  ]
}
