{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-expression",
    "version": "1.0.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.0.0-rc01.aar",
          "url": "protolayout-expression-1.0.0-rc01.aar",
          "size": 172707,
          "sha512": "5a0958297c52b872fe000e94b6faf8425337d2e53e8e8fdfe81b49632c815fd947d5bb4d935eaa1204157cb2c329cc1c05c43d3701a7b266898afdc8f1d437ac",
          "sha256": "e4ab7f0ec1b4234fa82b866e262a4684553cd9bb81470fc732eb862d3d4a2c03",
          "sha1": "294d28fd8e2f6182e0254a28c236fcad7a26c3ef",
          "md5": "18b3a0d3c9f3dfded42839241d403b26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.0.0-rc01.aar",
          "url": "protolayout-expression-1.0.0-rc01.aar",
          "size": 172707,
          "sha512": "5a0958297c52b872fe000e94b6faf8425337d2e53e8e8fdfe81b49632c815fd947d5bb4d935eaa1204157cb2c329cc1c05c43d3701a7b266898afdc8f1d437ac",
          "sha256": "e4ab7f0ec1b4234fa82b866e262a4684553cd9bb81470fc732eb862d3d4a2c03",
          "sha1": "294d28fd8e2f6182e0254a28c236fcad7a26c3ef",
          "md5": "18b3a0d3c9f3dfded42839241d403b26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.0.0-rc01-sources.jar",
          "url": "protolayout-expression-1.0.0-rc01-sources.jar",
          "size": 53189,
          "sha512": "37d280b82c753290435901ad876d43055fc49a4366e7d3b820ab669cc46d3aa78e117acf60f5746b286703cec4d0dda868e5dbffeabbc2aa04f07ebed9f45baf",
          "sha256": "3b4d27d887a0239a1fe07f79523cef51abb51c36dab3626f196f1571ee5f70a3",
          "sha1": "16a4ea6ee45ced16c34ba4336b38f5e013b8e2b5",
          "md5": "9295409c25ae47a48641bc97c4303ce4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.0.0-rc01-versionMetadata.json",
          "url": "protolayout-expression-1.0.0-rc01-versionMetadata.json",
          "size": 24555,
          "sha512": "20be3596b55c13fb2955c7d43ccd08cf55000738db3078df604fc5035d88b402b218fecb53e6d7bd841ae2071780ac5c71cc40434dad4ecb8c456bad93975772",
          "sha256": "7f0081e301859b8777d77e057f14bab0ffb5736729b7a019caf1c026968c65d0",
          "sha1": "4dd9d7209c1790b910198bb302e2699d4ae20be0",
          "md5": "73449a73e14dc86d5f5c576fd772420f"
        }
      ]
    }
  ]
}