{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel/2.8.0-alpha03/lifecycle-viewmodel-2.8.0-alpha03.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.8.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel.klib",
          "url": "lifecycle-viewmodel-linuxx64-2.8.0-alpha03.klib",
          "size": 44049,
          "sha512": "deb8370c2cac5c646d2a90a913faf23aa98e3009d9a5c9cfedb6bef787aca03f669347a227c740e462cac57cf42e17c3e7199846fdf4d8b09ff9d88a1cc07653",
          "sha256": "d01c10e6be5918c1f55e93e89adb770f381edfa71fdd65e1ab49109834c65f09",
          "sha1": "1136894d6ad22bd1af66e179b1d564502a2bf077",
          "md5": "463746dbbc5e7ce53467499c8df0eccb"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.8.0-alpha03"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-linuxx64-2.8.0-alpha03-sources.jar",
          "url": "lifecycle-viewmodel-linuxx64-2.8.0-alpha03-sources.jar",
          "size": 29662,
          "sha512": "c210bc5112d743cf2e5f774040edcb436f3056cb1950e9b9d32c7f108fd60feb7863c08ccd5d3fd113ac96be8a733ff4f7e07f9ea5316224b3b8936cca3267c4",
          "sha256": "7b67d73b365b0e0ab81ba4d9d13d8089e97540f0a8b750abb9219fa9096ec574",
          "sha1": "0a7fbdb612fb9d56858edd4d2b597275b7515f47",
          "md5": "70e3faa81d5a23a64495abe51386d418"
        }
      ]
    }
  ]
}