{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.2.0-alpha02.aar",
          "url": "protolayout-1.2.0-alpha02.aar",
          "size": 323370,
          "sha512": "d4361dcba22afdd91931da44798be02160c498d39af1c09c21aec3e3e61cf60792028692e8043d137f3c41ae20457e80adfff159b20e59ee2e00be74b78b73db",
          "sha256": "1dcdec4430100733b9ca806965cd2e3f89239e7527403c41174c3e0407915ad8",
          "sha1": "25a934aa1f2b8b5f4709f219c3211ce2451d646d",
          "md5": "54cfd17e23348b2696b25b49e57eb0f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.2.0-alpha02.aar",
          "url": "protolayout-1.2.0-alpha02.aar",
          "size": 323370,
          "sha512": "d4361dcba22afdd91931da44798be02160c498d39af1c09c21aec3e3e61cf60792028692e8043d137f3c41ae20457e80adfff159b20e59ee2e00be74b78b73db",
          "sha256": "1dcdec4430100733b9ca806965cd2e3f89239e7527403c41174c3e0407915ad8",
          "sha1": "25a934aa1f2b8b5f4709f219c3211ce2451d646d",
          "md5": "54cfd17e23348b2696b25b49e57eb0f0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.2.0-alpha02-versionMetadata.json",
          "url": "protolayout-1.2.0-alpha02-versionMetadata.json",
          "size": 72267,
          "sha512": "aca7420cd96a75ee928aad0dbcef2a114a1a0b5453ffca54a464fb7bf6a487f73313180f491692178b312ca791bf3156152399aa56b887c6ac5472238302eb73",
          "sha256": "cbea1a495d06765cdb2d4de33076b5e4327de5b17149f43593effdcb0f200ba3",
          "sha1": "b60bd11fc264a8882ea8998ef570e793f11b412a",
          "md5": "f048f6de633c8cd357f40f7cc7e2f87c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.2.0-alpha02"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.2.0-alpha02-sources.jar",
          "url": "protolayout-1.2.0-alpha02-sources.jar",
          "size": 72741,
          "sha512": "682f798e45cd2bc835c20c1ce847a34919947d59ea99976fa00dc739488bf5c0d0c1a7f9f236317cd9ba5432079427061c54a80c84d6d2dd0fff46a5bca5f909",
          "sha256": "f57e849de312d8ed7226719b4fc548800e013ed4b43dd08a58fa91a0ee434f7b",
          "sha1": "e0bbcf754df4f28f0b4f0f5bd4bc1240d44c2dea",
          "md5": "e7a82a061f9a2b44343439366a637b69"
        }
      ]
    }
  ]
}