{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-compose",
    "version": "1.8.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-compose-1.8.0-beta01-sources.jar",
          "url": "fragment-compose-1.8.0-beta01-sources.jar",
          "size": 4475,
          "sha512": "57f4789729b6f7efd4067a0e5acbf4a4e3d91f3e3c9c83a1ff01b39751c64511e5000f7aacb18cccb6be7052012616c3e690cc19ca0d2c0ded41a17f6b5a46b8",
          "sha256": "26447d0b9ed7e61ae97a1934466fb2385481e1105d81e183ef3944ac693339d4",
          "sha1": "fc87fa24c55b088060bc820fd83b2cb0cd51227a",
          "md5": "961cd4af6094931714a803b0085d5ea1"
        },
        {
          "name": "fragment-compose-1.8.0-beta01-samples-sources.jar",
          "url": "fragment-compose-1.8.0-beta01-samples-sources.jar",
          "size": 1516,
          "sha512": "78e2ae6b4108ab9f784b2808d38d88063433fa2099e02da5d724c3325036568aba1e4286dca1505ffd2f28b0b843154990dee2549dea712c2292a1fbc07c9d96",
          "sha256": "f002899b7793a5b8dc9b93769ffa3a77233932c0395ee1ee8c77fa8e264a74c9",
          "sha1": "83b1937763abee25fb2f21b577c69c26398bed00",
          "md5": "7972436b5f07aa593f16691f5132dbf5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-compose-1.8.0-beta01.aar",
          "url": "fragment-compose-1.8.0-beta01.aar",
          "size": 19690,
          "sha512": "1e7467f5e0a943c5f09916dd637a8c268c70005db7b93f5ca625219ad662564f83d5ef187775a0389d367b67a7bad763887c79d323b30c0a93b5a340737ca718",
          "sha256": "4abb6681a9f7125d9d9a8f45cfc3b83f5eda1b9a1495eb5616dd800fc2dc1c86",
          "sha1": "d326c389dd9b3b9fb9bcf2ed7578c4ffda9221d0",
          "md5": "dbd3f5f734938701da8886019bc126d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-compose-1.8.0-beta01.aar",
          "url": "fragment-compose-1.8.0-beta01.aar",
          "size": 19690,
          "sha512": "1e7467f5e0a943c5f09916dd637a8c268c70005db7b93f5ca625219ad662564f83d5ef187775a0389d367b67a7bad763887c79d323b30c0a93b5a340737ca718",
          "sha256": "4abb6681a9f7125d9d9a8f45cfc3b83f5eda1b9a1495eb5616dd800fc2dc1c86",
          "sha1": "d326c389dd9b3b9fb9bcf2ed7578c4ffda9221d0",
          "md5": "dbd3f5f734938701da8886019bc126d6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "fragment-compose is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-compose-1.8.0-beta01-versionMetadata.json",
          "url": "fragment-compose-1.8.0-beta01-versionMetadata.json",
          "size": 1215,
          "sha512": "285cd17bd54c25d618a141bf907ea2aaec1f87daf2658d5f625e7fd5b05ad16120494a2c76cd09e469deb27325d935a5200f83a51a4550589a1eaac0ad09b634",
          "sha256": "686dc2a7edd1d8996a958fb6b4368a329c3f12e5bdd0844ecc1351d5b2426d4d",
          "sha1": "618dd32cd4a59c86512ddde592f06720f1d7425b",
          "md5": "e813f0553ce827a8113d636a8511516d"
        }
      ]
    }
  ]
}