{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.4.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.0-alpha10"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha10"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-alpha10.aar",
          "url": "navigation-ui-ktx-2.4.0-alpha10.aar",
          "size": 1751,
          "sha512": "8aece0748e19b5386378e7eefe6321bb8a49bff02f105cbb780984e4f6ee5a1c0828719190c0c8e51b813f31c2b3481040eeb9972814696fd85b81f2716ddba5",
          "sha256": "f0bc0ab894373530a021018134f3850cbc4930bfa4144514c96dd339a8d4cc52",
          "sha1": "d0f73207da14414861dafdf857c14b10bd68bf3a",
          "md5": "72a7db6c8a96fed2d16fb0bef864f262"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.0-alpha10"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha10"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-alpha10.aar",
          "url": "navigation-ui-ktx-2.4.0-alpha10.aar",
          "size": 1751,
          "sha512": "8aece0748e19b5386378e7eefe6321bb8a49bff02f105cbb780984e4f6ee5a1c0828719190c0c8e51b813f31c2b3481040eeb9972814696fd85b81f2716ddba5",
          "sha256": "f0bc0ab894373530a021018134f3850cbc4930bfa4144514c96dd339a8d4cc52",
          "sha1": "d0f73207da14414861dafdf857c14b10bd68bf3a",
          "md5": "72a7db6c8a96fed2d16fb0bef864f262"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-alpha10-sources.jar",
          "url": "navigation-ui-ktx-2.4.0-alpha10-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
