{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-framework/2.6.2/sqlite-framework-2.6.2.module",
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14346506"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-tvosSimulatorArm64Main-2.6.2.klib",
          "url": "sqlite-framework-tvossimulatorarm64-2.6.2.klib",
          "size": 27899,
          "sha512": "b20150cd22eece0bd354ff2382f75d171c4e34030143d0f2d1045073d3652454356db4e2f58f0127fcdff10c632a556827720c7e493dc96725abb4340845f52b",
          "sha256": "9ac03b7693b6d2e0e12004cebf1266fd4b6f15294711d9e59b5a87e9ed56dc6f",
          "sha1": "4543b1c44e05ff05b6681fcfbadfa83732ba349d",
          "md5": "150179bbfc5996b1b543ea933580725b"
        },
        {
          "name": "sqlite-framework-tvosSimulatorArm64Cinterop-sqlite3Main-2.6.2.klib",
          "url": "sqlite-framework-tvossimulatorarm64-2.6.2-cinterop-sqlite3.klib",
          "size": 62715,
          "sha512": "51f5fa5f57939bd1236b15c8d9e9086449303cc25cc39f8950900eef5572c1d5732d43b5b77bd99fdf480ce175b2267037224addc1d5c87148dd9e12a41ec455",
          "sha256": "7f37a9c0679d15ef16fd2da0ad06b16eebfe256f1ef2b75cb5f08ce42cc44fd6",
          "sha1": "0d3e79cb6c827351a9755469a4d78fc728f0a39e",
          "md5": "30f2c0eb86ba9e74f57f43be6950f014"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-tvossimulatorarm64-2.6.2-sources.jar",
          "url": "sqlite-framework-tvossimulatorarm64-2.6.2-sources.jar",
          "size": 11679,
          "sha512": "65514d9ec6f825268230ff5f1b6f4e24480b64d18b9b577a3848a0ba1c78b7b94bd6b39f9b74b8a32105210aff54e8d7138498416d831810f41833d63ba8b215",
          "sha256": "26270a4d7248605bd8789f130ce2e2fdd51a80a62ead6bc981598953eba5e7aa",
          "sha1": "89eb4a142ef94606e93bddabd16bec09b849b870",
          "md5": "4bf8f6b2bf53ada7e066f1708d5733e2"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.2"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-tvossimulatorarm64-2.6.2-metadata.jar",
          "url": "sqlite-framework-tvossimulatorarm64-2.6.2-metadata.jar",
          "size": 4410,
          "sha512": "8a1dad28d8f0d29f274c988e1a7148c09ed9d4ecd45478639880bcba187912e129f9facb6125401ea05111d74fb0cc233d54f3a3f2ede532995fc33a73eb6dd5",
          "sha256": "009b67f8ad4ce8bfb48d7315e4883cd1b39e82bd9caece95a12ba6b7da46e4c3",
          "sha1": "b8eff1a3305e8d209805c9f38543d55f90f938e7",
          "md5": "edd9c586c0f4762042a6f92d03946e16"
        }
      ]
    }
  ]
}