{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-samples",
    "version": "1.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.5.0-alpha04.aar",
          "url": "animation-samples-1.5.0-alpha04.aar",
          "size": 249699,
          "sha512": "ebe99a91db665b2d52d0dfe70a0bbaf2f7460ec46a728b04d01f04ae084440c8610fb2536f7797da5ff0cdb02ac5918f7ffd9c6f0c475765a1622bcaac6a4ece",
          "sha256": "262d017312cdb315e218927126f584cab6170e245bcc335f510832e7428a5b48",
          "sha1": "c3ee8857200a6f16b5f74b40bd24dacaa2ee14ac",
          "md5": "459af3269acb8a4950bb57684252058d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.5.0-alpha04.aar",
          "url": "animation-samples-1.5.0-alpha04.aar",
          "size": 249699,
          "sha512": "ebe99a91db665b2d52d0dfe70a0bbaf2f7460ec46a728b04d01f04ae084440c8610fb2536f7797da5ff0cdb02ac5918f7ffd9c6f0c475765a1622bcaac6a4ece",
          "sha256": "262d017312cdb315e218927126f584cab6170e245bcc335f510832e7428a5b48",
          "sha1": "c3ee8857200a6f16b5f74b40bd24dacaa2ee14ac",
          "md5": "459af3269acb8a4950bb57684252058d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.5.0-alpha04-sources.jar",
          "url": "animation-samples-1.5.0-alpha04-sources.jar",
          "size": 17152,
          "sha512": "20d03d5920e93c0b77835147a7126157e21b087ed9aac8c115be16adc6e06faa2631df75306e3154d29c14b03d238f8a602d9a8b28060234e18313ea9ad8164d",
          "sha256": "87f759daa84f0bee225f244f3bb5b846e54be399bd307292be2c7ff5f3329222",
          "sha1": "de79cf57c7ab0715cd0d33f586fbc2c755feaaa7",
          "md5": "4f51c15bd419977bdd9ee28e29c7cb30"
        }
      ]
    }
  ]
}