{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit-samples",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-unit-samples-1.0.1.aar",
          "url": "ui-unit-samples-1.0.1.aar",
          "size": 4241,
          "sha512": "4c875be60fd29b826b3bde8eac9f47da7afe69eb043b31efe352a649dd122354a4bc483957c0f8a0d7a36725f5ec4246732061da2e255e95d74ad0336c46124c",
          "sha256": "bda43857c4ce2ed7851e48c5af2fd2f5b684e5632a40928214202519a5a3d0df",
          "sha1": "f667931bdd071ed53593cf8047c71240b800d7c1",
          "md5": "ad03242a7ddda45817bb8f603eb3ebd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-samples-1.0.1.aar",
          "url": "ui-unit-samples-1.0.1.aar",
          "size": 4241,
          "sha512": "4c875be60fd29b826b3bde8eac9f47da7afe69eb043b31efe352a649dd122354a4bc483957c0f8a0d7a36725f5ec4246732061da2e255e95d74ad0336c46124c",
          "sha256": "bda43857c4ce2ed7851e48c5af2fd2f5b684e5632a40928214202519a5a3d0df",
          "sha1": "f667931bdd071ed53593cf8047c71240b800d7c1",
          "md5": "ad03242a7ddda45817bb8f603eb3ebd1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-samples-1.0.1-sources.jar",
          "url": "ui-unit-samples-1.0.1-sources.jar",
          "size": 1579,
          "sha512": "1bad171b700e4c0f17114e21bbd79eb1d30fe5e87025f2839c66c2818cd4f829f322f168834381538e2bcef000f72c8201df942bc7ecac83e4fa4ad6718873c8",
          "sha256": "12a5c233a99eb05cfadefcaffba76bebc8e220cb694db3c44fa26025c7123879",
          "sha1": "76735f3cf03b3f8cce1953cad579d5637d748173",
          "md5": "1bb4d2b42176226bd4d07ebcf124c2c3"
        }
      ]
    }
  ]
}
