{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test",
    "version": "1.8.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-1.8.0-alpha03-multiplatform-sources.jar",
          "url": "ui-test-1.8.0-alpha03-multiplatform-sources.jar",
          "size": 163396,
          "sha512": "4c25afed827e0ed11fb8990a9ce77f5d66a40bdb5a53662be31f8ceb1d821a0d50bc5053f82c87c0356b20d89eb3675052e21dfd55faf0cc2e8c790580d9c323",
          "sha256": "b05f0247d218a871870f51f9a4520d2a1add47ca7e10213082e494451baed454",
          "sha1": "d504a231fa8df649ae1f3f71f4d8afdef5e15047",
          "md5": "7a8764d8125ec4a5d2e601161326f4b8"
        },
        {
          "name": "ui-test-1.8.0-alpha03-samples-sources.jar",
          "url": "ui-test-1.8.0-alpha03-samples-sources.jar",
          "size": 15960,
          "sha512": "3e63ea52d4f8ea2d57564042f08784fd9ed905851f3b0dba4290211943007a8ff2140afe55783ad783bb49b7936aa83d0f5c8e484cc73baa2d42c1d93d2c751a",
          "sha256": "5a4192d3e0bb16d5d3cce017376cbfe6066bcfbe6e13e6aaba14d908a9aef7f5",
          "sha1": "f926f8226342d07e7c41694fd72b6f739e4ea14d",
          "md5": "ff31c37825406d79d4a5e73c29f3f354"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-test-1.8.0-alpha03-versionMetadata.json",
          "size": 47281,
          "sha512": "48ce3b5320a9d44b6614befc7f19281dd7728a3a6dadc12b53fe99ef1d1ff57744dc32a00a980651c68b4dda9ca83a8ddb4d2515e831150eef95ea1b7a051bc5",
          "sha256": "3882d50985fad4f92016f33251e5cc86e8ada99a20d34dcf0a38ca6d2c589538",
          "sha1": "d49a0c272d7562ff2337137bfe5296828d0903d7",
          "md5": "5f4b1ded2a4a2928743d589471b6e10a"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-metadata-1.8.0-alpha03.jar",
          "url": "ui-test-1.8.0-alpha03.jar",
          "size": 32840,
          "sha512": "e0cd26e348db287ccf0aa2a7c74ac100a98163c83664519fe88786c400b061351b0e7fb85998dcc6e12f0a213b8f79c144a35475d5665bb7a1b1b71710b4a848",
          "sha256": "cf7cbb526f56f5e41cede9178db9abc94b62fdd7c1865449b6c07173085e2ae4",
          "sha1": "cefdc2eb0aa18eb3a7ab1bb29e21b8f6639f88bd",
          "md5": "135ab6434513e1b1d9579ecc3efd515c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "ui-test is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-kotlin-1.8.0-alpha03-sources.jar",
          "url": "ui-test-1.8.0-alpha03-sources.jar",
          "size": 117439,
          "sha512": "e9254e579c606830465ebe3c8ad78ecee552480fd93c46ed9c2f42ec7069e780d2c91ad88e4f93569d32e49b89b242c687d162e71e61bbcae2e0a948d35c0215",
          "sha256": "86dad6e1aba41b8366d3cbecf32bdd79c544cc4576476adf03439fafe7bb0c76",
          "sha1": "aaf7fa32e6ede737f48919e8531913f33c9ef038",
          "md5": "38007a1b7a2e758ca442224b851a3580"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-test-android/1.8.0-alpha03/ui-test-android-1.8.0-alpha03.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-android",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-test-android/1.8.0-alpha03/ui-test-android-1.8.0-alpha03.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-android",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-test-android/1.8.0-alpha03/ui-test-android-1.8.0-alpha03.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-android",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-test-jvmstubs/1.8.0-alpha03/ui-test-jvmstubs-1.8.0-alpha03.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-jvmstubs",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-test-jvmstubs/1.8.0-alpha03/ui-test-jvmstubs-1.8.0-alpha03.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-jvmstubs",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-test-jvmstubs/1.8.0-alpha03/ui-test-jvmstubs-1.8.0-alpha03.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-jvmstubs",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-test-linuxx64stubs/1.8.0-alpha03/ui-test-linuxx64stubs-1.8.0-alpha03.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-linuxx64stubs",
        "version": "1.8.0-alpha03"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-test-linuxx64stubs/1.8.0-alpha03/ui-test-linuxx64stubs-1.8.0-alpha03.module",
        "group": "androidx.compose.ui",
        "module": "ui-test-linuxx64stubs",
        "version": "1.8.0-alpha03"
      }
    }
  ]
}