{
  "formatVersion": "1.1",
  "component": {
    "url": "../../room-runtime/2.8.0-rc01/room-runtime-2.8.0-rc01.module",
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.8.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13879186"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-iosSimulatorArm64Main-2.8.0-rc01.klib",
          "url": "room-runtime-iossimulatorarm64-2.8.0-rc01.klib",
          "size": 263178,
          "sha512": "6f3269efe6fae40cad74fdea7054bedeebe86c0efb291c90cd66efb0a37a014c51a0acb0ab2312683a9bd6c18750e82d9898a553a3f20432aaf60a2c39c49e0c",
          "sha256": "f2906dbcac8117e69de5add2a4d057de1d1b6825655f71afdb89221f4bbfbd8f",
          "sha1": "891fa709c54cdf2b0083202bc080f1ad2e02e325",
          "md5": "367b8dbe42d7ae3ed29e5037c8b496f0"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-runtime-iossimulatorarm64-2.8.0-rc01-sources.jar",
          "url": "room-runtime-iossimulatorarm64-2.8.0-rc01-sources.jar",
          "size": 104515,
          "sha512": "de5b128fcf6ca63d678c683fab3b088f4e83238421907dff5129c7336b2e4cd6a420d1ea52c5dca99517cc6d383fe6a68cd7fdae964b7e0d419e8b36f70901ee",
          "sha256": "9d2d42c4b13f93d8fd0b36f2db28f8e8efedc979dcf4c99213e4c91b0d80bb8b",
          "sha1": "0cafca6b132c82a9099385c55437f3187342895a",
          "md5": "bdf912970e306bd011e7e27b216681e2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.0-rc01"
          },
          "reason": "room-runtime is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-iossimulatorarm64-2.8.0-rc01-metadata.jar",
          "url": "room-runtime-iossimulatorarm64-2.8.0-rc01-metadata.jar",
          "size": 4382,
          "sha512": "292d23a3d97bf35683c158ebd3d956b8943c2916d4578e7dceacb92f0ca13ab04dbc48fb8f2d79c4626a81b59a80c3e6b11635144767f511513955c2296777f3",
          "sha256": "b62474a3963794d0962863fea25d9825ef015c3c63611f1b1f29a7c125e794ca",
          "sha1": "9ae8ed429e247e90bd4b75d8bfcdae7bad233882",
          "md5": "24303c3536afc5d5126b3372eca1231b"
        }
      ]
    }
  ]
}