{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core-samples",
    "version": "1.8.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.8.0-alpha03-sources.jar",
          "url": "animation-core-samples-1.8.0-alpha03-sources.jar",
          "size": 25960,
          "sha512": "d28d26bc9437b7478fefa29b185717e0ed2e4cfe5744fe8810cd26c6d822791dbc46991cb06cd9fe30adc248d26fd342113569dae3a2ce422670bc6d8e918296",
          "sha256": "78a774beb3943ae731753d64622dc3a9d2325950a29079b5f9bd3489ab17bffa",
          "sha1": "a1d95ca45a0ee265a32ee656330c359fc33c82e1",
          "md5": "19ea202b492d4d162d7f5eaf1647d13b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.8.0-alpha03.aar",
          "url": "animation-core-samples-1.8.0-alpha03.aar",
          "size": 256304,
          "sha512": "2a44bc4b5d3abab8734e6a6ec6ba70071ad15f1305e6b83c3c047569a626f8511857b853b6e4dcfb399c9b45d65879d66f0fa2b72526784223b226fe479b341e",
          "sha256": "90be1ee93365232febe7546f6a5350590a06e4215d3376a609ecbf30c5b4c2c0",
          "sha1": "48490a24528463b871b1983c59c14b528c364148",
          "md5": "b62f9fbdcb3c053193022e7336263542"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha03"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.8.0-alpha03.aar",
          "url": "animation-core-samples-1.8.0-alpha03.aar",
          "size": 256304,
          "sha512": "2a44bc4b5d3abab8734e6a6ec6ba70071ad15f1305e6b83c3c047569a626f8511857b853b6e4dcfb399c9b45d65879d66f0fa2b72526784223b226fe479b341e",
          "sha256": "90be1ee93365232febe7546f6a5350590a06e4215d3376a609ecbf30c5b4c2c0",
          "sha1": "48490a24528463b871b1983c59c14b528c364148",
          "md5": "b62f9fbdcb3c053193022e7336263542"
        }
      ]
    }
  ]
}