{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.8.0-rc03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13310709"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "material-1.8.0-rc03-multiplatform-sources.jar",
          "url": "material-1.8.0-rc03-multiplatform-sources.jar",
          "size": 262110,
          "sha512": "b337ae1b6f3f81722b6d00de951926355a1c71ff50ed1a23e26b2576c14a0d29ce6915a5d9917d1d131231b222bf4e7c20fbf0ca013fc0e51a3b32790209b0a9",
          "sha256": "4e1b89d5b94ca172420ee27814fc762beb00f26022b07c27c5d34787851e23fc",
          "sha1": "f15c2ae67fdbde20912670db704e119b6116b523",
          "md5": "ec9b0f0e47dd507e795dff9231bdfa81"
        },
        {
          "name": "material-1.8.0-rc03-samples-sources.jar",
          "url": "material-1.8.0-rc03-samples-sources.jar",
          "size": 49593,
          "sha512": "ed3a3f5515cc254a271495379efd6312fe2df0e2ba36d74a561a2321849302df70042e595672d73d93487831492ab9f370cadb0bf222beae9040fa211897a8b7",
          "sha256": "da19c146e2e0b1850ef33a249d0335a0af00d94b4cffb416102f284b40ef3d2b",
          "sha1": "055ca7a063778ee67721ce202ba2713ba4575699",
          "md5": "a14291836f2ae2711ae691054490f03a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material-1.8.0-rc03-versionMetadata.json",
          "size": 92852,
          "sha512": "7b1e3d9d969cdf197582e6eb27f16a1844a6d3a8a4227a08708c861f8ababb4d0bebb8eda5d901b155b7d2b1cd75aea40d18f694069ced98ade210445582cfde",
          "sha256": "f6c38b38675488d33b8b25aca3113853cdb30d8d84ec328190f0594029bae151",
          "sha1": "d2fa60d208f07439ad88994fa012935820cd9961",
          "md5": "6a989eb4c6f07cd82803a02e37a47b36"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.8.0-rc03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-rc03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.4"
          }
        }
      ],
      "files": [
        {
          "name": "material-metadata-1.8.0-rc03.jar",
          "url": "material-1.8.0-rc03.jar",
          "size": 58378,
          "sha512": "33979807db89c0e6ad3dc48ff81aa2dbfddb13550479414b9c7e817f543246059a4e3d9b2518404120688e9fbf131fa2dcc684abe235bae6fac83e8d129a8b4d",
          "sha256": "14628710ae6ae58067d58d15e77b992568db3370401d07df13ae35002aca7926",
          "sha1": "094b54e28a11affe2dd49e396b7e7ec6435739fb",
          "md5": "d63f53f145c790a8eaa7d9de3bfc71b8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-kotlin-1.8.0-rc03-sources.jar",
          "url": "material-1.8.0-rc03-sources.jar",
          "size": 255995,
          "sha512": "58153031ecb672f9591914010d762e11e8969d796a9ff47312a5b9bcf6cb863cb076ae28da030136f79abc475071a5aaa3ca9ab1882548a57a6a6ce7ce75b53e",
          "sha256": "9a2f9cccf3b3e907ac051ee53cd4853be817e5e021d165e88a3b1e426b19c419",
          "sha1": "1aa0de29e401d989d037d9578fa38811ae827944",
          "md5": "886fce8f094c6f798b72768b6ea2bb76"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-android/1.8.0-rc03/material-android-1.8.0-rc03.module",
        "group": "androidx.compose.material",
        "module": "material-android",
        "version": "1.8.0-rc03"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-android/1.8.0-rc03/material-android-1.8.0-rc03.module",
        "group": "androidx.compose.material",
        "module": "material-android",
        "version": "1.8.0-rc03"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material-android/1.8.0-rc03/material-android-1.8.0-rc03.module",
        "group": "androidx.compose.material",
        "module": "material-android",
        "version": "1.8.0-rc03"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-jvmstubs/1.8.0-rc03/material-jvmstubs-1.8.0-rc03.module",
        "group": "androidx.compose.material",
        "module": "material-jvmstubs",
        "version": "1.8.0-rc03"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-jvmstubs/1.8.0-rc03/material-jvmstubs-1.8.0-rc03.module",
        "group": "androidx.compose.material",
        "module": "material-jvmstubs",
        "version": "1.8.0-rc03"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-jvmstubs/1.8.0-rc03/material-jvmstubs-1.8.0-rc03.module",
        "group": "androidx.compose.material",
        "module": "material-jvmstubs",
        "version": "1.8.0-rc03"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-linuxx64stubs/1.8.0-rc03/material-linuxx64stubs-1.8.0-rc03.module",
        "group": "androidx.compose.material",
        "module": "material-linuxx64stubs",
        "version": "1.8.0-rc03"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-linuxx64stubs/1.8.0-rc03/material-linuxx64stubs-1.8.0-rc03.module",
        "group": "androidx.compose.material",
        "module": "material-linuxx64stubs",
        "version": "1.8.0-rc03"
      }
    }
  ]
}