{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles-material",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "tiles-material-1.1.0-alpha02.aar",
          "url": "tiles-material-1.1.0-alpha02.aar",
          "size": 42764,
          "sha512": "db670a7df568012e067d400571d888473871195ecfd681c761831702f819812599947f3942ab0bd80b909348ef30e6a51a351e39c43d98bc7eef88f87277490e",
          "sha256": "e3574e89adb05ca828c0f85e9e7244749a1f8a06748128becf3e6b2e22780049",
          "sha1": "10c71eec1e78bab3283a5dbe1f389dcd6548c532",
          "md5": "28df633b2ed8ff25a953e1a999fb388f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "tiles-material-1.1.0-alpha02.aar",
          "url": "tiles-material-1.1.0-alpha02.aar",
          "size": 42764,
          "sha512": "db670a7df568012e067d400571d888473871195ecfd681c761831702f819812599947f3942ab0bd80b909348ef30e6a51a351e39c43d98bc7eef88f87277490e",
          "sha256": "e3574e89adb05ca828c0f85e9e7244749a1f8a06748128becf3e6b2e22780049",
          "sha1": "10c71eec1e78bab3283a5dbe1f389dcd6548c532",
          "md5": "28df633b2ed8ff25a953e1a999fb388f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tiles-material-1.1.0-alpha02-sources.jar",
          "url": "tiles-material-1.1.0-alpha02-sources.jar",
          "size": 35279,
          "sha512": "99eb8dc07838cd49f3210b99b649fe344370315ea1671b2de934707af0728562d3a7443375b1ae75f331e57564915aea5fb7a04f5e86dcc37c0799a3b88c9337",
          "sha256": "da712e4e4bf09d6a813af1000ecbe7784e6c6b011c863aee79da40b06f1a942a",
          "sha1": "db1d7112b056a585809e854e4633917351ac3c13",
          "md5": "a7da6d05e62761af7ea565b512e3f1d4"
        }
      ]
    }
  ]
}
