{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-accessibility-samples",
    "version": "1.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14396805"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-accessibility-samples-1.9.5-sources.jar",
          "url": "ui-test-accessibility-samples-1.9.5-sources.jar",
          "size": 6758,
          "sha512": "923fbf70e766f029ccdafc1abaf2e8bb706dd1a9874280a529dc51f88398a4925a7a083eaf3f245f38a592a70edfe2e7b3f4aeecbbb989e09860863e72989bcf",
          "sha256": "cc6b9da33f34ad7b1992d5fa30db2fa56eb4736215906b684daea05fd0b682b4",
          "sha1": "a67685163fc7468bc0a180dc943cb0c3966225cc",
          "md5": "7eec8bccec0bb28bee2ec3c45a21d357"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-accessibility-samples-1.9.5.aar",
          "url": "ui-test-accessibility-samples-1.9.5.aar",
          "size": 13381,
          "sha512": "e61ca3815e55b0b435b8e5213ac53ad1b30469c3e36bfe0f1f3d67f052f538189eedfa96f65e96624392da1504546bb500609316e0dedb273efbccc8c77d1194",
          "sha256": "056d8ebfdbe92cfe28cffd456f6c8b3e1b0f118efd7ce6c21cefffeb5768ff1a",
          "sha1": "8d11e6916dba1e92d491cec6afe1c8a130bcecdc",
          "md5": "24eaf70dc59e243701d4d66dcf9e7cb4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.5"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-accessibility",
          "version": {
            "requires": "3.7.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.5"
          },
          "reason": "ui-test-accessibility-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-accessibility-samples-1.9.5.aar",
          "url": "ui-test-accessibility-samples-1.9.5.aar",
          "size": 13381,
          "sha512": "e61ca3815e55b0b435b8e5213ac53ad1b30469c3e36bfe0f1f3d67f052f538189eedfa96f65e96624392da1504546bb500609316e0dedb273efbccc8c77d1194",
          "sha256": "056d8ebfdbe92cfe28cffd456f6c8b3e1b0f118efd7ce6c21cefffeb5768ff1a",
          "sha1": "8d11e6916dba1e92d491cec6afe1c8a130bcecdc",
          "md5": "24eaf70dc59e243701d4d66dcf9e7cb4"
        }
      ]
    }
  ]
}