{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles-tooling-preview",
    "version": "1.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12750671"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-tooling-preview-1.5.0-alpha05-sources.jar",
          "url": "tiles-tooling-preview-1.5.0-alpha05-sources.jar",
          "size": 9412,
          "sha512": "3304fcb31c69520805bcd240b501052bfe49e64977a9ccb4dbf01b61fafc3841ed5a0ae99b0c0f56038c8ab38b64081eaf93bed7409d4ce9e802db31956f40ae",
          "sha256": "46b9b5a1fe5859952d0729fa55c3dd6bb84d7843ee5fa27a2bd14a3d300ed195",
          "sha1": "84d5c9d97caa990fadd80dad2192170514c164af",
          "md5": "d47b69ee90b2a973fffcccaf96f50cfc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear-tooling-preview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-tooling-preview-1.5.0-alpha05.aar",
          "url": "tiles-tooling-preview-1.5.0-alpha05.aar",
          "size": 13536,
          "sha512": "7ca08b6db1187a671452cf25486f46459d5fcc649c7d8b303a003cbf265814dd3fd08a28198a09445edbd8a99bf3aed868895969829afe4bc51d2e932eea807f",
          "sha256": "c535c86816ff52c3b90dca50ec593bb422c3d73c42bf732194ea914489dc5083",
          "sha1": "934af5ccb0d24de261a6f130b1fc0d38e0414421",
          "md5": "f81e72eb318364e2a61dab2eb2d42f04"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear-tooling-preview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "tiles-tooling-preview-1.5.0-alpha05.aar",
          "url": "tiles-tooling-preview-1.5.0-alpha05.aar",
          "size": 13536,
          "sha512": "7ca08b6db1187a671452cf25486f46459d5fcc649c7d8b303a003cbf265814dd3fd08a28198a09445edbd8a99bf3aed868895969829afe4bc51d2e932eea807f",
          "sha256": "c535c86816ff52c3b90dca50ec593bb422c3d73c42bf732194ea914489dc5083",
          "sha1": "934af5ccb0d24de261a6f130b1fc0d38e0414421",
          "md5": "f81e72eb318364e2a61dab2eb2d42f04"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "tiles-tooling-preview is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-tooling-preview-1.5.0-alpha05-versionMetadata.json",
          "url": "tiles-tooling-preview-1.5.0-alpha05-versionMetadata.json",
          "size": 1974,
          "sha512": "bf451fbcceb5ab4ba0a3903b01d63a73a6dd25abd2ef096b54e394606b2a2b997743c10535d018b225cea4496e5afdfa002cea3c479159d572b417c01bc3da2b",
          "sha256": "2d9f027a35ebb16e1b778ed8a65679cf1cbfca79116bcbedc02ff9fa948781aa",
          "sha1": "921bb28b8927be2c8788155c08b137d09d882937",
          "md5": "a3a7a3bc332648efa450f53958232db2"
        }
      ]
    }
  ]
}