{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout-samples",
    "version": "1.9.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13569180"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.9.0-alpha04-sources.jar",
          "url": "foundation-layout-samples-1.9.0-alpha04-sources.jar",
          "size": 32445,
          "sha512": "4b47eba1242faac42addf902d14456bc08fffc5796b9b353e77f5ad77554e7eb85a66543eef751a02140e239b6546cda16c68d7f5ee5616c4ed448d6ca32f855",
          "sha256": "cc9d91070f42afc49780498177ea940828172ea3c01acfcc69e0b9ae1703127e",
          "sha1": "e112280aeb75104c14def66360f79494bcc15ef6",
          "md5": "7b4f5a0b573bfe6b6861b5bca6c22d61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.9.0-alpha04.aar",
          "url": "foundation-layout-samples-1.9.0-alpha04.aar",
          "size": 372868,
          "sha512": "f656d5721a41011bf83d9e727a28abbf454e7fe14ff74e1e9ccf54de4ae5344ff38f43f318892244bff963c3aee5cb8d4ed952d2f871c4faa9ab4e1dd2d6bc88",
          "sha256": "57daea67b42c35415926f860a1d0174c70b11dc6fbd109582bc9a4ece4fffdc4",
          "sha1": "8a8528a4663f914951ce956a495d7f1e833f7a10",
          "md5": "b364f872fb1f703693998bd154cbaa82"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.9.0-alpha04.aar",
          "url": "foundation-layout-samples-1.9.0-alpha04.aar",
          "size": 372868,
          "sha512": "f656d5721a41011bf83d9e727a28abbf454e7fe14ff74e1e9ccf54de4ae5344ff38f43f318892244bff963c3aee5cb8d4ed952d2f871c4faa9ab4e1dd2d6bc88",
          "sha256": "57daea67b42c35415926f860a1d0174c70b11dc6fbd109582bc9a4ece4fffdc4",
          "sha1": "8a8528a4663f914951ce956a495d7f1e833f7a10",
          "md5": "b364f872fb1f703693998bd154cbaa82"
        }
      ]
    }
  ]
}