{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-foundation-samples",
    "version": "1.2.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "compose-foundation-samples-1.2.0-alpha07.aar",
          "url": "compose-foundation-samples-1.2.0-alpha07.aar",
          "size": 169797,
          "sha512": "c111a8e27ad21d27cb9804c26cc8fa2e1aff0bcfbebe09592488c17ce51933d9824a5d5ae6d4230b978d4d60298b229b5fd27ed3a201f71e741212f7734161dc",
          "sha256": "d98f5fb3295d464b2bec4c14904d86735125b5a02912ca76ca69ab37b255b3db",
          "sha1": "811182c15c4cc4947a6aec59792ce31d060e40eb",
          "md5": "c830fede2bc3f1e6174543301246fa15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "compose-foundation-samples-1.2.0-alpha07.aar",
          "url": "compose-foundation-samples-1.2.0-alpha07.aar",
          "size": 169797,
          "sha512": "c111a8e27ad21d27cb9804c26cc8fa2e1aff0bcfbebe09592488c17ce51933d9824a5d5ae6d4230b978d4d60298b229b5fd27ed3a201f71e741212f7734161dc",
          "sha256": "d98f5fb3295d464b2bec4c14904d86735125b5a02912ca76ca69ab37b255b3db",
          "sha1": "811182c15c4cc4947a6aec59792ce31d060e40eb",
          "md5": "c830fede2bc3f1e6174543301246fa15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "compose-foundation-samples-1.2.0-alpha07-sources.jar",
          "url": "compose-foundation-samples-1.2.0-alpha07-sources.jar",
          "size": 7052,
          "sha512": "c5ab2f5da395e3ac4b9b1ec0422ef8c755d185ac95d4dbac5c2a159c798581611b71bb02d82a8d3266518772c362773e92215e57006ee1e1ca391cb85b229bae",
          "sha256": "fbf12dd3388b56c6e012941108853614fbd9ad9c8dcdae327b525f648de860ee",
          "sha1": "96a18bcd8faf5e28f8d87c18fbdb75296e4b8eb9",
          "md5": "354cc5b3740d345f181b95c04428e24b"
        }
      ]
    }
  ]
}