{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.7.0-alpha03.aar",
          "url": "lifecycle-viewmodel-savedstate-2.7.0-alpha03.aar",
          "size": 39299,
          "sha512": "b86270913d9fb9949b477e5e73b74ebe069b6206360467fe10e0afcb9951502d244ed62f374e6d3b552707d4906260f70d12330c1e5a82f1ebe78d5b25aef9f6",
          "sha256": "6768617a1d7aaf9532a9d1252929d6a945da5989bf6e0df88d7bea42711a906e",
          "sha1": "1dcdddbd33ece1e5d9d5ff469e36d910d15f1d0c",
          "md5": "0c7601a74cda6e6863a4abc1c6659f60"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.7.0-alpha03.aar",
          "url": "lifecycle-viewmodel-savedstate-2.7.0-alpha03.aar",
          "size": 39299,
          "sha512": "b86270913d9fb9949b477e5e73b74ebe069b6206360467fe10e0afcb9951502d244ed62f374e6d3b552707d4906260f70d12330c1e5a82f1ebe78d5b25aef9f6",
          "sha256": "6768617a1d7aaf9532a9d1252929d6a945da5989bf6e0df88d7bea42711a906e",
          "sha1": "1dcdddbd33ece1e5d9d5ff469e36d910d15f1d0c",
          "md5": "0c7601a74cda6e6863a4abc1c6659f60"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.7.0-alpha03-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-2.7.0-alpha03-sources.jar",
          "size": 15765,
          "sha512": "5227b7a13440155634eab7ca609e10eb27c0eab0eb654a841067773277613bd1ac48a4cbdf63bb95e8fa31eaaf78be5ef0a997192da5b18786d23147fbc500a6",
          "sha256": "9014876584af07bae2fcffe389a8cac07f7074ff32541dd9c1d2a4d077ff4dd8",
          "sha1": "8eb1c5d46c388c3dc333d640efb640a7782aafca",
          "md5": "b05fe3e9184581aa01c0bae5d73130cb"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.7.0-alpha03-versionMetadata.json",
          "url": "lifecycle-viewmodel-savedstate-2.7.0-alpha03-versionMetadata.json",
          "size": 3135,
          "sha512": "121b6eba39097d4528c1b6ec79e2e173f486936c4e3b1da225c55af09181aabaf49893a395684fe1cbc16bf636c031083221c3af8dc582cc7efafab2f5b1d3fc",
          "sha256": "82b8218b73bd4ca88f6e7d34e068a53cb256460a0a46acf3f397cc921c508df6",
          "sha1": "373998f58a4a808ffa1ba1ba80892ead99c38a02",
          "md5": "c2c7b07988cddcf2e8cd91eb7d173bfc"
        }
      ]
    }
  ]
}