{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-rxjava3",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-rxjava3-2.8.1.aar",
          "url": "work-rxjava3-2.8.1.aar",
          "size": 5626,
          "sha512": "1c59089bbd32355f2f49f5c680450cca6a464cefd0f17531ea76d879021c7a4844179e0039e258dbe9af46107df66ac82def163e5ce8216202fab4bffc0ae7ee",
          "sha256": "fdce448a6aeda32797e3a825e1b401f17972a517366480f43f75cb8c57d4f769",
          "sha1": "d7172d2544dc89d6ad7ff4188997b41df75a6684",
          "md5": "968e46d7e9a5fee2949d6ac7369a67ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-rxjava3-2.8.1.aar",
          "url": "work-rxjava3-2.8.1.aar",
          "size": 5626,
          "sha512": "1c59089bbd32355f2f49f5c680450cca6a464cefd0f17531ea76d879021c7a4844179e0039e258dbe9af46107df66ac82def163e5ce8216202fab4bffc0ae7ee",
          "sha256": "fdce448a6aeda32797e3a825e1b401f17972a517366480f43f75cb8c57d4f769",
          "sha1": "d7172d2544dc89d6ad7ff4188997b41df75a6684",
          "md5": "968e46d7e9a5fee2949d6ac7369a67ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-rxjava3-2.8.1-sources.jar",
          "url": "work-rxjava3-2.8.1-sources.jar",
          "size": 3737,
          "sha512": "91fa2804cdebd22cf42fdc6407d0d02c64480702ee602fa815c2e336810ae02e9aede02765cc311282d4147ab3937f3a39ea7458ab254c58eb3a3e1a36e78564",
          "sha256": "dc8d8bc994e9d74827aba248cff2e8f1fe06b8df960f466aa0eec50fed966c9c",
          "sha1": "06f3a696cfa410ed2ac15247787ce855f0910ef7",
          "md5": "a4fb98f32a4100e38fe13daf8151f1e4"
        }
      ]
    }
  ]
}