{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget-testing-samples",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-samples-1.1.0-beta02.aar",
          "url": "glance-appwidget-testing-samples-1.1.0-beta02.aar",
          "size": 24376,
          "sha512": "14b84c201e4d6301fe463347b0caba985f1dae1e12ff43b8d41a4daaade5a4ad85fe785175f4777d4fad23c8cf08f9fd9dd3c8695aa687a227f3610b8b4a18ad",
          "sha256": "87b79fb0612e74cba46de3d108041a5f32a89e73baecbfb4d6160dd74d04c83b",
          "sha1": "2eb6e519e913311dd1ed2e353e3f39b904828da6",
          "md5": "f914223372f70c38b0ee5ad608ce0c32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.6.0-alpha05"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-samples-1.1.0-beta02.aar",
          "url": "glance-appwidget-testing-samples-1.1.0-beta02.aar",
          "size": 24376,
          "sha512": "14b84c201e4d6301fe463347b0caba985f1dae1e12ff43b8d41a4daaade5a4ad85fe785175f4777d4fad23c8cf08f9fd9dd3c8695aa687a227f3610b8b4a18ad",
          "sha256": "87b79fb0612e74cba46de3d108041a5f32a89e73baecbfb4d6160dd74d04c83b",
          "sha1": "2eb6e519e913311dd1ed2e353e3f39b904828da6",
          "md5": "f914223372f70c38b0ee5ad608ce0c32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "glance-appwidget-testing-samples is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-samples-1.1.0-beta02-sources.jar",
          "url": "glance-appwidget-testing-samples-1.1.0-beta02-sources.jar",
          "size": 2215,
          "sha512": "37958345ae3514af9f0f49d0f3156e0e081a1832a1fc69ab3e6a2f7822b15660a0a6bad068841cd0a5c2f61ee04fcb4070079174ae1b98b30d07fa34c2072ce8",
          "sha256": "7b23681810036e258476c1b234de669d24ea252d9ffd157bb4a95802d2393de3",
          "sha1": "688704d1b3d925ff9ccc89af28694043308aba40",
          "md5": "6eaae4193c27d8b7a6186cf622626dec"
        }
      ]
    }
  ]
}