{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing",
    "version": "1.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId:": "6473093"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.3.0-alpha05.aar",
          "url": "fragment-testing-1.3.0-alpha05.aar",
          "size": 21988,
          "sha512": "5c229c7d07b581d4d9101e6d55bbae74eaf60a281d5b34bec58c9ed9cdebda544071136abc952c246d895ba717beb8eaeb90e860d9f91093982d404d0e99a5ea",
          "sha256": "ead7e2ef08f4f9c7f888016e73108fd56d32d4910285a1bfd5f64faf9c881ff0",
          "sha1": "4dd1e7cb144ea57ff6e3219ff4caa3c1e5362cbd",
          "md5": "105de4d861e70988b543ad2accab2e96"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.3.0-alpha05.aar",
          "url": "fragment-testing-1.3.0-alpha05.aar",
          "size": 21988,
          "sha512": "5c229c7d07b581d4d9101e6d55bbae74eaf60a281d5b34bec58c9ed9cdebda544071136abc952c246d895ba717beb8eaeb90e860d9f91093982d404d0e99a5ea",
          "sha256": "ead7e2ef08f4f9c7f888016e73108fd56d32d4910285a1bfd5f64faf9c881ff0",
          "sha1": "4dd1e7cb144ea57ff6e3219ff4caa3c1e5362cbd",
          "md5": "105de4d861e70988b543ad2accab2e96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-testing-1.3.0-alpha05-sources.jar",
          "url": "fragment-testing-1.3.0-alpha05-sources.jar",
          "size": 6136,
          "sha512": "6bcf3fc84158e9061f0b4399de04c2362c896227ad2906fec6cc63bc2f88c3c6d867b5b1c7a814e0b3a398a6e6745f06752c2776d84c11d1dcd012d37f0aba76",
          "sha256": "538e4468bf243f62aa93cc17e392333c429647c8c4c0989893b788e620da940b",
          "sha1": "08683837c37106eae812cf0f94097011fcc6fc1b",
          "md5": "0b5f513df2a79d8ec78b93d6475e6c29"
        }
      ]
    }
  ]
}
