{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-rxjava2",
    "version": "3.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0-beta03"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "paging-rxjava2-3.0.0-beta03.aar",
          "url": "paging-rxjava2-3.0.0-beta03.aar",
          "size": 36487,
          "sha512": "47a59338c9e6b4a73c1014a631502a0dfd6897ad1fba7da07c5ebd935e8f15afc67e5e42d4bcf40953b0c76dd69f4ee6a0f7c44f02c42686da5aef2de14da606",
          "sha256": "6f43ae9c62762d8c9c11be7608d07cde95e32668c92cfecfa5b0f01a7432ba66",
          "sha1": "654affdb34982378f13ada06591747b9653f0e10",
          "md5": "c2443ac6dc2fee7114e5d19772e6763c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0-beta03"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "paging-rxjava2-3.0.0-beta03.aar",
          "url": "paging-rxjava2-3.0.0-beta03.aar",
          "size": 36487,
          "sha512": "47a59338c9e6b4a73c1014a631502a0dfd6897ad1fba7da07c5ebd935e8f15afc67e5e42d4bcf40953b0c76dd69f4ee6a0f7c44f02c42686da5aef2de14da606",
          "sha256": "6f43ae9c62762d8c9c11be7608d07cde95e32668c92cfecfa5b0f01a7432ba66",
          "sha1": "654affdb34982378f13ada06591747b9653f0e10",
          "md5": "c2443ac6dc2fee7114e5d19772e6763c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-rxjava2-3.0.0-beta03-sources.jar",
          "url": "paging-rxjava2-3.0.0-beta03-sources.jar",
          "size": 12753,
          "sha512": "df019fcc5f241a7725939ce4d228587e089c0739fecde9fe0c5e83adde611adcff43858e320dc1db344dc2855c5266f44f22b71245c1cd26b4d5657a4e7dbb71",
          "sha256": "0d2b0791ed11cd4c4d0e1a45903dda568f812346d67d4fbb003915d1e5486a4a",
          "sha1": "5dae967e1651b064f177b110960537b7589de29d",
          "md5": "4ad5f46063054da3ab88c0ae865688b2"
        }
      ]
    }
  ]
}
