{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava2-samples",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.8.0-alpha01-sources.jar",
          "url": "runtime-rxjava2-samples-1.8.0-alpha01-sources.jar",
          "size": 6108,
          "sha512": "f3d49c42fbfdef1bf5dc448470390407b06f9065bfddc7e1f8c464662fc396e14a51f0b553ffdff066b5b92fe8e47dbf60e27cc38c0abaebe087269c74bddfa7",
          "sha256": "7de164b0d0756b949c8a3f1ec53cc3867803b4fadb2539510784943dace34990",
          "sha1": "0e4b053760ff4b7a97370bf48f6317d7c778a27c",
          "md5": "4732460fb8e830281f90670db5b51c50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.8.0-alpha01.aar",
          "url": "runtime-rxjava2-samples-1.8.0-alpha01.aar",
          "size": 13993,
          "sha512": "8dff057b21768cf8d17d06b89087390e6090e41e444a2a83dead9120ed63b3da33b85a19b6afee81fb8785f9dd28fbe9ab05bb1e00726a96e046378f0e45f4ed",
          "sha256": "0a0bb37663f72311f59bc98819ff647552328bfb7d499c3e170d0e66712f141b",
          "sha1": "194c30fc620f15b563cc603d502058d889ba9cd2",
          "md5": "56417187a742b6df8fc906daa743fa94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.8.0-alpha01.aar",
          "url": "runtime-rxjava2-samples-1.8.0-alpha01.aar",
          "size": 13993,
          "sha512": "8dff057b21768cf8d17d06b89087390e6090e41e444a2a83dead9120ed63b3da33b85a19b6afee81fb8785f9dd28fbe9ab05bb1e00726a96e046378f0e45f4ed",
          "sha256": "0a0bb37663f72311f59bc98819ff647552328bfb7d499c3e170d0e66712f141b",
          "sha1": "194c30fc620f15b563cc603d502058d889ba9cd2",
          "md5": "56417187a742b6df8fc906daa743fa94"
        }
      ]
    }
  ]
}