{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-annotation/1.10.0-beta01/runtime-annotation-1.10.0-beta01.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-annotation",
    "version": "1.10.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14298655"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-annotation-watchosX64Main-1.10.0-beta01.klib",
          "url": "runtime-annotation-watchosx64-1.10.0-beta01.klib",
          "size": 16755,
          "sha512": "09cff6109e66725b2b7556660f5afc60a669abb6927c40e00e3a5a94a7dde3d017386ac3fc7096995a893ee1705792dfb9773a0e57f7f70b51e3e17c764ed9fe",
          "sha256": "bb6e5af8a8111fc39da93f6849bc7ff77fadc8bce3afac169c77aee13bf14a81",
          "sha1": "75284539e71d763b297b395b1066afd3e0a3fabc",
          "md5": "9d2002a3ac2f22b6e0c8a00d48aa171c"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-annotation-watchosx64-1.10.0-beta01-sources.jar",
          "url": "runtime-annotation-watchosx64-1.10.0-beta01-sources.jar",
          "size": 12735,
          "sha512": "276cb4822fdf51dc912d7f7dbe232d94caffb4d778a9fded373f0ff98ec91c861080a52ba9124761dcb68c9969083100964a67ea8d2cf78987299aa3f2adb6b7",
          "sha256": "272b2b47cf1d938a66fa4c92e73ab8820c91f9c0d07208050aa5986988bc73b9",
          "sha1": "f7129a6199a2a16d5fcaff5d8320154e5d572b6a",
          "md5": "83c19e85b13a100c7c227b87f13580a4"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.10.0-beta01"
          },
          "reason": "runtime-annotation is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-annotation-watchosx64-1.10.0-beta01-metadata.jar",
          "url": "runtime-annotation-watchosx64-1.10.0-beta01-metadata.jar",
          "size": 4602,
          "sha512": "ec8523e8363e696398cdacca28788b8aefedba160ec094f04eb38405ff3a570c51a5092296c787f94286bd47551c942c86e254655f6a62e1c83069f3cfa1d41e",
          "sha256": "5dad84d9fb7a5ec9169b934f501ea724cf084fa806e46db585fe1f880aa82b38",
          "sha1": "881017553738778e0185e45a55a9783763183386",
          "md5": "0826ab75c7ce41a8e1445462d48eec74"
        }
      ]
    }
  ]
}