{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-appdigest",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-appdigest-1.0.0-alpha01.aar",
          "url": "core-appdigest-1.0.0-alpha01.aar",
          "size": 23771,
          "sha512": "d4fcdfbcb6bbd8b1ee83a05b3288a52e1d4ba0aacc5905a830c61db957ee471e71b2d02f0b77719a66e9581a5b8b5796fec92359095d35aa7669b5ee0f404722",
          "sha256": "e46082b7c6e6243d3bb37a03f14be884e0ac319445ba68c6e2f160852462ccf6",
          "sha1": "a62ddf9489a73433de29c535285fc697f27cfc97",
          "md5": "95967ac6fd676855652cd07baf26e172"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.56"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-appdigest-1.0.0-alpha01.aar",
          "url": "core-appdigest-1.0.0-alpha01.aar",
          "size": 23771,
          "sha512": "d4fcdfbcb6bbd8b1ee83a05b3288a52e1d4ba0aacc5905a830c61db957ee471e71b2d02f0b77719a66e9581a5b8b5796fec92359095d35aa7669b5ee0f404722",
          "sha256": "e46082b7c6e6243d3bb37a03f14be884e0ac319445ba68c6e2f160852462ccf6",
          "sha1": "a62ddf9489a73433de29c535285fc697f27cfc97",
          "md5": "95967ac6fd676855652cd07baf26e172"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-appdigest-1.0.0-alpha01-sources.jar",
          "url": "core-appdigest-1.0.0-alpha01-sources.jar",
          "size": 14005,
          "sha512": "f247bf1cdb579b0865d7b69611395311b66f558307faa4ffb3e4ce0af634f00adfff3c2f9b9635a9fe20233d14fff73501e20bf88a7dc0f8df4b2e49f120bd90",
          "sha256": "b69c062a07e50213a6d563c7dd235f3240fc5cabc8d326481bf52b8cff812bfc",
          "sha1": "5a26f5817b0b2b768cc76efbdc2ce0067271bda1",
          "md5": "38a868f7f42aaaf742b0f24d301a802d"
        }
      ]
    }
  ]
}
