{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-framework/2.5.0-alpha03/sqlite-framework-2.5.0-alpha03.module",
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework.klib",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha03.klib",
          "size": 20671,
          "sha512": "3b26f63a72e5e08717ebe24d41173250acfb704808e6cb711ebccb4527c635a829dec749418b9f1c6fd445a14eec2af24c09f3a62cd42f22b6bb49c37a1615af",
          "sha256": "e2777f409199973e72b273e1d5278ad1f4d042c658ba85b22efb346e24c9de86",
          "sha1": "32c00306f8be247b05759ad762bdde306d76f5ce",
          "md5": "a7953817571b1c71e18eca1c100754c0"
        },
        {
          "name": "sqlite-framework-cinterop-sqlite3.klib",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha03-cinterop-sqlite3.klib",
          "size": 61939,
          "sha512": "455ca8149317ba1c4567ed5c70366f66154f6cc01d5735ad942f4ff94be91bcc7cb5b3730930c91938d03be912a515408a27cad2cc1f8218d5b94ec3c224eb65",
          "sha256": "b85f9824e54a9fe11decb0a46e64c0369a7de2303381b50ad966b6ce354f5005",
          "sha1": "31478771bc34edc6569c79780acac43118900713",
          "md5": "154a3c9c9af5ffc40df2a55b17c34f1a"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-macosarm64-2.5.0-alpha03-sources.jar",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha03-sources.jar",
          "size": 5965,
          "sha512": "edaf5f0d1136cd98a0bdd6018658cfd3d30b2a757fac157ec3a001f6cfda52454f5b002e653161f6496eccc0e4ec6d5c3469b8214324241956442c3dee8b0d3a",
          "sha256": "c5c09a0af403fe3cff47f0cee0defa6a54af6d344fec75bbab816cb9ff110f45",
          "sha1": "8e3de5823910d7770187fdd986d0ebad4c1da017",
          "md5": "5f6d10734599ae8b0f40dcc5c2a16183"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-macosarm64-2.5.0-alpha03-metadata.jar",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha03-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}