{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-rxjava3",
    "version": "1.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13953699"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-rxjava3-1.5.0-rc01-sources.jar",
          "url": "window-rxjava3-1.5.0-rc01-sources.jar",
          "size": 5789,
          "sha512": "7e2cb093ee7c3f753ff00b88f1a14e44876bf65d06815b5fb893db75658ec693148df0e08ba1f2cbdaf60b26282a656bb6bb2e9a2722c583ff557612becd1299",
          "sha256": "90773b88d75dae96c751df41920ac6c53bbbbb183c345c5feca1893379eaafd7",
          "sha1": "206f37a08920f93b714ed2736050136ae058bf84",
          "md5": "e0708965471d435dc40d32e3c7aa315b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx3",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-rxjava3-1.5.0-rc01.aar",
          "url": "window-rxjava3-1.5.0-rc01.aar",
          "size": 7530,
          "sha512": "b5763abfb01cc9647476dc784c3ce8ea95874f592cd8755ce3340e54f98b95dcb683730dd4c8b7843cf1ac857fa1745e22be13544ee1b5dbff55bd88de1001ef",
          "sha256": "393f20c9552e0d9d06f95d0f08f9f1a2d290d919fbc12a9cad789911b89698b3",
          "sha1": "01fdffe8f9a668aa92db5c4a42bb3a886cb34a63",
          "md5": "016144db614ab4ff622009ca9e034285"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx3",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-rxjava3-1.5.0-rc01.aar",
          "url": "window-rxjava3-1.5.0-rc01.aar",
          "size": 7530,
          "sha512": "b5763abfb01cc9647476dc784c3ce8ea95874f592cd8755ce3340e54f98b95dcb683730dd4c8b7843cf1ac857fa1745e22be13544ee1b5dbff55bd88de1001ef",
          "sha256": "393f20c9552e0d9d06f95d0f08f9f1a2d290d919fbc12a9cad789911b89698b3",
          "sha1": "01fdffe8f9a668aa92db5c4a42bb3a886cb34a63",
          "md5": "016144db614ab4ff622009ca9e034285"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-rxjava3-1.5.0-rc01-versionMetadata.json",
          "url": "window-rxjava3-1.5.0-rc01-versionMetadata.json",
          "size": 592,
          "sha512": "2213501c5d4d2d834729ea3c2bd595b27523b60d3ffa821055a87fadefc29e1ac41825e8e6ff57bb1bee16d86bda22b530bc2801ed05205863c958fbe0e4d514",
          "sha256": "c16f28081231c82789cc6e945904c1ed6f7208710b0a8ad41cac1c660d944980",
          "sha1": "c7db8327f224716348997f741c0071862fea8517",
          "md5": "a1650e3d1a59fa4909d6c9e98d8e8073"
        }
      ]
    }
  ]
}