{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-framework/2.5.0-alpha11/sqlite-framework-2.5.0-alpha11.module",
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.5.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha11"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha11"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha11"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework.klib",
          "url": "sqlite-framework-macosx64-2.5.0-alpha11.klib",
          "size": 26436,
          "sha512": "e7738ade3c1933fc598d98d815a72c66e027b3187608a3af9a60699f01f107e283c15a24d57b4fbe8e7bfabe60e94d3e3afc6b623c0f65b3ef7581212c60e666",
          "sha256": "a93489b58d2f00ccbb5da129badeee6ec28513ce56de3328b29d1fc7775bf09c",
          "sha1": "0bae472a2ec2e62e7c2e038534be4753ea792cab",
          "md5": "bd46ed681f37e8ff9d60992e734c813e"
        },
        {
          "name": "sqlite-framework-cinterop-sqlite3.klib",
          "url": "sqlite-framework-macosx64-2.5.0-alpha11-cinterop-sqlite3.klib",
          "size": 67062,
          "sha512": "ac01eab42f3f9778e8f7ca98d0334c01ec79642e6e6a5b90f5b59ad9d14708d140e096e569fb97ecf732cf0777f7ddeaa81beebfe9bd9ed0a86057c8ce6ccf02",
          "sha256": "9bc931cfbc5975cf36bc40e00899fcec1eaf16d8bac50c87b3c4c4c4af0231f2",
          "sha1": "cabd7ceaf5b9fb0e0e0812970841497066bd8635",
          "md5": "79ee66b6c7bcc37628ff0fe99771d8f8"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha11"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha11"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha11"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-macosx64-2.5.0-alpha11-sources.jar",
          "url": "sqlite-framework-macosx64-2.5.0-alpha11-sources.jar",
          "size": 10563,
          "sha512": "85c7c053fc686de9ada01a3d8338a8f63185dfa2fe383f58628709415f5b8769dad3466f389d7cf0bca41da1645a7a90b654a313d553a032f93f4d628095a705",
          "sha256": "74cbdd2258d07815021a0f7097801a773ba5cc058dc28d8f2b430de877e6688c",
          "sha1": "f025ae3e65ab2e827bc57759c4cdb4bd346c73ca",
          "md5": "83d0dbc35716120af0b1b35f5227507f"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha11"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha11"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha11"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-macosx64-2.5.0-alpha11-metadata.jar",
          "url": "sqlite-framework-macosx64-2.5.0-alpha11-metadata.jar",
          "size": 4410,
          "sha512": "8a1dad28d8f0d29f274c988e1a7148c09ed9d4ecd45478639880bcba187912e129f9facb6125401ea05111d74fb0cc233d54f3a3f2ede532995fc33a73eb6dd5",
          "sha256": "009b67f8ad4ce8bfb48d7315e4883cd1b39e82bd9caece95a12ba6b7da46e4c3",
          "sha1": "b8eff1a3305e8d209805c9f38543d55f90f938e7",
          "md5": "edd9c586c0f4762042a6f92d03946e16"
        }
      ]
    }
  ]
}