{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core-samples",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "animation-core-samples-1.2.0-alpha04.aar",
          "url": "animation-core-samples-1.2.0-alpha04.aar",
          "size": 142508,
          "sha512": "faa5aca5ff9714bd3c4331d6724f74c7b7194bafe9e0831ba0dd1dc76b88d48ae045d865868434ffd5b53e4cc129a2bae6d222e5126dbd2332dfb982cd825ccb",
          "sha256": "ee25179d9cdee96e59def0a554b53a1e5903bd302225d62781d2fbc73f9a9d9d",
          "sha1": "2bf4ae42923d6f21b5724c550aca92bfe681052e",
          "md5": "b62612adc833dd0b857a40f6e8fabdb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.2.0-alpha04.aar",
          "url": "animation-core-samples-1.2.0-alpha04.aar",
          "size": 142508,
          "sha512": "faa5aca5ff9714bd3c4331d6724f74c7b7194bafe9e0831ba0dd1dc76b88d48ae045d865868434ffd5b53e4cc129a2bae6d222e5126dbd2332dfb982cd825ccb",
          "sha256": "ee25179d9cdee96e59def0a554b53a1e5903bd302225d62781d2fbc73f9a9d9d",
          "sha1": "2bf4ae42923d6f21b5724c550aca92bfe681052e",
          "md5": "b62612adc833dd0b857a40f6e8fabdb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-samples-1.2.0-alpha04-sources.jar",
          "url": "animation-core-samples-1.2.0-alpha04-sources.jar",
          "size": 16170,
          "sha512": "5c70e3b0ec6e46d316767929753ef790088fda06dae6ada30908816f46f0150587802312da8b46ef666443970ccdcab5bb02a34d8c320780aded2f908be9d2fd",
          "sha256": "adf21cbfbeebf807c918ec1e2d839b2d4d182497dc71607f26cfd7863c6a49bb",
          "sha1": "b8d0480b0af6fc7d8aa32526989e4489f6aa3037",
          "md5": "44452c0d018a153c340c66c3af8c5dcd"
        }
      ]
    }
  ]
}
