{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ink",
    "module": "ink-geometry",
    "version": "1.0.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13307273"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-geometry-1.0.0-alpha04-multiplatform-sources.jar",
          "url": "ink-geometry-1.0.0-alpha04-multiplatform-sources.jar",
          "size": 74950,
          "sha512": "2145b5b235f8901605bde1f5facba5306459a4758799b51b0191f43189b78dbe530db2cd6ff899719cb22313a629c3ed67ac417d3862f10deb99de8d370108c0",
          "sha256": "a844c5cc8bcf43289abf8207b99feb06c68eb335222f2ab3b368a05240aa3746",
          "sha1": "2f56a8fc6e7055b3ccd6ae2c8a81a7435e9cf604",
          "md5": "0cc29804d134cf68f7e558797340cdf0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ink-geometry-1.0.0-alpha04-versionMetadata.json",
          "size": 25173,
          "sha512": "0a038f5dbd2a73b710167e246b95b244db726de105e07ce59b3ffd313e3dc4419a7e64dee8f80feddfa21c7e26b7ae0af949c80ec3f0dd2e575f6386f73d2b78",
          "sha256": "357e5879e949f0da5a1ff59c35195c982b123fa075ca340774268911cde5c8e7",
          "sha1": "74ad06501626d9901a66752db589c0c64b2d3059",
          "md5": "d85b11635ba6466ba713a1e001f15cf6"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-geometry-metadata-1.0.0-alpha04.jar",
          "url": "ink-geometry-1.0.0-alpha04.jar",
          "size": 4857,
          "sha512": "a589ec498dd9946506eb82a9994c1c0f0f56548aa23b9db48ad36074cd6add31f89cf72cb0cb54bab88c0a0d973fc2ac1077c061bc57515d2ffb6111af58b57c",
          "sha256": "11e5b3ecb7afb16c8b3495e195408d50fddc98675add5d33d1c77bfa37e5530d",
          "sha1": "22e09bfcfa049c0ced3bc1df894ca8e6e0d53ea0",
          "md5": "93833afe4a096a4bd2c39c24de3d939f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha04"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-geometry-kotlin-1.0.0-alpha04-sources.jar",
          "url": "ink-geometry-1.0.0-alpha04-sources.jar",
          "size": 70775,
          "sha512": "105d1876c07d3cb1ef3a9f6b5869b3133bb0e39fc6e684a336ed435889480b9a781bd5e4de9a4c9f9dd07a961d6a624e808f017e65936913d35472d6fcbfcc65",
          "sha256": "196eadfad03ebf0a0b36851e135f4c6ac35da06782328b775fe9264e84475a91",
          "sha1": "8fe33cec1f38e2eb99185cb3b4e7fd1e8867607f",
          "md5": "021ac5440c1a83d7599fd7023aa4dfd0"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ink-geometry-android/1.0.0-alpha04/ink-geometry-android-1.0.0-alpha04.module",
        "group": "androidx.ink",
        "module": "ink-geometry-android",
        "version": "1.0.0-alpha04"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ink-geometry-android/1.0.0-alpha04/ink-geometry-android-1.0.0-alpha04.module",
        "group": "androidx.ink",
        "module": "ink-geometry-android",
        "version": "1.0.0-alpha04"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ink-geometry-android/1.0.0-alpha04/ink-geometry-android-1.0.0-alpha04.module",
        "group": "androidx.ink",
        "module": "ink-geometry-android",
        "version": "1.0.0-alpha04"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-geometry-jvm/1.0.0-alpha04/ink-geometry-jvm-1.0.0-alpha04.module",
        "group": "androidx.ink",
        "module": "ink-geometry-jvm",
        "version": "1.0.0-alpha04"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-geometry-jvm/1.0.0-alpha04/ink-geometry-jvm-1.0.0-alpha04.module",
        "group": "androidx.ink",
        "module": "ink-geometry-jvm",
        "version": "1.0.0-alpha04"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-geometry-jvm/1.0.0-alpha04/ink-geometry-jvm-1.0.0-alpha04.module",
        "group": "androidx.ink",
        "module": "ink-geometry-jvm",
        "version": "1.0.0-alpha04"
      }
    }
  ]
}