{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-core/1.6.0-alpha03/material-icons-core-1.6.0-alpha03.module",
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.6.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.6.0-alpha03.aar",
          "size": 709692,
          "sha512": "414a96ff98be0dbd0b5ca661af6beae99b710f5c4a81281ac5ebab1aed285ba959fddc9db8c50fef4437122a891246902ec0fe980b7d0ee32aa7bf9e792b1d4c",
          "sha256": "1ba539387a698b61578254bf8dbc07d5d11d6190a251358429565947b2bc26d1",
          "sha1": "62c2f955b37b155dbfe5d9a63b976c3f9a2e75b0",
          "md5": "3ac791a85fd0c9f639efce72cce5a853"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.6.0-alpha03.aar",
          "size": 709692,
          "sha512": "414a96ff98be0dbd0b5ca661af6beae99b710f5c4a81281ac5ebab1aed285ba959fddc9db8c50fef4437122a891246902ec0fe980b7d0ee32aa7bf9e792b1d4c",
          "sha256": "1ba539387a698b61578254bf8dbc07d5d11d6190a251358429565947b2bc26d1",
          "sha1": "62c2f955b37b155dbfe5d9a63b976c3f9a2e75b0",
          "md5": "3ac791a85fd0c9f639efce72cce5a853"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-android-1.6.0-alpha03-sources.jar",
          "url": "material-icons-core-android-1.6.0-alpha03-sources.jar",
          "size": 245508,
          "sha512": "14905fd8a0a3e679a92cf0650d82ada3294b49fe27ac7d1a607b0587244b381f4c591f63f5df5c4466a879eada76ee55b1dd2fc1eddc0a41640d6340fdb1a57f",
          "sha256": "48729ddeaa4270ce03e67a8a017ac6af4fb7ec988496ec87d1a5f9c5957aad4a",
          "sha1": "0e8bea2a68a490251b0c0c672cbf16bbcac861dc",
          "md5": "2dfcae2b1db00005e5e62eefdc988de1"
        }
      ]
    }
  ]
}