{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava2",
    "version": "1.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-1.3.0-beta01.aar",
          "url": "runtime-rxjava2-1.3.0-beta01.aar",
          "size": 23794,
          "sha512": "275a0d1dbe0f5ac358f6bc349adc4a366a7d6d7bb6cd7db503e276110c5e76f977d0bbf7a7a775ba5a12c2e42add50650c5cc38fd0893483f30d17b834464b45",
          "sha256": "268e485812066993e547e9fe8057e3ed524db75f1294c719d4e0d81852515f22",
          "sha1": "5971f91be1b840c87ca255d16d86f8b641081d47",
          "md5": "1272508b632111f0e79b9750e65456b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-1.3.0-beta01.aar",
          "url": "runtime-rxjava2-1.3.0-beta01.aar",
          "size": 23794,
          "sha512": "275a0d1dbe0f5ac358f6bc349adc4a366a7d6d7bb6cd7db503e276110c5e76f977d0bbf7a7a775ba5a12c2e42add50650c5cc38fd0893483f30d17b834464b45",
          "sha256": "268e485812066993e547e9fe8057e3ed524db75f1294c719d4e0d81852515f22",
          "sha1": "5971f91be1b840c87ca255d16d86f8b641081d47",
          "md5": "1272508b632111f0e79b9750e65456b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-rxjava2-1.3.0-beta01-sources.jar",
          "url": "runtime-rxjava2-1.3.0-beta01-sources.jar",
          "size": 2227,
          "sha512": "4ccb09788677591ff07ba2857e2a2c680c1f438e549f8c15fb6cde63f0efe07876269ed4a1036aaa4385c7f0fa3c7f97df3cbb27862f6bd9bf6df625481cf14a",
          "sha256": "342468c598af52c3071cab1f42a632ed6a6865d7faf66c3fd6d346ef2223628d",
          "sha1": "6b1b6ccf1fab2c2026994d1dc69a2b9e9db8ddbe",
          "md5": "8ab41ef7a0d228255e99d085ba61f207"
        }
      ]
    }
  ]
}