{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-core/1.1.7/datastore-core-1.1.7.module",
    "group": "androidx.datastore",
    "module": "datastore-core",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core.klib",
          "url": "datastore-core-macosarm64-1.1.7.klib",
          "size": 61245,
          "sha512": "58088707ed41bc6e1e99942cd84ea58e14f720b93e3b372fe250a593d76138de05d3571e06efa5b1d19f5f5884c3b3f32fd74b9333bb84d26ec386241727276d",
          "sha256": "6cfdb583a9cf83caaeaca9968594d3655e86096214e5fbe1ec865a7a6c08deca",
          "sha1": "fdbeb37e215dc8a8ca3e52c3e95b88cfe33939af",
          "md5": "43ac9cd1646beb0a9605ffebd30fbca8"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-macosarm64-1.1.7-sources.jar",
          "url": "datastore-core-macosarm64-1.1.7-sources.jar",
          "size": 34475,
          "sha512": "42c58358a322e5e2201c6a18e7f1e422a2e9458256de7f275322ec4e9cec8f11892236e10992614f91abb7b5b14ff826bf89e775cbccabea96f8ef6d094f29d1",
          "sha256": "9c23054ee4d2581b713fa6c378be367f8bd89cf783f1dd6dc3b6f7be29b2a703",
          "sha1": "c27822300ed754bac7e61983e33cfc26a129f537",
          "md5": "092be64ded16abf063006d96f17cf646"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-core-macosarm64-1.1.7-metadata.jar",
          "url": "datastore-core-macosarm64-1.1.7-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}