{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-3.3.0-rc01-multiplatform-sources.jar",
          "url": "paging-common-3.3.0-rc01-multiplatform-sources.jar",
          "size": 162407,
          "sha512": "ea187196786a635118ac8b0193921215ea5d846d1336e8079a5823ada309d308f715072e3a362a1a9a3d594b8ea2442d553498c6e09f0c8f00950eee9898eee8",
          "sha256": "121edc42c3995f1c6bf1633c8a808579b217e80f9e72e3bdb957a5add4f041d7",
          "sha1": "32c2ff8e4710ed1685983a82d30dcceb2c302221",
          "md5": "4419364cf2a9cbd380ce14b21491aae8"
        },
        {
          "name": "paging-common-3.3.0-rc01-samples-sources.jar",
          "url": "paging-common-3.3.0-rc01-samples-sources.jar",
          "size": 40591,
          "sha512": "cbdd887c89003f6b02e6d351773c1559a0dbef7b10cbe911b23cca6356a342b14e594999a9760eee35148e941d87f9005d86db0f299f9a5c4c5201f2e6219625",
          "sha256": "e38a380af1a161410207cb358cb5fcf1ec844432d92a5c9a741524a4767ef970",
          "sha1": "a577b372155d466531746351cd9d1dfb4812d0d5",
          "md5": "6a209d35769c6bb11bbca1bcbcd5b8ad"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "paging-common-3.3.0-rc01-versionMetadata.json",
          "size": 36214,
          "sha512": "31e2137a2c1eb452376e1e3b84440c6cae2fc8163e9d7a3ed3ca391977b9650b338c5e14a6d430b89f8b585919c5844ac4e909a908ab3975b4a5e1297d12c539",
          "sha256": "aef75c49e67489f9c222e5d8caa915a024b68c225ae0571e3918e969028c86b1",
          "sha1": "fa17969720760f70c0c32d4ebb6f553875d9c82a",
          "md5": "ea71c6f383cb71689490aebff55f4b59"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-beta02"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-metadata-3.3.0-rc01.jar",
          "url": "paging-common-3.3.0-rc01.jar",
          "size": 19815,
          "sha512": "4e97bb152b2666fdbdac4d88f0a276bc56d515ea69289eaf77b3e37f5e47c4f63a3a87f6608817e0ee3b261e3ceb2014687d58cea30e9aff43e2bfac68c5cd45",
          "sha256": "abb78f01df84b8692432a08ce683f93b1daf27d51b31450bfd172e6593aa1ab6",
          "sha1": "9251818d927ef4fb7e799105e0ca715cd7f2f08b",
          "md5": "954ed8579015fcabf7fd63ebf01ed457"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-compose",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.3.0-rc01"
          },
          "reason": "paging-common is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-common-kotlin-3.3.0-rc01-sources.jar",
          "url": "paging-common-3.3.0-rc01-sources.jar",
          "size": 155746,
          "sha512": "ffb07d4a541c81632d7f4e1c827b6ad0ea0a8ee4081584b6e888e5c4527bd36f1bb39abe9684f849fa9f221d64663758a62355c048a905abdbdb5be52874be15",
          "sha256": "e4dc79e043c729a4276e8ffc6d1067d67217440d3a72977fe2d68ba777d8fc9c",
          "sha1": "46e565d9c90d3d025772944549a4c5159805ec59",
          "md5": "3b0581dbf92cb8f7d2b7423627375f17"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-common-android/3.3.0-rc01/paging-common-android-3.3.0-rc01.module",
        "group": "androidx.paging",
        "module": "paging-common-android",
        "version": "3.3.0-rc01"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-common-android/3.3.0-rc01/paging-common-android-3.3.0-rc01.module",
        "group": "androidx.paging",
        "module": "paging-common-android",
        "version": "3.3.0-rc01"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../paging-common-android/3.3.0-rc01/paging-common-android-3.3.0-rc01.module",
        "group": "androidx.paging",
        "module": "paging-common-android",
        "version": "3.3.0-rc01"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../paging-common-jvm/3.3.0-rc01/paging-common-jvm-3.3.0-rc01.module",
        "group": "androidx.paging",
        "module": "paging-common-jvm",
        "version": "3.3.0-rc01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../paging-common-jvm/3.3.0-rc01/paging-common-jvm-3.3.0-rc01.module",
        "group": "androidx.paging",
        "module": "paging-common-jvm",
        "version": "3.3.0-rc01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../paging-common-jvm/3.3.0-rc01/paging-common-jvm-3.3.0-rc01.module",
        "group": "androidx.paging",
        "module": "paging-common-jvm",
        "version": "3.3.0-rc01"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-linuxx64/3.3.0-rc01/paging-common-linuxx64-3.3.0-rc01.module",
        "group": "androidx.paging",
        "module": "paging-common-linuxx64",
        "version": "3.3.0-rc01"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../paging-common-linuxx64/3.3.0-rc01/paging-common-linuxx64-3.3.0-rc01.module",
        "group": "androidx.paging",
        "module": "paging-common-linuxx64",
        "version": "3.3.0-rc01"
      }
    }
  ]
}