{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit",
    "version": "1.0.0-beta06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7321851"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-beta06"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-beta06.aar",
          "url": "ui-unit-1.0.0-beta06.aar",
          "size": 57132,
          "sha512": "0f5a1b554bd962e22d0a63a28838d8d52d04416b33e893961bcb63be158a7d07d26a355fd4371bf5b5b78e3fc044e088d1c8080fbd605479dfc43a5095886373",
          "sha256": "2a24d9c27bb8772da5f1566c75d838e32568566e43d73a01983c3f4ad2f55a5d",
          "sha1": "32641fd7cb0c4128abecee4fa23ae32ad19f6c55",
          "md5": "aa59d54dba90d7b776d433bed4210bf6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0-beta06"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-beta06"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-1.0.0-beta06.aar",
          "url": "ui-unit-1.0.0-beta06.aar",
          "size": 57132,
          "sha512": "0f5a1b554bd962e22d0a63a28838d8d52d04416b33e893961bcb63be158a7d07d26a355fd4371bf5b5b78e3fc044e088d1c8080fbd605479dfc43a5095886373",
          "sha256": "2a24d9c27bb8772da5f1566c75d838e32568566e43d73a01983c3f4ad2f55a5d",
          "sha1": "32641fd7cb0c4128abecee4fa23ae32ad19f6c55",
          "md5": "aa59d54dba90d7b776d433bed4210bf6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-1.0.0-beta06-sources.jar",
          "url": "ui-unit-1.0.0-beta06-sources.jar",
          "size": 21567,
          "sha512": "27bb5e069638b94ea43d560110659c73229b4f153a8a20ed313160e2b1599476b51e23120473d101a174e990d5ef994da25b19144698f49e415262a0af43a9be",
          "sha256": "b2b2482c3ce2543f33a6c80656c362576703131ba40f73defaa5fe12bbdb3f4b",
          "sha1": "45609ba6acc37203c150962de7f243948ea71e19",
          "md5": "34954b6248d6d3c94a8b1a4623291224"
        }
      ]
    }
  ]
}
