{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-rxjava2/1.10.0-alpha02/runtime-rxjava2-1.10.0-alpha02.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava2",
    "version": "1.10.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13969651"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha02"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2.aar",
          "url": "runtime-rxjava2-android-1.10.0-alpha02.aar",
          "size": 28160,
          "sha512": "0010605ac383e673d7223e168b4841652bbe194bb27f5ce3059f5c405effb7ba75371b747f1a7d8bf114b14e63094aac22dc59cff5788d0f6837f32cbdc31dc7",
          "sha256": "ff91458bd9408b8af466a0f8378239645d8eb0d89fb66f1b9adf224fe3e81be4",
          "sha1": "e45c51b91373473136f857c877a76640f880c992",
          "md5": "528b794a216538263217de45a3b0e232"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha02"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2.aar",
          "url": "runtime-rxjava2-android-1.10.0-alpha02.aar",
          "size": 28160,
          "sha512": "0010605ac383e673d7223e168b4841652bbe194bb27f5ce3059f5c405effb7ba75371b747f1a7d8bf114b14e63094aac22dc59cff5788d0f6837f32cbdc31dc7",
          "sha256": "ff91458bd9408b8af466a0f8378239645d8eb0d89fb66f1b9adf224fe3e81be4",
          "sha1": "e45c51b91373473136f857c877a76640f880c992",
          "md5": "528b794a216538263217de45a3b0e232"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "runtime-rxjava2 is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-android-1.10.0-alpha02-sources.jar",
          "url": "runtime-rxjava2-android-1.10.0-alpha02-sources.jar",
          "size": 6774,
          "sha512": "76b7c724d22a87ba433f9c7f99274139d7494d9387074e3f27ee7af6eb7729bfc4e7b905a9b26e13e771c7d08d6ed60da46291659dc2215f89c25103ff2ab8fe",
          "sha256": "db8af0db58a34c531ce5c905f48560c3ccbf4bed24ee69c52f533f45047e62fc",
          "sha1": "9f02974584a51d69715d42383200ab29683512de",
          "md5": "2b75a8a2d3b5ccb6f5eff0d9cef5d416"
        },
        {
          "name": "runtime-rxjava2-1.10.0-alpha02-samples-sources.jar",
          "url": "runtime-rxjava2-android-1.10.0-alpha02-samples-sources.jar",
          "size": 6108,
          "sha512": "f3d49c42fbfdef1bf5dc448470390407b06f9065bfddc7e1f8c464662fc396e14a51f0b553ffdff066b5b92fe8e47dbf60e27cc38c0abaebe087269c74bddfa7",
          "sha256": "7de164b0d0756b949c8a3f1ec53cc3867803b4fadb2539510784943dace34990",
          "sha1": "0e4b053760ff4b7a97370bf48f6317d7c778a27c",
          "md5": "4732460fb8e830281f90670db5b51c50"
        }
      ]
    }
  ]
}