{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0-rc02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.0-alpha15.aar",
          "url": "material3-1.0.0-alpha15.aar",
          "size": 2800408,
          "sha512": "e75a2176e38b8e5bfd88842ea951cf9ad997a3c2ac7e4f52d6db0c69df16e24ca24c63a736409d2cf027f5fd075b38429cd3e8ad4615ac604907ba1389675fee",
          "sha256": "2e576fcc8132394c52e2d68745d0de1472a473b075ccc6f5112378929c38d9b2",
          "sha1": "228b8f180f42bae59f682632b718f5f98f8c4c86",
          "md5": "55307536d43f57884270b632092f5dfc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0-rc02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.0.0-alpha15.aar",
          "url": "material3-1.0.0-alpha15.aar",
          "size": 2800408,
          "sha512": "e75a2176e38b8e5bfd88842ea951cf9ad997a3c2ac7e4f52d6db0c69df16e24ca24c63a736409d2cf027f5fd075b38429cd3e8ad4615ac604907ba1389675fee",
          "sha256": "2e576fcc8132394c52e2d68745d0de1472a473b075ccc6f5112378929c38d9b2",
          "sha1": "228b8f180f42bae59f682632b718f5f98f8c4c86",
          "md5": "55307536d43f57884270b632092f5dfc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-1.0.0-alpha15-sources.jar",
          "url": "material3-1.0.0-alpha15-sources.jar",
          "size": 261035,
          "sha512": "ef4156b07e14179975dd0c8c58d6b75df3a8e7e37e876bb5e55bea884b73670d475c49b5e5ab8685f5f80c06c1c7e7bc85d2be58db9f3f9241d04b755e348092",
          "sha256": "623736d777dcab946098f544b13aae798b26f96e2e7c154e101874c61cddb823",
          "sha1": "5046534572cfcdf93d0c4210ad8b74d07a1f028d",
          "md5": "e80f6cccdbdb14c2fc328c0ec57098d2"
        }
      ]
    }
  ]
}