{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-viewbinding-samples",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-samples-1.1.0-beta02.aar",
          "url": "ui-viewbinding-samples-1.1.0-beta02.aar",
          "size": 9718,
          "sha512": "0e3212b554beb548b499d2295c1d1996932bff0f7e75f3839b3b05a04fbe8d89509206f20ca3970c12f7176b9da52a13d2a9bf59ca0728127517c0724a725dfa",
          "sha256": "0c1f77f3299d76749ad08144ad808a955d3f00afc7d5103c47666bdf3f421d1f",
          "sha1": "bce958bae508d24dd6714c7317f3ca62ded80b30",
          "md5": "ac5c15c0e17cb7db94d27b9721ba97db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-samples-1.1.0-beta02.aar",
          "url": "ui-viewbinding-samples-1.1.0-beta02.aar",
          "size": 9718,
          "sha512": "0e3212b554beb548b499d2295c1d1996932bff0f7e75f3839b3b05a04fbe8d89509206f20ca3970c12f7176b9da52a13d2a9bf59ca0728127517c0724a725dfa",
          "sha256": "0c1f77f3299d76749ad08144ad808a955d3f00afc7d5103c47666bdf3f421d1f",
          "sha1": "bce958bae508d24dd6714c7317f3ca62ded80b30",
          "md5": "ac5c15c0e17cb7db94d27b9721ba97db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-viewbinding-samples-1.1.0-beta02-sources.jar",
          "url": "ui-viewbinding-samples-1.1.0-beta02-sources.jar",
          "size": 1517,
          "sha512": "8a312b184765944e6cdd2a19f32ef47de77d2124ebdebdeef7eadcf37f208bf2ea3e9d28f3762b5ee24263d9ab10cb5024ea4a095a56cda122998fffe59b94a2",
          "sha256": "a1e23ebca5ce3ac9f020ac001520017c0221eb8305544092b8a807fe48c82e0f",
          "sha1": "4a0578956b7cccf0d6a316c2e370305974b55c58",
          "md5": "4e0cb348f1b27b827ae8b187ebe50959"
        }
      ]
    }
  ]
}
