{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-samples",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "animation-samples-1.1.0-alpha05.aar",
          "url": "animation-samples-1.1.0-alpha05.aar",
          "size": 230628,
          "sha512": "6b1cc70b1aa444be1919a1717ef857d5900fdce8ace7379234ad5b97d2b09c608cb150c24fec08eee14418bc9d39f31525f32cec6b3caf0a0a1a64583e12d1f6",
          "sha256": "78923140493ad0f97e351ba7fe2cf58f47a9457574c3c3cc08c04598575c59d6",
          "sha1": "8f1c78e20c8cabd492c57ef8527ca6d052cfc4cf",
          "md5": "132c9af86f2086bd25657ec1a747a3bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.1.0-alpha05.aar",
          "url": "animation-samples-1.1.0-alpha05.aar",
          "size": 230628,
          "sha512": "6b1cc70b1aa444be1919a1717ef857d5900fdce8ace7379234ad5b97d2b09c608cb150c24fec08eee14418bc9d39f31525f32cec6b3caf0a0a1a64583e12d1f6",
          "sha256": "78923140493ad0f97e351ba7fe2cf58f47a9457574c3c3cc08c04598575c59d6",
          "sha1": "8f1c78e20c8cabd492c57ef8527ca6d052cfc4cf",
          "md5": "132c9af86f2086bd25657ec1a747a3bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-samples-1.1.0-alpha05-sources.jar",
          "url": "animation-samples-1.1.0-alpha05-sources.jar",
          "size": 17167,
          "sha512": "0b1de45aece1fd5b1108433aaf0bd089b402aa9ae5470d94ffc4963db1d701778590be2710cdd033d6cf681c05730669d3612148bcef7afbec49bce0b7994cfb",
          "sha256": "11ebca555d2b580d6273c7960c9532d45562fffa9deee5feae877432301a991c",
          "sha1": "75a108e29b422a9a22f932a9e2472c221ffdfe9c",
          "md5": "036c64879a8c9768dc42b071f89c04fe"
        }
      ]
    }
  ]
}
