{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-graphics/1.8.0-alpha05/animation-graphics-1.8.0-alpha05.module",
    "group": "androidx.compose.animation",
    "module": "animation-graphics",
    "version": "1.8.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha05"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha05"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha05"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics.klib",
          "url": "animation-graphics-linuxx64stubs-1.8.0-alpha05.klib",
          "size": 68059,
          "sha512": "5f5a2243671f8b92a0333e0d159b73fa02fa5d5085a098d3d23e4c4b9eee8d815fa82ed744a3cf36ee19b2ccccd1cabd8c2a03f414d77e8542655b4ff898cdb5",
          "sha256": "c4ca64c6afec6ac4c3cf1c38adb4b96f924b55ffdffcdce1fd6903889e556ff2",
          "sha1": "6e1e88e1cd7df6773767bc3e34615e35df2deab2",
          "md5": "cefb99b262f59bf6db18b3c1d3e56beb"
        }
      ]
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha05"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.0-alpha05"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.0-alpha05"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-linuxx64stubs-1.8.0-alpha05-sources.jar",
          "url": "animation-graphics-linuxx64stubs-1.8.0-alpha05-sources.jar",
          "size": 14163,
          "sha512": "b366cf050ff740457e893a196cec759c013cfb8695f178cf866aab9a9933962fa9eba1324ca9133c7bb6bf459dc205c1caeeff0a3258228e905019321776e7da",
          "sha256": "79a218c38807469cd1a034ee2930ed7b4849f2890e07f92dfa6eb4ad393bf6cc",
          "sha1": "9fb721b15da5d9389136b4e8773ba244df008ec9",
          "md5": "6d88b49bbb6f992dd82bbac4c198d394"
        }
      ]
    }
  ]
}