{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3-samples",
    "version": "1.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material3-samples-1.0.0-alpha06.aar",
          "url": "material3-samples-1.0.0-alpha06.aar",
          "size": 594512,
          "sha512": "88a1e9a8dd7bd52c52ed63d1be70abe448b8a276e671e7230f6b839595f5eb36c78c28df91da560396e0cc7bd1280e3b3bbef67745ad024b1d6befc1c7a70d87",
          "sha256": "4f6e1b4e177c48c2c8aa92b5c690da87e5b2aada640446b0fd280e3d69904c44",
          "sha1": "259960fd5c97187bcbaa30d58a28872be06b18fe",
          "md5": "3ece24337abd47e4f0b842bfe6b871fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material3-samples-1.0.0-alpha06.aar",
          "url": "material3-samples-1.0.0-alpha06.aar",
          "size": 594512,
          "sha512": "88a1e9a8dd7bd52c52ed63d1be70abe448b8a276e671e7230f6b839595f5eb36c78c28df91da560396e0cc7bd1280e3b3bbef67745ad024b1d6befc1c7a70d87",
          "sha256": "4f6e1b4e177c48c2c8aa92b5c690da87e5b2aada640446b0fd280e3d69904c44",
          "sha1": "259960fd5c97187bcbaa30d58a28872be06b18fe",
          "md5": "3ece24337abd47e4f0b842bfe6b871fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-samples-1.0.0-alpha06-sources.jar",
          "url": "material3-samples-1.0.0-alpha06-sources.jar",
          "size": 24907,
          "sha512": "e717f5ea71798919936c4ce0e3cc00eec0487d8ba2ef9385ded33c2ec3dc32b7d41610a9bc5deef137198c68904338543353f99cbfe8fd9f30ccf8d2561a881f",
          "sha256": "652927f645657a18e93b33c53eb4a88c129c7c12c1cc1d087503fad377bb999e",
          "sha1": "ee0072f0b6037b778b76eb51682b417a9af0e4e1",
          "md5": "013e27759ccda99198b4ce605c1fedf4"
        }
      ]
    }
  ]
}
