{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-samples",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-samples-1.3.0-alpha01.aar",
          "url": "window-samples-1.3.0-alpha01.aar",
          "size": 13120,
          "sha512": "d082e6fe0c7bd1468db1b5892f6fec62a25e263b17dd1005eda44c05838eefba6618b8bdab5a784d2735ef1e139a0bc0ab698b9e6c12f3d3cfe02a9da4d0ea21",
          "sha256": "4ef845ab9ba6b935f6df0bbb8008d10af83e672446c5b453ebeb57a29f19d0bc",
          "sha1": "7d48ac40e56d8898fe8ff60d94e1bd7a8c21d4e2",
          "md5": "b76e141561941d0312941fd037e0480a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-samples-1.3.0-alpha01.aar",
          "url": "window-samples-1.3.0-alpha01.aar",
          "size": 13120,
          "sha512": "d082e6fe0c7bd1468db1b5892f6fec62a25e263b17dd1005eda44c05838eefba6618b8bdab5a784d2735ef1e139a0bc0ab698b9e6c12f3d3cfe02a9da4d0ea21",
          "sha256": "4ef845ab9ba6b935f6df0bbb8008d10af83e672446c5b453ebeb57a29f19d0bc",
          "sha1": "7d48ac40e56d8898fe8ff60d94e1bd7a8c21d4e2",
          "md5": "b76e141561941d0312941fd037e0480a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "window-samples is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-samples-1.3.0-alpha01-sources.jar",
          "url": "window-samples-1.3.0-alpha01-sources.jar",
          "size": 3568,
          "sha512": "f92fca2c8173093a6669f284fb473bc11fb18bf4fc20a30740875655608a18f80a669772366052c8dc0cf57ead7403faf056e5d0b288bae2f2b74d37077c54cb",
          "sha256": "1b6a0669243bff243293e002934c340253b79229ab9ed0201ed2ed9a4e476fc8",
          "sha1": "4e5745950262dc6ea4d0cb50a16ce298d9467bce",
          "md5": "4f1f601dca2a7ecbff673f7254406738"
        }
      ]
    }
  ]
}