{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-runtime-ktx",
    "version": "3.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-ktx-3.1.0-alpha04.aar",
          "url": "paging-runtime-ktx-3.1.0-alpha04.aar",
          "size": 1743,
          "sha512": "c6f64ebb991271119a9b6973d1b18a040de09c78d88802f87fafb40d1627a94d93df3fb4dc93648695d21195635089fdfb08f65b68da22f6e38e22e03789d68a",
          "sha256": "774bb88455a1d7e750ad7336f6a3a0aeb993b33230d3abe44408f617cf84a448",
          "sha1": "a82bd55c767c8c91a34b59373e03144fcaeaea5a",
          "md5": "59374dc60164cdc874061239cc7e7ec2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.1.0-alpha04"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-ktx-3.1.0-alpha04.aar",
          "url": "paging-runtime-ktx-3.1.0-alpha04.aar",
          "size": 1743,
          "sha512": "c6f64ebb991271119a9b6973d1b18a040de09c78d88802f87fafb40d1627a94d93df3fb4dc93648695d21195635089fdfb08f65b68da22f6e38e22e03789d68a",
          "sha256": "774bb88455a1d7e750ad7336f6a3a0aeb993b33230d3abe44408f617cf84a448",
          "sha1": "a82bd55c767c8c91a34b59373e03144fcaeaea5a",
          "md5": "59374dc60164cdc874061239cc7e7ec2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-runtime-ktx-3.1.0-alpha04-sources.jar",
          "url": "paging-runtime-ktx-3.1.0-alpha04-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
