{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-samples",
    "version": "1.2.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-test-samples-1.2.0-alpha06.aar",
          "url": "ui-test-samples-1.2.0-alpha06.aar",
          "size": 43500,
          "sha512": "5f84bf8324c475c859bed83d3e213faa642c6e50a9a9ac6d22b18ee7feb5ca3f169ad2172777f95ca6b0a99f14d25722131e1146880e91694ad0cd2607e89f02",
          "sha256": "f9b8c509e7e63ecf887bdc37c26d6537a7f02fa8f9a7b980606aa79020449af8",
          "sha1": "200ca42ac6fa264f0e12672c4ef4a9a5427e1c0f",
          "md5": "a1de7b68a97e86fdcab167769d3eeda3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.2.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-samples-1.2.0-alpha06.aar",
          "url": "ui-test-samples-1.2.0-alpha06.aar",
          "size": 43500,
          "sha512": "5f84bf8324c475c859bed83d3e213faa642c6e50a9a9ac6d22b18ee7feb5ca3f169ad2172777f95ca6b0a99f14d25722131e1146880e91694ad0cd2607e89f02",
          "sha256": "f9b8c509e7e63ecf887bdc37c26d6537a7f02fa8f9a7b980606aa79020449af8",
          "sha1": "200ca42ac6fa264f0e12672c4ef4a9a5427e1c0f",
          "md5": "a1de7b68a97e86fdcab167769d3eeda3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-samples-1.2.0-alpha06-sources.jar",
          "url": "ui-test-samples-1.2.0-alpha06-sources.jar",
          "size": 8399,
          "sha512": "5a0605048360ddac5a7fcbf91fdd0ecfc97b3fafd57a39356d562db932d4373438bf3da552a7315b6fc97135aa3197a262e14db0817ff2334275fb65582cf7f5",
          "sha256": "a1ee0e8a5428be3f57acb5bfd6f6ecae481c37a52770f0a2963d1a40a3987fb3",
          "sha1": "555f1fac8e0c1389e3ce629f99db2c7c3b5e7707",
          "md5": "a170048e750140b3f53d4f78343f568f"
        }
      ]
    }
  ]
}