{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-guava",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7318172"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "paging-guava-3.0.0.aar",
          "url": "paging-guava-3.0.0.aar",
          "size": 20766,
          "sha512": "aba7f164c962f429e9c95944f7c70d2f5eae4de1999eb1e7d1843c835a9a5a7f61ddbcdfdb0eecc3403884e0a3fcccdf30a404470e71b7c8251c8de5d11dce0b",
          "sha256": "09ed2b44c807c7ba56cde50a00dbf7723db67e355a09b734b550ede0553e5bbe",
          "sha1": "2299d642a3032495e36ce30fe593935f1683ce71",
          "md5": "ddd1e47e256fab4f6d18fa6da0de2d15"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "paging-guava-3.0.0.aar",
          "url": "paging-guava-3.0.0.aar",
          "size": 20766,
          "sha512": "aba7f164c962f429e9c95944f7c70d2f5eae4de1999eb1e7d1843c835a9a5a7f61ddbcdfdb0eecc3403884e0a3fcccdf30a404470e71b7c8251c8de5d11dce0b",
          "sha256": "09ed2b44c807c7ba56cde50a00dbf7723db67e355a09b734b550ede0553e5bbe",
          "sha1": "2299d642a3032495e36ce30fe593935f1683ce71",
          "md5": "ddd1e47e256fab4f6d18fa6da0de2d15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-guava-3.0.0-sources.jar",
          "url": "paging-guava-3.0.0-sources.jar",
          "size": 4782,
          "sha512": "8fc0f498cb309315546049c3b8d6259c4f53224252126b3562286e74ee8dac4deb9c549eca37bb8d8907800386800cdc11613823632a061b095622394b5d275e",
          "sha256": "b493a6ff80a46b7786e0dd57269b148e64d2ca8fe7b4e965464cdd62c0b431af",
          "sha1": "54a3751815014aae94b6403f89fbdbeca7cb7fb4",
          "md5": "aa573d5d66dd4b0e9e4a68ee8dc91d22"
        }
      ]
    }
  ]
}
