{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-emojipicker",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-emojipicker-1.4.0-beta01.aar",
          "url": "emoji2-emojipicker-1.4.0-beta01.aar",
          "size": 237814,
          "sha512": "162ce47d5429bc578281cd0eba4acb175ecce00241bb00f87a123327e046d2e83e910d63e7af35900adc61e57c0a364f426ad13659ca820480ef44a8b67d0548",
          "sha256": "176b872001b3ea1d155626184cf1ce1cf870aa822932f26e4ea755e7061af3e8",
          "sha1": "9c2d15806a965b9e9990e0fb7e8aafecf006c134",
          "md5": "8b691adeb83fc47becf443a08408cb50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-emojipicker-1.4.0-beta01.aar",
          "url": "emoji2-emojipicker-1.4.0-beta01.aar",
          "size": 237814,
          "sha512": "162ce47d5429bc578281cd0eba4acb175ecce00241bb00f87a123327e046d2e83e910d63e7af35900adc61e57c0a364f426ad13659ca820480ef44a8b67d0548",
          "sha256": "176b872001b3ea1d155626184cf1ce1cf870aa822932f26e4ea755e7061af3e8",
          "sha1": "9c2d15806a965b9e9990e0fb7e8aafecf006c134",
          "md5": "8b691adeb83fc47becf443a08408cb50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-emojipicker-1.4.0-beta01-sources.jar",
          "url": "emoji2-emojipicker-1.4.0-beta01-sources.jar",
          "size": 28078,
          "sha512": "f3acd823d008dbd5701f0ac61b8447bd75f03b3a61f6057ea11b2b0d9cf163986f3bbdbc455c5b55836e0e52e810e81795a810ec8d68279d2d28962ef9a6ae87",
          "sha256": "ffb157acd398a9b9135bca39715a846264defd3bb6f8a1c28cad825b39128b46",
          "sha1": "9a51a8d61c5aedd09d5914dac5e4f7da873057b8",
          "md5": "df82612d32662b7656cd1a5983afbf28"
        }
      ]
    }
  ]
}