{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-guava",
    "version": "1.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-guava-1.0.0-beta01.aar",
          "url": "watchface-guava-1.0.0-beta01.aar",
          "size": 22540,
          "sha512": "5c6ba320d37fc756c635bd125b9dfc13cd576bde3c5b6219751aaf36e36ec8d6b8567268d14e40933cab57be6799c55623bc5bc32b5c41f3ab7a13c1fc2fdbc1",
          "sha256": "1579a9ba2fa405bacb40a246a9090278be4ad285623e9222ef3763d596549ec7",
          "sha1": "1a0f3fb7bbc729a1a60f44c4674b8a9aad77535f",
          "md5": "cb0f0fc793e6263cebe310bf114d1cbd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-android"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-guava-1.0.0-beta01.aar",
          "url": "watchface-guava-1.0.0-beta01.aar",
          "size": 22540,
          "sha512": "5c6ba320d37fc756c635bd125b9dfc13cd576bde3c5b6219751aaf36e36ec8d6b8567268d14e40933cab57be6799c55623bc5bc32b5c41f3ab7a13c1fc2fdbc1",
          "sha256": "1579a9ba2fa405bacb40a246a9090278be4ad285623e9222ef3763d596549ec7",
          "sha1": "1a0f3fb7bbc729a1a60f44c4674b8a9aad77535f",
          "md5": "cb0f0fc793e6263cebe310bf114d1cbd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "watchface-guava-1.0.0-beta01-sources.jar",
          "url": "watchface-guava-1.0.0-beta01-sources.jar",
          "size": 5468,
          "sha512": "5499b97924159a92e8ebb2c9748c66e40b95735641e25cd37dd5854c6f5f809ef241368e45a29794653db5ebaa48b26ed2268fc62b05da156c9b4ce72a202002",
          "sha256": "9a56caf8cd479b7be4111f1503fdad8c89d65674ab815e659a73250bac9d3b1a",
          "sha1": "2c0bf82fb81a2ac7b6d14865d18f73c9c0781c14",
          "md5": "06a0ab2b0d67aafc55942534121fa76e"
        }
      ]
    }
  ]
}
