{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear-watchface-style",
    "version": "1.0.0-alpha22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear-watchface-data",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "wear-watchface-style-1.0.0-alpha22.aar",
          "url": "wear-watchface-style-1.0.0-alpha22.aar",
          "size": 92275,
          "sha512": "919279c166fdd23f22b865f07f8ee2a749e567a4b34102c2bfdaef833a4c3d161a1c83c1759d50d8b66fd764fef1b46e1c0ff95d797951a38adedbf623b75e65",
          "sha256": "05f9a6a82229c22b702c35d0d4c3ace79ee75378a1a087d17614fcced469e5d2",
          "sha1": "5de62ef40e10291c64bf9d62d2814b9075026efb",
          "md5": "be045ae6a14114700a023429eb4079cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear-watchface-data",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-watchface-style-1.0.0-alpha22.aar",
          "url": "wear-watchface-style-1.0.0-alpha22.aar",
          "size": 92275,
          "sha512": "919279c166fdd23f22b865f07f8ee2a749e567a4b34102c2bfdaef833a4c3d161a1c83c1759d50d8b66fd764fef1b46e1c0ff95d797951a38adedbf623b75e65",
          "sha256": "05f9a6a82229c22b702c35d0d4c3ace79ee75378a1a087d17614fcced469e5d2",
          "sha1": "5de62ef40e10291c64bf9d62d2814b9075026efb",
          "md5": "be045ae6a14114700a023429eb4079cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-watchface-style-1.0.0-alpha22-sources.jar",
          "url": "wear-watchface-style-1.0.0-alpha22-sources.jar",
          "size": 16193,
          "sha512": "e9e272d410bf71444562471e3b6f2c1083a35c4d064536958ef831c08319e4aef6c3d37a391d3b077af287652060bed5a3c21478afc28717db2c638661c28f28",
          "sha256": "62b484b348c896a34077f4711aa237425ade6d8d990f4146b4d42c31b4cd927c",
          "sha1": "21e69e9aea6525d9edff931864abc455a183812f",
          "md5": "9e3199a77f701d05d12a85226acf0e9f"
        }
      ]
    }
  ]
}
