{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe-integration",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 1115115,
          "sha512": "99bd224158c52cbb10f7efe33028a0c826210a017a261a3915fcb3acbcc9cece0c4b89b69a24422e526f0e2c3061d38e24e3ff224bfe98b0c0907c8a29d1576c",
          "sha256": "53e6a30c7fbde380ced1d667f4f0cdb3093dcae9599918df519e069a902f8c6f",
          "sha1": "84eaaa828f1258c2ba078d5ae3b9b755ef28c2a8",
          "md5": "34fe9d4820f06633d7ac36043a72f64a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-listenablefuture-callback",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.44"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.13.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 1115115,
          "sha512": "99bd224158c52cbb10f7efe33028a0c826210a017a261a3915fcb3acbcc9cece0c4b89b69a24422e526f0e2c3061d38e24e3ff224bfe98b0c0907c8a29d1576c",
          "sha256": "53e6a30c7fbde380ced1d667f4f0cdb3093dcae9599918df519e069a902f8c6f",
          "sha1": "84eaaa828f1258c2ba078d5ae3b9b755ef28c2a8",
          "md5": "34fe9d4820f06633d7ac36043a72f64a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "size": 117443,
          "sha512": "5247530a88231e094dae88c222f0518b40b91bff289c74e2c7a8706bdcb6320c22797ace52312034a61068e36701062a6215025c587612ef8c10867df57b272d",
          "sha256": "aa67597ee1888239edaab76f6fea4be7ba7af32e83a79d1da5f67578f6b29f13",
          "sha1": "101576f53cf4ae35a4e12dd14a5d06c3a1b32d3e",
          "md5": "d10c26cf688ee2eec2d7fdb1bdbe78e0"
        }
      ]
    }
  ]
}