{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials.registry",
    "module": "registry-provider",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14202175"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-mdoc",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-openid",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-sdjwtvc",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-provider-play-services",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        }
      ],
      "files": [
        {
          "name": "registry-provider-1.0.0-alpha03-sources.jar",
          "url": "registry-provider-1.0.0-alpha03-sources.jar",
          "size": 34811,
          "sha512": "ed1d8202f4e205828dda8f7046ade0387b747ae161e277ea8b226a3d8c47755537d588ec4b501e3fa8bf55ba2bf9eb66f31a7d89c079bf08a248aeed8ce2222b",
          "sha256": "2ddab5a840fab1b46244a6478afe56907463bc900a208d72c53704c2a1783e2d",
          "sha1": "7274f1bcb079e02b4eb3218abba987a1c67a1f07",
          "md5": "3366e20ba0ac6dda6668bc5dcc43d073"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-mdoc",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-openid",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-sdjwtvc",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-provider-play-services",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "registry-provider-1.0.0-alpha03.aar",
          "url": "registry-provider-1.0.0-alpha03.aar",
          "size": 49310,
          "sha512": "97aa6cb36db23f3c5965b92ee4e42422b456775c04cb9969c5ecbd64a63f6161d983855b0ce3df27991c97ff4a35855e731471effe109771ae86fc37bba75fb1",
          "sha256": "6d0655ebb8f4127cb6645a60b2d81621aedb5c0e0c406db447af40e874ab8a99",
          "sha1": "c29a9eb721a6a4f171028904fbc2df597e63dbe4",
          "md5": "ab8e69e24438b21bb25ba5c34780fa84"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-mdoc",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-openid",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-sdjwtvc",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-provider-play-services",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "registry-provider-1.0.0-alpha03.aar",
          "url": "registry-provider-1.0.0-alpha03.aar",
          "size": 49310,
          "sha512": "97aa6cb36db23f3c5965b92ee4e42422b456775c04cb9969c5ecbd64a63f6161d983855b0ce3df27991c97ff4a35855e731471effe109771ae86fc37bba75fb1",
          "sha256": "6d0655ebb8f4127cb6645a60b2d81621aedb5c0e0c406db447af40e874ab8a99",
          "sha1": "c29a9eb721a6a4f171028904fbc2df597e63dbe4",
          "md5": "ab8e69e24438b21bb25ba5c34780fa84"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-mdoc",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-openid",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-digitalcredentials-sdjwtvc",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-provider-play-services",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "registry-provider is in atomic group androidx.credentials.registry"
        }
      ],
      "files": [
        {
          "name": "registry-provider-1.0.0-alpha03-versionMetadata.json",
          "url": "registry-provider-1.0.0-alpha03-versionMetadata.json",
          "size": 11863,
          "sha512": "cbc938627787e181d59fd36837133f85b952e4bedcc38c0d0035315632cc10d6d29afe1dbb57ca10b480244ad3f485f23e6482a3ad5fa35b700e5120d5d9dcc5",
          "sha256": "714260d61291e626fda0b0b73dc873076b25de8d5f7b7a7374dd7b88e1447669",
          "sha1": "c8b610864567c7240ae2bf65cb9ed0f0fa3e8819",
          "md5": "c71c92e991312206f947b1746e71d8f8"
        }
      ]
    }
  ]
}