{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler-daemon",
    "version": "1.2.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compiler-daemon-1.2.0-alpha08.jar",
          "url": "compiler-daemon-1.2.0-alpha08.jar",
          "size": 18747,
          "sha512": "6f9392e6d0a494e5faa8d6c84d4300c5b4c4b8c212913745cecb911e5ddc1823ad7346a76b594c511d21a81079a5142dec8b2aaf00d9c8c0e617dbd9d1b6ec74",
          "sha256": "3afb8284a51560602433ac1d3aa269c37fab2f7ba7ccbb056fbff1df2742ba40",
          "sha1": "7b1ecd0e7e7ffb30dbdc31a8a4d3748b3a3a51fa",
          "md5": "018720dd94a428e29cb0cb6c230ae4b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler-hosted",
          "version": {
            "requires": "1.2.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-compiler",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "compiler-daemon-1.2.0-alpha08.jar",
          "url": "compiler-daemon-1.2.0-alpha08.jar",
          "size": 18747,
          "sha512": "6f9392e6d0a494e5faa8d6c84d4300c5b4c4b8c212913745cecb911e5ddc1823ad7346a76b594c511d21a81079a5142dec8b2aaf00d9c8c0e617dbd9d1b6ec74",
          "sha256": "3afb8284a51560602433ac1d3aa269c37fab2f7ba7ccbb056fbff1df2742ba40",
          "sha1": "7b1ecd0e7e7ffb30dbdc31a8a4d3748b3a3a51fa",
          "md5": "018720dd94a428e29cb0cb6c230ae4b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-daemon-1.2.0-alpha08-sources.jar",
          "url": "compiler-daemon-1.2.0-alpha08-sources.jar",
          "size": 4892,
          "sha512": "82c42c85202fa741151dceb0609ed07834e1ac8e1c2f003513dfaa0f0be85bc95f41192d1e1b71851051f5b066982d470b6b4796e32e20e0676def686a393245",
          "sha256": "3b212ab63a7fe11496b4b452af3a1bebe4d747e48b4a31e80a6aa3266f328e88",
          "sha1": "f82c83bdd065a5a0854da7167024c8ac0722d13c",
          "md5": "7fbd80747d413ff68ede6c207a63a60c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-daemon-1.2.0-alpha08-all.jar",
          "url": "compiler-daemon-1.2.0-alpha08-all.jar",
          "size": 59694952,
          "sha512": "cfef55ac070e2a50d78256fba424097193c3a0a205676ac1e5e02d117e08972037a24cbbdf1a2ad0e59e38be8e979ac665620a9ecc4ddbad2b22d1b3cce8ae0c",
          "sha256": "4942f035cdc8b3bbe472271e6b9ea35a79748ceb91795b9dc606fd16aaa830f2",
          "sha1": "3f35c61df4430756f030335c9ee093cf736eaa25",
          "md5": "88d50c2f510baa4d1839534ff6890a07"
        }
      ]
    }
  ]
}