{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.3.2.aar",
          "url": "runtime-1.3.2.aar",
          "size": 2075358,
          "sha512": "b0fa71bf25e1decf7bd66bd307bd7ca66d19fa58de5e1335bc2b15aba5569cff5558cfbd6fb2c67347b77c4f5fafcca293dc3ab2c16fb09c6c70c08fe0b87b1f",
          "sha256": "359eec304ff1fc93c14cf501526299a2e4f889fc587897d4cfaf8ff1cc2982e0",
          "sha1": "c253d75d11d0dad35e3977661ed4deaf6f7f1997",
          "md5": "9a8ad3cd2929c64d20393611cf1d9422"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-1.3.2.aar",
          "url": "runtime-1.3.2.aar",
          "size": 2075358,
          "sha512": "b0fa71bf25e1decf7bd66bd307bd7ca66d19fa58de5e1335bc2b15aba5569cff5558cfbd6fb2c67347b77c4f5fafcca293dc3ab2c16fb09c6c70c08fe0b87b1f",
          "sha256": "359eec304ff1fc93c14cf501526299a2e4f889fc587897d4cfaf8ff1cc2982e0",
          "sha1": "c253d75d11d0dad35e3977661ed4deaf6f7f1997",
          "md5": "9a8ad3cd2929c64d20393611cf1d9422"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-1.3.2-sources.jar",
          "url": "runtime-1.3.2-sources.jar",
          "size": 303170,
          "sha512": "7037b7355d067f85d9989578d8ae1ea331fb443498b385e10386b05f50e2075fd5124b094d66f17621430e0d40f7b86e8403ef5393aba2006abff784c936566a",
          "sha256": "fbcb175eb9d9910277145aff78e1d2c9bdb2234149c8d3f967e50f4ed4695808",
          "sha1": "273d35cfbe92da18bb3a99492f0dcd4e6eead30f",
          "md5": "80f915f9e604873c46a50e2713c629e4"
        }
      ]
    }
  ]
}