{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.6.0-alpha04.aar",
          "url": "navigation-common-2.6.0-alpha04.aar",
          "size": 172346,
          "sha512": "951a2c63e06954f6ccd5e118e776439bab3f21ab10c77825269d1df1514da5dfb263e9ba16a00c1fe3fb9006b11f18e7877d397880d59d08d376c653a22d11e0",
          "sha256": "c66e8ea8946ea7111ad4f96844dec87e01045ba029413cac838624b8724dd951",
          "sha1": "3cf5dc8fd6398fa0855ab34155cfc21f5ec13836",
          "md5": "b2f0b520e96adf5f41f967737c0b5eaa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.6.0-alpha04.aar",
          "url": "navigation-common-2.6.0-alpha04.aar",
          "size": 172346,
          "sha512": "951a2c63e06954f6ccd5e118e776439bab3f21ab10c77825269d1df1514da5dfb263e9ba16a00c1fe3fb9006b11f18e7877d397880d59d08d376c653a22d11e0",
          "sha256": "c66e8ea8946ea7111ad4f96844dec87e01045ba029413cac838624b8724dd951",
          "sha1": "3cf5dc8fd6398fa0855ab34155cfc21f5ec13836",
          "md5": "b2f0b520e96adf5f41f967737c0b5eaa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-2.6.0-alpha04-sources.jar",
          "url": "navigation-common-2.6.0-alpha04-sources.jar",
          "size": 57084,
          "sha512": "abf99ab9361cbefad047b80c296924050d34d7ff6263b803f07738933001036003b2b8faa302ad88410bcd42f9ef7d07aac1d0964f64ba27ed053cfca0612bd8",
          "sha256": "0f276085721ef38d2cb08b9de64826b24cf4f5a2d29d267a6130c5e1809f3206",
          "sha1": "f156f334c49e4014b89185abdbf196f174a4dc80",
          "md5": "92b281e679c4d61a400f74c35bef3a19"
        }
      ]
    }
  ]
}