{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-viewbinding-samples",
    "version": "1.6.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-samples-1.6.0-alpha07.aar",
          "url": "ui-viewbinding-samples-1.6.0-alpha07.aar",
          "size": 18582,
          "sha512": "1b5eb1e91018f6376cfceacc450a5c797a218d194c4a2a6fd11480ff70adac4c7b25362f6959dab5e5da4324d4c5587a99f5cd33d056ece6ea74a2646d45fb06",
          "sha256": "2636de0249985cfe8a0ec4825f0490d43892661129ea42c8bbab5f40f79dc9af",
          "sha1": "8933202396c10b48496fc50463d5cf7faf1a4184",
          "md5": "41506dbcdb8757e6991cc6195c3e0367"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0-alpha07"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.0-alpha02"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-samples-1.6.0-alpha07.aar",
          "url": "ui-viewbinding-samples-1.6.0-alpha07.aar",
          "size": 18582,
          "sha512": "1b5eb1e91018f6376cfceacc450a5c797a218d194c4a2a6fd11480ff70adac4c7b25362f6959dab5e5da4324d4c5587a99f5cd33d056ece6ea74a2646d45fb06",
          "sha256": "2636de0249985cfe8a0ec4825f0490d43892661129ea42c8bbab5f40f79dc9af",
          "sha1": "8933202396c10b48496fc50463d5cf7faf1a4184",
          "md5": "41506dbcdb8757e6991cc6195c3e0367"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0-alpha07"
          },
          "reason": "ui-viewbinding-samples is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-samples-1.6.0-alpha07-sources.jar",
          "url": "ui-viewbinding-samples-1.6.0-alpha07-sources.jar",
          "size": 1721,
          "sha512": "3141e2924eed4a9f7ce49e19f1ad9342c04e600344f7e8c5c3d51d6617f14a100e3a227542fb80029e2faec7cee8eeb9fb480e502bc769cc66852d5c4c6a6d3f",
          "sha256": "0ddb10bb285c53c9ffc5183a0ef92664d3b497d3388e2002b91727551e00f239",
          "sha1": "c52e89ee925b54238f047b98699e2e2ebb4b5b0d",
          "md5": "2ba4fc45e6c0734a412de779e604c720"
        }
      ]
    }
  ]
}