{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava3",
    "version": "1.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7154166"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava3-1.0.0-beta01.aar",
          "url": "runtime-rxjava3-1.0.0-beta01.aar",
          "size": 25056,
          "sha512": "ad481efebc1e5232f424617797655d9c143271f902157d7ac502bbc4c9d90312ddf6eef578e429826e06d561f2d28a2e9c7d42aab6e7528cb94209317b916cfa",
          "sha256": "da13371f07cb0e30ef896246b33588a58b7859afbf5f38e9e9a13769d44d9aec",
          "sha1": "0532d32ede8680433248f162ce9b567c063aa06b",
          "md5": "0e8a31bbdf8632ecea84c23239d6b36a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava3-1.0.0-beta01.aar",
          "url": "runtime-rxjava3-1.0.0-beta01.aar",
          "size": 25056,
          "sha512": "ad481efebc1e5232f424617797655d9c143271f902157d7ac502bbc4c9d90312ddf6eef578e429826e06d561f2d28a2e9c7d42aab6e7528cb94209317b916cfa",
          "sha256": "da13371f07cb0e30ef896246b33588a58b7859afbf5f38e9e9a13769d44d9aec",
          "sha1": "0532d32ede8680433248f162ce9b567c063aa06b",
          "md5": "0e8a31bbdf8632ecea84c23239d6b36a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-rxjava3-1.0.0-beta01-sources.jar",
          "url": "runtime-rxjava3-1.0.0-beta01-sources.jar",
          "size": 2234,
          "sha512": "cb08a0d39fde12fe624d93f2e09c94cbe881f8b113df257744acc349138b04c6e7f6e8344cc659d878da9e4d0aeab34a58fd05d8be09eaaa18a8249e3336e372",
          "sha256": "e2d577605af518c7ef2b1dd8f91739602d6562ced82bdcd13cb6347c9f9cae54",
          "sha1": "6a81e97b8e1b3320b53e65ef75b07d2793bc99f4",
          "md5": "5b6eba3aa3b922dfd848803b0ea1a746"
        }
      ]
    }
  ]
}
