{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.xr.runtime",
    "module": "runtime-testing",
    "version": "1.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13018526"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.xr.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "reason": "runtime-testing is in atomic group androidx.xr.runtime"
        },
        {
          "group": "androidx.xr.runtime",
          "module": "runtime-openxr",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "reason": "runtime-testing is in atomic group androidx.xr.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-testing-1.0.0-alpha02-sources.jar",
          "url": "runtime-testing-1.0.0-alpha02-sources.jar",
          "size": 14461,
          "sha512": "3ff0d606a59261446a669bea05b9a470e6f5d9b1de23dbc2af07c6c2392889dd5f7246a5642652fcc15da15c528e839d5fef68349427caa2124e51ec9f355208",
          "sha256": "6d99cb7283d7c779b47ecb3fc18c31cc4aa0247e718c04d04da64e0ba57f5685",
          "sha1": "e32b3aa776ba78f5e34fd34002e463a320df3ee7",
          "md5": "33ead0b3a829a96c68fb364fe21620b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.xr.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.xr.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "reason": "runtime-testing is in atomic group androidx.xr.runtime"
        },
        {
          "group": "androidx.xr.runtime",
          "module": "runtime-openxr",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "reason": "runtime-testing is in atomic group androidx.xr.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-testing-1.0.0-alpha02.aar",
          "url": "runtime-testing-1.0.0-alpha02.aar",
          "size": 26279,
          "sha512": "bf30a1ba9aae9785caaf82da622bc3cb4c30ab2d1ee083f8a44e91bc7ed9e1e07de39d55f4d3d494ccbcefe63320e52ebf4b4144bd359a3a41a12f46de404ff1",
          "sha256": "71cf07834abfbd369df83cb798ba213266ef839d095b04d37683a5876868b608",
          "sha1": "1e9ef45018676390e082ea6edcf3b365acf665c0",
          "md5": "e09b075d197fc07c694b1e5b7a773dd5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.xr.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.xr.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "reason": "runtime-testing is in atomic group androidx.xr.runtime"
        },
        {
          "group": "androidx.xr.runtime",
          "module": "runtime-openxr",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "reason": "runtime-testing is in atomic group androidx.xr.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-testing-1.0.0-alpha02.aar",
          "url": "runtime-testing-1.0.0-alpha02.aar",
          "size": 26279,
          "sha512": "bf30a1ba9aae9785caaf82da622bc3cb4c30ab2d1ee083f8a44e91bc7ed9e1e07de39d55f4d3d494ccbcefe63320e52ebf4b4144bd359a3a41a12f46de404ff1",
          "sha256": "71cf07834abfbd369df83cb798ba213266ef839d095b04d37683a5876868b608",
          "sha1": "1e9ef45018676390e082ea6edcf3b365acf665c0",
          "md5": "e09b075d197fc07c694b1e5b7a773dd5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.xr.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "reason": "runtime-testing is in atomic group androidx.xr.runtime"
        },
        {
          "group": "androidx.xr.runtime",
          "module": "runtime-openxr",
          "version": {
            "requires": "1.0.0-alpha02"
          },
          "reason": "runtime-testing is in atomic group androidx.xr.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-testing-1.0.0-alpha02-versionMetadata.json",
          "url": "runtime-testing-1.0.0-alpha02-versionMetadata.json",
          "size": 8340,
          "sha512": "5296479607cfaa56bcb4fb6ed8df3d40b7f6f36fba22cb06ec6c5a816e8c7c47753073a4eb574908e2900a4116359bcd71efdf2069502d4a30efc2c8f2c4fb7b",
          "sha256": "f9cd2da428daa6a7110dbf4521025cd242d77713bb6f269eee25a677b702ce0b",
          "sha1": "61e09682f46a3a3be8d29cc7f0ec276a111e6b25",
          "md5": "480c868dc39b37bd38c96a51b437ad0c"
        }
      ]
    }
  ]
}