{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-view",
    "version": "1.0.0-alpha27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc05"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.0.0-alpha27.aar",
          "url": "camera-view-1.0.0-alpha27.aar",
          "size": 87953,
          "sha512": "1ec79da42fbaaabcba1340e3178e3f508bde8fe3c33cc28c5c8eacee881baacf9a33443d87ed95fe6ef67855cd8d8963ed8940d0e351fda27eb53f82de28eb04",
          "sha256": "3fce5c167f3207a208b8e5af4ea3717e314b8c21da7b903e335fd633a8e31d80",
          "sha1": "941a18b09bd49b7d5a468a012314e1d279e4a312",
          "md5": "73595e00dd79bd977b3d3212db347e64"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc05"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-rc05"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.0.0-alpha27.aar",
          "url": "camera-view-1.0.0-alpha27.aar",
          "size": 87953,
          "sha512": "1ec79da42fbaaabcba1340e3178e3f508bde8fe3c33cc28c5c8eacee881baacf9a33443d87ed95fe6ef67855cd8d8963ed8940d0e351fda27eb53f82de28eb04",
          "sha256": "3fce5c167f3207a208b8e5af4ea3717e314b8c21da7b903e335fd633a8e31d80",
          "sha1": "941a18b09bd49b7d5a468a012314e1d279e4a312",
          "md5": "73595e00dd79bd977b3d3212db347e64"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-view-1.0.0-alpha27-sources.jar",
          "url": "camera-view-1.0.0-alpha27-sources.jar",
          "size": 70102,
          "sha512": "7645f6c764f8113bf9811f4aaa052d982565c2d1088001571c53c1ef644b65435297cdba266fdc7896798a74a7d0feb7bc454913c70926f6de30d5d64354387e",
          "sha256": "b9afcb3ce0fc086abf95e25391480fc2bfabc57ba022e426a4bdf60ec1adf095",
          "sha1": "e807e32262b932717f47845db8711cc6803faf33",
          "md5": "76e335d72e46a3aef7a74874021c35f0"
        }
      ]
    }
  ]
}
