{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.1.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.1.0-alpha06.aar",
          "url": "foundation-1.1.0-alpha06.aar",
          "size": 1289767,
          "sha512": "6661719aac984d57e8d7a2bc6baa7d813b181edd378cbb97954a5dff578750471ea4a57b4ca154161364fe889de8b2629ff5c2a8e28001ea19b3dc9c487cebd9",
          "sha256": "c1ef5c9d37651ab702b372e4989499c93db14936f4dc40927dcd2b50f1e33e53",
          "sha1": "1513c77d366e499deba3022e4ca598cf120195cf",
          "md5": "5066b05e13bb2794f00f5ac1385c30f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.1.0-alpha06.aar",
          "url": "foundation-1.1.0-alpha06.aar",
          "size": 1289767,
          "sha512": "6661719aac984d57e8d7a2bc6baa7d813b181edd378cbb97954a5dff578750471ea4a57b4ca154161364fe889de8b2629ff5c2a8e28001ea19b3dc9c487cebd9",
          "sha256": "c1ef5c9d37651ab702b372e4989499c93db14936f4dc40927dcd2b50f1e33e53",
          "sha1": "1513c77d366e499deba3022e4ca598cf120195cf",
          "md5": "5066b05e13bb2794f00f5ac1385c30f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-1.1.0-alpha06-sources.jar",
          "url": "foundation-1.1.0-alpha06-sources.jar",
          "size": 260860,
          "sha512": "49e94a1425d0d5e0e9f173da3f384018ec58747ffc286605c501b0630b56a2493e4c3d685ac3a91f3459b0d7b29165d706615f31458307baf9128ea7992b8e84",
          "sha256": "59b7dbff4325d248f0a50fc2978b744799b9c6678e05ecea60c4f69f81e1f8f0",
          "sha1": "d7dad469b6c89478fe2e3a90e3a0da26260623ea",
          "md5": "07e1d799eb124e5d88651c8249812d03"
        }
      ]
    }
  ]
}
