{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.3.0-alpha03/collection-1.3.0-alpha03.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "collection.klib",
          "url": "collection-macosx64-1.3.0-alpha03.klib",
          "size": 128682,
          "sha512": "95b94cabe1a0a0ddde9046bcfbe3e0ff2b5194ab0e8603d045c95fd6e9b564994cad8b2a9c7c37c973ac691cb037e032df76ccdd948c6929df20e1e8f9b0b338",
          "sha256": "bed0f57b2d13ed03c19fbd4e61b630083b9bfda57a515deb9bd805776183ffcc",
          "sha1": "1b36f103f2f7c609d9c268fd7e300c29f989051d",
          "md5": "1203733b6341280eda9ab3fdd2fb2fba"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "collection-macosx64-1.3.0-alpha03-metadata.jar",
          "url": "collection-macosx64-1.3.0-alpha03-metadata.jar",
          "size": 4728,
          "sha512": "3ec010d52d77dbaf2a57ddd273d7889b42cc8256108b9d3622f439237be164d093827473619d8890edf139ed9263c872f7600a1f87ba6e184ae5ce85b7b24d61",
          "sha256": "82af76fc9072272ae9aac497e99fc9cc748ca414c5bd8289a7f2b83a6bf108cb",
          "sha1": "daf5a635c7122fd0b3188e83ef8fec7d11b466d6",
          "md5": "6a0801f04201bef65f397cafe6bf4572"
        }
      ]
    }
  ]
}