{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-gcm",
    "version": "2.7.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "work-gcm-2.7.0-beta01.aar",
          "url": "work-gcm-2.7.0-beta01.aar",
          "size": 14516,
          "sha512": "5864431464b003a919be4aa567453be0ada4166466b9a3d212321b004977388b8b1d91c5d6ec0103b75d0afd1e6fb2a4e05c8bae2dd5a106433542422a23bdf5",
          "sha256": "2a3c4e831ec21abb825f45ccfbe1b8fc55d7b1aa28b617c2c01d94ec67389634",
          "sha1": "cd06c654052ee8e13fc782a7b3817ecc63cb0a5d",
          "md5": "58de3d63b3d1ef61fbba06ded1ca5a00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0-beta01"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-gcm",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "work-gcm-2.7.0-beta01.aar",
          "url": "work-gcm-2.7.0-beta01.aar",
          "size": 14516,
          "sha512": "5864431464b003a919be4aa567453be0ada4166466b9a3d212321b004977388b8b1d91c5d6ec0103b75d0afd1e6fb2a4e05c8bae2dd5a106433542422a23bdf5",
          "sha256": "2a3c4e831ec21abb825f45ccfbe1b8fc55d7b1aa28b617c2c01d94ec67389634",
          "sha1": "cd06c654052ee8e13fc782a7b3817ecc63cb0a5d",
          "md5": "58de3d63b3d1ef61fbba06ded1ca5a00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-gcm-2.7.0-beta01-sources.jar",
          "url": "work-gcm-2.7.0-beta01-sources.jar",
          "size": 8418,
          "sha512": "9b391c834c384db810692b2caf4d6828ec1ee14ec2e6756875c5964a14df23dd3e45411d14458f3d555247a8d9a0aaf00c56b7d545f87e624d5fd5075cf1ef0c",
          "sha256": "10be4edbd61eb889357ad78762aa5f9ead27942b1ef9d80ece6dbd91d73b9499",
          "sha1": "ff4bf1305841c2d860dcfae56bef28f34208510b",
          "md5": "c78ad7146775f0c4764bd50cf1b184d5"
        }
      ]
    }
  ]
}
