{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-preferences/1.1.0-alpha04/datastore-preferences-1.1.0-alpha04.module",
    "group": "androidx.datastore",
    "module": "datastore-preferences",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences.klib",
          "url": "datastore-preferences-iosarm64-1.1.0-alpha04.klib",
          "size": 5618,
          "sha512": "e5cf00c785f48cb5d191189917f756a4012adb420d3f44c871e3d98f1bf30fe98d16f2566aa693e11450f46a84d9f55d4eb6ee9d78d7381ac2808f3d4c9ed1c4",
          "sha256": "75375204891afb0e436cdf754439fcb97a61b88f4865f749707542ad296fa160",
          "sha1": "d1223e015d314239bd7b8498a372b0bd1f4aefc0",
          "md5": "639ac5e2e916e48cde841194805edc98"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-iosarm64-1.1.0-alpha04-metadata.jar",
          "url": "datastore-preferences-iosarm64-1.1.0-alpha04-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}