{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-runtime-ktx",
    "version": "3.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7184376"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.0.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-ktx-3.0.0-beta02.aar",
          "url": "paging-runtime-ktx-3.0.0-beta02.aar",
          "size": 3369,
          "sha512": "f41696a1f8d57a5a264d1ff31c4ece4348bce34a5032cd56cf74f49a8717f45aabbc4f203ed231bc73b668acafadfc704e2021dcd870f4544d98edcd53ed64c6",
          "sha256": "2d5cf09f552252e05cf4c2071d74ebc3b9cbc030d212ec04f3e4a830ef8dad23",
          "sha1": "54cfb9c31fd46b2403c2e1ec6dcfebf7467bcf1f",
          "md5": "fc785eb031182a772b5a90d70287d796"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.0.0-beta02"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.0.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-ktx-3.0.0-beta02.aar",
          "url": "paging-runtime-ktx-3.0.0-beta02.aar",
          "size": 3369,
          "sha512": "f41696a1f8d57a5a264d1ff31c4ece4348bce34a5032cd56cf74f49a8717f45aabbc4f203ed231bc73b668acafadfc704e2021dcd870f4544d98edcd53ed64c6",
          "sha256": "2d5cf09f552252e05cf4c2071d74ebc3b9cbc030d212ec04f3e4a830ef8dad23",
          "sha1": "54cfb9c31fd46b2403c2e1ec6dcfebf7467bcf1f",
          "md5": "fc785eb031182a772b5a90d70287d796"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-runtime-ktx-3.0.0-beta02-sources.jar",
          "url": "paging-runtime-ktx-3.0.0-beta02-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
