{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.9.0-alpha01.aar",
          "url": "media3-ui-1.9.0-alpha01.aar",
          "size": 429836,
          "sha512": "61c2c3c08406cfe688193825e03fa2b31cfa384b7e8a04a01447989a0e50b5a2f6bf31c1aaa76010ff4253a94fa08270630852298600a702fb4cfa64b2bfea80",
          "sha256": "564d69fe1a0e45ba1c448a46945c8e3fc34f2b26cb17f7f49d59f21dd1ac7ba7",
          "sha1": "cd6e4ee9d51eccbb236015bda579a186d03c7fc1",
          "md5": "ef997342c6f821454c72f860b6f5328e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.9.0-alpha01.aar",
          "url": "media3-ui-1.9.0-alpha01.aar",
          "size": 429836,
          "sha512": "61c2c3c08406cfe688193825e03fa2b31cfa384b7e8a04a01447989a0e50b5a2f6bf31c1aaa76010ff4253a94fa08270630852298600a702fb4cfa64b2bfea80",
          "sha256": "564d69fe1a0e45ba1c448a46945c8e3fc34f2b26cb17f7f49d59f21dd1ac7ba7",
          "sha1": "cd6e4ee9d51eccbb236015bda579a186d03c7fc1",
          "md5": "ef997342c6f821454c72f860b6f5328e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.9.0-alpha01-sources.jar",
          "url": "media3-ui-1.9.0-alpha01-sources.jar",
          "size": 117407,
          "sha512": "a52593eb6d3ec14f26d4b01c6aed98afca70fec65441e8da355ea084d8c8da59cc3b131cfb59ae097617c12e87261147ed009cca1b1d653179f0d466a1ad66a4",
          "sha256": "fe67b16099caba31673d5ab30b1db72c7ceacaafb982e12a6a5538aaaef0c008",
          "sha1": "f0e0e61793a2b67b45c0453dc36add4718dada90",
          "md5": "a722f076154ad2abcb1cc66c33577597"
        }
      ]
    }
  ]
}
