{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core.uwb",
    "module": "uwb",
    "version": "1.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "uwb-1.0.0-alpha02.aar",
          "url": "uwb-1.0.0-alpha02.aar",
          "size": 31406,
          "sha512": "1178818b994ee5119c07dab756090979b7804f0639bc68394db4329d26e7568af443949b1a5ad49aa83add8b9b597a01e0162e97e26ba1ae3174ccc3764418b0",
          "sha256": "7db7cc40d220b82bd670d1d1e5f03ea69fe684010c89743a82770805a6661302",
          "sha1": "2827f7cbe787c4ec8d15a10e3704e4b27d0ef177",
          "md5": "8f8e1639f50d22bb60cb0b02166d7988"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-nearby",
          "version": {
            "requires": "18.2.0"
          },
          "excludes": [
            {
              "group": "androidx.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-play-services",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "uwb-1.0.0-alpha02.aar",
          "url": "uwb-1.0.0-alpha02.aar",
          "size": 31406,
          "sha512": "1178818b994ee5119c07dab756090979b7804f0639bc68394db4329d26e7568af443949b1a5ad49aa83add8b9b597a01e0162e97e26ba1ae3174ccc3764418b0",
          "sha256": "7db7cc40d220b82bd670d1d1e5f03ea69fe684010c89743a82770805a6661302",
          "sha1": "2827f7cbe787c4ec8d15a10e3704e4b27d0ef177",
          "md5": "8f8e1639f50d22bb60cb0b02166d7988"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uwb-1.0.0-alpha02-sources.jar",
          "url": "uwb-1.0.0-alpha02-sources.jar",
          "size": 17450,
          "sha512": "68934cff7180d1d82d9e2a36c4b2e8957379d19c988943e394190532984468a483c6be6d66313307937ebf360c6aca7407deec91d020ec3d52652f9452b123b1",
          "sha256": "b75cfb18558e1da468a45cbb0be343c432e44fbf754d4a5a502a600671ab3a64",
          "sha1": "70a6cb85a8ca5c348f394692906fa8d865ab8c2c",
          "md5": "16ed83c5bf1babcf301a4e133042b5f1"
        }
      ]
    }
  ]
}