{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive-layout/1.1.0-alpha09/adaptive-layout-1.1.0-alpha09.module",
    "group": "androidx.compose.material3.adaptive",
    "module": "adaptive-layout",
    "version": "1.1.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12891226"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha09"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha09"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-alpha09"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-layout-release.aar",
          "url": "adaptive-layout-android-1.1.0-alpha09.aar",
          "size": 364226,
          "sha512": "562844a74cb66c200563f77d58a94c62661d27cc7e686b75f4973e17013b67b397f990f2bada3fd95f8829e637de0062e38b7c56d731911740d7658e405035e1",
          "sha256": "1a2596d6b697c41a91fb18c5aa84b14ea90543f1ebc8d97e1c35cfb097f2397a",
          "sha1": "633bf7dd52b3003df03bf05c64baf74992696689",
          "md5": "2f3492915738d3ee57ebd16fe89940dc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha09"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.5"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha09"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-alpha09"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-layout-release.aar",
          "url": "adaptive-layout-android-1.1.0-alpha09.aar",
          "size": 364226,
          "sha512": "562844a74cb66c200563f77d58a94c62661d27cc7e686b75f4973e17013b67b397f990f2bada3fd95f8829e637de0062e38b7c56d731911740d7658e405035e1",
          "sha256": "1a2596d6b697c41a91fb18c5aa84b14ea90543f1ebc8d97e1c35cfb097f2397a",
          "sha1": "633bf7dd52b3003df03bf05c64baf74992696689",
          "md5": "2f3492915738d3ee57ebd16fe89940dc"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.1.0-alpha09"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.1.0-alpha09"
          },
          "reason": "adaptive-layout is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-layout-1.1.0-alpha09-samples-sources.jar",
          "url": "adaptive-layout-android-1.1.0-alpha09-samples-sources.jar",
          "size": 9242,
          "sha512": "abcb2083572a001d5fecf5320c76fd86809d1fe822eb85b8212d879e40dbb272a203b549ea917b95418e4126d01d7a879c6ae3bbd7ff1f832c8d5d65e82a70da",
          "sha256": "d7c2bc22f9c3a13e47430891f192fd6996ad32805e1681ac426539eac45db601",
          "sha1": "ba850d4df156df0942d0d032fb21dd8529ca9884",
          "md5": "1b3584cbb9cb0c1ee1c0157e92223412"
        },
        {
          "name": "adaptive-layout-android-1.1.0-alpha09-sources.jar",
          "url": "adaptive-layout-android-1.1.0-alpha09-sources.jar",
          "size": 65579,
          "sha512": "1a7a72ced6d037c0430c7cf6da7a2ab2339d5b836dcf0dfda1b4292a59cf183731daf0e369799e80a4c84789610a6e50ff1254a64859ce6b1f9441dc97d9f544",
          "sha256": "b76dee7a9cd1585c88836c58fd0b62a4fceb03459d0c2e3dcd9e0dd94b7e955a",
          "sha1": "1eaf8967a8078bc67595a2b1dab0d1a25fe14a44",
          "md5": "28d676434b65db399d4547a905a5de86"
        }
      ]
    }
  ]
}