{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-viewbinding",
    "version": "1.0.0-beta04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7262094"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-viewbinding-1.0.0-beta04.aar",
          "url": "ui-viewbinding-1.0.0-beta04.aar",
          "size": 16033,
          "sha512": "1c924509e03ab8a611ec5fe408e85c6338676ff5ed9a6fca776eb3740fc6045cfb4e4275daa6a658c4aeb395e9c1e007d1c578e30e3df873a23bf8d218080f4b",
          "sha256": "85de0939f82bf8edc224c2c5bd36665fae52513644b6f725b83541c6c0a2ba5d",
          "sha1": "dfb871439ade0ff50998e684045ec5cb6554bcf7",
          "md5": "01f3c5ff8f00b15918afafc311ee69e3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-beta04"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.1.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-1.0.0-beta04.aar",
          "url": "ui-viewbinding-1.0.0-beta04.aar",
          "size": 16033,
          "sha512": "1c924509e03ab8a611ec5fe408e85c6338676ff5ed9a6fca776eb3740fc6045cfb4e4275daa6a658c4aeb395e9c1e007d1c578e30e3df873a23bf8d218080f4b",
          "sha256": "85de0939f82bf8edc224c2c5bd36665fae52513644b6f725b83541c6c0a2ba5d",
          "sha1": "dfb871439ade0ff50998e684045ec5cb6554bcf7",
          "md5": "01f3c5ff8f00b15918afafc311ee69e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-viewbinding-1.0.0-beta04-sources.jar",
          "url": "ui-viewbinding-1.0.0-beta04-sources.jar",
          "size": 2897,
          "sha512": "2a142ec49194868e0c51d1ef2355c903b1878ea4d270951dd395d228670e8f06eaa99944757b71d7079d994546f6dd27f164ac77a9fb56bf4e23db561cc6d242",
          "sha256": "aeae38161791b8082af0f3ceb6b588c3c8ae3c17ef02ca1379afed180d20a027",
          "sha1": "7786317b37f068f08e7e79b5249a391e18bcd4b8",
          "md5": "855181ec8f4b50f9ba61169adec7a376"
        }
      ]
    }
  ]
}
