{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava2-samples",
    "version": "1.8.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.8.0-alpha02-sources.jar",
          "url": "runtime-rxjava2-samples-1.8.0-alpha02-sources.jar",
          "size": 6108,
          "sha512": "f3d49c42fbfdef1bf5dc448470390407b06f9065bfddc7e1f8c464662fc396e14a51f0b553ffdff066b5b92fe8e47dbf60e27cc38c0abaebe087269c74bddfa7",
          "sha256": "7de164b0d0756b949c8a3f1ec53cc3867803b4fadb2539510784943dace34990",
          "sha1": "0e4b053760ff4b7a97370bf48f6317d7c778a27c",
          "md5": "4732460fb8e830281f90670db5b51c50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.8.0-alpha02.aar",
          "url": "runtime-rxjava2-samples-1.8.0-alpha02.aar",
          "size": 13992,
          "sha512": "4db8d19fe45e70816266d2f1eb100590a1b1efb2a00a017ed82486fb24166ff57d4204698802295a1ca0fabacd475b1cbc6588074abedf169bd52156e28dadd8",
          "sha256": "165dd2235d36193f6a147b083e3d9c28ccf52f692b04cb0d190aff1c20a31c5c",
          "sha1": "3f6f223c81ec91ee38f68c9e1171c1aa4fc410fe",
          "md5": "3a95993b216765576d377f7e7556479b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.8.0-alpha02.aar",
          "url": "runtime-rxjava2-samples-1.8.0-alpha02.aar",
          "size": 13992,
          "sha512": "4db8d19fe45e70816266d2f1eb100590a1b1efb2a00a017ed82486fb24166ff57d4204698802295a1ca0fabacd475b1cbc6588074abedf169bd52156e28dadd8",
          "sha256": "165dd2235d36193f6a147b083e3d9c28ccf52f692b04cb0d190aff1c20a31c5c",
          "sha1": "3f6f223c81ec91ee38f68c9e1171c1aa4fc410fe",
          "md5": "3a95993b216765576d377f7e7556479b"
        }
      ]
    }
  ]
}