{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-lifecycle",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7153397"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.1.0-alpha02.aar",
          "url": "camera-lifecycle-1.1.0-alpha02.aar",
          "size": 17947,
          "sha512": "5b7536900bc2c38c17e87df83ce4111d27daac087891ffc2858f777c01233fc203723c91ef7dc3dc888d51e9f3dc0e3e6a40ead765f58328abc9923a5f25f822",
          "sha256": "82f314d6f96c477b0d9fb2586731e5ff32fde15fb5c389c8cffc15d37c5e9770",
          "sha1": "60874af8cf8d130922ff75515f8479a558a7746d",
          "md5": "0e6d7d9d29ecdf9d25327773db2d6b29"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.1.0-alpha02.aar",
          "url": "camera-lifecycle-1.1.0-alpha02.aar",
          "size": 17947,
          "sha512": "5b7536900bc2c38c17e87df83ce4111d27daac087891ffc2858f777c01233fc203723c91ef7dc3dc888d51e9f3dc0e3e6a40ead765f58328abc9923a5f25f822",
          "sha256": "82f314d6f96c477b0d9fb2586731e5ff32fde15fb5c389c8cffc15d37c5e9770",
          "sha1": "60874af8cf8d130922ff75515f8479a558a7746d",
          "md5": "0e6d7d9d29ecdf9d25327773db2d6b29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-lifecycle-1.1.0-alpha02-sources.jar",
          "url": "camera-lifecycle-1.1.0-alpha02-sources.jar",
          "size": 16501,
          "sha512": "8e70194af85c59b458e48c76dd6c2ecdc383d1033daf15c45c2917d2e77c65b8fa54737cadcbd31bf4f1c9899391743209ae3f479f20aee735788e6e054b741c",
          "sha256": "193420741b08e80ba9b88f436b57609b66091e0a1aa338194653b75e51ba64a3",
          "sha1": "e96bab97456cfeb2d53ec7749e86f14c06b81bfa",
          "md5": "f7f886407c236cebc4393acdfc6eff83"
        }
      ]
    }
  ]
}
