{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-views",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-1.3.0-alpha01.aar",
          "url": "emoji2-views-1.3.0-alpha01.aar",
          "size": 14008,
          "sha512": "971ddce949a3059ea86233fb8ddb2c2f14b032828edf4a3a26922bc125c0a9a7fc5b3d9b778aa6450ea6a36fb67c5c1e039f89602072cf2cd46f358b397e2aa9",
          "sha256": "8316cf623fb05396bcfd3aa7dc9b711830f091823f998342e7c914250ab36032",
          "sha1": "ce848341feb6b5ca247d81fb83a7c773ed5fd3de",
          "md5": "22005d9295c3ef29fedd12ff0910e515"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-1.3.0-alpha01.aar",
          "url": "emoji2-views-1.3.0-alpha01.aar",
          "size": 14008,
          "sha512": "971ddce949a3059ea86233fb8ddb2c2f14b032828edf4a3a26922bc125c0a9a7fc5b3d9b778aa6450ea6a36fb67c5c1e039f89602072cf2cd46f358b397e2aa9",
          "sha256": "8316cf623fb05396bcfd3aa7dc9b711830f091823f998342e7c914250ab36032",
          "sha1": "ce848341feb6b5ca247d81fb83a7c773ed5fd3de",
          "md5": "22005d9295c3ef29fedd12ff0910e515"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji2-views-1.3.0-alpha01-sources.jar",
          "url": "emoji2-views-1.3.0-alpha01-sources.jar",
          "size": 11217,
          "sha512": "cacb346745b33232d3150acc68c6c8db39958cc25633d9e10c504f8f3b9715357722f71282fa709235313039cfba45a111ef9c4ff1df9919287f042332fb17b5",
          "sha256": "d30c62939561ddb63a058c57338d471fbadcc4140ae82d0762c702a3723c350c",
          "sha1": "0798e652918c327d7d5c59589b0eafb0b746adc6",
          "md5": "4e563ef1dee865543e0fa73d83cfd4e2"
        }
      ]
    }
  ]
}