{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-view",
    "version": "1.0.0-alpha31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.0.0-alpha31.aar",
          "url": "camera-view-1.0.0-alpha31.aar",
          "size": 89497,
          "sha512": "5c5e0134aa668d988a3e2a5eb5ecffd1e9d233a87b993b0600c96f20c47766785fc82ee0aa245416ec576a15bada13eef3a796a23939be02175bf327bcbec589",
          "sha256": "a8ed4c07605f60dff30b67925f411ff1a8dfe96c89ff2a027d4c272b80a0ffec",
          "sha1": "4576216f21cb58783f27a62e498050b245ab3761",
          "md5": "57dfe825e9046d18b26c81550ad2c9e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-view-1.0.0-alpha31.aar",
          "url": "camera-view-1.0.0-alpha31.aar",
          "size": 89497,
          "sha512": "5c5e0134aa668d988a3e2a5eb5ecffd1e9d233a87b993b0600c96f20c47766785fc82ee0aa245416ec576a15bada13eef3a796a23939be02175bf327bcbec589",
          "sha256": "a8ed4c07605f60dff30b67925f411ff1a8dfe96c89ff2a027d4c272b80a0ffec",
          "sha1": "4576216f21cb58783f27a62e498050b245ab3761",
          "md5": "57dfe825e9046d18b26c81550ad2c9e7"
        }
      ]
    }
  ]
}
