{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-alpha12.aar",
          "url": "tracing-perfetto-1.0.0-alpha12.aar",
          "size": 23155,
          "sha512": "147ea08774ac7bd5580131ad065c0251764b4746f838b8d675a66496cdc012987dd1291668a27742d85a13f4a48ef9084a7e725ccd1d5d0d50bf96e24c152b39",
          "sha256": "c1c044479ab16dac649b1172fcbf18488f5f5a7c7c3205c2b8ce4d1980013fc5",
          "sha1": "515064b29ff84faff4b43247653ffa2a454620db",
          "md5": "34e058afeff84e8d364b0933824c85ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-common",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-alpha12.aar",
          "url": "tracing-perfetto-1.0.0-alpha12.aar",
          "size": 23155,
          "sha512": "147ea08774ac7bd5580131ad065c0251764b4746f838b8d675a66496cdc012987dd1291668a27742d85a13f4a48ef9084a7e725ccd1d5d0d50bf96e24c152b39",
          "sha256": "c1c044479ab16dac649b1172fcbf18488f5f5a7c7c3205c2b8ce4d1980013fc5",
          "sha1": "515064b29ff84faff4b43247653ffa2a454620db",
          "md5": "34e058afeff84e8d364b0933824c85ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.2.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-alpha12-sources.jar",
          "url": "tracing-perfetto-1.0.0-alpha12-sources.jar",
          "size": 12038,
          "sha512": "14b88a9e01b8a66b863d5f60f25977e342806542c9083231d6c4851aa3580b4effad0ddfea143c33d1084e1654562a08ff36b74bd0b8a7d2da5152ed31171094",
          "sha256": "46d9416cedb81395bb1ec581a03148c0c5a6f58242f633451c474b79f4d165d6",
          "sha1": "72cc595b727b5b65a2c3953f3b939ad0f00feaa5",
          "md5": "178a3a6b519801eafdf5ad9e0343263e"
        }
      ]
    }
  ]
}