{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.0.1.aar",
          "url": "material-icons-core-1.0.1.aar",
          "size": 686042,
          "sha512": "0d50c61796e36f6a7e13f6b1b91e1bf4ccdaddd6e09c00ccb5a258291e52ef67e37bb7f1b6aa15181accd7d6ad86bb7bd6d9cc5967112c25051267a0c7c82a12",
          "sha256": "4c1cf6fd61d67c7a6b9f85d888493133c36bc1b560bd706d1be235b559926756",
          "sha1": "9fb52b068e0bd80e28745d5e77de686cb706ad14",
          "md5": "38664d02537ec57ca94ff6a058fa2cbf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.0.1.aar",
          "url": "material-icons-core-1.0.1.aar",
          "size": 686042,
          "sha512": "0d50c61796e36f6a7e13f6b1b91e1bf4ccdaddd6e09c00ccb5a258291e52ef67e37bb7f1b6aa15181accd7d6ad86bb7bd6d9cc5967112c25051267a0c7c82a12",
          "sha256": "4c1cf6fd61d67c7a6b9f85d888493133c36bc1b560bd706d1be235b559926756",
          "sha1": "9fb52b068e0bd80e28745d5e77de686cb706ad14",
          "md5": "38664d02537ec57ca94ff6a058fa2cbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-core-1.0.1-sources.jar",
          "url": "material-icons-core-1.0.1-sources.jar",
          "size": 240119,
          "sha512": "03bcd78849cb7a91014c675e4c0f9717912ed79ec759d214486a519f9f469b80bb32d507b100b9bc7458a6f20b6e749915a35bd50f1d4162f911642b67d5af2d",
          "sha256": "ec3e98c276fc21507b93c47e9290c28b538c77896cf0483bc2f78a5dc437ab67",
          "sha1": "f6ebb4e631e995de2b75617bed6175b0fe306294",
          "md5": "7a263fd8d6a465089336845f3de2e06b"
        }
      ]
    }
  ]
}
