{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles-material",
    "version": "1.2.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "tiles-material-1.2.0-alpha07.aar",
          "url": "tiles-material-1.2.0-alpha07.aar",
          "size": 71566,
          "sha512": "bc754316b9c6f3074f7e9e5691a4f3c8ad98741e20f90fbabf6827c2cfbc6ab4937647bc860b50b3f685d4a297ad8993001ced1703780928ddf88736be3870a5",
          "sha256": "f470ab3b1fdc3b67ad7a4748c4688208ce2c3db70ddf2eed61a871ad50e5a99e",
          "sha1": "c4af156200e6ad49dda34981d5d388f21de68544",
          "md5": "0fe03999506b5efca65e75401dcafa36"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "tiles-material-1.2.0-alpha07.aar",
          "url": "tiles-material-1.2.0-alpha07.aar",
          "size": 71566,
          "sha512": "bc754316b9c6f3074f7e9e5691a4f3c8ad98741e20f90fbabf6827c2cfbc6ab4937647bc860b50b3f685d4a297ad8993001ced1703780928ddf88736be3870a5",
          "sha256": "f470ab3b1fdc3b67ad7a4748c4688208ce2c3db70ddf2eed61a871ad50e5a99e",
          "sha1": "c4af156200e6ad49dda34981d5d388f21de68544",
          "md5": "0fe03999506b5efca65e75401dcafa36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "tiles-material-1.2.0-alpha07-sources.jar",
          "url": "tiles-material-1.2.0-alpha07-sources.jar",
          "size": 56949,
          "sha512": "233e7e1585e1b4a12e0a4774f02eeb125dc2fd9dddb3a46b36dd41b1dc5c45afcb7a8ad19ffbb517191d68bc0744a30c0a5960115db101b7e58e1188d50720ca",
          "sha256": "143dd0a965a3be118c9a1c7c1bc7d527ae32df21c58a75be8ff7628d740330de",
          "sha1": "7d6eee416885db80c81c66cee439bc67ce152f1f",
          "md5": "fb1e7ae38b8f1190d6aa925444fc05f2"
        }
      ]
    }
  ]
}