{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-graphics-samples",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13409421"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.8.1-sources.jar",
          "url": "animation-graphics-samples-1.8.1-sources.jar",
          "size": 6285,
          "sha512": "bed0f8c06216faeabb1a9143e041b968b46c1e909154b923c99bd1b707e8ce7ecd9034fe1a1b39e9576f7e490bc06368c54b557c05dba77a142f2b8277e0949b",
          "sha256": "54fdc97f32a7bf899e26157c30cce216e4780b58ca0ca1656f8cd8bea9400f1c",
          "sha1": "30947162c55ae8c0200104a4d8a62f97bda585ef",
          "md5": "b4e3fdff32ffba133904aa9c93d69470"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.8.1.aar",
          "url": "animation-graphics-samples-1.8.1.aar",
          "size": 11686,
          "sha512": "2b1a55f156196e9e9f93089ab9a2547b08b24f7178ea5136d75d4b056f9687a16cfdc6e98579903dad16f2a81c0aaa9d60b32eb5f1d9b0e3580950c19d89d567",
          "sha256": "259da501d82c8a7ab5d3dc8db1241a95f5f7c5388a7c84b21a5ca2b69e5770e0",
          "sha1": "3df531274a7ee4d4ee0054bf4c0be03302966bd6",
          "md5": "75133d9de73543fa4b6f4e9fe561fa00"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.1"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.8.1.aar",
          "url": "animation-graphics-samples-1.8.1.aar",
          "size": 11686,
          "sha512": "2b1a55f156196e9e9f93089ab9a2547b08b24f7178ea5136d75d4b056f9687a16cfdc6e98579903dad16f2a81c0aaa9d60b32eb5f1d9b0e3580950c19d89d567",
          "sha256": "259da501d82c8a7ab5d3dc8db1241a95f5f7c5388a7c84b21a5ca2b69e5770e0",
          "sha1": "3df531274a7ee4d4ee0054bf4c0be03302966bd6",
          "md5": "75133d9de73543fa4b6f4e9fe561fa00"
        }
      ]
    }
  ]
}