{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.4.2/collection-1.4.2.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection.klib",
          "url": "collection-tvossimulatorarm64-1.4.2.klib",
          "size": 788207,
          "sha512": "21cdb9121c4e993a40f9cf97de60172e1d9d4b4a1c0f686f1e421ef58d64331a414d22cd9e4aa5e43bc13f3a84fa458bd64d3e5ea442a3d7951339d3b684ead1",
          "sha256": "4e54421e4cb83efe624750522eefca36e9985e0f2af6fd8f7224a9f09d1bbe9b",
          "sha1": "b6a018a86a8f800aadb1c2b0e4a663bcf731e4d0",
          "md5": "5219f673a5d3db5794d4d80a920b44bc"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-tvossimulatorarm64-1.4.2-sources.jar",
          "url": "collection-tvossimulatorarm64-1.4.2-sources.jar",
          "size": 229289,
          "sha512": "f2496e0154b8bc10f98bce49aecd0fcc5885f3140b2b12e11296e1612861b9761f6c38ffbeff31e701198020bf5308ecab077a77d23bc2ffc29f0b52469716d3",
          "sha256": "4e1578a49db3bb347ced3cf6cc02bcae7afd9f6e06cbc48ad8224ec127082cff",
          "sha1": "ae88005388678866b6d64c006a40cc5f4f4313ac",
          "md5": "bf555a9fbb887f5208b189ee12e74120"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-tvossimulatorarm64-1.4.2-metadata.jar",
          "url": "collection-tvossimulatorarm64-1.4.2-metadata.jar",
          "size": 3792,
          "sha512": "da7cde9a50f1600dfa645777df6844f2caf692116c6c97868e04e7b96a3c85a1293aedb541616b586ae40d65bb78ce5d7841d66cabaed7f7b89ce2d5ec1d7c16",
          "sha256": "d1a4bc5f34b8c6e363bf91a7074eb53a0bf6f28d37bb092bbba2aae0e0c2fd9d",
          "sha1": "483d10483cb43984f76fcccb8522b2afedcbfcce",
          "md5": "7f5822425472bbea2d39cd881efe5cb4"
        }
      ]
    }
  ]
}