{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose-samples",
    "version": "2.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-samples-2.8.2-sources.jar",
          "url": "navigation-compose-samples-2.8.2-sources.jar",
          "size": 11296,
          "sha512": "de1a633658a10a834f78203651defdba1b51fc96de5ecbe0308007b0e0e6f502aa7da40acbe0c229330c5f3b413ddf2d3614263eba735c709ce2138e3df53394",
          "sha256": "3e15db75e78018d734ba4839ac0b0ca3b067415af1d5850a2810dcacd73f411e",
          "sha1": "1900b29173e399a9b4584cb84ca2067222fc0517",
          "md5": "3e636d70a85d8e869c462b639a97317a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-samples-2.8.2.aar",
          "url": "navigation-compose-samples-2.8.2.aar",
          "size": 283064,
          "sha512": "17e10fb32ec7a39abbabf0858daaf3c0bf09917d25e909fb4375dfa723452d269172fafb51319bd06d28ab73c6485a21e75434fd1aa8f00d3fe754fae9ebb8ff",
          "sha256": "361a44c96ad60d608038c99ab0fa6cfba06118ab912394ec495f0aa08f8b22e5",
          "sha1": "40ddca15ed94c3964ffe42237851d078f4447638",
          "md5": "51b7be23dd742e206be7b14be4b7d81a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.2"
          },
          "reason": "navigation-compose-samples is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-samples-2.8.2.aar",
          "url": "navigation-compose-samples-2.8.2.aar",
          "size": 283064,
          "sha512": "17e10fb32ec7a39abbabf0858daaf3c0bf09917d25e909fb4375dfa723452d269172fafb51319bd06d28ab73c6485a21e75434fd1aa8f00d3fe754fae9ebb8ff",
          "sha256": "361a44c96ad60d608038c99ab0fa6cfba06118ab912394ec495f0aa08f8b22e5",
          "sha1": "40ddca15ed94c3964ffe42237851d078f4447638",
          "md5": "51b7be23dd742e206be7b14be4b7d81a"
        }
      ]
    }
  ]
}