{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava2-samples",
    "version": "1.8.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13166392"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.8.0-rc01-sources.jar",
          "url": "runtime-rxjava2-samples-1.8.0-rc01-sources.jar",
          "size": 6108,
          "sha512": "f3d49c42fbfdef1bf5dc448470390407b06f9065bfddc7e1f8c464662fc396e14a51f0b553ffdff066b5b92fe8e47dbf60e27cc38c0abaebe087269c74bddfa7",
          "sha256": "7de164b0d0756b949c8a3f1ec53cc3867803b4fadb2539510784943dace34990",
          "sha1": "0e4b053760ff4b7a97370bf48f6317d7c778a27c",
          "md5": "4732460fb8e830281f90670db5b51c50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.8.0-rc01.aar",
          "url": "runtime-rxjava2-samples-1.8.0-rc01.aar",
          "size": 14206,
          "sha512": "390245d3f17858969e386a29bf1d651287385b79e5da63a86138708ee73a50e3ad77ce187755e2bde889547f858394b40f4eb2ffbe02af8fadf38aec727aec93",
          "sha256": "02ec0662a54a9f93615826b9e6e16327daee8fe61deea3860b519932b404a2c3",
          "sha1": "b1f02e2e8807eda697c8d204c5e119ba27ebe3dc",
          "md5": "7ee49cbee314ebf27d1bd75f20717f38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.8.0-rc01"
          },
          "reason": "runtime-rxjava2-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-samples-1.8.0-rc01.aar",
          "url": "runtime-rxjava2-samples-1.8.0-rc01.aar",
          "size": 14206,
          "sha512": "390245d3f17858969e386a29bf1d651287385b79e5da63a86138708ee73a50e3ad77ce187755e2bde889547f858394b40f4eb2ffbe02af8fadf38aec727aec93",
          "sha256": "02ec0662a54a9f93615826b9e6e16327daee8fe61deea3860b519932b404a2c3",
          "sha1": "b1f02e2e8807eda697c8d204c5e119ba27ebe3dc",
          "md5": "7ee49cbee314ebf27d1bd75f20717f38"
        }
      ]
    }
  ]
}