{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-lint",
    "version": "1.10.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14053080"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-lint is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-lint is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-lint-1.10.0-alpha03.jar",
          "url": "foundation-lint-1.10.0-alpha03.jar",
          "size": 1116666,
          "sha512": "74bdb72da9866957c410941ca4838ccf845f6b2596046a1ede6830f5f9bc5572ac5b59d445732cc68f39cfc0c82359935d0b6ac33ea82da7dafcd3add16cb352",
          "sha256": "b9c5b72ac1623b139e1d2d7cc4529380303cbc0c59633e5ac61a24c18a0cfcea",
          "sha1": "b9c9f7e96c535b6cd8d64bd7195b5ad57d9a3d59",
          "md5": "45ad1c4659849b1262fbbffb223b197e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-lint is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-lint is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-lint-1.10.0-alpha03.jar",
          "url": "foundation-lint-1.10.0-alpha03.jar",
          "size": 1116666,
          "sha512": "74bdb72da9866957c410941ca4838ccf845f6b2596046a1ede6830f5f9bc5572ac5b59d445732cc68f39cfc0c82359935d0b6ac33ea82da7dafcd3add16cb352",
          "sha256": "b9c5b72ac1623b139e1d2d7cc4529380303cbc0c59633e5ac61a24c18a0cfcea",
          "sha1": "b9c9f7e96c535b6cd8d64bd7195b5ad57d9a3d59",
          "md5": "45ad1c4659849b1262fbbffb223b197e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-lint is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-lint is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-lint-1.10.0-alpha03-sources.jar",
          "url": "foundation-lint-1.10.0-alpha03-sources.jar",
          "size": 11923,
          "sha512": "c9c90654e7fd0713c333cfdf4149ebcaeb7844b2014f2ea4bcd9ff2496bf74d4e7da665cc37ed3053b64f0e179716bad24819ea4303f500da08943096b5b5637",
          "sha256": "6c67942db0fa891a641c8111b36c694d8b0174daec2b4096d66e3297bfdd959e",
          "sha1": "18e8b2f9612147c1e09857fd9759fdeeac782710",
          "md5": "fa057feb857f4534bf55949cb481acca"
        }
      ]
    }
  ]
}