{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-rxjava2",
    "version": "2.10.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-rxjava2-2.10.4-sources.jar",
          "url": "work-rxjava2-2.10.4-sources.jar",
          "size": 7524,
          "sha512": "7d6f778c758fc050417f86c7f4c4df105e04f4a0feb4726053bb01c18146d5e02fc0f32313f2201494a84924166cfaffc14c077ba5f006fc40c36310deae7d1f",
          "sha256": "2ad6f7d1b08d0e90613bc5c7146a071aa753b14969924134fd1a25067c6a3fb6",
          "sha1": "fc03adf076fc0f0e0499522f8ab5c9d29c96ce5c",
          "md5": "d49e7f20e1d8137f7693e7fe8f02971d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-rxjava2-2.10.4.aar",
          "url": "work-rxjava2-2.10.4.aar",
          "size": 9494,
          "sha512": "6cd45ca321aada595f78626d200e9302d63cc2dc8f2206f2be5b1e505b4178e72208ecf063303a066739fbcfbd319561df53d56817c8734c882982f3048aadb1",
          "sha256": "1a700fd08fb97f9749cc0a811a9e81ee5e6ea4bcbd86e5ebe92c1695f2849215",
          "sha1": "f13642ef740771662da2bbc5d5bda074d821a0c6",
          "md5": "f64ad9412e61de83242650fb8abdc06a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.4"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-rxjava2-2.10.4.aar",
          "url": "work-rxjava2-2.10.4.aar",
          "size": 9494,
          "sha512": "6cd45ca321aada595f78626d200e9302d63cc2dc8f2206f2be5b1e505b4178e72208ecf063303a066739fbcfbd319561df53d56817c8734c882982f3048aadb1",
          "sha256": "1a700fd08fb97f9749cc0a811a9e81ee5e6ea4bcbd86e5ebe92c1695f2849215",
          "sha1": "f13642ef740771662da2bbc5d5bda074d821a0c6",
          "md5": "f64ad9412e61de83242650fb8abdc06a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.4"
          },
          "reason": "work-rxjava2 is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-rxjava2-2.10.4-versionMetadata.json",
          "url": "work-rxjava2-2.10.4-versionMetadata.json",
          "size": 603,
          "sha512": "1a28d84fe7862921a68f6e5be7ffb0682cdc81f946f4e641a57946c30654a134f80c897b40c635e3731a89f0d0c5160afd555d1d8c60f7afabb47e1c3d33c9dc",
          "sha256": "017249a404e3dcfb2acfe1a493135b8857c64012dfcc6b492e2da2e0199ece20",
          "sha1": "1ef88943ba78a9c5d193f8c4d8534a343cc5c9fc",
          "md5": "1f175b8e6b292b36c11901bbd33a9cfb"
        }
      ]
    }
  ]
}