{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-complications-permission-dialogs-sample",
    "version": "1.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13314704"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-push",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-permission-dialogs-sample-1.3.0-alpha07-sources.jar",
          "url": "watchface-complications-permission-dialogs-sample-1.3.0-alpha07-sources.jar",
          "size": 7818,
          "sha512": "b14593ebf18c9d5e84da24a4432354c843ebaddae2c7e1e76cef58056fc12ccaef6e022eccf226aafa4bab2e27afab3a167b0c78745cb953e8c98f29fe640f12",
          "sha256": "1fb793ed4b79cec02d6990f9a84a85b7292b8e1a23f155c45ef9577ce0070b0d",
          "sha1": "b58cbddb512a6be0c8ae30f3270704407fae8950",
          "md5": "c728c8c321101d11ec656aa307882738"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-push",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-complications-permission-dialogs-sample-1.3.0-alpha07.aar",
          "url": "watchface-complications-permission-dialogs-sample-1.3.0-alpha07.aar",
          "size": 11515,
          "sha512": "3d8a0bdb49779259d072f5aa2cb4e3181b20e4fd9f8196bc7ccb032da6822a440b2a65578060c17dc3131ce82984f5a9615ea4d0b9f21d8271a134f62900301b",
          "sha256": "d7865d7f6e29f38964482f6210886c3cefd0f1190a362d626e480d8eb1be5c7b",
          "sha1": "95adf985f4bc37a9f3a4d5b9e5f0f6e3bd3813b4",
          "md5": "1f426d42a8d5f68f783611d469262591"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-push",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-complications-permission-dialogs-sample is in atomic group androidx.wear.watchface"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-complications-permission-dialogs-sample-1.3.0-alpha07.aar",
          "url": "watchface-complications-permission-dialogs-sample-1.3.0-alpha07.aar",
          "size": 11515,
          "sha512": "3d8a0bdb49779259d072f5aa2cb4e3181b20e4fd9f8196bc7ccb032da6822a440b2a65578060c17dc3131ce82984f5a9615ea4d0b9f21d8271a134f62900301b",
          "sha256": "d7865d7f6e29f38964482f6210886c3cefd0f1190a362d626e480d8eb1be5c7b",
          "sha1": "95adf985f4bc37a9f3a4d5b9e5f0f6e3bd3813b4",
          "md5": "1f426d42a8d5f68f783611d469262591"
        }
      ]
    }
  ]
}