{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer",
    "version": "1.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-alpha01.aar",
          "url": "media3-exoplayer-1.9.0-alpha01.aar",
          "size": 1634864,
          "sha512": "03349f18909f0b782be745500ee9fb51371e104963f96ed08723556d6364ce574e877d8702875979c31a1bd7506264a8cc8f86bfb68f4bc3224a7b14a95c375a",
          "sha256": "2a8f2e10ffe76067312e283033c7da93f23d1d170cfd222af1e832e25d6491ab",
          "sha1": "e26af488504f29a1dc22a789c2c5f214b05c2d0f",
          "md5": "0f72bbf603e2c5f9fc63a43c3ed8d6bd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-alpha01.aar",
          "url": "media3-exoplayer-1.9.0-alpha01.aar",
          "size": 1634864,
          "sha512": "03349f18909f0b782be745500ee9fb51371e104963f96ed08723556d6364ce574e877d8702875979c31a1bd7506264a8cc8f86bfb68f4bc3224a7b14a95c375a",
          "sha256": "2a8f2e10ffe76067312e283033c7da93f23d1d170cfd222af1e832e25d6491ab",
          "sha1": "e26af488504f29a1dc22a789c2c5f214b05c2d0f",
          "md5": "0f72bbf603e2c5f9fc63a43c3ed8d6bd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-1.9.0-alpha01-sources.jar",
          "url": "media3-exoplayer-1.9.0-alpha01-sources.jar",
          "size": 1165411,
          "sha512": "239dcd1418d28b69c2c087cb2cdd763be9337bf2f045f4066c40107fe8d71a72aadc2d20eb85ef16740462c5b94e882603d4c4c92466dffe7594f8047f2e8578",
          "sha256": "589bbf4aa588c3bae5a8e7ed2a899fdeaeb5cccfa2968d565f52e3944aefbe6a",
          "sha1": "30e1333d8cb6dc240dead6a4927610a47ee9a8ea",
          "md5": "dc17b630c6deabec2bd8bec3c003fc1c"
        }
      ]
    }
  ]
}
