{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-samples",
    "version": "1.4.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-samples-1.4.0-alpha04-sources.jar",
          "url": "window-samples-1.4.0-alpha04-sources.jar",
          "size": 10955,
          "sha512": "cf502015493f3c3d116dc30dccffd003a93f0903bf0dd25befe7f900f4bdc31e80ba11431dae471e22d045ce5be851a4fca73fa7d7ce9c2631a65bcd80064ec7",
          "sha256": "f76cd2d9d638d693b9d8702c90754e5dd8d7e94af9604609f643749d1e6c76a6",
          "sha1": "d801b1597b4ebac0b1306e0ec25f96234a00bbde",
          "md5": "3774405788dac1e557b5bced2d34db25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-samples-1.4.0-alpha04.aar",
          "url": "window-samples-1.4.0-alpha04.aar",
          "size": 29703,
          "sha512": "1f219051c7d51d3ffce3927492be0eea686af820ca3fc8d0f48c198d5ad8c23ac2fcea218e7c2929ac917156b4af99a1ef4d96847ef3e24838d0610271111f60",
          "sha256": "2862dfd8d85fb49f5ed8ce130a73fa8a0a5b28883672f440f8e15b80df88a25e",
          "sha1": "e06f6bf87624fa9a8108a0b491afc195de72db49",
          "md5": "46b15eb64833b4818c38345a27cd85d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha04"
          },
          "reason": "window-samples is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-samples-1.4.0-alpha04.aar",
          "url": "window-samples-1.4.0-alpha04.aar",
          "size": 29703,
          "sha512": "1f219051c7d51d3ffce3927492be0eea686af820ca3fc8d0f48c198d5ad8c23ac2fcea218e7c2929ac917156b4af99a1ef4d96847ef3e24838d0610271111f60",
          "sha256": "2862dfd8d85fb49f5ed8ce130a73fa8a0a5b28883672f440f8e15b80df88a25e",
          "sha1": "e06f6bf87624fa9a8108a0b491afc195de72db49",
          "md5": "46b15eb64833b4818c38345a27cd85d3"
        }
      ]
    }
  ]
}