{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout-samples",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.7.5-sources.jar",
          "url": "foundation-layout-samples-1.7.5-sources.jar",
          "size": 26643,
          "sha512": "beb80b648aa2e4d43ba2c7e2d0a5cbf39846f6063620f94f0d4be4b738c9a92086b4d7345bade4466d52a329d3d7c4c9117abb11b80dfafebdf58264aad4538f",
          "sha256": "d5cdba46a265c956ea9026ccc9d100f133ca39836fad6d61f897cb2173f91306",
          "sha1": "c30fcc13ba6e6f10f524c3e5b3fee1f92ead2616",
          "md5": "344cf5e95eb6c8ee9077a1ac7bbd6dfe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.7.5.aar",
          "url": "foundation-layout-samples-1.7.5.aar",
          "size": 400712,
          "sha512": "4ffdf6527a4002f3a2801005f720b08fa138a5753fd9d123c6fe7d85f599197452d6ff0c8f022d255781095c0e099bc3dc18cf9092f7649757d2c72df39a1aee",
          "sha256": "63f79e6fec5b9087ef454909dc25ac0d3b49ffdebcd63dc75518ff89ef10796a",
          "sha1": "3579a31bca15b77d4c8746aff903178e63294aec",
          "md5": "2b42e763e198d64a93c36ce48cfbbcc3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "foundation-layout-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-samples-1.7.5.aar",
          "url": "foundation-layout-samples-1.7.5.aar",
          "size": 400712,
          "sha512": "4ffdf6527a4002f3a2801005f720b08fa138a5753fd9d123c6fe7d85f599197452d6ff0c8f022d255781095c0e099bc3dc18cf9092f7649757d2c72df39a1aee",
          "sha256": "63f79e6fec5b9087ef454909dc25ac0d3b49ffdebcd63dc75518ff89ef10796a",
          "sha1": "3579a31bca15b77d4c8746aff903178e63294aec",
          "md5": "2b42e763e198d64a93c36ce48cfbbcc3"
        }
      ]
    }
  ]
}