{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear-input",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6794065"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-input-1.0.0-alpha01.aar",
          "url": "wear-input-1.0.0-alpha01.aar",
          "size": 110699,
          "sha512": "98aa679c27a190fed522770e1e077e84cd0ba932f4c4533dac45232ada7d4353cad8bfc4cc413b69d32f9570b248aab70ece2241f4ea29c65a80fbc325986b5b",
          "sha256": "4172a124e2d8f0860748c6bd28afa60d4e5ace5afd7687304888b01f74b6c144",
          "sha1": "88a4a8ba8aa5c374bd489850eb5b169eb7439dc1",
          "md5": "705c81e9a9e24cec94b2705588b4e201"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-input-1.0.0-alpha01.aar",
          "url": "wear-input-1.0.0-alpha01.aar",
          "size": 110699,
          "sha512": "98aa679c27a190fed522770e1e077e84cd0ba932f4c4533dac45232ada7d4353cad8bfc4cc413b69d32f9570b248aab70ece2241f4ea29c65a80fbc325986b5b",
          "sha256": "4172a124e2d8f0860748c6bd28afa60d4e5ace5afd7687304888b01f74b6c144",
          "sha1": "88a4a8ba8aa5c374bd489850eb5b169eb7439dc1",
          "md5": "705c81e9a9e24cec94b2705588b4e201"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-input-1.0.0-alpha01-sources.jar",
          "url": "wear-input-1.0.0-alpha01-sources.jar",
          "size": 10423,
          "sha512": "81bed1930f53b084cba7fb4a72d556d9a854c9ce5fc619de14ac27228a7b7eac25008bc20be07bb262d5d8002a393784bcd0798dc8b0a7161e9af1a8b47fed5f",
          "sha256": "5362d9c0ff89ec7648047edc2662bf685fea4f9829d2df400b52601d687c008d",
          "sha1": "6353d4b483bf5d97849bf8ee5ebd86162c0816db",
          "md5": "50d50f2f6ab9d966129cd07d548f0f9a"
        }
      ]
    }
  ]
}
