{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-rxjava3",
    "version": "2.10.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-rxjava3-2.10.3-sources.jar",
          "url": "work-rxjava3-2.10.3-sources.jar",
          "size": 7610,
          "sha512": "31b87a9fc5fff7892956b582a089039d13b3fcafb4eb03c45df450285cca5a944702c5f70479f8e4964bd01645a43c540288b91ca41165fffc4ad16eab261a21",
          "sha256": "43e83a94804d4f8ca9a26a1bba2029c40122c6326b16e3a9ac95ed306a1181e5",
          "sha1": "fa661bbd33f3919ba56abe4705534914756cef8b",
          "md5": "afe4ab8e68214bee9465b7c480405206"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-rxjava3-2.10.3.aar",
          "url": "work-rxjava3-2.10.3.aar",
          "size": 9462,
          "sha512": "8878848e8c413b716b81d445f0659bb482cd2db9905d5e0afdcd3c72463a36188e9c747d267dd53ea3e39dfe677c0bfb7c893c9afba664687eb5279379012656",
          "sha256": "42aacf3d03f4115020555e767328660fc8bc316171be4bb3f06137527ad34f97",
          "sha1": "7facbbd41e12ac46d07071a53bba1682596ad7da",
          "md5": "357f5e36381a7c7d70874d9d7dd3a514"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.3"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-rxjava3-2.10.3.aar",
          "url": "work-rxjava3-2.10.3.aar",
          "size": 9462,
          "sha512": "8878848e8c413b716b81d445f0659bb482cd2db9905d5e0afdcd3c72463a36188e9c747d267dd53ea3e39dfe677c0bfb7c893c9afba664687eb5279379012656",
          "sha256": "42aacf3d03f4115020555e767328660fc8bc316171be4bb3f06137527ad34f97",
          "sha1": "7facbbd41e12ac46d07071a53bba1682596ad7da",
          "md5": "357f5e36381a7c7d70874d9d7dd3a514"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.10.3"
          },
          "reason": "work-rxjava3 is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-rxjava3-2.10.3-versionMetadata.json",
          "url": "work-rxjava3-2.10.3-versionMetadata.json",
          "size": 525,
          "sha512": "139a126003184026642afaa84789f0792b28835dd7df3d8f088ea1b0c0c80d061cefceb7d8992ce8cb23b1a5673ca6fb635429495e48158696df921cc81b6afa",
          "sha256": "ee6b3a84ae878aab6ecb09c8487f753b768b29f885f9de1136d95eabe55bfe31",
          "sha1": "f725103ca83e759e84d36c9c3eefb979077fd3ad",
          "md5": "56699d3bfd35a52acb6e0b792cf1e458"
        }
      ]
    }
  ]
}