{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate-samples",
    "version": "1.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13944572"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "savedstate-samples is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "savedstate-samples is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "savedstate-samples is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-samples-1.3.2-sources.jar",
          "url": "savedstate-samples-1.3.2-sources.jar",
          "size": 7259,
          "sha512": "ad179ef3e460809ceacda099a5359c56618e1ffed48f9cbb7a359a4f8d196c5b1565b01ca6965881847715ed7ae47d048ed7737f0d68ae76e2c07c37fcb0da0e",
          "sha256": "53346ce0ace2e73c49030da45c03357ed857ec819d82f6da43ba8a22539b39e6",
          "sha1": "a5a55eb6311a88e40e1661eeb1e2ee1eec95926f",
          "md5": "c2a1444de3e44722df513b82ab8f3a9a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "savedstate-samples is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "savedstate-samples is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "savedstate-samples is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-samples-1.3.2.aar",
          "url": "savedstate-samples-1.3.2.aar",
          "size": 85882,
          "sha512": "56ab3e2a3d4df0ddd200c02bff905106426e581f92af32b2d85cc9ffc72563fd3c0c36a6432352514b8c01b530e50ad600117930592509d99678b58437d0814c",
          "sha256": "27061dde1fbdeb22dec08d2ac84f4779115d8e5ac5f63d391cbaf4608296275c",
          "sha1": "1c7b65073ac1f669f03cc89497ea779aae48a661",
          "md5": "1675e4c6e179b89a2a96e095be3f6b15"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "savedstate-samples is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "savedstate-samples is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.2"
          },
          "reason": "savedstate-samples is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-samples-1.3.2.aar",
          "url": "savedstate-samples-1.3.2.aar",
          "size": 85882,
          "sha512": "56ab3e2a3d4df0ddd200c02bff905106426e581f92af32b2d85cc9ffc72563fd3c0c36a6432352514b8c01b530e50ad600117930592509d99678b58437d0814c",
          "sha256": "27061dde1fbdeb22dec08d2ac84f4779115d8e5ac5f63d391cbaf4608296275c",
          "sha1": "1c7b65073ac1f669f03cc89497ea779aae48a661",
          "md5": "1675e4c6e179b89a2a96e095be3f6b15"
        }
      ]
    }
  ]
}