{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.5.0-beta01/collection-1.5.0-beta01.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12750671"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "collection-tvosSimulatorArm64Main-1.5.0-beta01.klib",
          "url": "collection-tvossimulatorarm64-1.5.0-beta01.klib",
          "size": 955403,
          "sha512": "1c48ef2b56ba6cbc080ba3864aa8e247ada8ad0ffffbba574401e8b096d835277e751854700e9febde18101d3c58cf01baffd862374c7749759d5f51eaad4614",
          "sha256": "8d02ba037cdf6f2e79cca9fb87486012a97ea17a8abea496d81de0a62625ba72",
          "sha1": "caac546995e9c53c6a6d516da528ba61e88e8cdb",
          "md5": "d9b0a39286e32625b46c97eb690dd35e"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-tvossimulatorarm64-1.5.0-beta01-sources.jar",
          "url": "collection-tvossimulatorarm64-1.5.0-beta01-sources.jar",
          "size": 284193,
          "sha512": "64b03c760c024ba6d6e95dce55fc5f38d911a615e31087269b774a9eec8ac153bd8de4e434e1d6c3e8ee82334430ef818589edd2e09896be66400899c0c2cf7d",
          "sha256": "5da2ad73cf651c006cde18270c6777c837b94e865f44a72f17c13103a927bdf5",
          "sha1": "61882f0ddec82175db11823fa9c71d7a7debd6c8",
          "md5": "d42df2da22559db6af4b96c66575d3f8"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "collection-tvossimulatorarm64-1.5.0-beta01-metadata.jar",
          "url": "collection-tvossimulatorarm64-1.5.0-beta01-metadata.jar",
          "size": 7944,
          "sha512": "0da32e60b95dc2216f81eec71ac57ee9dbefd9aac7994a3aebc9e03a0ae86ff2e6a7b2e23b4e5ef26a3a703eaabc681807c39f1db85d17bd4210be8d5b81ccfe",
          "sha256": "8e8820d78b45a4ab5477bfdc1175513b52e55b4bc7efe0ae583224b7d9f00553",
          "sha1": "55c3465aca30d61b678b372740e8552dc8c29c53",
          "md5": "eb7a800e0900d91fea9d3fe9e5f49970"
        }
      ]
    }
  ]
}