{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-material3",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "glance-material3-1.0.0.aar",
          "url": "glance-material3-1.0.0.aar",
          "size": 4142,
          "sha512": "f2368bb435e960a2e4f86da1e7a927e82c3f2a32721cc043fcca0d6257b2cfe70fec78c1a336b9908533a7f4bcb92e2d5fcc0d902e2d73a484f03cc4ae6ec596",
          "sha256": "65a624561cb915cced3e31fc60759414d8580a75ad800d81878ef8879837fd3c",
          "sha1": "4295b3a6f259cb68d0d242536c4e0ff70a6b0e99",
          "md5": "d70bc9354dfa9fbe8e9dcc35a38a2087"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "glance-material3-1.0.0.aar",
          "url": "glance-material3-1.0.0.aar",
          "size": 4142,
          "sha512": "f2368bb435e960a2e4f86da1e7a927e82c3f2a32721cc043fcca0d6257b2cfe70fec78c1a336b9908533a7f4bcb92e2d5fcc0d902e2d73a484f03cc4ae6ec596",
          "sha256": "65a624561cb915cced3e31fc60759414d8580a75ad800d81878ef8879837fd3c",
          "sha1": "4295b3a6f259cb68d0d242536c4e0ff70a6b0e99",
          "md5": "d70bc9354dfa9fbe8e9dcc35a38a2087"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "glance-material3-1.0.0-sources.jar",
          "url": "glance-material3-1.0.0-sources.jar",
          "size": 1904,
          "sha512": "99e2bb6ca4ebd08739bf378667900eb0c3913d7b4f96d550302846d54dbebbc4983395448c0b203f37eec5dcfcb426b5fba7fffcd57ef1f6a16faa55f9ae94fb",
          "sha256": "c0fb0b3a353f605067905405fe8ed50fb4d6e4cc4cc15ac4f5b379ee24173be7",
          "sha1": "9ee339e12cc7c3edcf0e3421aa979e5ea579930b",
          "md5": "3426c25ded9a91e068f558db8d18b376"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "glance-material3-1.0.0-versionMetadata.json",
          "url": "glance-material3-1.0.0-versionMetadata.json",
          "size": 310,
          "sha512": "9ad981a05296f6e6cc957e9f9688756520999e65dfd639e0d15f252da77e09fc0a071fb1f0cb4c012ef63f6104909afbe3ce0354ede078a7d0953567cf90df4d",
          "sha256": "b2eb7599eeeb21db3d225c744b6e1a8378dc1382870b0f2b998a0554a76f5d12",
          "sha1": "bc4d5e85ee8400771093ce841eb6ffb88f565571",
          "md5": "59a51770f492c71ab5c8760668b0cee5"
        }
      ]
    }
  ]
}