{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.7.0-alpha03.aar",
          "url": "lifecycle-runtime-testing-2.7.0-alpha03.aar",
          "size": 1075695,
          "sha512": "3f29ef5c2546703fb247c7e6c28a4c7c1885f3a9a4401f4aab210b25ed01908b087acaac7807f86bf33026dd2251ee15711f7f6de813cb9896c106828a2558ff",
          "sha256": "d8dabcaf26cf4d6479060a9d336ca2b1b7fe1f4a02753ca4aa98b13dda43f660",
          "sha1": "2562f2db0f7b74486e49444faa056e5a13e25e44",
          "md5": "1d81a65930655433d52bb1c9edc8f088"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.7.0-alpha03.aar",
          "url": "lifecycle-runtime-testing-2.7.0-alpha03.aar",
          "size": 1075695,
          "sha512": "3f29ef5c2546703fb247c7e6c28a4c7c1885f3a9a4401f4aab210b25ed01908b087acaac7807f86bf33026dd2251ee15711f7f6de813cb9896c106828a2558ff",
          "sha256": "d8dabcaf26cf4d6479060a9d336ca2b1b7fe1f4a02753ca4aa98b13dda43f660",
          "sha1": "2562f2db0f7b74486e49444faa056e5a13e25e44",
          "md5": "1d81a65930655433d52bb1c9edc8f088"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.7.0-alpha03-sources.jar",
          "url": "lifecycle-runtime-testing-2.7.0-alpha03-sources.jar",
          "size": 2070,
          "sha512": "ee6b1ecf4f4f892d09fdf64e278b0406d1c220d0a8323d3b8662334db63c416d5c6d2ae1b3175557ebb253601fcf2299a9064f6df0a9226ec76d40bdbbc0572b",
          "sha256": "e5f19741e88a6901401d832f487bc5c18e743286be73b2527eb0138a9e14ec54",
          "sha1": "038cd9e0686c9cafa22d4067b9de37f7c3350f45",
          "md5": "56d492baf8def2a459064d6f3c19b371"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.7.0-alpha03"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-2.7.0-alpha03-versionMetadata.json",
          "url": "lifecycle-runtime-testing-2.7.0-alpha03-versionMetadata.json",
          "size": 823,
          "sha512": "cb027eeff3205d49bb64e8b4145cbb90f55163f1fa45476e52c92ea9f6a73ebf0341c07169962ed26828f712a425680ba138fe13a1f0702d3888522a75e84e38",
          "sha256": "ea61b4e4f1d98925c25aafb64c6b8d57060c757067fbd437713ebf7f35331ab4",
          "sha1": "69be5399995a5107422e91016306d3028c08ae9f",
          "md5": "4011baa8d76f52129e35ea89a39d1ebe"
        }
      ]
    }
  ]
}