{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7107201"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-1.0.0-alpha11.aar",
          "url": "ui-util-1.0.0-alpha11.aar",
          "size": 9903,
          "sha512": "6a2e4fc20a26e01079c3f6cbac549752b4063b1b89ce038c72d6e31474a58acf965cd8925ab95f9420c51575045b3a83ce9fbcc384c4aae29789646721539efb",
          "sha256": "ddfb215f9c351f48a605aaab9835e19c064f5f462b08d3136d3de2321c56f002",
          "sha1": "d4468be50b3f52e5e5644910e48cf0214ab846e4",
          "md5": "bc9237090f45d8cdcf81f48e1acebd34"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-1.0.0-alpha11.aar",
          "url": "ui-util-1.0.0-alpha11.aar",
          "size": 9903,
          "sha512": "6a2e4fc20a26e01079c3f6cbac549752b4063b1b89ce038c72d6e31474a58acf965cd8925ab95f9420c51575045b3a83ce9fbcc384c4aae29789646721539efb",
          "sha256": "ddfb215f9c351f48a605aaab9835e19c064f5f462b08d3136d3de2321c56f002",
          "sha1": "d4468be50b3f52e5e5644910e48cf0214ab846e4",
          "md5": "bc9237090f45d8cdcf81f48e1acebd34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-util-1.0.0-alpha11-sources.jar",
          "url": "ui-util-1.0.0-alpha11-sources.jar",
          "size": 5802,
          "sha512": "43ca55bf655020afb0f8133b00f59a8d8dc8f3e45aa59b3c1ac9aae555b0ed0ac476adf936b18a6a5600a89a353b6f3b322518bd67307c02b4a9b68777105de4",
          "sha256": "08d4ba03cf824be92d5d1b6d664e87dfd9cb4fbe89eae762402dc4c62508090c",
          "sha1": "10cbf7d47ac223e047f999be9d2e4d8658deaa7a",
          "md5": "bb217622b595459d265c8d3c3381f879"
        }
      ]
    }
  ]
}
