{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-rxjava2",
    "version": "2.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7209663"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "room-rxjava2-2.3.0-rc01.aar",
          "url": "room-rxjava2-2.3.0-rc01.aar",
          "size": 10635,
          "sha512": "727717626e8026c8ee97f155e91d24c2c0680342c5123e88a38a24a18f3733857bd95db6ab116e04dcec4d45b0b48b45d8425134349961659fbc908ca70de067",
          "sha256": "70b19608e8d25a8f9736c58b562890eff3e79313541ca2fb38e99de5be6e2a7f",
          "sha1": "8f316afee7b47b6eec5a2cae27a614c5eee0d301",
          "md5": "c96e1d92d18ba3c9faf5d13d47acd40e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0-rc01"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "room-rxjava2-2.3.0-rc01.aar",
          "url": "room-rxjava2-2.3.0-rc01.aar",
          "size": 10635,
          "sha512": "727717626e8026c8ee97f155e91d24c2c0680342c5123e88a38a24a18f3733857bd95db6ab116e04dcec4d45b0b48b45d8425134349961659fbc908ca70de067",
          "sha256": "70b19608e8d25a8f9736c58b562890eff3e79313541ca2fb38e99de5be6e2a7f",
          "sha1": "8f316afee7b47b6eec5a2cae27a614c5eee0d301",
          "md5": "c96e1d92d18ba3c9faf5d13d47acd40e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-rxjava2-2.3.0-rc01-sources.jar",
          "url": "room-rxjava2-2.3.0-rc01-sources.jar",
          "size": 3664,
          "sha512": "fbb760c28c25731ca14aefec22a0307d1a7148952c708f685897a61fe3a5e798248c6ec39151616e01101bf15eefb05a37b5d7648f29f2facb8c09feb9bb2972",
          "sha256": "0c9c4915c10b86f1f482af9e00d429234df44e89959015b69305094cc7004e07",
          "sha1": "0104bafc3fe7aedb917d8c793f9695a77021b984",
          "md5": "7b539c43ac77f2c2d35cbc8a8c0d2851"
        }
      ]
    }
  ]
}
