{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata-samples",
    "version": "1.2.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runtime-livedata-samples-1.2.0-beta03.aar",
          "url": "runtime-livedata-samples-1.2.0-beta03.aar",
          "size": 6569,
          "sha512": "57523c2d40e9a4079c9f5fb216154f77020cd3953f0ed18b840d7ac8550ef8c90f5f1fed9467de8e74fe898e33c55e538d4c2b0e78443054c99b0d1191c138c3",
          "sha256": "8c96f30c0cfd105c089dcf476b072d544c854f26096b1f28c4a8984933b3d32b",
          "sha1": "cdeba3ec2f0e7098d49404548d4561d3cf5bcf12",
          "md5": "b32a0aea473867f1bcb6d13f6ddeab74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.2.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-samples-1.2.0-beta03.aar",
          "url": "runtime-livedata-samples-1.2.0-beta03.aar",
          "size": 6569,
          "sha512": "57523c2d40e9a4079c9f5fb216154f77020cd3953f0ed18b840d7ac8550ef8c90f5f1fed9467de8e74fe898e33c55e538d4c2b0e78443054c99b0d1191c138c3",
          "sha256": "8c96f30c0cfd105c089dcf476b072d544c854f26096b1f28c4a8984933b3d32b",
          "sha1": "cdeba3ec2f0e7098d49404548d4561d3cf5bcf12",
          "md5": "b32a0aea473867f1bcb6d13f6ddeab74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-livedata-samples-1.2.0-beta03-sources.jar",
          "url": "runtime-livedata-samples-1.2.0-beta03-sources.jar",
          "size": 1663,
          "sha512": "499da5ccc575764cdfe3945cabe1a28937530305b6708e2b5ea275e8d4840acea9e625018d5079e5c1ae1bcb188d7504ce44e73f7def35016e07439b8acd5352",
          "sha256": "5bc70bceb46741194a33d166003ec4a3f23ef66abef61e51bc5ae65b01f24092",
          "sha1": "2aed546e633b44703f361e15d1caaa5824029852",
          "md5": "0481648d351992d722b5e6a739ed8618"
        }
      ]
    }
  ]
}