{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.7.0-rc01/foundation-1.7.0-rc01.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.7.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-rc01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-rc01"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.7.0-rc01.jar",
          "url": "foundation-desktop-1.7.0-rc01.jar",
          "size": 3810340,
          "sha512": "f41e3f92dc1d834e0260180ec94e8476571667bf835caf4f7db133f451fdba52a9ae6cf067bc16ca37315ffb31ed3e15710ca5f1a55ef03556a0cbc70d91df86",
          "sha256": "9387b40c9364bee1db273041477af2a140e1af68d47d429c36c8a6e5db094bbf",
          "sha1": "ccdb550f931dae11e2602e077088b0ee122ea72b",
          "md5": "8a905fa9d0d3a36e0d8c5c992841410c"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-rc01"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.7.0-rc01.jar",
          "url": "foundation-desktop-1.7.0-rc01.jar",
          "size": 3810340,
          "sha512": "f41e3f92dc1d834e0260180ec94e8476571667bf835caf4f7db133f451fdba52a9ae6cf067bc16ca37315ffb31ed3e15710ca5f1a55ef03556a0cbc70d91df86",
          "sha256": "9387b40c9364bee1db273041477af2a140e1af68d47d429c36c8a6e5db094bbf",
          "sha1": "ccdb550f931dae11e2602e077088b0ee122ea72b",
          "md5": "8a905fa9d0d3a36e0d8c5c992841410c"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-rc01"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-desktop-1.7.0-rc01-sources.jar",
          "url": "foundation-desktop-1.7.0-rc01-sources.jar",
          "size": 791394,
          "sha512": "691fc0a6f1f5252a893b5414be747f6177d1dc1d6c9816e21141a54e75405f318145f95b91d0aa395a20e1121708e19537985baa11331cf708c48c1bc6334eb9",
          "sha256": "97c9ca4215b1a7b97bda099412350e9be58e5475d6b30843912c0ed00b6ff211",
          "sha1": "0d3431e878c9639bc2a921e43be16a1d5011079f",
          "md5": "b52f88d6556520c87679186c30431a41"
        }
      ]
    }
  ]
}