{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ui",
    "module": "ui-text-android",
    "version": "0.1.0-dev12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6517017"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-android-0.1.0-dev12.aar",
          "url": "ui-text-android-0.1.0-dev12.aar",
          "size": 51013,
          "sha512": "e381b09ea324d24bb002b4017fa89e8213e2a614728cc988c68d1e1a26ea7e50aba605e91a30960c8d7fb727142265a39f8795bd5fc854d623d236df5f83954a",
          "sha256": "c84d34fea4eb1195704f078c5cf4cc4843bfb5327c1c9b996b1094f2551e1c36",
          "sha1": "112e514c070acb4f78944faa23b3596635f7d527",
          "md5": "b2bbff25cd0062e47596292be70250ad"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-android-0.1.0-dev12.aar",
          "url": "ui-text-android-0.1.0-dev12.aar",
          "size": 51013,
          "sha512": "e381b09ea324d24bb002b4017fa89e8213e2a614728cc988c68d1e1a26ea7e50aba605e91a30960c8d7fb727142265a39f8795bd5fc854d623d236df5f83954a",
          "sha256": "c84d34fea4eb1195704f078c5cf4cc4843bfb5327c1c9b996b1094f2551e1c36",
          "sha1": "112e514c070acb4f78944faa23b3596635f7d527",
          "md5": "b2bbff25cd0062e47596292be70250ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-android-0.1.0-dev12-sources.jar",
          "url": "ui-text-android-0.1.0-dev12-sources.jar",
          "size": 28870,
          "sha512": "0bd8d58d2c39df98fe6b6116818eee85de635f41ead01f4677426bfd7ba8e1f33dbfcd52b3fd8c8824de31fc3c1a0d8d3696bfa3f4a8fd0560b95d7b51ddbec5",
          "sha256": "f2ea92ca6e653b1064b913b6bcf9a852cadcc206afadcac2f25637ec24b533dc",
          "sha1": "b465c4b772e545db46eb8b26c5963cd7f3c70b8b",
          "md5": "aeef3a3d9feb2b1eacd635b13ab58d80"
        }
      ]
    }
  ]
}
