{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-core",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-1.4.0-alpha03-multiplatform-sources.jar",
          "url": "window-core-1.4.0-alpha03-multiplatform-sources.jar",
          "size": 13321,
          "sha512": "a8e4b99cc1699b840016ab45964d8ca85a2e95778eb9e880895dbfce784b914b7d8df4219f31f366398e010dd780846b3f5dcebcd8840b3b6e83dd0d8689528e",
          "sha256": "7e48d93bcc7913a051365425adefb542f65c4fd2b0b390f33a8a8ef7a5ca4bdc",
          "sha1": "e66c90d14a7b156ba318761d09235f7e8899264f",
          "md5": "2abdb9a3e2951a02fb07cbbd57d9d7e8"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "window-core-1.4.0-alpha03-versionMetadata.json",
          "size": 3688,
          "sha512": "eec7d01a3fba086478b26b52520e67fa4ede2f3866a30d6de5b819ddae96b9575f51f54e5b0b4d82c1b9106a03298ef15724ad4968d590267a8ec142d924731e",
          "sha256": "843623b01ec1cf4fbd090ed0c51cf3fcc85520635b9733550ef5b260ef744abe",
          "sha1": "1e85dc9e52cd4515ba4e12d8da7e51a5c73e69ba",
          "md5": "33e22ac62b4dafe16d73aab0e98bfb2d"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-metadata-1.4.0-alpha03.jar",
          "url": "window-core-1.4.0-alpha03.jar",
          "size": 9769,
          "sha512": "3668ba4779fbd5ebd9335b9b1f2bf89be49706513e26403c8292106af6430478345cabf4355c0df95b091ccf7e0483eae6674cd74622752f437b6ebc089fd75a",
          "sha256": "7d25dfe43fff6be8a9bcf4c85d9507b1a4068ebebee13a86331828ae55e8c7d6",
          "sha1": "ee778be3980e724dd6c886a783952f208f9bb401",
          "md5": "dbcf6282f4e193a7e7f16bc40f63099d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-kotlin-1.4.0-alpha03-sources.jar",
          "url": "window-core-1.4.0-alpha03-sources.jar",
          "size": 12933,
          "sha512": "38fdd1b09dc72e45b92457d2d61a0b8eff53041df8727aa6cf95b403c450f53cdde237311509f638955bda32f09a3daf5028b8a9555221bd3d4a62f03b432c7f",
          "sha256": "1b8d1607405ec5660c1c7268822ddc0f6fdc1b0e63351e0c21f0cc9a1e46b7d5",
          "sha1": "dfae7c5697df6a9cbfa19774cf622c46a2f9a3e0",
          "md5": "0fcd883d6b87a713f35aa69eac184a25"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../window-core-android/1.4.0-alpha03/window-core-android-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-android",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../window-core-android/1.4.0-alpha03/window-core-android-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-android",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../window-core-android/1.4.0-alpha03/window-core-android-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-android",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-iosarm64/1.4.0-alpha03/window-core-iosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-iosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-iosarm64/1.4.0-alpha03/window-core-iosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-iosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-iosarm64/1.4.0-alpha03/window-core-iosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-iosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-iossimulatorarm64/1.4.0-alpha03/window-core-iossimulatorarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-iossimulatorarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-iossimulatorarm64/1.4.0-alpha03/window-core-iossimulatorarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-iossimulatorarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-iossimulatorarm64/1.4.0-alpha03/window-core-iossimulatorarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-iossimulatorarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-iosx64/1.4.0-alpha03/window-core-iosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-iosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-iosx64/1.4.0-alpha03/window-core-iosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-iosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-iosx64/1.4.0-alpha03/window-core-iosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-iosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../window-core-jvm/1.4.0-alpha03/window-core-jvm-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-jvm",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../window-core-jvm/1.4.0-alpha03/window-core-jvm-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-jvm",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../window-core-jvm/1.4.0-alpha03/window-core-jvm-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-jvm",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-linuxarm64/1.4.0-alpha03/window-core-linuxarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-linuxarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-linuxarm64/1.4.0-alpha03/window-core-linuxarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-linuxarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-linuxx64/1.4.0-alpha03/window-core-linuxx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-linuxx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-linuxx64/1.4.0-alpha03/window-core-linuxx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-linuxx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-macosarm64/1.4.0-alpha03/window-core-macosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-macosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-macosarm64/1.4.0-alpha03/window-core-macosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-macosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-macosarm64/1.4.0-alpha03/window-core-macosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-macosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-macosx64/1.4.0-alpha03/window-core-macosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-macosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-macosx64/1.4.0-alpha03/window-core-macosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-macosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-macosx64/1.4.0-alpha03/window-core-macosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-macosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-tvosarm64/1.4.0-alpha03/window-core-tvosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-tvosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-tvosarm64/1.4.0-alpha03/window-core-tvosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-tvosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-tvosarm64/1.4.0-alpha03/window-core-tvosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-tvosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-tvossimulatorarm64/1.4.0-alpha03/window-core-tvossimulatorarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-tvossimulatorarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-tvossimulatorarm64/1.4.0-alpha03/window-core-tvossimulatorarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-tvossimulatorarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-tvossimulatorarm64/1.4.0-alpha03/window-core-tvossimulatorarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-tvossimulatorarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-tvosx64/1.4.0-alpha03/window-core-tvosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-tvosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-tvosx64/1.4.0-alpha03/window-core-tvosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-tvosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-tvosx64/1.4.0-alpha03/window-core-tvosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-tvosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchosarm32/1.4.0-alpha03/window-core-watchosarm32-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchosarm32",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchosarm32/1.4.0-alpha03/window-core-watchosarm32-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchosarm32",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchosarm32/1.4.0-alpha03/window-core-watchosarm32-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchosarm32",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchosarm64/1.4.0-alpha03/window-core-watchosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchosarm64/1.4.0-alpha03/window-core-watchosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchosarm64/1.4.0-alpha03/window-core-watchosarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchosarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchossimulatorarm64/1.4.0-alpha03/window-core-watchossimulatorarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchossimulatorarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchossimulatorarm64/1.4.0-alpha03/window-core-watchossimulatorarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchossimulatorarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchossimulatorarm64/1.4.0-alpha03/window-core-watchossimulatorarm64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchossimulatorarm64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchosx64/1.4.0-alpha03/window-core-watchosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchosx64/1.4.0-alpha03/window-core-watchosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchosx64",
        "version": "1.4.0-alpha03"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../window-core-watchosx64/1.4.0-alpha03/window-core-watchosx64-1.4.0-alpha03.module",
        "group": "androidx.window",
        "module": "window-core-watchosx64",
        "version": "1.4.0-alpha03"
      }
    }
  ]
}