{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text-google-fonts",
    "version": "1.7.0-beta07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-google-fonts-1.7.0-beta07-sources.jar",
          "url": "ui-text-google-fonts-1.7.0-beta07-sources.jar",
          "size": 8777,
          "sha512": "3f7be9c98c5376a0bb4ebe06cf11847cad3368a5e58faf8beccb8a7ae156b3117c743ed4dedd707f6e1945f1e8fbbf264f13c724aaa06f087658b55492f74deb",
          "sha256": "68cf99cb868ac8256a6217bc3484e14c0af10951d1411a75662072422254bbf3",
          "sha1": "69e494ca1a839ee0eb1c7f92a20300a2d00ad85a",
          "md5": "c03630e4094d435dd6353e6b5f01a299"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-google-fonts-1.7.0-beta07.aar",
          "url": "ui-text-google-fonts-1.7.0-beta07.aar",
          "size": 24158,
          "sha512": "8d933cc257b3a3a9a3d1f7923b0ccdebf9f8f050ddeee0f1201cae175d8b36447e0ea04d4b0dba341865e03d85c4ac61f01d340dd77081678d4feb92884e6eb3",
          "sha256": "fa9ae671911e4152537b40d7c33383deca15378c3658192fc66d2f1ea71ef3cb",
          "sha1": "cabd962591821f7c675578e37af79eff1b928661",
          "md5": "684ae6b0526664c98f67628d63dc8e0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta07"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-google-fonts-1.7.0-beta07.aar",
          "url": "ui-text-google-fonts-1.7.0-beta07.aar",
          "size": 24158,
          "sha512": "8d933cc257b3a3a9a3d1f7923b0ccdebf9f8f050ddeee0f1201cae175d8b36447e0ea04d4b0dba341865e03d85c4ac61f01d340dd77081678d4feb92884e6eb3",
          "sha256": "fa9ae671911e4152537b40d7c33383deca15378c3658192fc66d2f1ea71ef3cb",
          "sha1": "cabd962591821f7c675578e37af79eff1b928661",
          "md5": "684ae6b0526664c98f67628d63dc8e0f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.7.0-beta07"
          },
          "reason": "ui-text-google-fonts is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-text-google-fonts-1.7.0-beta07-versionMetadata.json",
          "url": "ui-text-google-fonts-1.7.0-beta07-versionMetadata.json",
          "size": 1496,
          "sha512": "7b66bee8ae256ad89239054d0970182f18bc94b910efbe37538943b7334428ec2cf6e1661efe5758135ab5d6cf4abd4c92c10d7d9d6e6881abb04f07f61af5d0",
          "sha256": "108ac2789d16440722976d430645e07aa728f311906827aaa5419f35ecb08d36",
          "sha1": "6a318fda933f10cf1e66c657bc463853a4ad5643",
          "md5": "1ffd4a0dbc08949ec34b9465caf4df44"
        }
      ]
    }
  ]
}