{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel/2.9.0-alpha06/lifecycle-viewmodel-2.9.0-alpha06.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.9.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel.klib",
          "url": "lifecycle-viewmodel-macosarm64-2.9.0-alpha06.klib",
          "size": 52195,
          "sha512": "2e0f5131c8d909c05d36ba3890725313f56d26247e7934a538531264dcca615f8b721c3f22fefd311834afcfe069c5c0532ac11e844296c5c06e293eeba0ca07",
          "sha256": "e6a16099b9dc3e26c50c149a39eb55a21f78c066716b625b96662054eda5831a",
          "sha1": "fed366afdaca5e8df22ed2ce60f53f92d9b0057e",
          "md5": "d427365dbbe95c86993341a39849706f"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-macosarm64-2.9.0-alpha06-sources.jar",
          "url": "lifecycle-viewmodel-macosarm64-2.9.0-alpha06-sources.jar",
          "size": 36291,
          "sha512": "72f3b0eaa159b5f6046e88f974aa91663e7b3bd64d2c34ad526e1073ca6fe3b5b2ad55a2cfdfed55d85ad33e723839842c86d0e0e830ed71829430a3c906e1c9",
          "sha256": "e7b2fd56a3e4e75b2ef98956b7729f6901c7c17fc06b7c5c2a34c5f55931c84d",
          "sha1": "279fd4814a07f769246df593b954f0043e7d732c",
          "md5": "6860670424a0e3a63de89793d026df55"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-macosarm64-2.9.0-alpha06-metadata.jar",
          "url": "lifecycle-viewmodel-macosarm64-2.9.0-alpha06-metadata.jar",
          "size": 8538,
          "sha512": "75918cd1274e97c541bec2170cc6ff15a80b827d23b54996be503a0de11deff587fa487aadbd6c29e22761ccd10b1b64c17063485a820fa0aeb8eee2be36764e",
          "sha256": "05d8c25e417e1d16f30c79a325d349b3b7ddfed975b954d8746a0ece95835b7b",
          "sha1": "878c5918f4bbacf539f28f685436bd96d51f4e59",
          "md5": "e7121ca2bf94c0f461d583cf73bddc85"
        }
      ]
    }
  ]
}