{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-common/2.9.0-alpha06/lifecycle-common-2.9.0-alpha06.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-common",
    "version": "2.9.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-common.klib",
          "url": "lifecycle-common-iosx64-2.9.0-alpha06.klib",
          "size": 26373,
          "sha512": "a8dffa60c7975e2f7dd2d3c42b008e2c1b347a757ad9a674987c90c15dec08228a050b5b14183c2b76b7054146162d3048601609ec1bec340adcc06fed79dbce",
          "sha256": "ee906afa9c62e25f455c68b65b51976733b67f35769672f0e754d4c8e58cc41c",
          "sha1": "2e3e4ded1d2bc12427e0ecb41ff8e8e99400b915",
          "md5": "bd7e2a6d8c5ce78be972f173e8c09a42"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-iosx64-2.9.0-alpha06-sources.jar",
          "url": "lifecycle-common-iosx64-2.9.0-alpha06-sources.jar",
          "size": 15832,
          "sha512": "c0665d60599307174d6ddfb0374db49605c61033f3457ad3e209e79199eef9c2448c2f6f1bd8c9812156addda38877bf33f16fa613bb95cd06908d56e5a15024",
          "sha256": "b3c5a0c0903395c91e4245e69fb0553d4f7e39b235cb7ee909509a1121b2288e",
          "sha1": "b4accc21aea4e3b2588ddf03e164063bd95d77b5",
          "md5": "a02b7b0af2678c8ca9ab620428f394ee"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-common is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-common-iosx64-2.9.0-alpha06-metadata.jar",
          "url": "lifecycle-common-iosx64-2.9.0-alpha06-metadata.jar",
          "size": 4428,
          "sha512": "4da161d849b61931ade6fffe11316506f6deb08ee27012bedf8720493277536f45454533da371bc8346df6082213de729f3e23ee90be384a1716c93ee0b4f450",
          "sha256": "18dc26439a4a0e8890f75121fe4efbd89d8dfcd8cdbb6052b0fe0f31e275fe8e",
          "sha1": "05cb47462b9f96bc49e792a474ad59c2a24a6c14",
          "md5": "7c9a74959768882b4328051cf77eba1a"
        }
      ]
    }
  ]
}