{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling/1.5.0-beta01/ui-tooling-1.5.0-beta01.module",
    "group": "androidx.compose.ui",
    "module": "ui-tooling",
    "version": "1.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-desktop-1.5.0-beta01.jar",
          "url": "ui-tooling-desktop-1.5.0-beta01.jar",
          "size": 28669,
          "sha512": "ff66bdbce1133e6d1708d15fa47d5c7a6411cd034973d96951a869d03d45fca9143e9c197eae2f1f4b90623506ee16c966dffffe110032e70365375a6f78a53c",
          "sha256": "f90dd8bad67bfe81fc364f7098d2d97bef1b129a096e6515e1a971a3e6e67433",
          "sha1": "4fcd4885670511be8929bd97fd4b3e0e11691fb6",
          "md5": "0ea72c332101a941e2be027a0d1fa112"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-desktop-1.5.0-beta01.jar",
          "url": "ui-tooling-desktop-1.5.0-beta01.jar",
          "size": 28669,
          "sha512": "ff66bdbce1133e6d1708d15fa47d5c7a6411cd034973d96951a869d03d45fca9143e9c197eae2f1f4b90623506ee16c966dffffe110032e70365375a6f78a53c",
          "sha256": "f90dd8bad67bfe81fc364f7098d2d97bef1b129a096e6515e1a971a3e6e67433",
          "sha1": "4fcd4885670511be8929bd97fd4b3e0e11691fb6",
          "md5": "0ea72c332101a941e2be027a0d1fa112"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-desktop-1.5.0-beta01-sources.jar",
          "url": "ui-tooling-desktop-1.5.0-beta01-sources.jar",
          "size": 9331,
          "sha512": "86fcccda46a84e9d76f81cc1851c980775f2e97b30da33f88a955cdd0aa3c3bff6ad8d501d72843f2869d8bb29fb354bf1c8b8bfa579f9a7ee89aa34cf2c354a",
          "sha256": "b6104763647a0a5e40849bc372afe51db84c465a3ac76a5b736719956e4c8383",
          "sha1": "511de234b329ff3bf6c12a16998cb118b82aa6da",
          "md5": "4c289160c45ffc4e896b797e2d2da883"
        }
      ]
    }
  ]
}