{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ink-brush/1.0.0-alpha07/ink-brush-1.0.0-alpha07.module",
    "group": "androidx.ink",
    "module": "ink-brush",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14202175"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-brush-jvm-1.0.0-alpha07.jar",
          "url": "ink-brush-jvm-1.0.0-alpha07.jar",
          "size": 322970,
          "sha512": "c03c849ebbb78426a0b67c467c8d938326fc9910c657288ed905c0d65e9d5fd23ef2a7b591ab2c2593d92d60484605de93b71d7832c63779399ee929e2585a8e",
          "sha256": "709c2926ef6d7834771e33dcb314fec6ff54edf7eb79011a8fd0d442527c5755",
          "sha1": "7c9018eb2357b161ddda27a5d6479c7dcbe71f38",
          "md5": "2ef64083e36d4df6dbe8bc12f8603fcf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ink-brush-jvm-1.0.0-alpha07.jar",
          "url": "ink-brush-jvm-1.0.0-alpha07.jar",
          "size": 322970,
          "sha512": "c03c849ebbb78426a0b67c467c8d938326fc9910c657288ed905c0d65e9d5fd23ef2a7b591ab2c2593d92d60484605de93b71d7832c63779399ee929e2585a8e",
          "sha256": "709c2926ef6d7834771e33dcb314fec6ff54edf7eb79011a8fd0d442527c5755",
          "sha1": "7c9018eb2357b161ddda27a5d6479c7dcbe71f38",
          "md5": "2ef64083e36d4df6dbe8bc12f8603fcf"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-brush is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-brush-jvm-1.0.0-alpha07-sources.jar",
          "url": "ink-brush-jvm-1.0.0-alpha07-sources.jar",
          "size": 116517,
          "sha512": "0172edf4e153cda9581d8406d67a16daf2a4e35c031510d98baaf26c64c901ae3b73c3663a361c7eeb6b0b82e765863c622a4df868109742ce6212702da1deb5",
          "sha256": "3caa6dd3f0f9b31d3579ec5f8acab7ddaaf644b031e3e40ff914f8b1570c98af",
          "sha1": "6d1903436d8ae9a0eab40af90bd05795d0b8e98a",
          "md5": "9cc47e96b34e3e56cc1cdd680fff7311"
        }
      ]
    }
  ]
}