{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-foundation",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta04"
          }
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.0.0-alpha12.aar",
          "url": "compose-foundation-1.0.0-alpha12.aar",
          "size": 58901,
          "sha512": "5ad0c637d555fbdb968996d14a1b1a9ec126d17f5855e9785ac642cc4f5ba0f52c4432abbdf2e3da669c66a8943258c4813a16d0fbd9e32f51009af256fc4e7b",
          "sha256": "aa3c50873307931ecc4b2535b4cc3d51dd1d009a760a55f1af29f85520ef4382",
          "sha1": "0921285670239a44acbb8cf9bf95a29ba497b11f",
          "md5": "503958ce706bfa699b62d99db3acf72e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.0-beta04"
          }
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.0.0-alpha12.aar",
          "url": "compose-foundation-1.0.0-alpha12.aar",
          "size": 58901,
          "sha512": "5ad0c637d555fbdb968996d14a1b1a9ec126d17f5855e9785ac642cc4f5ba0f52c4432abbdf2e3da669c66a8943258c4813a16d0fbd9e32f51009af256fc4e7b",
          "sha256": "aa3c50873307931ecc4b2535b4cc3d51dd1d009a760a55f1af29f85520ef4382",
          "sha1": "0921285670239a44acbb8cf9bf95a29ba497b11f",
          "md5": "503958ce706bfa699b62d99db3acf72e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-foundation-1.0.0-alpha12-sources.jar",
          "url": "compose-foundation-1.0.0-alpha12-sources.jar",
          "size": 11504,
          "sha512": "c8020c4aec4c0b34c90b10ebcdd40c0ab8f7dd6ede659986132f7dae36d5708bcf3a84863c209258fd6b71c4ff347a7903a528d3277bcb6d8b7162b17f578ad1",
          "sha256": "27a69e21200b6162caac95f8531e9b1bb59a066523dcb10558cf35f6083b98bf",
          "sha1": "c56ab447b856918b4b61967ac3370c9432d0d1e8",
          "md5": "c13c6a6c943425e4c77efad2c78485d4"
        }
      ]
    }
  ]
}
