{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-framework/2.5.0-alpha04/sqlite-framework-2.5.0-alpha04.module",
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework.klib",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha04.klib",
          "size": 21731,
          "sha512": "c9cf7dcfe469ca959429b534e82dfdff3656af832d8c0762bacc44d9a3b85ea5d23f2abad3c57261ead063f4219a415d4575b69c636a4fd884b92bad03ec44cb",
          "sha256": "d7e7d8e0cf19ea6bb6813b10ed662af3c79640d7c944b412efe198daa2dabc08",
          "sha1": "331b9ef5883c4b00cef6ace82013d90b864eae3c",
          "md5": "8352257fbbcc1e3de52fd15fcf4c7a62"
        },
        {
          "name": "sqlite-framework-cinterop-sqlite3.klib",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha04-cinterop-sqlite3.klib",
          "size": 62575,
          "sha512": "8aa18ad41f94d82694877b1b4fa54be451b50a53eb6e166bd0596d0e0b2f8fef545c2167a5f75f10f241cbfa01821ce12cdcb59096836b5db3edd1686670cb2e",
          "sha256": "982e96715eb0e7ab69d74bbd1da57648e70d7bf80c7f7c7828b4d746f55f830b",
          "sha1": "2c19d7a7cbdee0575ec1cdb6a701b5ac0805a30c",
          "md5": "4f39d3905f63defb71339b5074646717"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-macosarm64-2.5.0-alpha04-sources.jar",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha04-sources.jar",
          "size": 6447,
          "sha512": "a906724ff126b4eb45771098f402d656de4a491bb99b2930eca5c785bd4e8a5c108333beb29223023c1e2f86842d7f6043bdb46d91dd0beefad66c978363f92d",
          "sha256": "8f2e94767c01db90693e03fecfce56bb28f49ef3c7f6095a66b38ffe24c6fae6",
          "sha1": "2233c9c838953b3d5ba9730a590aa8df882c1ff7",
          "md5": "4cd225effdf48ebfb4ffa6ae3e83f7ac"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha04"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-macosarm64-2.5.0-alpha04-metadata.jar",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha04-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}