{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-foundation-samples",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compose-foundation-samples-1.0.0-alpha13.aar",
          "url": "compose-foundation-samples-1.0.0-alpha13.aar",
          "size": 10530,
          "sha512": "8f3e9d75b0fb4ccb90036ed9c5b09972f49c35b32a1f1b42f41462a2146eb871dac9f0bf629c557e9e88513775608a42af4ed911a827e261c7658a5112c746b9",
          "sha256": "907a6f6e343d493249fe25399dce87fe54158fdd2cd5303d9d0fbd140275585a",
          "sha1": "c7a7e04f5cdef3770a126b2f408831e51971792c",
          "md5": "9bbe8e9e79d26cd738822ec1c72bd709"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        }
      ],
      "files": [
        {
          "name": "compose-foundation-samples-1.0.0-alpha13.aar",
          "url": "compose-foundation-samples-1.0.0-alpha13.aar",
          "size": 10530,
          "sha512": "8f3e9d75b0fb4ccb90036ed9c5b09972f49c35b32a1f1b42f41462a2146eb871dac9f0bf629c557e9e88513775608a42af4ed911a827e261c7658a5112c746b9",
          "sha256": "907a6f6e343d493249fe25399dce87fe54158fdd2cd5303d9d0fbd140275585a",
          "sha1": "c7a7e04f5cdef3770a126b2f408831e51971792c",
          "md5": "9bbe8e9e79d26cd738822ec1c72bd709"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-foundation-samples-1.0.0-alpha13-sources.jar",
          "url": "compose-foundation-samples-1.0.0-alpha13-sources.jar",
          "size": 1883,
          "sha512": "56904fb4c2aaf66ccda4a6435200d21e994040db52164a396ab53a9787dd0daf9c9fbcb1a09eca12ba6defa96fd29b422cc0f6a3dc70cf151af4de74e6a7d3b0",
          "sha256": "88a2098e2521bc6ebbec45776ee2673ba551af6f3ced0c0d68dc6f258821637f",
          "sha1": "5d46ca519160ebdf568dba357ec3a0fa4247d3e8",
          "md5": "4142a1d066db8c2c9cbba0aa742104a8"
        }
      ]
    }
  ]
}
