{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-smoothstreaming",
    "version": "1.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-smoothstreaming-1.5.0-rc01.aar",
          "url": "media3-exoplayer-smoothstreaming-1.5.0-rc01.aar",
          "size": 51041,
          "sha512": "e380732a721f17f98e2c19bb66c241ce8e3cfa42dc389e5ac458de98b92a2dea597d6601272998abb3c66f38ce3156df94f46d8d3ee963e8bfd2623b6eea3208",
          "sha256": "6ec4c428a18993dd23e23755a96095b7e8b52937392977e7b01af01268e68061",
          "sha1": "b256998c42bc6898f14005c5bb6148f5aa45bb72",
          "md5": "16d0e40724c9b241bd2c0867a80c6d2d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-smoothstreaming-1.5.0-rc01.aar",
          "url": "media3-exoplayer-smoothstreaming-1.5.0-rc01.aar",
          "size": 51041,
          "sha512": "e380732a721f17f98e2c19bb66c241ce8e3cfa42dc389e5ac458de98b92a2dea597d6601272998abb3c66f38ce3156df94f46d8d3ee963e8bfd2623b6eea3208",
          "sha256": "6ec4c428a18993dd23e23755a96095b7e8b52937392977e7b01af01268e68061",
          "sha1": "b256998c42bc6898f14005c5bb6148f5aa45bb72",
          "md5": "16d0e40724c9b241bd2c0867a80c6d2d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-smoothstreaming-1.5.0-rc01-sources.jar",
          "url": "media3-exoplayer-smoothstreaming-1.5.0-rc01-sources.jar",
          "size": 30458,
          "sha512": "982967a7e4ab2816162a0c355cc517619ea0596f28961c4771ad221fa0e8926f3e8ed8a594a082e103d2879f15c5009892b39ece11dfba0f86f06ddd8c6ddf73",
          "sha256": "ce8d8b3ea8487be0052536da84f1aca005c210af7dc3953ab411f65822481e61",
          "sha1": "ca6fd6f520de21244e927fef260cc233856fa630",
          "md5": "376a6e2377252ac2cceb836b37949bb2"
        }
      ]
    }
  ]
}
