{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive-navigation3/1.0.0-alpha03/adaptive-navigation3-1.0.0-alpha03.module",
    "group": "androidx.compose.material3.adaptive",
    "module": "adaptive-navigation3",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14257682"
    }
  },
  "variants": [
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation3-linuxx64StubsMain-1.0.0-alpha03.klib",
          "url": "adaptive-navigation3-linuxx64stubs-1.0.0-alpha03.klib",
          "size": 59636,
          "sha512": "e9f31c72d570bd1cd500ac685918362ac9b35970748ed04969f65753bc4d72e4af4b247fbe289ec0c2f60644a8bd04586670d926103a189c57cf7a999b3d0020",
          "sha256": "f5127c0e41d1c07959954a316b43cad91753954deb58efa3c3b4438cf104e5ba",
          "sha1": "7f4e14585e1b1e8f55e25128217087e314889cf7",
          "md5": "99e00dc40f2e9d06db228d4600738ec1"
        }
      ]
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "adaptive-navigation3-linuxx64stubs-1.0.0-alpha03-sources.jar",
          "url": "adaptive-navigation3-linuxx64stubs-1.0.0-alpha03-sources.jar",
          "size": 14290,
          "sha512": "9256b6d58afb0ce5df5e6d551c7a0ecb5b3255642dbfdcbc0c179e5b765f837101ce9ae28e5aadc84740f7f68e4e61c75710f26595ff70b2d242458de16262fc",
          "sha256": "d911c2f7a15df70247ccb58d4c8e73c5a7e9bd0424e79524558a576de11a1dd7",
          "sha1": "0f2c0ba7535e870a855b953768f23ef202bd7b08",
          "md5": "d78ad95a69489e7874f20f8e03af73e3"
        }
      ]
    }
  ]
}