{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-video",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.0-alpha06.aar",
          "url": "camera-video-1.3.0-alpha06.aar",
          "size": 331318,
          "sha512": "c7f83061d73803eec1cfadf072ed5d38f8dae50b77f3425c8e5ccd774252ca2859caf72f0dfa2cb4cabae9b11f681a5aa3049463314961d8f727f666553307d1",
          "sha256": "a0665c18cffb4ae6b1db2449be2fe0e13c7bc64cd06a66bb56d7c46dbdd57392",
          "sha1": "e0f4a7f93f5bb1a191c2179d0d8d137a04b1c8ce",
          "md5": "3f2cff9fde32d2552303848694218603"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.0-alpha06.aar",
          "url": "camera-video-1.3.0-alpha06.aar",
          "size": 331318,
          "sha512": "c7f83061d73803eec1cfadf072ed5d38f8dae50b77f3425c8e5ccd774252ca2859caf72f0dfa2cb4cabae9b11f681a5aa3049463314961d8f727f666553307d1",
          "sha256": "a0665c18cffb4ae6b1db2449be2fe0e13c7bc64cd06a66bb56d7c46dbdd57392",
          "sha1": "e0f4a7f93f5bb1a191c2179d0d8d137a04b1c8ce",
          "md5": "3f2cff9fde32d2552303848694218603"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-viewfinder",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.3.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "camera-video-1.3.0-alpha06-sources.jar",
          "url": "camera-video-1.3.0-alpha06-sources.jar",
          "size": 239723,
          "sha512": "eed905d5cf33a1b7df10953cedcff2a2067e5312553f4357377817dcbcd80e22159ba2f26d61a576c2d6655c8c61d16a17d1d5655c83612b3acaa9651dc76915",
          "sha256": "f33729fa7f3084e4179bd162ba68528825af6d59dd574009650103e452467e92",
          "sha1": "fe132ef297fcc30b144153af9b9a15d759410bd2",
          "md5": "1a0599a5c2173b60bc8866b098dbfe9e"
        }
      ]
    }
  ]
}