{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/1.9.0-rc01/annotation-1.9.0-rc01.module",
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.9.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation.klib",
          "url": "annotation-watchosdevicearm64-1.9.0-rc01.klib",
          "size": 22773,
          "sha512": "3f9b665e1ca88694a8f44c3d98ad89e26184bd823e1b84510c14f045282d5ec0cc81353d8ac0a1378ce4e6a764b59e26b97423c39791f48f98278c14c72318e7",
          "sha256": "e479ed9453995975ede70b79f97a096fdb9adf044372086fb6da1e6d09a02469",
          "sha1": "488cdfdb21015404641a736b266967c9179e5670",
          "md5": "30a4ca3a840f10a048c5db74eb20f3e0"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "annotation-watchosdevicearm64-1.9.0-rc01-sources.jar",
          "url": "annotation-watchosdevicearm64-1.9.0-rc01-sources.jar",
          "size": 29195,
          "sha512": "e22aaf94c3233f50976e2de81bc79584bac8f067c661f771c9877410f9a0e0d75f98dc07578dab900db32b7ec48c1ebf9b9fbc3c5a8d70fa31879a83bd17ee32",
          "sha256": "a4c494907e7a51f59f371edfff1d0563785de655aab033efba4e67511090aa57",
          "sha1": "c7df6906c51cc706b45eed1fb71dcf008d9cc246",
          "md5": "1537702b6199e5b48e981f04b48329dd"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-watchosdevicearm64-1.9.0-rc01-metadata.jar",
          "url": "annotation-watchosdevicearm64-1.9.0-rc01-metadata.jar",
          "size": 4410,
          "sha512": "a0a7ba7851500dcb3c56aabce38b8b28af28cc15ac3fd5309bfaa1451fbd46013e05b80f3d354da6778693446781033b50dfd78983254e66b9e954c69b8a29e2",
          "sha256": "39a5c38f5e98e41a3c64f1b604ca19756c6ba59dc81b848adbad4ef3db7e8601",
          "sha1": "d4c14d03c73e28660f8bf4b4948affb05de4e5b8",
          "md5": "e61bbe977a3b9062cde5d440943589bb"
        }
      ]
    }
  ]
}