{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear-input-testing",
    "version": "1.0.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "6953474"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear",
          "module": "wear-input",
          "version": {
            "requires": "1.0.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "wear-input-testing-1.0.0-rc01.aar",
          "url": "wear-input-testing-1.0.0-rc01.aar",
          "size": 3709,
          "sha512": "7c41d12d8ad7ab56fca15a1ea06b6dad0a8f966acfc0d7ae0aa6b9c6104da0546f7db611cc7a95848e3c4dcaacd88134222d7f14e34fdfae4980c35517398249",
          "sha256": "c9b55b0ed346abf9f5d3882a85331cb2af4ee8bce45a022d1f4047a089acd06e",
          "sha1": "9c20e4b20cfa044ddb0e91f7976627df1b8377c1",
          "md5": "467b53cf5011c693178bec6fe9b7f26f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.wear",
          "module": "wear-input",
          "version": {
            "requires": "1.0.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "wear-input-testing-1.0.0-rc01.aar",
          "url": "wear-input-testing-1.0.0-rc01.aar",
          "size": 3709,
          "sha512": "7c41d12d8ad7ab56fca15a1ea06b6dad0a8f966acfc0d7ae0aa6b9c6104da0546f7db611cc7a95848e3c4dcaacd88134222d7f14e34fdfae4980c35517398249",
          "sha256": "c9b55b0ed346abf9f5d3882a85331cb2af4ee8bce45a022d1f4047a089acd06e",
          "sha1": "9c20e4b20cfa044ddb0e91f7976627df1b8377c1",
          "md5": "467b53cf5011c693178bec6fe9b7f26f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-input-testing-1.0.0-rc01-sources.jar",
          "url": "wear-input-testing-1.0.0-rc01-sources.jar",
          "size": 2530,
          "sha512": "39616b6b626b2e9c1d7f90d4957e2528619446b5e7dcb5b8c3128a5dc392672caac26418cbdd7d9874b4c76fbff56f16ef9de1240053298093b98c0bdc01f4da",
          "sha256": "ed83a08f588cf2450436f2943c794b4c24d443330b90036fae7e54534ec1a8e4",
          "sha1": "8f7830056502bf35b4ad735365627579fb03bcab",
          "md5": "664fea73cdd18df42a9b566a9ce53904"
        }
      ]
    }
  ]
}
