{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive-navigation/1.3.0-alpha03/adaptive-navigation-1.3.0-alpha03.module",
    "group": "androidx.compose.material3.adaptive",
    "module": "adaptive-navigation",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14347027"
    }
  },
  "variants": [
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation-jvmstubs-1.3.0-alpha03.jar",
          "url": "adaptive-navigation-jvmstubs-1.3.0-alpha03.jar",
          "size": 25920,
          "sha512": "6fb7859698eaff6c2afa8677ee2457e6a1ca76bccc9d88485b27dcbad234e228cf0abcab8f2db3e43694fadcb8dbde7ae0acb8fab37e66531fabd1a41b3489a2",
          "sha256": "7c8d432179ec85af63ff4a06c92a8b6eed8e9f737a5c973fc66636a58fcf13bc",
          "sha1": "ad1104d54bd015ca0b18c457897af1749c8fa373",
          "md5": "f729344f9aee0be49368cc853d2e43d8"
        }
      ]
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation-jvmstubs-1.3.0-alpha03.jar",
          "url": "adaptive-navigation-jvmstubs-1.3.0-alpha03.jar",
          "size": 25920,
          "sha512": "6fb7859698eaff6c2afa8677ee2457e6a1ca76bccc9d88485b27dcbad234e228cf0abcab8f2db3e43694fadcb8dbde7ae0acb8fab37e66531fabd1a41b3489a2",
          "sha256": "7c8d432179ec85af63ff4a06c92a8b6eed8e9f737a5c973fc66636a58fcf13bc",
          "sha1": "ad1104d54bd015ca0b18c457897af1749c8fa373",
          "md5": "f729344f9aee0be49368cc853d2e43d8"
        }
      ]
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation-jvmstubs-1.3.0-alpha03-sources.jar",
          "url": "adaptive-navigation-jvmstubs-1.3.0-alpha03-sources.jar",
          "size": 11572,
          "sha512": "5a62fd10d31b2875e42b237479b68458e769ac0eea9fcdb8aa34ecca1ba84c85a428c92adcc87bf862e81b643c1b476d3fa54b3fe7d2493ac318eda0bf1ee0d3",
          "sha256": "6f42e2bd10d0be1fe8807a2a209a50816b1475325cee4085d36c9c8a46fa68f0",
          "sha1": "852f68c758985ecbb02c1dee959a845c70717528",
          "md5": "a9a8d61230c6fe62eb756f6f66d8ad9b"
        }
      ]
    }
  ]
}