{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-navigation",
    "version": "1.8.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13094998"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-navigation-1.8.0-beta03-sources.jar",
          "url": "material-navigation-1.8.0-beta03-sources.jar",
          "size": 13417,
          "sha512": "4ed6da3dd0c92399ad42e68e5e1e475b8f876d2ca717f6f12c768ec106b560b18bf61eff892cd133490d633ed3634a49c7282bd75f359dc11b08f40e9c352601",
          "sha256": "c2eb6df038504f3c341194d0786234774b2c29563bea59e5187845ae7a4add62",
          "sha1": "817e70d4600ed66506cdf93df6eca7017919daaa",
          "md5": "097d112c3d99235ab2b118515499f7ce"
        },
        {
          "name": "material-navigation-1.8.0-beta03-samples-sources.jar",
          "url": "material-navigation-1.8.0-beta03-samples-sources.jar",
          "size": 6646,
          "sha512": "19065b921bd2b99ca5161a72ffd483ff87ae1da226ad013e8590c0fc17cccbb88cc2bf66773f20a8d995a5d4d5fb63675c97b1806f954edaa8be69c8c7464e88",
          "sha256": "db8b908a7295ed9b110f7aa2a583901f8ce16d2bfa9fc61d94948e502cb23d7e",
          "sha1": "cf669d4bd13d971a8ebd84ef5cdfbb24b4cfa4d2",
          "md5": "915a2445fd6f01b928ca287109946e38"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-navigation-1.8.0-beta03.aar",
          "url": "material-navigation-1.8.0-beta03.aar",
          "size": 56515,
          "sha512": "7572e698199aa4ab74327b93da66b490e6a03ecdc1b070bbe1338397b77e81d28a1e7659f5bcd687a883019658a13e9da2303ae3ea1dab006a4bc4c150ddf11c",
          "sha256": "c8bea96bf7af47ef1c9df0c5dcfd2637b8d2857f555d55f61368013dcc3b7f3b",
          "sha1": "08aff3af790cd548c68fb7bf48641b785f0ae9cf",
          "md5": "9a7c5a1ad5200e4df04f6284c80fe0d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.8.0-beta03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "material-navigation-1.8.0-beta03.aar",
          "url": "material-navigation-1.8.0-beta03.aar",
          "size": 56515,
          "sha512": "7572e698199aa4ab74327b93da66b490e6a03ecdc1b070bbe1338397b77e81d28a1e7659f5bcd687a883019658a13e9da2303ae3ea1dab006a4bc4c150ddf11c",
          "sha256": "c8bea96bf7af47ef1c9df0c5dcfd2637b8d2857f555d55f61368013dcc3b7f3b",
          "sha1": "08aff3af790cd548c68fb7bf48641b785f0ae9cf",
          "md5": "9a7c5a1ad5200e4df04f6284c80fe0d4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "material-navigation-1.8.0-beta03-versionMetadata.json",
          "url": "material-navigation-1.8.0-beta03-versionMetadata.json",
          "size": 3671,
          "sha512": "d70494df5a802841dae3c46f6df1bd16438cf954a6ec9edbfe476242bcf34c49c383ab5f1585c8d0f19a95ee5eb268426259fb92bab1d4e9d557a49f8ccc2110",
          "sha256": "17547ef45df6715a84115d23f2b0858629e0fc5b7f38ba0d258d30ceaa9143ba",
          "sha1": "6d0965222349651a313bde7c76f7fa17b586d323",
          "md5": "e68d8d58dd405501301798de0a25c71e"
        }
      ]
    }
  ]
}