{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-graphics/1.7.0-alpha01/animation-graphics-1.7.0-alpha01.module",
    "group": "androidx.compose.animation",
    "module": "animation-graphics",
    "version": "1.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-desktop-1.7.0-alpha01.jar",
          "url": "animation-graphics-desktop-1.7.0-alpha01.jar",
          "size": 73440,
          "sha512": "f26ec03feaaba031750825fe12a8e3cfbfc4991afc35e044ba7e743a95ad2c2a643465964b6141f64f85ee190d0b9381a8c73f1c16fd1e254361c7bc7701d6ac",
          "sha256": "d4f0d182b6151e15f28db5a9e59b341a8a30a38c5a5bca1587e9dd8ae6ac7451",
          "sha1": "587c97fae91749af6eae20223012156e29f9fc09",
          "md5": "f6685b5dfab938f606b9d1c4841095ec"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-desktop-1.7.0-alpha01.jar",
          "url": "animation-graphics-desktop-1.7.0-alpha01.jar",
          "size": 73440,
          "sha512": "f26ec03feaaba031750825fe12a8e3cfbfc4991afc35e044ba7e743a95ad2c2a643465964b6141f64f85ee190d0b9381a8c73f1c16fd1e254361c7bc7701d6ac",
          "sha256": "d4f0d182b6151e15f28db5a9e59b341a8a30a38c5a5bca1587e9dd8ae6ac7451",
          "sha1": "587c97fae91749af6eae20223012156e29f9fc09",
          "md5": "f6685b5dfab938f606b9d1c4841095ec"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.7.0-alpha01"
          },
          "reason": "animation-graphics is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-desktop-1.7.0-alpha01-sources.jar",
          "url": "animation-graphics-desktop-1.7.0-alpha01-sources.jar",
          "size": 9743,
          "sha512": "e51ab59a96d3cd8affce7f5e79935761954c4bd78f9f6afb88d4f887cdbf78a8fbf44832a1d4e2d18c90228a400bfc035a61ef7583dd07f1641c916abd8fae8f",
          "sha256": "33c0a487df0c077a095a31c1c2046bca6101ff80d13cdfe6025d6c32c061e437",
          "sha1": "55064314551e8b36116da62d928f86ec439af754",
          "md5": "8be283f5e12b9250962dc406b4903e28"
        }
      ]
    }
  ]
}