{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.5.0-beta01/collection-1.5.0-beta01.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12750671"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "collection-wasm-js-1.5.0-beta01.klib",
          "url": "collection-wasm-js-1.5.0-beta01.klib",
          "size": 987659,
          "sha512": "e5da8709e1cdcbc80d68d972b6086e33d53220768ac688ccb7d7820ef3ef999fb643603339c8c5825f29f43cd1497294e81b8e42e8289f96cdd358f85da6a2bb",
          "sha256": "36a3e2d597d32906129925efaaec85eb0d33067ba12e5f161fc5a96243a3ace8",
          "sha1": "131d7d34df5f49a22835c351be87807a9991c0d4",
          "md5": "f1416a1a0a3219dc56fea2ec2b41226f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "collection-wasm-js-1.5.0-beta01.klib",
          "url": "collection-wasm-js-1.5.0-beta01.klib",
          "size": 987659,
          "sha512": "e5da8709e1cdcbc80d68d972b6086e33d53220768ac688ccb7d7820ef3ef999fb643603339c8c5825f29f43cd1497294e81b8e42e8289f96cdd358f85da6a2bb",
          "sha256": "36a3e2d597d32906129925efaaec85eb0d33067ba12e5f161fc5a96243a3ace8",
          "sha1": "131d7d34df5f49a22835c351be87807a9991c0d4",
          "md5": "f1416a1a0a3219dc56fea2ec2b41226f"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-wasm-js-1.5.0-beta01-sources.jar",
          "url": "collection-wasm-js-1.5.0-beta01-sources.jar",
          "size": 281652,
          "sha512": "b476a020b188277b1eace0d6eaf28cb172129fe6d392c7e098737711b4c8eed234e4bfed2107bfee1d99aff5f985e1a13380014cde7707f77d1d129f9a23cec9",
          "sha256": "5d8b6ab71f433102099e7dfdfc1ba36427ccfc00d0294fa859e45d2519985bc3",
          "sha1": "fc714cfbe997d5454bb69aaffe64cd31a9e8ec0d",
          "md5": "1774141a0f729fceeb8adff8642ca301"
        }
      ]
    }
  ]
}