{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-junit4",
    "version": "1.2.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-1.2.0-beta02.aar",
          "url": "ui-test-junit4-1.2.0-beta02.aar",
          "size": 140438,
          "sha512": "86d2a0357e5daaf0e60dc7596723c9d39de25d9808d06f9cc282d1677d214cb4dab9ec7626040201b54ed7041ad30cee149dd0bebe96e323d74533f2a8c1f60e",
          "sha256": "92ee787f951c3dec6bc1434c9bfcaa15dd6887943acffd8e630eb71cddb90fdb",
          "sha1": "8d23cd147aeb8006bc5dec8e69f1baafb436d652",
          "md5": "570666d96a43c05ce9f2b20f1ff15acf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.2.0-beta02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-idling-resource",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-1.2.0-beta02.aar",
          "url": "ui-test-junit4-1.2.0-beta02.aar",
          "size": 140438,
          "sha512": "86d2a0357e5daaf0e60dc7596723c9d39de25d9808d06f9cc282d1677d214cb4dab9ec7626040201b54ed7041ad30cee149dd0bebe96e323d74533f2a8c1f60e",
          "sha256": "92ee787f951c3dec6bc1434c9bfcaa15dd6887943acffd8e630eb71cddb90fdb",
          "sha1": "8d23cd147aeb8006bc5dec8e69f1baafb436d652",
          "md5": "570666d96a43c05ce9f2b20f1ff15acf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-junit4-1.2.0-beta02-sources.jar",
          "url": "ui-test-junit4-1.2.0-beta02-sources.jar",
          "size": 39354,
          "sha512": "102b3246e49e58f09dd618893f640aabb3001611cfa4c4bb94218311ea024290daafe7cfc9e3c82a0212f9b22f7f656db08f1aea1f55e691e805150fae82ee00",
          "sha256": "6f2103edb66ce1f95d810193ae056888ddb3a534af2205bdc64f53b565044447",
          "sha1": "31a3feb90455b459e6cb3d6b7af466799e16fbf8",
          "md5": "47212790fc21076cf0da872d105a2c36"
        }
      ]
    }
  ]
}