{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-multiprocess",
    "version": "2.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7139158"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-multiprocess-2.7.0-alpha01.aar",
          "url": "work-multiprocess-2.7.0-alpha01.aar",
          "size": 55933,
          "sha512": "91d9cd7c077b4570075412283f4ba6f0f3d3452f14bfeaba0176e1ea8c4c511b4c5b631d077b4eecf3beaf80cbe6c7d363a05dac6ae5b22833f15b54242bb7bf",
          "sha256": "0c5ccddc6c5e0e6d0c09255b9b3379b9f650c5f1fccc5b513eda146692114710",
          "sha1": "ca389cbce62afde01b82d33688f5b98e983ff5ae",
          "md5": "f3388d4140a86bc5c43dbc72442b91d3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-multiprocess-2.7.0-alpha01.aar",
          "url": "work-multiprocess-2.7.0-alpha01.aar",
          "size": 55933,
          "sha512": "91d9cd7c077b4570075412283f4ba6f0f3d3452f14bfeaba0176e1ea8c4c511b4c5b631d077b4eecf3beaf80cbe6c7d363a05dac6ae5b22833f15b54242bb7bf",
          "sha256": "0c5ccddc6c5e0e6d0c09255b9b3379b9f650c5f1fccc5b513eda146692114710",
          "sha1": "ca389cbce62afde01b82d33688f5b98e983ff5ae",
          "md5": "f3388d4140a86bc5c43dbc72442b91d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-multiprocess-2.7.0-alpha01-sources.jar",
          "url": "work-multiprocess-2.7.0-alpha01-sources.jar",
          "size": 23999,
          "sha512": "1340987beddb995464e9557da697629e30540d84a2997766795f1851a21ded8121b44dcab7a52da0592cb05f30c41fdc3bfba895f540462895f8faf8e0a57117",
          "sha256": "dcd77297f70aeef29b5dda831777eb2ce5f758b2ae70af27a1a032f5f4270d81",
          "sha1": "4d5fc64ded02cd921b1c4ae188505bf120d1d54a",
          "md5": "d8538c4b5447f74b96686aa69b40b1bd"
        }
      ]
    }
  ]
}
