{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-runtime-testing/2.9.0-alpha05/lifecycle-runtime-testing-2.9.0-alpha05.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-runtime-testing",
    "version": "2.9.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing.klib",
          "url": "lifecycle-runtime-testing-linuxarm64-2.9.0-alpha05.klib",
          "size": 13554,
          "sha512": "9fe3743552fc3b4b14f21b678e512721ef4ee874d3b49694a0f3cff29ea2d4a0089360916a3b2f10644474404ba4da738e3d2a81514c6e246d7d715bdd484c37",
          "sha256": "e075946bce856fdca0a6019413f2b783a77bd798fa29cf1542120e181bb14c43",
          "sha1": "8341d58bd494e2d7e37dd428fac4cd531e32a123",
          "md5": "163ff7855a57bfb52f869f87e31af571"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha05"
          },
          "reason": "lifecycle-runtime-testing is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-runtime-testing-linuxarm64-2.9.0-alpha05-sources.jar",
          "url": "lifecycle-runtime-testing-linuxarm64-2.9.0-alpha05-sources.jar",
          "size": 6454,
          "sha512": "948193d20403ad6cec6108e9ac17c6ef76a59c4ca1e9e176481fb70be24238215776f95a6a2f219f9bffe97e8bd5d8fdf5f9e4f0bb7a41c84432b9e47287adb8",
          "sha256": "d18958a8311fb69cdb39783793ec7b2f28afecee8041b995b339c5216163f44f",
          "sha1": "6b66699dfb257cfe7296048784fd72da84f27f63",
          "md5": "8d096ae50c9371283d344d8f1b013023"
        }
      ]
    }
  ]
}