{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6824694"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.5.0-alpha03.aar",
          "url": "core-1.5.0-alpha03.aar",
          "size": 808230,
          "sha512": "411a0787403f55714ce6dc4086b1ff42a6f89a9e3a4828178729cc3aec0f57bdc4fc400ba09f6979a8d25a9108f80e16c6c043ade342afc5e736c087e566a704",
          "sha256": "cacd31aa9d00c13713cce5e942f3a90be8807da4054a0486f3e75c2c442af357",
          "sha1": "47d9ae7301c7b6d7110b7f6c2b7cc761582bdc2b",
          "md5": "e1ddaa8fb3a132ddf91740f7cb5482db"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.5.0-alpha03.aar",
          "url": "core-1.5.0-alpha03.aar",
          "size": 808230,
          "sha512": "411a0787403f55714ce6dc4086b1ff42a6f89a9e3a4828178729cc3aec0f57bdc4fc400ba09f6979a8d25a9108f80e16c6c043ade342afc5e736c087e566a704",
          "sha256": "cacd31aa9d00c13713cce5e942f3a90be8807da4054a0486f3e75c2c442af357",
          "sha1": "47d9ae7301c7b6d7110b7f6c2b7cc761582bdc2b",
          "md5": "e1ddaa8fb3a132ddf91740f7cb5482db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.5.0-alpha03-sources.jar",
          "url": "core-1.5.0-alpha03-sources.jar",
          "size": 682227,
          "sha512": "3b7672354e49c37008ade28e7b0ebcb3251efa7ae6783e400c75e033ad746af00919a4fdcd14044aaabc08cfaa1b6de2457f0cd0c2bc52b0d31461ea4fb183fe",
          "sha256": "1a3ed3a5e7c593e8245ff8eae0ded61aea468a1232fe4b06048cee0abed7f35b",
          "sha1": "ff6a4b3b289dcef3c7d7c13d005d483e0a395a5e",
          "md5": "4c8bd2c2c32151d483a136ceea2bf390"
        }
      ]
    }
  ]
}
