{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-test-junit4-accessibility/1.8.0/ui-test-junit4-accessibility-1.8.0.module",
    "group": "androidx.compose.ui",
    "module": "ui-test-junit4-accessibility",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13362296"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.apps.common.testing.accessibility.framework",
          "module": "accessibility-test-framework",
          "version": {
            "requires": "4.1.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-accessibility.aar",
          "url": "ui-test-junit4-accessibility-android-1.8.0.aar",
          "size": 9780,
          "sha512": "bf0fe0f771ebd0778056e8a316d9e3ce39e92cb9f54c9a53fbf771f6d2266817a15a75c7ea65ee53249e20b9ffc9804e199a033bfd4e2a5f583b50a2cb4cca1b",
          "sha256": "f3010a60a79163403fe54372a34c1a152a81a948bbe7338a1fceaaf569ed25d7",
          "sha1": "b69119348402fac2c0372b32be61a6d6fd606f65",
          "md5": "25de3904bef9c7dcacc8bfdb0b155973"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.android.apps.common.testing.accessibility.framework",
          "module": "accessibility-test-framework",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-accessibility.aar",
          "url": "ui-test-junit4-accessibility-android-1.8.0.aar",
          "size": 9780,
          "sha512": "bf0fe0f771ebd0778056e8a316d9e3ce39e92cb9f54c9a53fbf771f6d2266817a15a75c7ea65ee53249e20b9ffc9804e199a033bfd4e2a5f583b50a2cb4cca1b",
          "sha256": "f3010a60a79163403fe54372a34c1a152a81a948bbe7338a1fceaaf569ed25d7",
          "sha1": "b69119348402fac2c0372b32be61a6d6fd606f65",
          "md5": "25de3904bef9c7dcacc8bfdb0b155973"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.8.0"
          },
          "reason": "ui-test-junit4-accessibility is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-accessibility-android-1.8.0-sources.jar",
          "url": "ui-test-junit4-accessibility-android-1.8.0-sources.jar",
          "size": 8280,
          "sha512": "96d214232b4c6edc33698432271e8d45d841031f67e07ade3e377b64b2a16b473d5afbbb036e058be1ea794bc283359c6c452d530eec9565798fbf693183efb5",
          "sha256": "dec8edec34d20b964a81e4a0e3fb663d60232f7719915bd00bf21b142cb43e2b",
          "sha1": "a7e25bffbef99028f31e56749940cc4a76d5689d",
          "md5": "4000496fb058dfee2a4e72125b51ffdb"
        },
        {
          "name": "ui-test-junit4-accessibility-1.8.0-samples-sources.jar",
          "url": "ui-test-junit4-accessibility-android-1.8.0-samples-sources.jar",
          "size": 6927,
          "sha512": "2f094e772f0039b640fc8c11cf6e16581a7eeb7818530ba1051c76bfa4bab539411dac780f1b7339455b393511de4fa866ed00b9b6b873c5a7ad717caea9ac5e",
          "sha256": "532ec3b951667e0cb2f66dc2b35e38a4c2b355f6b0daf8bc3c5c94142986b8b3",
          "sha1": "ca9757d1de0b647eb7bf10d57feb92eb224a4ed9",
          "md5": "9ae9a2164dceed36b9478df18c38f6b8"
        }
      ]
    }
  ]
}