{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata-samples",
    "version": "1.8.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13032818"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-samples-1.8.0-beta02-sources.jar",
          "url": "runtime-livedata-samples-1.8.0-beta02-sources.jar",
          "size": 6028,
          "sha512": "34901352103b4c33687cf395e63da5e6139f53fa8599953a2de9a08a8259002b3d5bdf644d7928453593c2ec08934fa8b2c142c1fbd1144fcc1f4ced5ca59819",
          "sha256": "5341c25c6bb8c4071066a64604889081f32aebd5ceae83caf9057da4fa409c94",
          "sha1": "1b76e5dcc49b2dec00bd4fc466703be8a9447466",
          "md5": "87aa5c2d830a837b78ac4e860b65f790"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-samples-1.8.0-beta02.aar",
          "url": "runtime-livedata-samples-1.8.0-beta02.aar",
          "size": 10566,
          "sha512": "8c64cc4f1478d14c51f243b3f17cfad353cda284fbdce56e94f159a89789f81b03c935ac04245b564bb1868b5d91fca941443c4253722651daa9c2db7b1d9043",
          "sha256": "622ba2b72f76c130e9e3814b9ff3bc69db2adb624b08ce439809803b060e4d4f",
          "sha1": "cb5d6782f277d1cfb59bc2b109d2d141dca1dafd",
          "md5": "985156f13c1f17daa98d054aebca6a69"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.8.0-beta02"
          },
          "reason": "runtime-livedata-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-samples-1.8.0-beta02.aar",
          "url": "runtime-livedata-samples-1.8.0-beta02.aar",
          "size": 10566,
          "sha512": "8c64cc4f1478d14c51f243b3f17cfad353cda284fbdce56e94f159a89789f81b03c935ac04245b564bb1868b5d91fca941443c4253722651daa9c2db7b1d9043",
          "sha256": "622ba2b72f76c130e9e3814b9ff3bc69db2adb624b08ce439809803b060e4d4f",
          "sha1": "cb5d6782f277d1cfb59bc2b109d2d141dca1dafd",
          "md5": "985156f13c1f17daa98d054aebca6a69"
        }
      ]
    }
  ]
}