{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava2",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-1.3.0.aar",
          "url": "runtime-rxjava2-1.3.0.aar",
          "size": 23066,
          "sha512": "022289412dd9de93f68521698a961872f4d0214d810ac66b689adc4701f9363ac9cba152f7559f9a6d15431198bf106ed709818e7cd6c2834198f045a1f72ce8",
          "sha256": "ccb76df47a1a99f19b002ebf271aef3654e3276c0f1a63b088dcd57df313d5c7",
          "sha1": "277c74adc46a6cc8f6397317e8dda0e013ae3346",
          "md5": "f752a3d8d77cef12f97982e5ec3d2fef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava2-1.3.0.aar",
          "url": "runtime-rxjava2-1.3.0.aar",
          "size": 23066,
          "sha512": "022289412dd9de93f68521698a961872f4d0214d810ac66b689adc4701f9363ac9cba152f7559f9a6d15431198bf106ed709818e7cd6c2834198f045a1f72ce8",
          "sha256": "ccb76df47a1a99f19b002ebf271aef3654e3276c0f1a63b088dcd57df313d5c7",
          "sha1": "277c74adc46a6cc8f6397317e8dda0e013ae3346",
          "md5": "f752a3d8d77cef12f97982e5ec3d2fef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-rxjava2-1.3.0-sources.jar",
          "url": "runtime-rxjava2-1.3.0-sources.jar",
          "size": 2227,
          "sha512": "4ccb09788677591ff07ba2857e2a2c680c1f438e549f8c15fb6cde63f0efe07876269ed4a1036aaa4385c7f0fa3c7f97df3cbb27862f6bd9bf6df625481cf14a",
          "sha256": "342468c598af52c3071cab1f42a632ed6a6865d7faf66c3fd6d346ef2223628d",
          "sha1": "6b1b6ccf1fab2c2026994d1dc69a2b9e9db8ddbe",
          "md5": "8ab41ef7a0d228255e99d085ba61f207"
        }
      ]
    }
  ]
}