{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3.adaptive",
    "module": "adaptive-samples",
    "version": "1.2.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13635419"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0-alpha07"
          },
          "reason": "adaptive-samples is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha07"
          },
          "reason": "adaptive-samples is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          },
          "reason": "adaptive-samples is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-samples-1.2.0-alpha07-sources.jar",
          "url": "adaptive-samples-1.2.0-alpha07-sources.jar",
          "size": 10594,
          "sha512": "47fdf5cb4d364de51bc08f60342f4de791144123422f63dc656e03ee6773cde63b2c5856af5692520f57c68c46e4ef2ffc2f44259fee7c1d1a20481b7c71c9eb",
          "sha256": "a1174154702c6b7a5deaf508919fb691bb4e2339841b989a1779229d3aaa21c4",
          "sha1": "a5663672b0ebf287e8d3111901539a387bf1b4f7",
          "md5": "5d3521ee51b6c8d68c607cefc722c2ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0-alpha07"
          },
          "reason": "adaptive-samples is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha07"
          },
          "reason": "adaptive-samples is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          },
          "reason": "adaptive-samples is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-samples-1.2.0-alpha07.aar",
          "url": "adaptive-samples-1.2.0-alpha07.aar",
          "size": 151094,
          "sha512": "1fa6445c671ca5d6de72ba5e124af4a87166ff7d382c9afffd5d1a90d7c20112bf1694874912e25456522708beb548128c15902a844bfba4a1aff42fc73d3826",
          "sha256": "82d834a328f6fcaa225f5f59e7e514f7f61b9c6a6a483ccceb0d412d7c17aa12",
          "sha1": "9f5bba3fe7462476dfd23ec045249396743ec135",
          "md5": "42cc6fddd4d95255b4430a93c30a5804"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-rc01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-alpha16"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.4.0-alpha16"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-rc01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.2.0-alpha07"
          },
          "reason": "adaptive-samples is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.2.0-alpha07"
          },
          "reason": "adaptive-samples is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          },
          "reason": "adaptive-samples is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "adaptive-samples-1.2.0-alpha07.aar",
          "url": "adaptive-samples-1.2.0-alpha07.aar",
          "size": 151094,
          "sha512": "1fa6445c671ca5d6de72ba5e124af4a87166ff7d382c9afffd5d1a90d7c20112bf1694874912e25456522708beb548128c15902a844bfba4a1aff42fc73d3826",
          "sha256": "82d834a328f6fcaa225f5f59e7e514f7f61b9c6a6a483ccceb0d412d7c17aa12",
          "sha1": "9f5bba3fe7462476dfd23ec045249396743ec135",
          "md5": "42cc6fddd4d95255b4430a93c30a5804"
        }
      ]
    }
  ]
}