{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-android-stubs",
    "version": "1.4.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-benchmark",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-inspection",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-android-stubs-1.4.0-beta02.aar",
          "url": "ui-android-stubs-1.4.0-beta02.aar",
          "size": 4935,
          "sha512": "106ec5263821044eae0d533f60493801e91ac84e7bf1db659c299c6918ddc8779904c7f906f20b98eee9d161e341fbcb9b85afe3fe2a9bceaae6f0252ecd3458",
          "sha256": "1b6754f5f79c10f939fc146a0125580702693c44a7f54bc39f052d72ca2e2648",
          "sha1": "51a8298d1b4902104f6dcae8f8916d013155cd97",
          "md5": "54ca9e025645faaaa78104c42f3ead5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-benchmark",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-inspection",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-android-stubs-1.4.0-beta02.aar",
          "url": "ui-android-stubs-1.4.0-beta02.aar",
          "size": 4935,
          "sha512": "106ec5263821044eae0d533f60493801e91ac84e7bf1db659c299c6918ddc8779904c7f906f20b98eee9d161e341fbcb9b85afe3fe2a9bceaae6f0252ecd3458",
          "sha256": "1b6754f5f79c10f939fc146a0125580702693c44a7f54bc39f052d72ca2e2648",
          "sha1": "51a8298d1b4902104f6dcae8f8916d013155cd97",
          "md5": "54ca9e025645faaaa78104c42f3ead5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-benchmark",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-inspection",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-samples",
          "version": {
            "requires": "1.4.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-android-stubs-1.4.0-beta02-sources.jar",
          "url": "ui-android-stubs-1.4.0-beta02-sources.jar",
          "size": 2642,
          "sha512": "387016f8941b5ca76da28a0486612b7b747d8c6f8cf6437e5083e02c5416df33eb7f26ed79637995dc87a0ac23bced6394dd26070c9021fd4e9875272c927708",
          "sha256": "e8ddbe100aae3a4f9af4e4009410c6319fe7c8fe58d789a40d664ef591215354",
          "sha1": "a3b89a1e562981ce83723020e19d981f36e7453c",
          "md5": "098f7d135e3edb765481242175fd833a"
        }
      ]
    }
  ]
}