{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-android-stubs",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-android-stubs-1.2.0.aar",
          "url": "ui-android-stubs-1.2.0.aar",
          "size": 4914,
          "sha512": "fc266d8fd8ee49b0673ff2c44a46546bb616d5dc34b1b99191ee82d1c3050a0be73a5f3092cc8f64e68dc7565b1bcce624e7ba7ef6ec5aecdc88aa9989b1a320",
          "sha256": "0fb97aef78f797927402afab3ebe3df98b322688db3ffd484bb64797e02dcfa6",
          "sha1": "b8f37d5079bc2f957387770a7a4bb128c0e10925",
          "md5": "690a67a0b0e328e5d9803cea2e2c7c4d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-android-stubs-1.2.0.aar",
          "url": "ui-android-stubs-1.2.0.aar",
          "size": 4914,
          "sha512": "fc266d8fd8ee49b0673ff2c44a46546bb616d5dc34b1b99191ee82d1c3050a0be73a5f3092cc8f64e68dc7565b1bcce624e7ba7ef6ec5aecdc88aa9989b1a320",
          "sha256": "0fb97aef78f797927402afab3ebe3df98b322688db3ffd484bb64797e02dcfa6",
          "sha1": "b8f37d5079bc2f957387770a7a4bb128c0e10925",
          "md5": "690a67a0b0e328e5d9803cea2e2c7c4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-android-stubs-1.2.0-sources.jar",
          "url": "ui-android-stubs-1.2.0-sources.jar",
          "size": 2648,
          "sha512": "4e9c0dfd282bc5b75b58bda5366010c13cba0cdd41124f5743a097cc4d11f26b2d51e88deec69618feb772577b895f429062bf01bd2036e3276f63264320ff3e",
          "sha256": "95889698b2b84782751708196f761c96ff36fc0d0da82f4a5a8fd64863fc6478",
          "sha1": "e039bb6759272bab2fe7f6b5185fb5ee02ee1397",
          "md5": "72901f8022a153c26bc184a8c2fc2f2f"
        }
      ]
    }
  ]
}