{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear-watchface-guava",
    "version": "1.0.0-alpha22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear",
          "module": "wear-watchface",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-watchface-guava-1.0.0-alpha22.aar",
          "url": "wear-watchface-guava-1.0.0-alpha22.aar",
          "size": 5085,
          "sha512": "55596a2d27912ec1e3dd44d13eb844eb52a3d3999a4da9da6b854f6ed2c8c10cb7e8fa002c005f338ac40063b4b972655f0fc28daacb179481335376fef4edf5",
          "sha256": "fcb30cf05ab4e014c828bad11441868dbfad01921b589064b53cf93c26c6c8de",
          "sha1": "692b6b9464dc13552334896a64aca93e10321c76",
          "md5": "fe25c44c6b8ff6e99a9453ed555bbcfd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.wear",
          "module": "wear-watchface",
          "version": {
            "requires": "1.0.0-alpha22"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-watchface-guava-1.0.0-alpha22.aar",
          "url": "wear-watchface-guava-1.0.0-alpha22.aar",
          "size": 5085,
          "sha512": "55596a2d27912ec1e3dd44d13eb844eb52a3d3999a4da9da6b854f6ed2c8c10cb7e8fa002c005f338ac40063b4b972655f0fc28daacb179481335376fef4edf5",
          "sha256": "fcb30cf05ab4e014c828bad11441868dbfad01921b589064b53cf93c26c6c8de",
          "sha1": "692b6b9464dc13552334896a64aca93e10321c76",
          "md5": "fe25c44c6b8ff6e99a9453ed555bbcfd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-watchface-guava-1.0.0-alpha22-sources.jar",
          "url": "wear-watchface-guava-1.0.0-alpha22-sources.jar",
          "size": 1600,
          "sha512": "1535b4310c81131e44faa795ec05f5fa28ca160f4be3aa15ef87d55845d0e5cb3b81fc2aeef2455d6ccb2e5903dfb9989f971c8a167efd6d565528c6104fa078",
          "sha256": "7b32c643bbd5323738aeadf51eda93abc05bdeb5e451f3cb8b89478b0d528252",
          "sha1": "dd16cbc8d6203f89fb1a4458fdf26e4367dbf4a9",
          "md5": "f4fbc3a63053cc72b02e4c42e3529f94"
        }
      ]
    }
  ]
}
