{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-editor-samples",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-editor-samples-1.1.0.aar",
          "url": "watchface-editor-samples-1.1.0.aar",
          "size": 144624,
          "sha512": "16d3d1624a1e53c24d3c48742b3d411e5d3132c3bdbee93262d999fd3875e3471016a5148022b58462900b2cce39c672451d8e7e461160817a75187a63ebe647",
          "sha256": "29c0e1f0afffd832ee3e0d7158b59786f572d13ead06de31dcfbbc19261f1e32",
          "sha1": "ff5b211c9f20cee51812938b209945b5934e086d",
          "md5": "a1137916be4761c09d67f4bdb02a0887"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-editor-samples-1.1.0.aar",
          "url": "watchface-editor-samples-1.1.0.aar",
          "size": 144624,
          "sha512": "16d3d1624a1e53c24d3c48742b3d411e5d3132c3bdbee93262d999fd3875e3471016a5148022b58462900b2cce39c672451d8e7e461160817a75187a63ebe647",
          "sha256": "29c0e1f0afffd832ee3e0d7158b59786f572d13ead06de31dcfbbc19261f1e32",
          "sha1": "ff5b211c9f20cee51812938b209945b5934e086d",
          "md5": "a1137916be4761c09d67f4bdb02a0887"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "watchface-editor-samples-1.1.0-sources.jar",
          "url": "watchface-editor-samples-1.1.0-sources.jar",
          "size": 13250,
          "sha512": "97bf31ab09586dba2e8fcc0777e18f7f16058b1f4d64ef06e5d575afe40047a1d8fc0634dba0bdb863c2187cac0d6030c9f766c8e4c58bea177eada326cbc3a0",
          "sha256": "e0a377c6c2bb6ed2bef809278b686f3e6e10650b53c6511d585878ad80e782cb",
          "sha1": "2b57bc6135aafc2c79a3aef5e86a3fe1b22c49f9",
          "md5": "c701554b982cf6a4b941668b7f1c2682"
        }
      ]
    }
  ]
}