{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-rxjava3",
    "version": "1.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0-beta02"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.0.0-beta02"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava3-1.0.0-beta02.aar",
          "url": "datastore-preferences-rxjava3-1.0.0-beta02.aar",
          "size": 14282,
          "sha512": "8043aee189d7de72e04221748d831d4cb40adf9eb21e10a0067813fe471f05d46bbf35c185792e3cae471256ccdcad75d686a7706ac64be6e4fbac3347910f25",
          "sha256": "c7a2034ba41c3618033f3b8ffb532a5fc589f3bcc137cfb7694556370ad6da96",
          "sha1": "e53647f47a5331fe60e6fca825e701e073f27a36",
          "md5": "bc1f6a50514c01fab68ff625a9f8d7d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0-beta02"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.0.0-beta02"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx3",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava3-1.0.0-beta02.aar",
          "url": "datastore-preferences-rxjava3-1.0.0-beta02.aar",
          "size": 14282,
          "sha512": "8043aee189d7de72e04221748d831d4cb40adf9eb21e10a0067813fe471f05d46bbf35c185792e3cae471256ccdcad75d686a7706ac64be6e4fbac3347910f25",
          "sha256": "c7a2034ba41c3618033f3b8ffb532a5fc589f3bcc137cfb7694556370ad6da96",
          "sha1": "e53647f47a5331fe60e6fca825e701e073f27a36",
          "md5": "bc1f6a50514c01fab68ff625a9f8d7d6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datastore-preferences-rxjava3-1.0.0-beta02-sources.jar",
          "url": "datastore-preferences-rxjava3-1.0.0-beta02-sources.jar",
          "size": 5021,
          "sha512": "fc41cfa721f9e82281c7af64d51aa4b46b7561c82e35129f7116d05831ce063724a79836de1e5e7fa5deeb6fd705e604240f4d5abf24fe934526c01a23a05e39",
          "sha256": "a42fe7a579627ddad83bd773f3646fc449195d3534394bd95b7963d1fb842bf7",
          "sha1": "b49378a8921d6fc006d3b44cedf106399be61305",
          "md5": "d2d14997f1146ec82f6a3f663429a67a"
        }
      ]
    }
  ]
}
