{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-java",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "window-java-1.2.0-alpha02.aar",
          "url": "window-java-1.2.0-alpha02.aar",
          "size": 13809,
          "sha512": "969fcc077badbbfd418ce73638eb46c91e3996a8e85636bf8994f8c6154aea1449e83ff6d3efd8ec3058eae33e92cd211acf9e6fa782b3ce5e0d799ee3493fe6",
          "sha256": "b3a5343d9458ea0302fa2e080baf493ff29e0fc06b7267a9ada043280933e414",
          "sha1": "1e63441eadf18108ebb796fca0b613a3da75e8fc",
          "md5": "0e33d22e7982b3a0b478086e8ba112b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "window-java-1.2.0-alpha02.aar",
          "url": "window-java-1.2.0-alpha02.aar",
          "size": 13809,
          "sha512": "969fcc077badbbfd418ce73638eb46c91e3996a8e85636bf8994f8c6154aea1449e83ff6d3efd8ec3058eae33e92cd211acf9e6fa782b3ce5e0d799ee3493fe6",
          "sha256": "b3a5343d9458ea0302fa2e080baf493ff29e0fc06b7267a9ada043280933e414",
          "sha1": "1e63441eadf18108ebb796fca0b613a3da75e8fc",
          "md5": "0e33d22e7982b3a0b478086e8ba112b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "window-java-1.2.0-alpha02-sources.jar",
          "url": "window-java-1.2.0-alpha02-sources.jar",
          "size": 6272,
          "sha512": "0cd1b8261f86c32afb1e81c2d23ea109ad47cacca0b080a7193cdd90e9030b760526f4dc087afe5392caa8dc30b7a0240295091c811b767fed7741290fc4acd9",
          "sha256": "e45ce7ac80fb3bd4101cc8b6afe6a49d7fa3d7a91e162443741a6e491451df45",
          "sha1": "aa02aa0f03295677bd53fb2a2f977f8ffeb17735",
          "md5": "620d26110a934070d75047f45d9b066d"
        }
      ]
    }
  ]
}