{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-hls",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-exoplayer-hls-1.1.0.aar",
          "url": "media3-exoplayer-hls-1.1.0.aar",
          "size": 159344,
          "sha512": "d856285dced99e14e6787d7c3daa3e203dec1b50ee62add8090991f6c28ae2b74a4918b9c05d8067f9cf3a7625eb04082676d5dde59a8c258efe06290ce7058e",
          "sha256": "f6a0fa0d4b71550ebe7b3570a49f295eb865bce0bbc113318fd8ce6c4beaa619",
          "sha1": "757760a445c06f2f6b4e1083a49b8fbf48829a4c",
          "md5": "39e03c856cfbf3c0dae6bf66da77cfd6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-hls-1.1.0.aar",
          "url": "media3-exoplayer-hls-1.1.0.aar",
          "size": 159344,
          "sha512": "d856285dced99e14e6787d7c3daa3e203dec1b50ee62add8090991f6c28ae2b74a4918b9c05d8067f9cf3a7625eb04082676d5dde59a8c258efe06290ce7058e",
          "sha256": "f6a0fa0d4b71550ebe7b3570a49f295eb865bce0bbc113318fd8ce6c4beaa619",
          "sha1": "757760a445c06f2f6b4e1083a49b8fbf48829a4c",
          "md5": "39e03c856cfbf3c0dae6bf66da77cfd6"
        }
      ]
    },
    {
      "name": "sourcesElement",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-hls-1.1.0-sources.jar",
          "url": "media3-exoplayer-hls-1.1.0-sources.jar",
          "size": 118170,
          "sha512": "9af6113fb3a396f1faf16703e95314b1626bed7fb1f68d01130da2455b47eaf5c4343f09bfe4491a69def904d88eee9c7179e5d5ae318c1fe5b56bf85abecb32",
          "sha256": "f532337eee4aeee4b5a3dd2669be946c5579112b8ba840e172c7caed7dda5cd5",
          "sha1": "8770150d6b8b9f56a267e9c99e4403fba4cdf1cb",
          "md5": "6dcd83e7fc596f864d22fea75235180b"
        }
      ]
    }
  ]
}
