{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation3-runtime/1.0.0-alpha03/navigation3-runtime-1.0.0-alpha03.module",
    "group": "androidx.navigation3",
    "module": "navigation3-runtime",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13569325"
    }
  },
  "variants": [
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-jvmstubs-1.0.0-alpha03.jar",
          "url": "navigation3-runtime-jvmstubs-1.0.0-alpha03.jar",
          "size": 59061,
          "sha512": "3e3651f5f75d534348a476db70df5e9b09bf54d3c595af5c51b1adc94430b7fe7d3fa3b6ef9649f968e40f24d838b775eb7b33b3e33b5c136656d2e00ff195de",
          "sha256": "f808bde6ffba68e7447dd34bb42afc5ab15c46a17063e293dc18452b5d466850",
          "sha1": "6f371bf054eaa889352bb96a4574e4bb207e58ec",
          "md5": "3e85848989b0d78e2a3b48dd7a1f9837"
        }
      ]
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-jvmstubs-1.0.0-alpha03.jar",
          "url": "navigation3-runtime-jvmstubs-1.0.0-alpha03.jar",
          "size": 59061,
          "sha512": "3e3651f5f75d534348a476db70df5e9b09bf54d3c595af5c51b1adc94430b7fe7d3fa3b6ef9649f968e40f24d838b775eb7b33b3e33b5c136656d2e00ff195de",
          "sha256": "f808bde6ffba68e7447dd34bb42afc5ab15c46a17063e293dc18452b5d466850",
          "sha1": "6f371bf054eaa889352bb96a4574e4bb207e58ec",
          "md5": "3e85848989b0d78e2a3b48dd7a1f9837"
        }
      ]
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha03"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-jvmstubs-1.0.0-alpha03-sources.jar",
          "url": "navigation3-runtime-jvmstubs-1.0.0-alpha03-sources.jar",
          "size": 15111,
          "sha512": "4b86112acee2c60120e01397ae3915a869b0a106992d9c1d0707e03914432f9856c74a7ece255f2e13263947b5f2bb3ebb2144f662da083df3bca1a4bd30b26c",
          "sha256": "eea3b2d359f2ed9a0d7086c1ccaa5e1def4d467997448d18a59845abeb421632",
          "sha1": "a4028cc5165ea5b9dc191a2906efb2578da002f4",
          "md5": "90f94ed894e11925ce7104fd2791c07f"
        }
      ]
    }
  ]
}