{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent-testing/1.0.0-alpha07/navigationevent-testing-1.0.0-alpha07.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent-testing",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13969651"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-testing-tvosSimulatorArm64Main-1.0.0-alpha07.klib",
          "url": "navigationevent-testing-tvossimulatorarm64-1.0.0-alpha07.klib",
          "size": 15713,
          "sha512": "cb968e43a06a43ea034030dae6174db6e8aee842bdd09ac06b2f37daa8a702eff198bc4b1758dfc95e681484e45b453240f638f891c721c057eccee060d9ce78",
          "sha256": "196255dbea129b7cdd7c4cada342ea70d7466793007e9094356f1de9820a5f67",
          "sha1": "91045df0f13362538b64b0a04a3cf71e5ff1a6fc",
          "md5": "7d98762f501479d4f236b4cf10b211de"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-testing-tvossimulatorarm64-1.0.0-alpha07-sources.jar",
          "url": "navigationevent-testing-tvossimulatorarm64-1.0.0-alpha07-sources.jar",
          "size": 7750,
          "sha512": "00b1668da49862f759ac71c3d523670f09c3f6cc64c67da2196ee9a1d9342002f3ee0c8effac167ea8ef7a14e45ad1ab3d8127376a1e5a9a74c6a698b4c8cf5c",
          "sha256": "ed369caf8d603ff9c670d7bf4b2242410d697249b2557587c49355b38e976254",
          "sha1": "00603d01edec27feab0f49ddb2c620eebcb685be",
          "md5": "4d3f7e170e40362dba9ca00bede2cc54"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent-testing is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-testing-tvossimulatorarm64-1.0.0-alpha07-metadata.jar",
          "url": "navigationevent-testing-tvossimulatorarm64-1.0.0-alpha07-metadata.jar",
          "size": 4492,
          "sha512": "91283f18e42ae1010235d92f0e6ee6a3d75d042016bab6ce3f865a8d227b878f0f5cccd509fd548212ab38a8c6ef08b3a544842ef712e919509b2a0e8174f0f4",
          "sha256": "cc5823c9a2ad647bf1516894700150a96098b4829eb63879321ea325c2cfb1f9",
          "sha1": "fbb199e3028e86b256edc61d6c1b1c985d15c94d",
          "md5": "e464537f68712b5c60430de859958eb1"
        }
      ]
    }
  ]
}