{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.4.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.4.0-alpha04.aar",
          "url": "navigation-common-ktx-2.4.0-alpha04.aar",
          "size": 1754,
          "sha512": "2fd56994ae756a087033649e38552256906bee755cdf7201beb9f3c21471dcf6b4f08a3c1ab9e8c95e53520f40e1ef77a413d7cf7bc230b96e2808ed8312ad06",
          "sha256": "3908e3a5e11a2288adf756886b19f26c3c555b95a4e2833a691f53b35940dfcb",
          "sha1": "c3e771f32e6b9fd1c607449cb40c5cfc1de92015",
          "md5": "636f6704bfa6a7e248aca0d6f4468127"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.4.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.4.0-alpha04.aar",
          "url": "navigation-common-ktx-2.4.0-alpha04.aar",
          "size": 1754,
          "sha512": "2fd56994ae756a087033649e38552256906bee755cdf7201beb9f3c21471dcf6b4f08a3c1ab9e8c95e53520f40e1ef77a413d7cf7bc230b96e2808ed8312ad06",
          "sha256": "3908e3a5e11a2288adf756886b19f26c3c555b95a4e2833a691f53b35940dfcb",
          "sha1": "c3e771f32e6b9fd1c607449cb40c5cfc1de92015",
          "md5": "636f6704bfa6a7e248aca0d6f4468127"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.4.0-alpha04-sources.jar",
          "url": "navigation-common-ktx-2.4.0-alpha04-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
