{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core-samples",
    "version": "1.7.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-core-samples-1.7.7-sources.jar",
          "url": "material-icons-core-samples-1.7.7-sources.jar",
          "size": 1849,
          "sha512": "5e82b6fc611569270b0a77b159588b3d249a31627630b5e8a1eeb18b462eca347a9a9dfd07bac984a4b1b3df6d71fd490fda7a6f07995b5fcaaee4c2f038ec6c",
          "sha256": "262d79cf95faf69f89988b01d568d48b69742a95b0959b9238e2e797457938fa",
          "sha1": "578ff7394b718fb34c333c24bcfade35ccba41c5",
          "md5": "6dfd44933714f319df97b87cf801f994"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material-icons-core-samples-1.7.7.aar",
          "url": "material-icons-core-samples-1.7.7.aar",
          "size": 7389,
          "sha512": "9e17af1a26c3ef1722499c2ec5b054ddde4c37d7346de3e90bc84aa83072dc09042cb3e4c10d666c0de252a74b7f7af62f5c5c945c126b1c519c0172bf78b491",
          "sha256": "0dfd528a16338c372f8b34eb692070bcea5ba09e7503b3a8fb4329f46300e99e",
          "sha1": "dcaaf4ccb96b3e980582604d17881e642a8a454b",
          "md5": "14370520a487153f87fc1dcd91272b11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-samples-1.7.7.aar",
          "url": "material-icons-core-samples-1.7.7.aar",
          "size": 7389,
          "sha512": "9e17af1a26c3ef1722499c2ec5b054ddde4c37d7346de3e90bc84aa83072dc09042cb3e4c10d666c0de252a74b7f7af62f5c5c945c126b1c519c0172bf78b491",
          "sha256": "0dfd528a16338c372f8b34eb692070bcea5ba09e7503b3a8fb4329f46300e99e",
          "sha1": "dcaaf4ccb96b3e980582604d17881e642a8a454b",
          "md5": "14370520a487153f87fc1dcd91272b11"
        }
      ]
    }
  ]
}