{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-rxjava3",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava3-1.1.0-beta01.aar",
          "url": "datastore-rxjava3-1.1.0-beta01.aar",
          "size": 32353,
          "sha512": "bc89f9f1533847567ff9f20504969532c2bb30710ec7bcc1cb5432e88cb388408004873ffab8238213f42bece83fc423511003cf71925a331326b4039c01e100",
          "sha256": "ea51f3820122d9b18f9572d529118a2c589c733fd67d28d2332bf1d71d8089b8",
          "sha1": "1f97c9a3c6ebf7d28de6c7bbb4d45aec06819115",
          "md5": "255f75b0595957e34434f446a6fd7de2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx3",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava3-1.1.0-beta01.aar",
          "url": "datastore-rxjava3-1.1.0-beta01.aar",
          "size": 32353,
          "sha512": "bc89f9f1533847567ff9f20504969532c2bb30710ec7bcc1cb5432e88cb388408004873ffab8238213f42bece83fc423511003cf71925a331326b4039c01e100",
          "sha256": "ea51f3820122d9b18f9572d529118a2c589c733fd67d28d2332bf1d71d8089b8",
          "sha1": "1f97c9a3c6ebf7d28de6c7bbb4d45aec06819115",
          "md5": "255f75b0595957e34434f446a6fd7de2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava3-1.1.0-beta01-sources.jar",
          "url": "datastore-rxjava3-1.1.0-beta01-sources.jar",
          "size": 10008,
          "sha512": "ea8e92d155b1c9a85d6310f53bdee8fc7fc1a35524a10afcca7236fb1d009352b271f1ba94565bcc1382a13f8ec859109b176a515cb33d356f7e3ada0720b509",
          "sha256": "e7f2c200c99c12c49948e42dfa854ad9b5c9a299d1e50c9fe364029eef34d041",
          "sha1": "64ce832a5596e8725ce2933a6343d1b95bd0e153",
          "md5": "584cdfc8cf273edfb8d154c3f6a7f673"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "datastore-rxjava3 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava3-1.1.0-beta01-versionMetadata.json",
          "url": "datastore-rxjava3-1.1.0-beta01-versionMetadata.json",
          "size": 2661,
          "sha512": "915c97635205b79a41347a4c7bc2b728b8bebc46c75cb9e4a5aaa313a09c39f18b3089d3f74587cf0cc38a4570dd7511197a0160665ea115daa3c500f4f5866b",
          "sha256": "92d120f708e28825302cc7f7c88e138d54165b0a3f6515f28f21ae0218ab0e6f",
          "sha1": "8be08f2535dc0968e638d6c05374ecbae5092df4",
          "md5": "7945f988a725bea11e16e96ea5bbf8d6"
        }
      ]
    }
  ]
}