{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-graphics",
    "version": "1.1.0-beta04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-1.1.0-beta04.aar",
          "url": "animation-graphics-1.1.0-beta04.aar",
          "size": 102209,
          "sha512": "ba0fe19b209f526bc28150a2c4bb0d12c1c89d165116950fdf78656e2da801efffb305430d3b8e478af63e690f0452e028340959cba563fa34f70e3ae244429d",
          "sha256": "b54f375b014167b4bd8b9283d02ea7f7beb56d48a84e58de8fdf92e867a7570f",
          "sha1": "93ca9e90a974bc4fba3b3248274ef25c34651604",
          "md5": "3db884f895ff7d79168f27cb0147ea52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-1.1.0-beta04.aar",
          "url": "animation-graphics-1.1.0-beta04.aar",
          "size": 102209,
          "sha512": "ba0fe19b209f526bc28150a2c4bb0d12c1c89d165116950fdf78656e2da801efffb305430d3b8e478af63e690f0452e028340959cba563fa34f70e3ae244429d",
          "sha256": "b54f375b014167b4bd8b9283d02ea7f7beb56d48a84e58de8fdf92e867a7570f",
          "sha1": "93ca9e90a974bc4fba3b3248274ef25c34651604",
          "md5": "3db884f895ff7d79168f27cb0147ea52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-graphics-1.1.0-beta04-sources.jar",
          "url": "animation-graphics-1.1.0-beta04-sources.jar",
          "size": 19041,
          "sha512": "4851077df7d73b66e0d708518fa48209e09f1f3ee76b07c0c81b1e52355e4aec040d4a49287e369c85da486a86406e0f757f7c0e57b4ad79815e19d34eab996a",
          "sha256": "d02d01fff425567e1111032a8893fe6b8fe87fd1b3481f0b7e96042d880cd5ac",
          "sha1": "bf31b4d6673b593d148fb1b7f4e33850c7651ae3",
          "md5": "8e92782055986055bf508b3e16b20ef6"
        }
      ]
    }
  ]
}
