{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-data",
    "version": "1.2.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-data-1.2.0-alpha09.aar",
          "url": "watchface-data-1.2.0-alpha09.aar",
          "size": 268933,
          "sha512": "c34f1549e4c72d86555d2ef8ca2c842c7387cdc94dca3e70b986710188f7ef7be0b3ec4d11ee3fcced0ab92fe5786dbcf966a317205da8fc48c14557b31cc7a6",
          "sha256": "2011a57c34ea8917ba65374e4f93e8d4b6bd1936ea7f49d0441099b98bbe4e38",
          "sha1": "c9e28425f205c2a1c9419f71560e3004aebb37bc",
          "md5": "0304ebb44e174cfd94cb234c7f6dc927"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-data-1.2.0-alpha09.aar",
          "url": "watchface-data-1.2.0-alpha09.aar",
          "size": 268933,
          "sha512": "c34f1549e4c72d86555d2ef8ca2c842c7387cdc94dca3e70b986710188f7ef7be0b3ec4d11ee3fcced0ab92fe5786dbcf966a317205da8fc48c14557b31cc7a6",
          "sha256": "2011a57c34ea8917ba65374e4f93e8d4b6bd1936ea7f49d0441099b98bbe4e38",
          "sha1": "c9e28425f205c2a1c9419f71560e3004aebb37bc",
          "md5": "0304ebb44e174cfd94cb234c7f6dc927"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-data-1.2.0-alpha09-sources.jar",
          "url": "watchface-data-1.2.0-alpha09-sources.jar",
          "size": 75227,
          "sha512": "6b7d8f36f0f923356a8b34de6be7db982224d3db05e0edf72af8f162cabad4c132175902f8e76567414b00b5def0c39f3d43bf33d0189871ca311e02145483d1",
          "sha256": "12f8571f87f37813ad1fdf430b2ca0d37e35d96667a21281afa36079f808ff1c",
          "sha1": "6eea64f8cbdaee09cc2cd7fb38d3fea8e1aa6988",
          "md5": "d20d308e115894cf89ceae8bb8ad80e6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "watchface-data-1.2.0-alpha09-versionMetadata.json",
          "url": "watchface-data-1.2.0-alpha09-versionMetadata.json"
        }
      ]
    }
  ]
}