{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ui",
    "module": "ui-livedata",
    "version": "0.1.0-dev11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId:": "6470314"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-runtime",
          "version": {
            "requires": "0.1.0-dev11"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-livedata-0.1.0-dev11.aar",
          "url": "ui-livedata-0.1.0-dev11.aar",
          "size": 7487,
          "sha512": "01c39c131ad257a1d91386009795e7169781b276454e401871335c198c01f0ef1b7a6837a985222aadaf2facc216c48e5ea7f2d7f4ef5b2d35d58faf3b01b679",
          "sha256": "c42da5bece5757fbca93c4f7d3572926ceafb958861a700e4e68ee51821ba5e2",
          "sha1": "75a8a29b8f0ea11ea2e0f39b9de7b9662a79f9fe",
          "md5": "e8e501a42d3c52ccaa8e73fa645a2065"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose",
          "module": "compose-runtime",
          "version": {
            "requires": "0.1.0-dev11"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "androidx.ui",
          "module": "ui-core",
          "version": {
            "requires": "0.1.0-dev11"
          }
        }
      ],
      "files": [
        {
          "name": "ui-livedata-0.1.0-dev11.aar",
          "url": "ui-livedata-0.1.0-dev11.aar",
          "size": 7487,
          "sha512": "01c39c131ad257a1d91386009795e7169781b276454e401871335c198c01f0ef1b7a6837a985222aadaf2facc216c48e5ea7f2d7f4ef5b2d35d58faf3b01b679",
          "sha256": "c42da5bece5757fbca93c4f7d3572926ceafb958861a700e4e68ee51821ba5e2",
          "sha1": "75a8a29b8f0ea11ea2e0f39b9de7b9662a79f9fe",
          "md5": "e8e501a42d3c52ccaa8e73fa645a2065"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-livedata-0.1.0-dev11-sources.jar",
          "url": "ui-livedata-0.1.0-dev11-sources.jar",
          "size": 1651,
          "sha512": "da3f7738295563faa183f47553e3d2b2f0d343d675d421d05f9b4293bfc5a0f8e1a5d499aea605b83a7d87608b2d3dde6f01a30c15bdc2c6499cb708e3283e2a",
          "sha256": "ce7b740914ed8c45b983a1880276ac93ffd825b2a050c274d1b04cb2b4c31d6b",
          "sha1": "2f6517df776ab147244afc3112d5be0c32e53bf9",
          "md5": "cede67bfb80d507d5e9d44bd88b41df9"
        }
      ]
    }
  ]
}
