{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-java",
    "version": "1.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.4.0-alpha02-sources.jar",
          "url": "window-java-1.4.0-alpha02-sources.jar",
          "size": 13366,
          "sha512": "1f5dce55c43d673e465937b635d295caa8477e5d004c275c8d0c454adb395654f1b1ba1d5184a3652930d31ac5e55a9412b07a04aa3c0c3a1bf1e5d4cdff00cf",
          "sha256": "4ef5fef6a44172a320a2cbf8c8f73f5a2ec72c09e7fab676cb3540e72953892a",
          "sha1": "e20497ec48ed813ebfdd0546861a913f06f3d7e2",
          "md5": "25b9ade7944abb4c64c9e45ad7847a6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.4.0-alpha02.aar",
          "url": "window-java-1.4.0-alpha02.aar",
          "size": 17356,
          "sha512": "3534bd45715970e78c5caa65e67966b305356e61e4a9fe0ae63f449cae7f8491df0a9b38fde6a1ead7085ca0bfb484cffc2a7f60d798cc1be1b54eb6071873a5",
          "sha256": "ceed84b46b7bfd89421aae7bf6300ae30d8dec2d5120579918657e88001316e5",
          "sha1": "d2f67474f51216dd01131df487ce3fab67a1287f",
          "md5": "b42978e12f12cf5e5c53b790d5abacc0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.4.0-alpha02.aar",
          "url": "window-java-1.4.0-alpha02.aar",
          "size": 17356,
          "sha512": "3534bd45715970e78c5caa65e67966b305356e61e4a9fe0ae63f449cae7f8491df0a9b38fde6a1ead7085ca0bfb484cffc2a7f60d798cc1be1b54eb6071873a5",
          "sha256": "ceed84b46b7bfd89421aae7bf6300ae30d8dec2d5120579918657e88001316e5",
          "sha1": "d2f67474f51216dd01131df487ce3fab67a1287f",
          "md5": "b42978e12f12cf5e5c53b790d5abacc0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.4.0-alpha02-versionMetadata.json",
          "url": "window-java-1.4.0-alpha02-versionMetadata.json",
          "size": 2997,
          "sha512": "6b406e096178cc3d4bd26e919b787df84d64842601e7235be73387eec99353f2d4df9787f3c807841cc00ab15c2cccdf5201307ef5eb0d41171af45871ec38ab",
          "sha256": "bc977d04c79ebaf0925bb641cbe2221062841a1465395566b43bee82186715a1",
          "sha1": "af0d65c0f612231220e8acadc79e6e86d96badb9",
          "md5": "bdb306575bf9302a69d593a481d14cc4"
        }
      ]
    }
  ]
}