{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.10.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14053080"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-metadata-1.10.0-alpha03.jar",
          "url": "foundation-layout-1.10.0-alpha03.jar",
          "size": 48872,
          "sha512": "8e48008e82dc435d1944431de3f02cce9136b6b48f791d9c128180fa844147a9e7039e5d04dd5835e01ae7d049ed976ef405bc26585c4b26a1fc22cc8ef10f26",
          "sha256": "0e6d673d1ecc8ce2bbd74452640f579eb51040b3ce03b669eac10229cbff1b89",
          "sha1": "0a6b0e6a506a4ec095fba21b0f3cc84fb648068c",
          "md5": "10497bbf0482d662b53b9568af0043c4"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-kotlin-1.10.0-alpha03-sources.jar",
          "url": "foundation-layout-1.10.0-alpha03-sources.jar",
          "size": 96769,
          "sha512": "68301df9e61204631de4767d73b6494b05234b4f4f6e7200f11c72c026efb4b87f3cd476ab3c07d5f6bd19665b707e20ded3fdb929ec979bdc02c7e7145389d2",
          "sha256": "d6d1ece6c27393038a7134fdfb72f8fb3177a4c18f30a0f757de4426a0011779",
          "sha1": "d394cc40450f0dbf949fd48e86c5e0961c86bf5b",
          "md5": "ef5f7798e10711f15caedcb73aae1102"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.10.0-alpha03-multiplatform-sources.jar",
          "url": "foundation-layout-1.10.0-alpha03-multiplatform-sources.jar",
          "size": 111106,
          "sha512": "ecf794bbf0809cd660627b31eb1d8f331441d83370cdc036641bff4725fcd351ba7cfe937fdc51ff6966993c846aa878bf9acfe0b53f02b9e2ef3b1bb3112075",
          "sha256": "352348f003257fd92236e57ff70d367b8104059af54c5835679441d548c93414",
          "sha1": "71794d2ee9c0d0817d7e954ad1d99c43fa2ff6e4",
          "md5": "f0a461f24cf0fe5bb7d57cbbd9a89e9e"
        },
        {
          "name": "foundation-layout-1.10.0-alpha03-samples-sources.jar",
          "url": "foundation-layout-1.10.0-alpha03-samples-sources.jar",
          "size": 32472,
          "sha512": "732e88dfe78b0b5829e386da3e5a40879834de6eb6fc6c85b715190ad0dcc5e10c6d6f5bf9f7bf80ae2cfa14108977079eafd4dc7e02f4e5ca56efc03a22681c",
          "sha256": "b58c161d02d590a00d629e5e9a12d722fec07f8a162dba9ec6fc61471fa587ca",
          "sha1": "fda5fcf4b03c9011e3b43c07d1f1e08d10ae69f6",
          "md5": "f7395a0d36f8b10268321693019e2723"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.10.0-alpha03"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-layout-1.10.0-alpha03-versionMetadata.json",
          "size": 57465,
          "sha512": "9f22d52df2726c0e5d49d884fa3d7a78a5378366d4c38e74aa27e15b277fbdf967569236d46bec643322c1778bba3dc1d77fd619ea743e307bd1a33929f3568c",
          "sha256": "51a5e0019214b8c2926c1caa56c1df0e5b744a2ff1533fd8bbb3b3e4a83cb074",
          "sha1": "a2cd0c1966f287f1e06c45a6612b23baf30b15b6",
          "md5": "0b6db88e6327ec01292d352e8ce826b5"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.10.0-alpha03/foundation-layout-android-1.10.0-alpha03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.10.0-alpha03"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.10.0-alpha03/foundation-layout-android-1.10.0-alpha03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.10.0-alpha03"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.10.0-alpha03/foundation-layout-android-1.10.0-alpha03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.10.0-alpha03"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-jvmstubs/1.10.0-alpha03/foundation-layout-jvmstubs-1.10.0-alpha03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-jvmstubs",
        "version": "1.10.0-alpha03"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-jvmstubs/1.10.0-alpha03/foundation-layout-jvmstubs-1.10.0-alpha03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-jvmstubs",
        "version": "1.10.0-alpha03"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-jvmstubs/1.10.0-alpha03/foundation-layout-jvmstubs-1.10.0-alpha03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-jvmstubs",
        "version": "1.10.0-alpha03"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-layout-linuxx64stubs/1.10.0-alpha03/foundation-layout-linuxx64stubs-1.10.0-alpha03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-linuxx64stubs",
        "version": "1.10.0-alpha03"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../foundation-layout-linuxx64stubs/1.10.0-alpha03/foundation-layout-linuxx64stubs-1.10.0-alpha03.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-linuxx64stubs",
        "version": "1.10.0-alpha03"
      }
    }
  ]
}