{
  "formatVersion": "1.1",
  "component": {
    "url": "../../adaptive-navigation3/1.3.0-alpha03/adaptive-navigation3-1.3.0-alpha03.module",
    "group": "androidx.compose.material3.adaptive",
    "module": "adaptive-navigation3",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14347027"
    }
  },
  "variants": [
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation3 is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation3 is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation3 is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation3-linuxx64StubsMain-1.3.0-alpha03.klib",
          "url": "adaptive-navigation3-linuxx64stubs-1.3.0-alpha03.klib",
          "size": 63274,
          "sha512": "d5a74974c121e72a517924c255a4c064d20b12fc5ff0413b169ca4e55c1476a598a8b27b83bee2d66aee1cd9a58e1e4ae62366bac0c802f123fd5472f44551f1",
          "sha256": "070c2f5a24c076ed464ae280779dc926e9f0967cfe556a723444ea14741021d6",
          "sha1": "d2a52818d1d6c69d312af66a853edc840f861051",
          "md5": "f6afe2e4ebbd8811b73875b001868fbc"
        }
      ]
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation3 is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-layout",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation3 is in atomic group androidx.compose.material3.adaptive"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive-navigation",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "adaptive-navigation3 is in atomic group androidx.compose.material3.adaptive"
        }
      ],
      "files": [
        {
          "name": "adaptive-navigation3-linuxx64stubs-1.3.0-alpha03-sources.jar",
          "url": "adaptive-navigation3-linuxx64stubs-1.3.0-alpha03-sources.jar",
          "size": 14674,
          "sha512": "546de2e882b0107066ada29f24e24c85449c1197b4b8bd7663b3cef5d4146e5b1b39b15d80d5fbac44f7003aa3f1b4e8af4fcf4e48604e7876f2a7f133da1a97",
          "sha256": "c1268665baedd38c7408ca09a8a1811790f23b88650f9443557de37b4f6da84b",
          "sha1": "95b0051d1fcdfeb2b8918ec919d4ac7c4b891110",
          "md5": "3f42d9d484b0c9e21fb39439a92c4540"
        }
      ]
    }
  ]
}