{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.asynclayoutinflater",
    "module": "asynclayoutinflater",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13120768"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.asynclayoutinflater",
          "module": "asynclayoutinflater-appcompat",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "asynclayoutinflater is in atomic group androidx.asynclayoutinflater"
        }
      ],
      "files": [
        {
          "name": "asynclayoutinflater-1.1.0-beta01-sources.jar",
          "url": "asynclayoutinflater-1.1.0-beta01-sources.jar",
          "size": 8756,
          "sha512": "0652f6bec675e13d34754a3342edae9e3538fdef8b32d172ba537bb8e5436789fd2a607b82ad85833785c87b85ad641dc87aea18abb027b140c65395d22c6984",
          "sha256": "2c641835ef1150a1b9a2cd3bbce10183b9fa62fd85c312e8e3a5ae4bbdc2794f",
          "sha1": "99f2674a5634599d095b40937ee60b37f1a9acd3",
          "md5": "1d6e9c6b1ce494216d81cd72da929b1f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.asynclayoutinflater",
          "module": "asynclayoutinflater-appcompat",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "asynclayoutinflater is in atomic group androidx.asynclayoutinflater"
        }
      ],
      "files": [
        {
          "name": "asynclayoutinflater-1.1.0-beta01.aar",
          "url": "asynclayoutinflater-1.1.0-beta01.aar",
          "size": 13227,
          "sha512": "b40de2cef6338d316204e69f94156c0e086e9051a83e662984630568cabbb176c7cf32e2af105da5fb3489382a487f6a34ecf3c3e9e39d27ddfe44965c387753",
          "sha256": "83d680d94301e84f2df9e63b7540ef51b649081ca24d3616d7b9dd2020d41117",
          "sha1": "5620f2c86a2be2abc9e4e1e93f070ba6f3251709",
          "md5": "019b8857fcdc9782159942e2be603ac5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.asynclayoutinflater",
          "module": "asynclayoutinflater-appcompat",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "asynclayoutinflater is in atomic group androidx.asynclayoutinflater"
        }
      ],
      "files": [
        {
          "name": "asynclayoutinflater-1.1.0-beta01.aar",
          "url": "asynclayoutinflater-1.1.0-beta01.aar",
          "size": 13227,
          "sha512": "b40de2cef6338d316204e69f94156c0e086e9051a83e662984630568cabbb176c7cf32e2af105da5fb3489382a487f6a34ecf3c3e9e39d27ddfe44965c387753",
          "sha256": "83d680d94301e84f2df9e63b7540ef51b649081ca24d3616d7b9dd2020d41117",
          "sha1": "5620f2c86a2be2abc9e4e1e93f070ba6f3251709",
          "md5": "019b8857fcdc9782159942e2be603ac5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.asynclayoutinflater",
          "module": "asynclayoutinflater-appcompat",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "asynclayoutinflater is in atomic group androidx.asynclayoutinflater"
        }
      ],
      "files": [
        {
          "name": "asynclayoutinflater-1.1.0-beta01-versionMetadata.json",
          "url": "asynclayoutinflater-1.1.0-beta01-versionMetadata.json",
          "size": 996,
          "sha512": "2ed56da3d04f09e4582677f649ff342d48113a30e2b6c558cfaa3fb6812d4da71a044edd0dcc86a865c0fce22733aded09baecbcf04610338e2121544ceb9eb3",
          "sha256": "0a5735310a56c3dc1604714e9da0beb3f4783c6ad13155e3c4ad60738419a1f7",
          "sha1": "d2ed50e6744a6b49a0cfac54e01381324f6af939",
          "md5": "14155a966f73649000cc7cf62e788c48"
        }
      ]
    }
  ]
}