{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-samples",
    "version": "1.7.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-beta03"
          },
          "reason": "foundation-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-beta03"
          },
          "reason": "foundation-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-samples-1.7.0-beta03-sources.jar",
          "url": "foundation-samples-1.7.0-beta03-sources.jar",
          "size": 70960,
          "sha512": "e6915fda8c84b27f1fb4ef88ad8fecf0946b6bb5ed172c17baeec6ea1c7f178203f3e8877e6fe31c05f4b48ae924697aa34fce3e48971495e938535a707372ad",
          "sha256": "5a6b849641c2a695f3a0581b3c0580ea75330660c32a6fd60ebaf475fdfc7b3f",
          "sha1": "73cc34ad1d4dc4fd23d3af615e71abf6880c7510",
          "md5": "644d279dff3106b5f276edd15a0ec1f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-beta03"
          },
          "reason": "foundation-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-beta03"
          },
          "reason": "foundation-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-samples-1.7.0-beta03.aar",
          "url": "foundation-samples-1.7.0-beta03.aar",
          "size": 1211452,
          "sha512": "a7a198087416bdc6e79c25b61c2491321fa87b5df0e2fe3cfb7e0b0e5ddfb637f5ac45826265188ec76ec2410296a22808470699e22b8f2bd647c4b27e28a284",
          "sha256": "e146f1e610058e62a6e2810b74b0466bd00cce7f49d50eb1b82a376f5382dba8",
          "sha1": "28e8ae5081adcab6e5a6e453a4a96867114359cd",
          "md5": "83c6154e79960c137bcb8cfa8c6909ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-beta03"
          },
          "reason": "foundation-samples is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.0-beta03"
          },
          "reason": "foundation-samples is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-samples-1.7.0-beta03.aar",
          "url": "foundation-samples-1.7.0-beta03.aar",
          "size": 1211452,
          "sha512": "a7a198087416bdc6e79c25b61c2491321fa87b5df0e2fe3cfb7e0b0e5ddfb637f5ac45826265188ec76ec2410296a22808470699e22b8f2bd647c4b27e28a284",
          "sha256": "e146f1e610058e62a6e2810b74b0466bd00cce7f49d50eb1b82a376f5382dba8",
          "sha1": "28e8ae5081adcab6e5a6e453a4a96867114359cd",
          "md5": "83c6154e79960c137bcb8cfa8c6909ed"
        }
      ]
    }
  ]
}