{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-samples",
    "version": "1.0.0-beta05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7285231"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material-samples-1.0.0-beta05.aar",
          "url": "material-samples-1.0.0-beta05.aar",
          "size": 723790,
          "sha512": "28b9dcb7ed269920b047e5ec3ffff69bbd61410973b43724fa155946afbd5f3b03883560001d04f600c054a8fd434c0f3a10aafcecdd5166375e425e2a59fb06",
          "sha256": "b0c7030b911f82b81dc7528a2a6bf4b9da8d59200645573d0bc0147f406c7fcf",
          "sha1": "df999b0b2556eca25b43c8324a0f23e6453985e0",
          "md5": "4480e26adf01b33402ed0f5fa9cac5b6"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-beta05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0-beta05"
          }
        }
      ],
      "files": [
        {
          "name": "material-samples-1.0.0-beta05.aar",
          "url": "material-samples-1.0.0-beta05.aar",
          "size": 723790,
          "sha512": "28b9dcb7ed269920b047e5ec3ffff69bbd61410973b43724fa155946afbd5f3b03883560001d04f600c054a8fd434c0f3a10aafcecdd5166375e425e2a59fb06",
          "sha256": "b0c7030b911f82b81dc7528a2a6bf4b9da8d59200645573d0bc0147f406c7fcf",
          "sha1": "df999b0b2556eca25b43c8324a0f23e6453985e0",
          "md5": "4480e26adf01b33402ed0f5fa9cac5b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-samples-1.0.0-beta05-sources.jar",
          "url": "material-samples-1.0.0-beta05-sources.jar",
          "size": 33529,
          "sha512": "7b9e094454fc1c918328bad1f8fc78d4b87af97f0f71621170712dabc708dad574bd49eeaa9a7465dc500d678ff22295adb83f964f014f4d104d1e4281e6e5dd",
          "sha256": "d291923a7c0be7220adc5eed346a08c791dfd35743e8a89112a7b39b7059d5be",
          "sha1": "9d2bef3900ea9a428e865c6c2cf5ba11b7dce8ac",
          "md5": "44c5b66d046a351af5cd980987050a4d"
        }
      ]
    }
  ]
}
