{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-samples",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "foundation-samples-1.1.0-alpha05.aar",
          "url": "foundation-samples-1.1.0-alpha05.aar",
          "size": 396604,
          "sha512": "80b225ec098387258f11f4dbb006cd67cb34e4e4087af77f0019fcc362c34c456cfe03eb689032fb6110e948deb7c734c1bf3b4df7fd90ff514a2e291833bab1",
          "sha256": "bbfc588a7b20a8c6dc94979aef3f395e4cee6fd2812d0b511e2c018210ba8d52",
          "sha1": "aec34fb463d9a60992b71374be9eaa9d59418465",
          "md5": "8aa70a3f9717b8a436fef49adf029c6f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-samples-1.1.0-alpha05.aar",
          "url": "foundation-samples-1.1.0-alpha05.aar",
          "size": 396604,
          "sha512": "80b225ec098387258f11f4dbb006cd67cb34e4e4087af77f0019fcc362c34c456cfe03eb689032fb6110e948deb7c734c1bf3b4df7fd90ff514a2e291833bab1",
          "sha256": "bbfc588a7b20a8c6dc94979aef3f395e4cee6fd2812d0b511e2c018210ba8d52",
          "sha1": "aec34fb463d9a60992b71374be9eaa9d59418465",
          "md5": "8aa70a3f9717b8a436fef49adf029c6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-samples-1.1.0-alpha05-sources.jar",
          "url": "foundation-samples-1.1.0-alpha05-sources.jar",
          "size": 29468,
          "sha512": "33d1a2d68d408578dfbadaf0825608768d03659b3854bd6aecd5c1301487cb25dd4456d065b340d954576515de148008374330569763ee422be061aa8682e234",
          "sha256": "b7d73500326709dbb3546b1ebfce0677000f971de6687eb87c14efad08c2f879",
          "sha1": "145d2765cc5856464e4d6c9db7c44f4c31cb4b67",
          "md5": "395d3639a9c603a1207b160c333c0ea7"
        }
      ]
    }
  ]
}
