{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-samples",
    "version": "1.2.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "foundation-samples-1.2.0-rc02.aar",
          "url": "foundation-samples-1.2.0-rc02.aar",
          "size": 618843,
          "sha512": "0fc3221cac283f8ec1feb42d26ae897ef64ac83a04b306e03e51fdda8a6c25ce3d108906d6fb8500d7436c6823ced80a00027ad677084b75aad5e340fd5ea039",
          "sha256": "6d34dbf690605365388baa21b5f2a3f46d7637e9e9f46296bf2cb5e5b0bdcd8e",
          "sha1": "8d977d2db8b44982a0248b59d02e575f11e684cf",
          "md5": "32ee85ee4b0c67b5d06f8c40fc217b50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0-rc02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.0-rc02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-samples-1.2.0-rc02.aar",
          "url": "foundation-samples-1.2.0-rc02.aar",
          "size": 618843,
          "sha512": "0fc3221cac283f8ec1feb42d26ae897ef64ac83a04b306e03e51fdda8a6c25ce3d108906d6fb8500d7436c6823ced80a00027ad677084b75aad5e340fd5ea039",
          "sha256": "6d34dbf690605365388baa21b5f2a3f46d7637e9e9f46296bf2cb5e5b0bdcd8e",
          "sha1": "8d977d2db8b44982a0248b59d02e575f11e684cf",
          "md5": "32ee85ee4b0c67b5d06f8c40fc217b50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-samples-1.2.0-rc02-sources.jar",
          "url": "foundation-samples-1.2.0-rc02-sources.jar",
          "size": 41087,
          "sha512": "ecb63e7af06ffca2d19431fb7746f737941b12306e2f3b857e2ad7480d33be751f5912fb8fab61eb59b99e62692507b1b96fc6f293da16f4fa9bd4cac85b5645",
          "sha256": "77b238fffbcb4bbe77538974398c2d2813ed652160c573a45ccafbcd8407562e",
          "sha1": "202f55e6e8a7c34cee782cd343def89fce5e9388",
          "md5": "f275c4aa8f60981ae7bd647bd84e67a2"
        }
      ]
    }
  ]
}