{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-guava",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "room-guava-2.5.0.aar",
          "url": "room-guava-2.5.0.aar",
          "size": 6904,
          "sha512": "18ce89e4ab030e018c6f47ecc7a837102dca5a18c450bf40269618e28ade07581daa293677d434df0c7fe5a865de81a6415424ae0e29cb474481d730d195f61c",
          "sha256": "412b683c0076f45343bfcccf7991cd64a71763aa4b3ed11debdb2a903a0adee8",
          "sha1": "c550bc73f71a7d6ebe4b39057fa3805d419c3ca5",
          "md5": "7005bea97071ca7c301bfe8fa89970a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "listenablefuture"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "room-guava-2.5.0.aar",
          "url": "room-guava-2.5.0.aar",
          "size": 6904,
          "sha512": "18ce89e4ab030e018c6f47ecc7a837102dca5a18c450bf40269618e28ade07581daa293677d434df0c7fe5a865de81a6415424ae0e29cb474481d730d195f61c",
          "sha256": "412b683c0076f45343bfcccf7991cd64a71763aa4b3ed11debdb2a903a0adee8",
          "sha1": "c550bc73f71a7d6ebe4b39057fa3805d419c3ca5",
          "md5": "7005bea97071ca7c301bfe8fa89970a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-guava-2.5.0-sources.jar",
          "url": "room-guava-2.5.0-sources.jar",
          "size": 2362,
          "sha512": "9aba5cabb9c3b225d02e83fa95580a85cea01669543d4270e5889424493e08f31f929fd1606677c01faf55ab4218836329319afcc3de2ffc823f171b8e85cbca",
          "sha256": "158d4cdfa7e990720f10633f32ae0d43478a7af4008d49554c8a2b81883a731d",
          "sha1": "4cb73006e500fbea67ef95ee4a03b97eef62f295",
          "md5": "aeef46739353f9103f9245e02cff72c3"
        }
      ]
    }
  ]
}