{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text-samples",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-text-samples-1.3.0-beta02.aar",
          "url": "ui-text-samples-1.3.0-beta02.aar",
          "size": 57275,
          "sha512": "f4564df06b53b377e1ec13008ca0be510f6f520147eb24d61b7ffef05cbe9346f4624310644a57ef70895df7ec3993be36edf04ea054862bccad382882ea92a1",
          "sha256": "c646ebdbc9e1370c99f93e84903c9e23b020a9c8aaa87aa83f7bbc2a7706cfea",
          "sha1": "6a30a530e77a2ec8c514d8f50573a2b6720bd4da",
          "md5": "4335bacedaa394fa0b45b7bce16791ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-samples-1.3.0-beta02.aar",
          "url": "ui-text-samples-1.3.0-beta02.aar",
          "size": 57275,
          "sha512": "f4564df06b53b377e1ec13008ca0be510f6f520147eb24d61b7ffef05cbe9346f4624310644a57ef70895df7ec3993be36edf04ea054862bccad382882ea92a1",
          "sha256": "c646ebdbc9e1370c99f93e84903c9e23b020a9c8aaa87aa83f7bbc2a7706cfea",
          "sha1": "6a30a530e77a2ec8c514d8f50573a2b6720bd4da",
          "md5": "4335bacedaa394fa0b45b7bce16791ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-samples-1.3.0-beta02-sources.jar",
          "url": "ui-text-samples-1.3.0-beta02-sources.jar",
          "size": 11638,
          "sha512": "0b42e3de0ef967911b37980e70491257a9c9b41fa955d2f8801b7172cd7caeb611467293b5da599e0d1d26b863f81a888dba9d17d5c8821ab9f428f2801e08ed",
          "sha256": "9bb943d8ca18c64c9ebe003b2f1703602a9dc2055694bcc19787ae4fe3b71ba0",
          "sha1": "4303b50914168a280a95cf05d277859c6e08986d",
          "md5": "628fefaf2f31b96f446f4e1e712a412a"
        }
      ]
    }
  ]
}