{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-framework/2.6.1/sqlite-framework-2.6.1.module",
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14087977"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-tvosSimulatorArm64Main-2.6.1.klib",
          "url": "sqlite-framework-tvossimulatorarm64-2.6.1.klib",
          "size": 27688,
          "sha512": "daeca41180ffcb6abe1b8c8ce359946a94d180195eada446105c9518057b77c8453194305f7bcb49faa92f280b550a27a7606fb7daf1ca81685dde618bd7d0b8",
          "sha256": "bfafca673faedf262d428b89f3452507f416f565a6b45363577972afb32e3f16",
          "sha1": "7b077963c3a8e82156ec6c7c9820613c1b6a5fd5",
          "md5": "bb0e905c6c407310e68ee4114c112b67"
        },
        {
          "name": "sqlite-framework-tvosSimulatorArm64Cinterop-sqlite3Main-2.6.1.klib",
          "url": "sqlite-framework-tvossimulatorarm64-2.6.1-cinterop-sqlite3.klib",
          "size": 62715,
          "sha512": "51f5fa5f57939bd1236b15c8d9e9086449303cc25cc39f8950900eef5572c1d5732d43b5b77bd99fdf480ce175b2267037224addc1d5c87148dd9e12a41ec455",
          "sha256": "7f37a9c0679d15ef16fd2da0ad06b16eebfe256f1ef2b75cb5f08ce42cc44fd6",
          "sha1": "0d3e79cb6c827351a9755469a4d78fc728f0a39e",
          "md5": "30f2c0eb86ba9e74f57f43be6950f014"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-tvossimulatorarm64-2.6.1-sources.jar",
          "url": "sqlite-framework-tvossimulatorarm64-2.6.1-sources.jar",
          "size": 11642,
          "sha512": "52d1ee84def4b3060c2fc0e93592da440ae52bdbf5cc842b0001d3856cad09f9f05f7063bf06f7777218a0cac144f077910f12bc571fae7c3fd8163f6a851825",
          "sha256": "00d017faa9e9e6d2faeca22dd7e7598250cf1227894a11869dcc983f3b46d14c",
          "sha1": "ba01bc389204900a44ec3c2ee351dadecb45ab8a",
          "md5": "ec5eb8260aec879006a0798ea49e701f"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-tvossimulatorarm64-2.6.1-metadata.jar",
          "url": "sqlite-framework-tvossimulatorarm64-2.6.1-metadata.jar",
          "size": 4410,
          "sha512": "8a1dad28d8f0d29f274c988e1a7148c09ed9d4ecd45478639880bcba187912e129f9facb6125401ea05111d74fb0cc233d54f3a3f2ede532995fc33a73eb6dd5",
          "sha256": "009b67f8ad4ce8bfb48d7315e4883cd1b39e82bd9caece95a12ba6b7da46e4c3",
          "sha1": "b8eff1a3305e8d209805c9f38543d55f90f938e7",
          "md5": "edd9c586c0f4762042a6f92d03946e16"
        }
      ]
    }
  ]
}