{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.4.0-beta01.aar",
          "url": "navigation-compose-2.4.0-beta01.aar",
          "size": 1076136,
          "sha512": "49efef1451b47bf6fd66f261da24877c06fdb0d78b112a032fec035f47e897a670216a1974e647c5b2cdff1152fa49774402765664522bec0c2b1708ae350ef2",
          "sha256": "af10c55526aa744cfbf3a4745379dfcb3a7655f10776973f0072f02619acf291",
          "sha1": "89204594efa03288878db511ed5aff54d326f4c7",
          "md5": "91819a666e1103dd1828b4103da2611f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.4.0-beta01.aar",
          "url": "navigation-compose-2.4.0-beta01.aar",
          "size": 1076136,
          "sha512": "49efef1451b47bf6fd66f261da24877c06fdb0d78b112a032fec035f47e897a670216a1974e647c5b2cdff1152fa49774402765664522bec0c2b1708ae350ef2",
          "sha256": "af10c55526aa744cfbf3a4745379dfcb3a7655f10776973f0072f02619acf291",
          "sha1": "89204594efa03288878db511ed5aff54d326f4c7",
          "md5": "91819a666e1103dd1828b4103da2611f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-compose-2.4.0-beta01-sources.jar",
          "url": "navigation-compose-2.4.0-beta01-sources.jar",
          "size": 10735,
          "sha512": "b55e899d0eafb6a848acfaf441e553472e0b9c05012328fd00d0750b6b292152ca4967de46f2c9746371c03b6858916c8c33211f6308653ab23994c4c03a794c",
          "sha256": "203ecec2812672eb46c5e994c45094227a91b4338663af89356b42676e0b50c5",
          "sha1": "d2f0f3801fcc0da7721e02c6570aa6d236c710ac",
          "md5": "2d2f41c524ac9bc0979c7bc37e5cd576"
        }
      ]
    }
  ]
}
