{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore/1.1.7/datastore-1.1.7.module",
    "group": "androidx.datastore",
    "module": "datastore",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore.klib",
          "url": "datastore-macosarm64-1.1.7.klib",
          "size": 5172,
          "sha512": "0b428b0b6af964165330f32cb916e8f68b24ab164b68fb35e287ff2afa4cc4c1467eda7df90d4b9950293570ae0326185aed1a2d298c2d280146b66220f9ca13",
          "sha256": "d7e9ae7c62749e0513878a63fcf5f2a1b0eaf28776c597d672228a970499e330",
          "sha1": "ba473197ed6b455483356ffa94a38f73dfa262f2",
          "md5": "f6597f78ea412f4074539c10ef7ea1e8"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-macosarm64-1.1.7-sources.jar",
          "url": "datastore-macosarm64-1.1.7-sources.jar",
          "size": 1341,
          "sha512": "48de278a82cfb6fc113edd394205966ee0beb6493b9c3c61ba52ea5a9c4be273d5f02123953bcf9198dc1d18f2add3b78528338a4b6b54781ee02edc88f133ef",
          "sha256": "7a24c7744ca68ec6743a8c4eeae576a882f4f0cd5f4aef8e9d9a1aad4b513521",
          "sha1": "c25d7545ec4051b59d015022ea12c242d2faaec3",
          "md5": "11ca7c4df35f50a801b3f6a7e6a79cdd"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.7"
          },
          "reason": "datastore is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-macosarm64-1.1.7-metadata.jar",
          "url": "datastore-macosarm64-1.1.7-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}