{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.heifwriter",
    "module": "heifwriter",
    "version": "1.1.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14096524"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "heifwriter-1.1.0-rc02-sources.jar",
          "url": "heifwriter-1.1.0-rc02-sources.jar",
          "size": 42240,
          "sha512": "26a21a0c50ee4ed6b02ba77f0a1759e18dc974f643987045820951ef8f5feb0a929c0aba45147a9b598217f84c2bc8ebf129b7191898019d23ae036ec7f3e516",
          "sha256": "e598f8ad136344224dbca360a9e3eef6ab1085f478b16809221c50003aa92b4e",
          "sha1": "d8070e9f220c6249360e9e7b45e8d03b843e6966",
          "md5": "65bf5e21eeb12d65b0de626059ccfefe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "heifwriter-1.1.0-rc02.aar",
          "url": "heifwriter-1.1.0-rc02.aar",
          "size": 53499,
          "sha512": "9e769ba721ad243cbf0c384aed1ff899d02f2bdd353f6585e8c94ff34650a190c85b2510b9e83ce9f80fdd20030a3c13bd5d1a6145d432c7923590e2db38db09",
          "sha256": "b2738e3568274653f7337bc288437699e08b90870f77ba8976fb067650090742",
          "sha1": "6d6e91cf63275df0bafc40b8912c008d25a073e5",
          "md5": "c109822b63511e379bfd292fb5eb8782"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "heifwriter-1.1.0-rc02.aar",
          "url": "heifwriter-1.1.0-rc02.aar",
          "size": 53499,
          "sha512": "9e769ba721ad243cbf0c384aed1ff899d02f2bdd353f6585e8c94ff34650a190c85b2510b9e83ce9f80fdd20030a3c13bd5d1a6145d432c7923590e2db38db09",
          "sha256": "b2738e3568274653f7337bc288437699e08b90870f77ba8976fb067650090742",
          "sha1": "6d6e91cf63275df0bafc40b8912c008d25a073e5",
          "md5": "c109822b63511e379bfd292fb5eb8782"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "heifwriter-1.1.0-rc02-versionMetadata.json",
          "url": "heifwriter-1.1.0-rc02-versionMetadata.json",
          "size": 3385,
          "sha512": "2b84f90a359a6f69fcac7e8f5a93ee0d250aa5e4fe4aa678a7d5ba45999d8a026cc273258121e7e71d532b539cab78d84b787b6777bdbe4ac43bd0f8def4545a",
          "sha256": "c1a959579a8819bf9d6908ad6a3af0473431a115920c5b35410399e9889ad463",
          "sha1": "16ed40ab175587cf13c3c9b14bcfbd6cf8ac0612",
          "md5": "75e6d1e845c921ff1306d4d4684ff740"
        }
      ]
    }
  ]
}