{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appsearch",
    "module": "appsearch",
    "version": "1.0.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appsearch-1.0.0-alpha04.aar",
          "url": "appsearch-1.0.0-alpha04.aar",
          "size": 96872,
          "sha512": "e242184a9e156e5126492a89753553961e37915b8f8bcdc50f75b94f93a2a94c560166c61bf013abbb7146c0ded41b8dad68a2700bd739387646e29857545592",
          "sha256": "a653fd14a792408cea45540826660384264738725eaed39d1c52d32c5592f123",
          "sha1": "f6f979e745365412ccc374875a4879641f480809",
          "md5": "c38be2d3062ef3d82e4b870b9bc6f19f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appsearch-1.0.0-alpha04.aar",
          "url": "appsearch-1.0.0-alpha04.aar",
          "size": 96872,
          "sha512": "e242184a9e156e5126492a89753553961e37915b8f8bcdc50f75b94f93a2a94c560166c61bf013abbb7146c0ded41b8dad68a2700bd739387646e29857545592",
          "sha256": "a653fd14a792408cea45540826660384264738725eaed39d1c52d32c5592f123",
          "sha1": "f6f979e745365412ccc374875a4879641f480809",
          "md5": "c38be2d3062ef3d82e4b870b9bc6f19f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appsearch-1.0.0-alpha04-sources.jar",
          "url": "appsearch-1.0.0-alpha04-sources.jar",
          "size": 82076,
          "sha512": "16f5f55d59ab9ce5cfd203f15d0ab97fd244b981266d456bed6f8f2b1435da025160898585edabc94b33e6a6c0709625c1a99f99ae7694911f66875e0b960bfb",
          "sha256": "9a80a30d2f6c2b4072b935febce325f7c5c51b77750fb0d06d2d0784024f1a8b",
          "sha1": "7da2ebed7a488118e6a3ff4441ea6c2e5c6c6859",
          "md5": "48557c770bd1d2e37fd7d9a9ec6c8a82"
        }
      ]
    }
  ]
}
