{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata-samples",
    "version": "1.1.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runtime-livedata-samples-1.1.0-beta03.aar",
          "url": "runtime-livedata-samples-1.1.0-beta03.aar",
          "size": 5561,
          "sha512": "7bcf46688df0bea8df9d35b57f70c7f3891c16c537c8f7d4229ead8460d8f9fa78f069588806d228f028f5f9b59dfd8a547b43e68cec3876d1561c389d63c5a9",
          "sha256": "e1fcac0033c0c5b5cb7fecbbfa333208cb328e32bd5fdd968fab13480dd26d26",
          "sha1": "f5553fc315cf0f817cc021c68c2eea5bac7f77db",
          "md5": "744e47d10ae9d6f066ef5b5746276229"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.1.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-samples-1.1.0-beta03.aar",
          "url": "runtime-livedata-samples-1.1.0-beta03.aar",
          "size": 5561,
          "sha512": "7bcf46688df0bea8df9d35b57f70c7f3891c16c537c8f7d4229ead8460d8f9fa78f069588806d228f028f5f9b59dfd8a547b43e68cec3876d1561c389d63c5a9",
          "sha256": "e1fcac0033c0c5b5cb7fecbbfa333208cb328e32bd5fdd968fab13480dd26d26",
          "sha1": "f5553fc315cf0f817cc021c68c2eea5bac7f77db",
          "md5": "744e47d10ae9d6f066ef5b5746276229"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-livedata-samples-1.1.0-beta03-sources.jar",
          "url": "runtime-livedata-samples-1.1.0-beta03-sources.jar",
          "size": 1663,
          "sha512": "499da5ccc575764cdfe3945cabe1a28937530305b6708e2b5ea275e8d4840acea9e625018d5079e5c1ae1bcb188d7504ce44e73f7def35016e07439b8acd5352",
          "sha256": "5bc70bceb46741194a33d166003ec4a3f23ef66abef61e51bc5ae65b01f24092",
          "sha1": "2aed546e633b44703f361e15d1caaa5824029852",
          "md5": "0481648d351992d722b5e6a739ed8618"
        }
      ]
    }
  ]
}
