{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.0.0-alpha20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-1.0.0-alpha20.aar",
          "url": "compose-material-1.0.0-alpha20.aar",
          "size": 769760,
          "sha512": "16b35d40328c38a17822f639fee9c25d541d8c91221d04072139e60395fff6ca654a1661a717fc692463694164d8f0dbd5bd427718c11c67c42a001a34f2deb6",
          "sha256": "f8a2dd0566111c7c9f5b83792463100d0a6e151d894d7c179513b18ca45bf920",
          "sha1": "e8e3a999ebd58af17924269d0c571ec8f8e6a9ef",
          "md5": "514209583145f188125859b08e0eed74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-1.0.0-alpha20.aar",
          "url": "compose-material-1.0.0-alpha20.aar",
          "size": 769760,
          "sha512": "16b35d40328c38a17822f639fee9c25d541d8c91221d04072139e60395fff6ca654a1661a717fc692463694164d8f0dbd5bd427718c11c67c42a001a34f2deb6",
          "sha256": "f8a2dd0566111c7c9f5b83792463100d0a6e151d894d7c179513b18ca45bf920",
          "sha1": "e8e3a999ebd58af17924269d0c571ec8f8e6a9ef",
          "md5": "514209583145f188125859b08e0eed74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-material-1.0.0-alpha20-sources.jar",
          "url": "compose-material-1.0.0-alpha20-sources.jar",
          "size": 131759,
          "sha512": "3e9281c4c2a53a993e6ef2d1be0e057bb93a3e21b3618c2827a02d5f0ea47edc5e7c39642bbc1965c43a89cd81ef61e244a64c8c1d8acebff738928840b63b46",
          "sha256": "f17db7b69cba9b6b928ce57440e36852c2f19faf93a77bf920006c1b07975d8e",
          "sha1": "7af3f807302d82b084533130141cedfe9d0cec9c",
          "md5": "5f8336e46fe9c068a2082ea8a341f1c4"
        }
      ]
    }
  ]
}