{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-samples",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7067732"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runtime-samples-1.0.0-alpha10.aar",
          "url": "runtime-samples-1.0.0-alpha10.aar",
          "size": 193417,
          "sha512": "b6e5755f42e5ef46c499b34beb4247bfaa50b48c2b056c6eacd64bd25554d500870f7fafd1721c530643f3cd0de5f3f9e827a415e41b93bcf1905b0b64935205",
          "sha256": "ce9cb23cbe69206421988954daec659866f6d0b32a4eb17541abd2f124e13184",
          "sha1": "e9dbb1fea61138370548af53bad39c7519b7af69",
          "md5": "ce790754258cc10ef31aeb30482c854b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-samples-1.0.0-alpha10.aar",
          "url": "runtime-samples-1.0.0-alpha10.aar",
          "size": 193417,
          "sha512": "b6e5755f42e5ef46c499b34beb4247bfaa50b48c2b056c6eacd64bd25554d500870f7fafd1721c530643f3cd0de5f3f9e827a415e41b93bcf1905b0b64935205",
          "sha256": "ce9cb23cbe69206421988954daec659866f6d0b32a4eb17541abd2f124e13184",
          "sha1": "e9dbb1fea61138370548af53bad39c7519b7af69",
          "md5": "ce790754258cc10ef31aeb30482c854b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-samples-1.0.0-alpha10-sources.jar",
          "url": "runtime-samples-1.0.0-alpha10-sources.jar",
          "size": 16174,
          "sha512": "536c98eaa480d470583d28502c531368550c651de6f734368ae23c69153a2409a8af25e55659eeb1b150cd03ad1e7ee879c3e576e2a39d98b493167737457661",
          "sha256": "85a527b9fcd8d3f5f0abd3f3fa088b94c6223cc4e5cefd391a9845abe0693acd",
          "sha1": "af8007c3694ce9b1b600b479d16fed1a958d4e5b",
          "md5": "699be2a0e07f3d274ba79bd8ac79bb00"
        }
      ]
    }
  ]
}
