{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.0.3.aar",
          "url": "animation-1.0.3.aar",
          "size": 1249499,
          "sha512": "d949ac92707496ce3526eb1e1e0a1ed652946096d8c170e8a1192aebdeb3e5ee2b0e2a3fbe77df298e27bf20e48f407741a1a0da0d10e601200f1af9ce062332",
          "sha256": "e646cd9082d23dc2117ad5b6e4bd7173d3ea22b18ef1ce826c3ce1d159ad9d17",
          "sha1": "6b7d6886768aeb251eb5a9a64f3ec57e97074c99",
          "md5": "3888d7e344c52edd335559434396fd6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "animation-1.0.3.aar",
          "url": "animation-1.0.3.aar",
          "size": 1249499,
          "sha512": "d949ac92707496ce3526eb1e1e0a1ed652946096d8c170e8a1192aebdeb3e5ee2b0e2a3fbe77df298e27bf20e48f407741a1a0da0d10e601200f1af9ce062332",
          "sha256": "e646cd9082d23dc2117ad5b6e4bd7173d3ea22b18ef1ce826c3ce1d159ad9d17",
          "sha1": "6b7d6886768aeb251eb5a9a64f3ec57e97074c99",
          "md5": "3888d7e344c52edd335559434396fd6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-1.0.3-sources.jar",
          "url": "animation-1.0.3-sources.jar",
          "size": 37035,
          "sha512": "c8dd5349bb81f8abe41ed31e2d96dae36f8d49a58bdb9b739d4ebbbb1d11d98a2f83b8477da44cc613f08eb453b91c5340cede8537435f9badcb459573799a85",
          "sha256": "3baf8e47e8c7600cf243706a93e20596bcacfbfcd1e4fed0c61ca453a627684c",
          "sha1": "e6e8324157b87ff500fa6e0de4a9272f5bdc37ba",
          "md5": "52baf39ee09ff3f6a5ae44d9495910fc"
        }
      ]
    }
  ]
}
