{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core-samples",
    "version": "1.7.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material-icons-core-samples-1.7.0-alpha06.aar",
          "url": "material-icons-core-samples-1.7.0-alpha06.aar",
          "size": 8203,
          "sha512": "4081e004d80c72553f620c70fd2e2be0e48837f86a5e917ce6f244c61bf8a6a549546769044062b68cc10dc61726b8fa6ac2c566ded5ef7ea885a10ebe9a4acc",
          "sha256": "5bb3c14aa39902e79d761a2c82e2fa092cbf255924777510ab08dd61a7a6deea",
          "sha1": "a38de29a72c9f1f3b33a2fa684cc983ef00fd639",
          "md5": "55f0ba15753184fe88ccd175f86414d0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.0-alpha06"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-samples-1.7.0-alpha06.aar",
          "url": "material-icons-core-samples-1.7.0-alpha06.aar",
          "size": 8203,
          "sha512": "4081e004d80c72553f620c70fd2e2be0e48837f86a5e917ce6f244c61bf8a6a549546769044062b68cc10dc61726b8fa6ac2c566ded5ef7ea885a10ebe9a4acc",
          "sha256": "5bb3c14aa39902e79d761a2c82e2fa092cbf255924777510ab08dd61a7a6deea",
          "sha1": "a38de29a72c9f1f3b33a2fa684cc983ef00fd639",
          "md5": "55f0ba15753184fe88ccd175f86414d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-core-samples-1.7.0-alpha06-sources.jar",
          "url": "material-icons-core-samples-1.7.0-alpha06-sources.jar",
          "size": 1849,
          "sha512": "5e82b6fc611569270b0a77b159588b3d249a31627630b5e8a1eeb18b462eca347a9a9dfd07bac984a4b1b3df6d71fd490fda7a6f07995b5fcaaee4c2f038ec6c",
          "sha256": "262d79cf95faf69f89988b01d568d48b69742a95b0959b9238e2e797457938fa",
          "sha1": "578ff7394b718fb34c333c24bcfade35ccba41c5",
          "md5": "6dfd44933714f319df97b87cf801f994"
        }
      ]
    }
  ]
}