{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose-samples",
    "version": "1.10.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "activity-compose-samples is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "activity-compose-samples is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "activity-compose-samples is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-samples-1.10.0-alpha02-sources.jar",
          "url": "activity-compose-samples-1.10.0-alpha02-sources.jar",
          "size": 7854,
          "sha512": "77fe4b73cbf1d0beb9fb5ad91859e5d00093ae7063f1f966ed932a3dc59083a09dd5a7c490db0ce31584a507ee6c6761cae2cd86e85221360546e67c515d24cf",
          "sha256": "f407f42db5338bcd2b175a5f903022699983d64374477c46bbef441fa0588e87",
          "sha1": "47fa378780764e0c90ec26fcf05211137198bb91",
          "md5": "efab3826b7ba8ed96016a31d9055265d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "activity-compose-samples is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "activity-compose-samples is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "activity-compose-samples is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-samples-1.10.0-alpha02.aar",
          "url": "activity-compose-samples-1.10.0-alpha02.aar",
          "size": 37704,
          "sha512": "a987449380704ea4658699602aabb8af314cd3b19b3e93ea39d4ba1f453ea42cd0fdf2b2ea7236d8a50c900e081f9bc972596086a264554ce47b48cf2a4e936f",
          "sha256": "99d779f2720b9c287b0517ab0afd90e8294840c4be3760c6ae544223aa235ed0",
          "sha1": "8a7483ee0da721454859e50bfbaa4a94f8698774",
          "md5": "984959098fd99edefd6dc8f4c1893be6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha02"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "activity-compose-samples is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "activity-compose-samples is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha02"
          },
          "reason": "activity-compose-samples is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-samples-1.10.0-alpha02.aar",
          "url": "activity-compose-samples-1.10.0-alpha02.aar",
          "size": 37704,
          "sha512": "a987449380704ea4658699602aabb8af314cd3b19b3e93ea39d4ba1f453ea42cd0fdf2b2ea7236d8a50c900e081f9bc972596086a264554ce47b48cf2a4e936f",
          "sha256": "99d779f2720b9c287b0517ab0afd90e8294840c4be3760c6ae544223aa235ed0",
          "sha1": "8a7483ee0da721454859e50bfbaa4a94f8698774",
          "md5": "984959098fd99edefd6dc8f4c1893be6"
        }
      ]
    }
  ]
}