{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui-leanback",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-leanback-1.8.0.aar",
          "url": "media3-ui-leanback-1.8.0.aar",
          "size": 16323,
          "sha512": "983a048b7ed8d4cfcdfe5cce429c5929c825eaf58cac04e4d65e54c8456b7b67100773468eb6fdb1da9b5e3932faa6a725cfc56a49e984a8d569b3ee3d2dcf2b",
          "sha256": "a086f20d5272e738fea51a3b672d5dc1fbb0ad68649ddde1d62fe72abf237d9f",
          "sha1": "d81a32b37973b03b99c3688024404fc9b772922e",
          "md5": "b81f38ded0f280188b7fedbb04d19e25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.leanback",
          "module": "leanback",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-leanback-1.8.0.aar",
          "url": "media3-ui-leanback-1.8.0.aar",
          "size": 16323,
          "sha512": "983a048b7ed8d4cfcdfe5cce429c5929c825eaf58cac04e4d65e54c8456b7b67100773468eb6fdb1da9b5e3932faa6a725cfc56a49e984a8d569b3ee3d2dcf2b",
          "sha256": "a086f20d5272e738fea51a3b672d5dc1fbb0ad68649ddde1d62fe72abf237d9f",
          "sha1": "d81a32b37973b03b99c3688024404fc9b772922e",
          "md5": "b81f38ded0f280188b7fedbb04d19e25"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-leanback-1.8.0-sources.jar",
          "url": "media3-ui-leanback-1.8.0-sources.jar",
          "size": 4407,
          "sha512": "20a816c372ac5e7835dbf83737469ea30354dd6b21d38d7164482fdbab04c9dbfa979ae2d9273f2c5449d39c331eb29e564a0d9226f660a9c17f6e12920f71b0",
          "sha256": "b48620ff7de85c0a7998d584cc30c0a365a5d94f218bc91c4f3f82db1c246276",
          "sha1": "8dd5e7d7535bc7ed58d9c8c102f5ca83e104e91f",
          "md5": "0861a5a93f2eb1dc600500acfe88e220"
        }
      ]
    }
  ]
}
