{
  "formatVersion": "1.1",
  "component": {
    "url": "../../window-core/1.4.0-alpha02/window-core-1.4.0-alpha02.module",
    "group": "androidx.window",
    "module": "window-core",
    "version": "1.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core.aar",
          "url": "window-core-android-1.4.0-alpha02.aar",
          "size": 18381,
          "sha512": "6a23d9b8fc29b8f05fb503246ce262f48b57d59ceeb3499587daae86a42690a8b4843061b8089fa182291e68278c9f0b922703e5d1433c0d67bc61d9e242f42c",
          "sha256": "2bbc1b761a73a113f7a75193b8460622d8baee1c2494471b1114975bf6ef13f6",
          "sha1": "f6858b07e6d295a33b870e2335ed2629906b317f",
          "md5": "7e540e63316d145b1de5e1698f9109e5"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core.aar",
          "url": "window-core-android-1.4.0-alpha02.aar",
          "size": 18381,
          "sha512": "6a23d9b8fc29b8f05fb503246ce262f48b57d59ceeb3499587daae86a42690a8b4843061b8089fa182291e68278c9f0b922703e5d1433c0d67bc61d9e242f42c",
          "sha256": "2bbc1b761a73a113f7a75193b8460622d8baee1c2494471b1114975bf6ef13f6",
          "sha1": "f6858b07e6d295a33b870e2335ed2629906b317f",
          "md5": "7e540e63316d145b1de5e1698f9109e5"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "window-core is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-core-android-1.4.0-alpha02-sources.jar",
          "url": "window-core-android-1.4.0-alpha02-sources.jar",
          "size": 12553,
          "sha512": "1457158560acd7479053b81229c595283cd1fd71627dc9c6327c85caa0f72af77a0349b61a6814ab656bfe8c882e767f1a2c174761b482b389baf21538e7d258",
          "sha256": "3d47000b41a84cd5c31cbce5e4b7d3678a61e4823b84c04c4e37e218d4c220d9",
          "sha1": "01139026867e6b2e2ec6eed5f33700f8e97451c1",
          "md5": "60294da074d8310f75f9dad382d96724"
        }
      ]
    }
  ]
}