{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class-samples",
    "version": "1.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-samples-1.2.0-rc01.aar",
          "url": "material3-window-size-class-samples-1.2.0-rc01.aar",
          "size": 7163,
          "sha512": "347979d5b6c39f7490048978657a1f7af1006d9e84eca0ce8aaae751433442a2106bdde80d8836ab41e6135ce7d85052e225f10db8f542fe665473872922494f",
          "sha256": "b08d574fc6d4c5073c5f958cec0e9b6af9eb59b159a5d44688aabcacedf42b4b",
          "sha1": "5f040c71aac7dfb243aff905d6087612211811d9",
          "md5": "92528863ac1b0a18e2950891ed30cd0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-samples-1.2.0-rc01.aar",
          "url": "material3-window-size-class-samples-1.2.0-rc01.aar",
          "size": 7163,
          "sha512": "347979d5b6c39f7490048978657a1f7af1006d9e84eca0ce8aaae751433442a2106bdde80d8836ab41e6135ce7d85052e225f10db8f542fe665473872922494f",
          "sha256": "b08d574fc6d4c5073c5f958cec0e9b6af9eb59b159a5d44688aabcacedf42b4b",
          "sha1": "5f040c71aac7dfb243aff905d6087612211811d9",
          "md5": "92528863ac1b0a18e2950891ed30cd0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "material3-window-size-class-samples is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-samples-1.2.0-rc01-sources.jar",
          "url": "material3-window-size-class-samples-1.2.0-rc01-sources.jar",
          "size": 2091,
          "sha512": "7c35126c800d9603aad88f87adabf877249beae1b2bf98c84b25a53cf8937abbc2eca4566e5736f284d5d82d55fd68b2906defb69ce2563bcd542b52918dcdac",
          "sha256": "1d6e4e511180f40d014f5bad53e73305e05a9be7af3750e2b98f71764b636b49",
          "sha1": "e6471d0232b77c1d0b3c1a9972fae7111403a10a",
          "md5": "cae3e7e82b7a07f4b83c5f593e2049fc"
        }
      ]
    }
  ]
}