{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decoder",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-decoder-1.2.0-alpha01.aar",
          "url": "media3-decoder-1.2.0-alpha01.aar",
          "size": 17364,
          "sha512": "3f4894ea16135fee7ed66aabc40916561dc8f006232a8a7654e38e3428b6da802f0f1484c1b28c43b75a30ba46325b7afe1384921257972e67937b06898090ed",
          "sha256": "ba9f7f3554439b76424a6a3332531bc5a7f30bf0694736cc264b4acbeb47a3ac",
          "sha1": "950e73b65ba1b4f5c22847de2623ec9b0bce1088",
          "md5": "ad02031a1e0e9c86a15e8318cfa1a46c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decoder-1.2.0-alpha01.aar",
          "url": "media3-decoder-1.2.0-alpha01.aar",
          "size": 17364,
          "sha512": "3f4894ea16135fee7ed66aabc40916561dc8f006232a8a7654e38e3428b6da802f0f1484c1b28c43b75a30ba46325b7afe1384921257972e67937b06898090ed",
          "sha256": "ba9f7f3554439b76424a6a3332531bc5a7f30bf0694736cc264b4acbeb47a3ac",
          "sha1": "950e73b65ba1b4f5c22847de2623ec9b0bce1088",
          "md5": "ad02031a1e0e9c86a15e8318cfa1a46c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decoder-1.2.0-alpha01-sources.jar",
          "url": "media3-decoder-1.2.0-alpha01-sources.jar",
          "size": 18264,
          "sha512": "a6942290456e9cf93888af673a20368f7b42ff4d23fcecfff3f3317f15220015cc8e1803bf7b0e8194633f8b7a362ff823def19822bc4805835b16e306113347",
          "sha256": "cff09d05fa90aa03d5decd9864699a2c1c3eeefdfd4b3354eabd014e97d1f9cf",
          "sha1": "245b2d53281e15d3ba56b15ba5fb04bfa5d8e9a0",
          "md5": "b5b168b4f7ddf7ac97ecd8c481e6aca5"
        }
      ]
    }
  ]
}
