{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.9.0-alpha01.aar",
          "url": "media3-extractor-1.9.0-alpha01.aar",
          "size": 798554,
          "sha512": "a590cf665ab245ee727d6fbe8bf962510b608f064e740be4e2347af1ea79459a781b9ddfc3ead0aa1c819e643bd17fd44250b40c0ef11917abec6c80e18459d8",
          "sha256": "df162ff57cc8532845764791181ec2c1c10c2f088a86b1894d6d370e99463c08",
          "sha1": "20decc1bd0322922b0a06be904592bdf42f078c2",
          "md5": "3b921e43827816c0808d0b8c2a8a4368"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.9.0-alpha01.aar",
          "url": "media3-extractor-1.9.0-alpha01.aar",
          "size": 798554,
          "sha512": "a590cf665ab245ee727d6fbe8bf962510b608f064e740be4e2347af1ea79459a781b9ddfc3ead0aa1c819e643bd17fd44250b40c0ef11917abec6c80e18459d8",
          "sha256": "df162ff57cc8532845764791181ec2c1c10c2f088a86b1894d6d370e99463c08",
          "sha1": "20decc1bd0322922b0a06be904592bdf42f078c2",
          "md5": "3b921e43827816c0808d0b8c2a8a4368"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.9.0-alpha01-sources.jar",
          "url": "media3-extractor-1.9.0-alpha01-sources.jar",
          "size": 690192,
          "sha512": "5195e323e8bf3e1135bd37e24a8be22171b70b2ea5a18f4e33b8285a84729ce2e809c711b6fa022c5479215a5dc83f9595e45691e0f9ca231d1931ec2a1b97f8",
          "sha256": "377cbc0850c75f4b383056f2aa226d609c5c6ee635e48cbda8e73e6108c40c18",
          "sha1": "a9de6af49c6915d4a643360d4f81dbd7e3d3b61a",
          "md5": "2a8070710ba15302d9b247e7253746c2"
        }
      ]
    }
  ]
}
