{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0-rc01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-1.2.0-rc01.aar",
          "url": "compose-material-1.2.0-rc01.aar",
          "size": 1140228,
          "sha512": "36addb08776f15b298239ffde45b83619b55b127c2d4584016bf9a0a67586010ade7bd88a710e1162f29ebac952b06de70204ab20ad1e0053ead36eec1f728b7",
          "sha256": "c51d1ae1cb4ae80b2feedc02f93267fdfd25aa48b275bc2a73c5865cfbb67f2f",
          "sha1": "f160a5d8f4dbe8cb1e2494c10a2f1772b6be1a9e",
          "md5": "5d38899d0d1a6859229c0a2dfb6b35e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-1.2.0-rc01.aar",
          "url": "compose-material-1.2.0-rc01.aar",
          "size": 1140228,
          "sha512": "36addb08776f15b298239ffde45b83619b55b127c2d4584016bf9a0a67586010ade7bd88a710e1162f29ebac952b06de70204ab20ad1e0053ead36eec1f728b7",
          "sha256": "c51d1ae1cb4ae80b2feedc02f93267fdfd25aa48b275bc2a73c5865cfbb67f2f",
          "sha1": "f160a5d8f4dbe8cb1e2494c10a2f1772b6be1a9e",
          "md5": "5d38899d0d1a6859229c0a2dfb6b35e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material-1.2.0-rc01-sources.jar",
          "url": "compose-material-1.2.0-rc01-sources.jar",
          "size": 168500,
          "sha512": "f223b69eba33d693f636df82e65987e5ec3952e5968b3a3301d05c7acb2cc49a179b60f76202b83cfa0599c1d4bfbb8fc18c2eb67903474546e708f131068b69",
          "sha256": "c3621d23525949aeea479df9a45f48d7489b92c12eed240eea551bab5d6137bc",
          "sha1": "7cdec5027931b436dd32782c1204e1c5a2bee3b9",
          "md5": "a5bfd70f8069d36597a6f2f643a29de2"
        }
      ]
    }
  ]
}