{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-material3",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protolayout-material3-1.0.0-alpha01-sources.jar",
          "url": "protolayout-material3-1.0.0-alpha01-sources.jar",
          "size": 5726,
          "sha512": "575bed254b40a4a1f659f9c934c8be3064ad70b5db77bcf432b4cc8e3e4c23378dc9cd05e4f1b65a02b0237812f071377f9b002d0a0cb11f47239f87397d2efc",
          "sha256": "c335f32afec678973029805b1bda297c8a654734549d804b0fa345de5f7eca99",
          "sha1": "48d8f1fe8e026eb31ca730dbab62b5e7b81f0d10",
          "md5": "503de664e7ad473f173b682556ab6d99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "protolayout-material3-1.0.0-alpha01.aar",
          "url": "protolayout-material3-1.0.0-alpha01.aar",
          "size": 5806,
          "sha512": "75df37548641898a298de09867a9ef87baa18b4a3b974ccace8f481a712d67aacb5e2c5f2999894d59581575f56829a7ab7afd2bbef55a5418166788a7f433f4",
          "sha256": "2fd9e36fa1e59a597f2d0a392c7e8547fcb1512d54e3d98d117f5d1d36ac192d",
          "sha1": "cd9496ab95c68efcaad246e138ba90cfc3317c82",
          "md5": "6c48fa5b0dda25dc18ae5d1e12d848e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "protolayout-material3-1.0.0-alpha01.aar",
          "url": "protolayout-material3-1.0.0-alpha01.aar",
          "size": 5806,
          "sha512": "75df37548641898a298de09867a9ef87baa18b4a3b974ccace8f481a712d67aacb5e2c5f2999894d59581575f56829a7ab7afd2bbef55a5418166788a7f433f4",
          "sha256": "2fd9e36fa1e59a597f2d0a392c7e8547fcb1512d54e3d98d117f5d1d36ac192d",
          "sha1": "cd9496ab95c68efcaad246e138ba90cfc3317c82",
          "md5": "6c48fa5b0dda25dc18ae5d1e12d848e3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "protolayout-material3-1.0.0-alpha01-versionMetadata.json",
          "url": "protolayout-material3-1.0.0-alpha01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}