{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material3-samples",
    "version": "1.5.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12750671"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material3-samples-1.5.0-alpha07-sources.jar",
          "url": "compose-material3-samples-1.5.0-alpha07-sources.jar",
          "size": 53164,
          "sha512": "d53a0973853a6fca237952de11405767f3f57fe25e4e2b219fc5510044385fdf643c77d7c8abaaa07fef9f3f15de4650e4b318d4084123b276abc81fa30017d4",
          "sha256": "2feefe6291ffe66117aef651b2c905266851b28dc68fbc6fcd0b92042b5fa3ba",
          "sha1": "e71bfc6e411465f2e5e8eb45defa866f1bc3aa52",
          "md5": "3bc3e947d55dde5c8ea8aaeb67717132"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material3-samples-1.5.0-alpha07.aar",
          "url": "compose-material3-samples-1.5.0-alpha07.aar",
          "size": 1194908,
          "sha512": "c6ca7889a1d2257b169f3481e575f98a6837f66727a1895fdc912f78fc35f9f3cb3c78754c35b2285d285455f8014633196bd23d3807e21893b552ce16eb1a54",
          "sha256": "099edd63706e49e3e738f7ffe1c06ebe948277e97ebb79b713f803a852464842",
          "sha1": "e6946e8054f2f4e4353d00854395bbc55685ffd0",
          "md5": "d1e379e190657ff42129089e247452da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.0.0-alpha30"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha07"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "compose-material3-samples is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material3-samples-1.5.0-alpha07.aar",
          "url": "compose-material3-samples-1.5.0-alpha07.aar",
          "size": 1194908,
          "sha512": "c6ca7889a1d2257b169f3481e575f98a6837f66727a1895fdc912f78fc35f9f3cb3c78754c35b2285d285455f8014633196bd23d3807e21893b552ce16eb1a54",
          "sha256": "099edd63706e49e3e738f7ffe1c06ebe948277e97ebb79b713f803a852464842",
          "sha1": "e6946e8054f2f4e4353d00854395bbc55685ffd0",
          "md5": "d1e379e190657ff42129089e247452da"
        }
      ]
    }
  ]
}