{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-samples",
    "version": "1.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13624324"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.8.3-sources.jar",
          "url": "animation-samples-1.8.3-sources.jar",
          "size": 29600,
          "sha512": "601ac79771ddc26bb1314fbd0e18478fcfa47628ebcec7314eebd7fbfa1d56a48b16e9ad99eeeba6c7b0fcb27e4b7867d2c7f434bfa337afb2fb436106328751",
          "sha256": "43c34f29475a01ffdad25f3c0bfdd130f1dee8d5718992263562dfd130ef772c",
          "sha1": "fd04d34c483dc99377b6199c1461d8649ff3deee",
          "md5": "2e8b15c19b23bf42d542835e6b19e822"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.8.3.aar",
          "url": "animation-samples-1.8.3.aar",
          "size": 680448,
          "sha512": "5646d306b7bedf320a6a25b9c9a9acabdf43fdf0f2cebe10b7ff929a28e2a1fa1a4735a9a96de5af19a52efa6abcf106572cd487e6efbaf0feb65f5cab69955f",
          "sha256": "00f3164b4759b9ecb425e129513017ca5506c4fecb445a41dea2189540c9cdd6",
          "sha1": "c5c664604cf990803b741d29a2ef5199386cb2f1",
          "md5": "18bcb148d9209fe2e48fdcddbaa96c0d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.3"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.3"
          },
          "reason": "animation-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "animation-samples-1.8.3.aar",
          "url": "animation-samples-1.8.3.aar",
          "size": 680448,
          "sha512": "5646d306b7bedf320a6a25b9c9a9acabdf43fdf0f2cebe10b7ff929a28e2a1fa1a4735a9a96de5af19a52efa6abcf106572cd487e6efbaf0feb65f5cab69955f",
          "sha256": "00f3164b4759b9ecb425e129513017ca5506c4fecb445a41dea2189540c9cdd6",
          "sha1": "c5c664604cf990803b741d29a2ef5199386cb2f1",
          "md5": "18bcb148d9209fe2e48fdcddbaa96c0d"
        }
      ]
    }
  ]
}