{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava3-samples",
    "version": "1.8.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12979508"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava3-samples-1.8.0-beta01-sources.jar",
          "url": "runtime-rxjava3-samples-1.8.0-beta01-sources.jar",
          "size": 6113,
          "sha512": "c72ac97efb671291e38cdb248c54e074c33f01d51041d9d3251f2bfe079da3c48d2a48ed1dc995f806ae83164384a21ac0605a6b13d5bd9aa90797502f2f25a6",
          "sha256": "8b09c066e1d6b84e4f026fac308869abc2743f020c5890377494e390d7a8f38a",
          "sha1": "be603d7c4c9cfb458dc04de274dc0a1cac5aebc5",
          "md5": "6f0e53bb9d3d71130dc104def5781dc1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava3-samples-1.8.0-beta01.aar",
          "url": "runtime-rxjava3-samples-1.8.0-beta01.aar",
          "size": 14262,
          "sha512": "00fd61c4e53835fd7da10846166a222c9931a8ef24410694db90c9ee64815f59207592c5cc6d2988c642a909de357aec293655545c8e60d0d73ec9f550b3720f",
          "sha256": "330dbca221d39bcdeef2876ecf532417d96662f456d9f81e9d6a5d4cfa3e1844",
          "sha1": "2aeea83e761397b281064762dd3ab2f0088783fc",
          "md5": "11bca64dfdb20c1275b7930b245e16fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "runtime-rxjava3-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava3-samples-1.8.0-beta01.aar",
          "url": "runtime-rxjava3-samples-1.8.0-beta01.aar",
          "size": 14262,
          "sha512": "00fd61c4e53835fd7da10846166a222c9931a8ef24410694db90c9ee64815f59207592c5cc6d2988c642a909de357aec293655545c8e60d0d73ec9f550b3720f",
          "sha256": "330dbca221d39bcdeef2876ecf532417d96662f456d9f81e9d6a5d4cfa3e1844",
          "sha1": "2aeea83e761397b281064762dd3ab2f0088783fc",
          "md5": "11bca64dfdb20c1275b7930b245e16fb"
        }
      ]
    }
  ]
}