{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/1.9.0-alpha03/annotation-1.9.0-alpha03.module",
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.9.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation.klib",
          "url": "annotation-androidnativearm32-1.9.0-alpha03.klib",
          "size": 22694,
          "sha512": "91428a94e02aeda2b927e0ddacd984645ae41f3eed683620c0c25348eed49d3e9e8ffdecbf5e8b7260462149c2a50a82471dd34352b1c8c215ac7e3c7b2650aa",
          "sha256": "669bd468fb2a6d00363a29aeb4acbe59563fc99d8d39a455bedf42d0ba55af57",
          "sha1": "b968038f7e00c2b51d96e7e738da016edc02078c",
          "md5": "d6560d4147e513542b4c96c5544a9afe"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "annotation-androidnativearm32-1.9.0-alpha03-sources.jar",
          "url": "annotation-androidnativearm32-1.9.0-alpha03-sources.jar",
          "size": 29195,
          "sha512": "e22aaf94c3233f50976e2de81bc79584bac8f067c661f771c9877410f9a0e0d75f98dc07578dab900db32b7ec48c1ebf9b9fbc3c5a8d70fa31879a83bd17ee32",
          "sha256": "a4c494907e7a51f59f371edfff1d0563785de655aab033efba4e67511090aa57",
          "sha1": "c7df6906c51cc706b45eed1fb71dcf008d9cc246",
          "md5": "1537702b6199e5b48e981f04b48329dd"
        }
      ]
    }
  ]
}