{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-view",
    "version": "1.4.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-view-1.4.0-rc02-sources.jar",
          "url": "camera-view-1.4.0-rc02-sources.jar",
          "size": 92152,
          "sha512": "f87bd0daa37e896865d3b98b68012667d0f9019aef5ef341fb6f4c966fcc8dfb9294c57c7ef2ca0e486a143785d547156f8b9a745bc76aeaf86b37870c18ee9c",
          "sha256": "b6f8609358df84f95110fece8c737a7d343536c7221c7eb2a0edc26085d5a237",
          "sha1": "200f99180c059f21b5b8298a9fc8a4f301961477",
          "md5": "11dbbde69c7ad5298a2195acd12d3e0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-rc02"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-view-1.4.0-rc02.aar",
          "url": "camera-view-1.4.0-rc02.aar",
          "size": 111162,
          "sha512": "4aa8540c01a26a88af44a0dfff09868d8b543ab41f9faea953fac0a59da22fa9f1ea99191a8b2daca7354d7d0ec86bff0196e5d470fcf3b55f718214932fa5bb",
          "sha256": "e57028904bb00a589d8099b041d92d04565c177b1f2a89da19bfb8b7c6eb2e5d",
          "sha1": "0c98498ad27068c5f74ee61effeed58e144da51b",
          "md5": "d4794fe55904c8d9ba2458fd40bc61db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-rc02"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-rc02"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-rc02"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-view-1.4.0-rc02.aar",
          "url": "camera-view-1.4.0-rc02.aar",
          "size": 111162,
          "sha512": "4aa8540c01a26a88af44a0dfff09868d8b543ab41f9faea953fac0a59da22fa9f1ea99191a8b2daca7354d7d0ec86bff0196e5d470fcf3b55f718214932fa5bb",
          "sha256": "e57028904bb00a589d8099b041d92d04565c177b1f2a89da19bfb8b7c6eb2e5d",
          "sha1": "0c98498ad27068c5f74ee61effeed58e144da51b",
          "md5": "d4794fe55904c8d9ba2458fd40bc61db"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-rc02"
          },
          "reason": "camera-view is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-view-1.4.0-rc02-versionMetadata.json",
          "url": "camera-view-1.4.0-rc02-versionMetadata.json",
          "size": 14607,
          "sha512": "d796bf772c416b58a658b6778daffa1345a6a388fcc63091a7ea0f25c873e08af768041e74a1772732d1a237b2de808403768358f69c8b73e41efcb256ce6861",
          "sha256": "21b9585f8d99a88309b804404207083f1f83f0abc35c31934c049fdd1de201ba",
          "sha1": "bf99c66c6d5ae50f283a0c0c15c5604ded4e06af",
          "md5": "0cd384b76b308851d33f5514ea162652"
        }
      ]
    }
  ]
}