{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.7.5/foundation-1.7.5.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-jvmstubs-1.7.5.jar",
          "url": "foundation-jvmstubs-1.7.5.jar",
          "size": 3557046,
          "sha512": "fc88cbfbeac668992eeb8f53f243861242dcc89e9109e48a74ce09ca461a66f02bce44ff4aaf6209c60e2021264fe2387979caea81291a8b5a7ec93be4695531",
          "sha256": "f5eb40dd17fd53d3c96b16e0b83b0fcd4513a39b3622ae46a29128ccd0a60a77",
          "sha1": "69daf7ab3583d034ef0f600318cc69bf2ef19e3b",
          "md5": "f44ab59456c43981ff048598f3d9aaa9"
        }
      ]
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-jvmstubs-1.7.5.jar",
          "url": "foundation-jvmstubs-1.7.5.jar",
          "size": 3557046,
          "sha512": "fc88cbfbeac668992eeb8f53f243861242dcc89e9109e48a74ce09ca461a66f02bce44ff4aaf6209c60e2021264fe2387979caea81291a8b5a7ec93be4695531",
          "sha256": "f5eb40dd17fd53d3c96b16e0b83b0fcd4513a39b3622ae46a29128ccd0a60a77",
          "sha1": "69daf7ab3583d034ef0f600318cc69bf2ef19e3b",
          "md5": "f44ab59456c43981ff048598f3d9aaa9"
        }
      ]
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-jvmstubs-1.7.5-sources.jar",
          "url": "foundation-jvmstubs-1.7.5-sources.jar",
          "size": 774134,
          "sha512": "aa82c53f412872eb5c85ea5ff37b82a95c8ca61c493a4904da3fca8058baa7f54f829cda17826eded5ebc0569ce0412e2c542448d915933424827e32cde47c34",
          "sha256": "919cb1ca92b6c6fe5de46e36375f194cdb82ff18e730f7105fbd70318ca293a5",
          "sha1": "3f52cae5bfb78ae3477a42767e0db2fe4afc7d6c",
          "md5": "99a7802601921bbac37b552ca7011ab9"
        }
      ]
    }
  ]
}