{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-navigation",
    "version": "1.4.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.4.0-beta02-sources.jar",
          "url": "compose-navigation-1.4.0-beta02-sources.jar",
          "size": 8791,
          "sha512": "2c1e662247ec894c9211ebe7431d8da9695471cb810f1137f9c4bb9a49b86c3b607cc946e2f8083534c9576b164f7d7b73240af5bc218fec46312d98032b9b18",
          "sha256": "bb240708a8b5b2567d4374d23913f5e07b9910f7bf0b600da69fceb26a53855c",
          "sha1": "e1c3948d43de68996e2347e291528f424215bfca",
          "md5": "a102c10615986a921abdb19e155f435d"
        },
        {
          "name": "compose-navigation-1.4.0-beta02-samples-sources.jar",
          "url": "compose-navigation-1.4.0-beta02-samples-sources.jar",
          "size": 2364,
          "sha512": "ca81a346711ffb995b1dbdfd75ca38f83724b80fd50ba0ae51c44126238f4b48f7bc8627c6e812cb7a9c5fc6a6a5a01a2b84dec91e793c566df1d9875ae00323",
          "sha256": "cc3cbdd816d42ba2072a9e7629e37174d66a9ee1ed128f4e18f61e60e6576a74",
          "sha1": "c63d872e0730842a15af478fd0e9e13ab13d497e",
          "md5": "9d426a8117c50440f22ffe360eaabee6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.4.0-beta02.aar",
          "url": "compose-navigation-1.4.0-beta02.aar",
          "size": 60277,
          "sha512": "786d34f1ae8c854bc50dbb95a64d5072ab28312a65c2c6b8145b7cbc3116b582f623f85c16e34db07e35e5fa00a6cada4ac6d5b179d826f0c574a74371387111",
          "sha256": "390fc664937fe8609908b826ead380637b32020dd2f603b95dc53515530f2360",
          "sha1": "1eacc1a8fad49bce8b464703dbc06232e79eab85",
          "md5": "fca277124cb3d8ad99400937798b2319"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-beta02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.4.0-beta02.aar",
          "url": "compose-navigation-1.4.0-beta02.aar",
          "size": 60277,
          "sha512": "786d34f1ae8c854bc50dbb95a64d5072ab28312a65c2c6b8145b7cbc3116b582f623f85c16e34db07e35e5fa00a6cada4ac6d5b179d826f0c574a74371387111",
          "sha256": "390fc664937fe8609908b826ead380637b32020dd2f603b95dc53515530f2360",
          "sha1": "1eacc1a8fad49bce8b464703dbc06232e79eab85",
          "md5": "fca277124cb3d8ad99400937798b2319"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-beta02"
          },
          "reason": "compose-navigation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-navigation-1.4.0-beta02-versionMetadata.json",
          "url": "compose-navigation-1.4.0-beta02-versionMetadata.json",
          "size": 3090,
          "sha512": "7303d24ef507c79cd8f666d45bcb4fa1bd1672ee1c14e07fb7604d8722fd6c2069271f96f846d0de3043caaa512e59b15705ccae5fd9a57e8acf0e469112b61b",
          "sha256": "c0aecd11cc6b257bb821b3e6bf7b8650e88a8e6630ed9c023f993eeb8e86aa39",
          "sha1": "a1f6d1a0e7020d2981be1e99a40dea5352a8a8af",
          "md5": "d5dacd1ef905477bfaf5ead77047966d"
        }
      ]
    }
  ]
}