{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation3-runtime/1.0.0-alpha09/navigation3-runtime-1.0.0-alpha09.module",
    "group": "androidx.navigation3",
    "module": "navigation3-runtime",
    "version": "1.0.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14046583"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-wasm-js-1.0.0-alpha09.klib",
          "url": "navigation3-runtime-wasm-js-1.0.0-alpha09.klib",
          "size": 59905,
          "sha512": "6fa228300cf318b9460a1b4191e586a874ab7d259fb79939f3e88a65316b841484e7a64642b0dd2fb78df4c677233f24b9d90335d81480c573ebde1652d15352",
          "sha256": "c7b5f00f21744f8a0eec46ae415d2f4f239d3eff93f90adc0c1d66ff7de819ee",
          "sha1": "e2ea5cdf1456dc777c586b508e52149e46d29b34",
          "md5": "2e197997155747294067605f07be335a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-wasm-js-1.0.0-alpha09.klib",
          "url": "navigation3-runtime-wasm-js-1.0.0-alpha09.klib",
          "size": 59905,
          "sha512": "6fa228300cf318b9460a1b4191e586a874ab7d259fb79939f3e88a65316b841484e7a64642b0dd2fb78df4c677233f24b9d90335d81480c573ebde1652d15352",
          "sha256": "c7b5f00f21744f8a0eec46ae415d2f4f239d3eff93f90adc0c1d66ff7de819ee",
          "sha1": "e2ea5cdf1456dc777c586b508e52149e46d29b34",
          "md5": "2e197997155747294067605f07be335a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "navigation3-runtime is in atomic group androidx.navigation3"
        }
      ],
      "files": [
        {
          "name": "navigation3-runtime-wasm-js-1.0.0-alpha09-sources.jar",
          "url": "navigation3-runtime-wasm-js-1.0.0-alpha09-sources.jar",
          "size": 23909,
          "sha512": "18970009c7c8cfdf2830d437520d5e2034fc9ca8a04697c41f921ca94f260ac76655d2614e2bccf580101ba204ec9b10ea7e5a730e32c19198dd5ccd1755d3b7",
          "sha256": "b348e269f81423315b7f3ca00ef0171f6b91efd548bb3e20e66e5b245ad85756",
          "sha1": "258c01f9c6992e8a35bd30caadde30594b51b015",
          "md5": "29a402f386a24c0e46fd3f19209f66f4"
        }
      ]
    }
  ]
}