{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.1.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.1.0-alpha03.aar",
          "url": "material-icons-core-1.1.0-alpha03.aar",
          "size": 683343,
          "sha512": "eb7500601738bf395d0468f74696c7334ada578b8dda47c17e7997776ad01d83a2252b399445b4f8d554d70e5ed9df40456f8a806c0bb24a40c6f8f03eb0c4f5",
          "sha256": "d3cff084b7d2bad3cf58f1556f438a0522da9ededac9bfc3fd2d4493701adf77",
          "sha1": "09f7102548f472b28f3bac752ead13506e9a8c39",
          "md5": "b8619917504493ad0e372f2005b75caa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.1.0-alpha03.aar",
          "url": "material-icons-core-1.1.0-alpha03.aar",
          "size": 683343,
          "sha512": "eb7500601738bf395d0468f74696c7334ada578b8dda47c17e7997776ad01d83a2252b399445b4f8d554d70e5ed9df40456f8a806c0bb24a40c6f8f03eb0c4f5",
          "sha256": "d3cff084b7d2bad3cf58f1556f438a0522da9ededac9bfc3fd2d4493701adf77",
          "sha1": "09f7102548f472b28f3bac752ead13506e9a8c39",
          "md5": "b8619917504493ad0e372f2005b75caa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-core-1.1.0-alpha03-sources.jar",
          "url": "material-icons-core-1.1.0-alpha03-sources.jar",
          "size": 239472,
          "sha512": "085cc31348d5eaadb77428c583dc7f5b64ee2f70d889f3c0e9a7e2b0a5cc9ce49d9ed3c455b1f8d20bd592404294a9643df33c2e483451fdb3b5fe4bd01f35ed",
          "sha256": "fc0ff8f5661fc0182d3d7f06f46a6025704eb4106fc4dbe9cb2a2220653bcb67",
          "sha1": "2eda8306585f2e3b3f9c529613c0e78bb4f46d21",
          "md5": "bc04aeaf6b8811771be92556266c5a27"
        }
      ]
    }
  ]
}
