{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.2.0-rc02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.2.0-rc02.aar",
          "url": "runtime-saveable-1.2.0-rc02.aar",
          "size": 1072549,
          "sha512": "bb0890f22bf405261993d8e3be71152610413b5f65657255875157961fc78c444f53ae84d6c8f28b97c55590fb8d4bc54c669f6d383d3ea8364742c4398aa96d",
          "sha256": "f693dd0c5e7406976cc7ae480c4e16d128eaf303a8512a0055175083a32b73f4",
          "sha1": "17998df7078a89be450a296b915020b36a02bb2e",
          "md5": "3aaf6f3294e2f24d3f1ddd8489ab34d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-rc02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.2.0-rc02.aar",
          "url": "runtime-saveable-1.2.0-rc02.aar",
          "size": 1072549,
          "sha512": "bb0890f22bf405261993d8e3be71152610413b5f65657255875157961fc78c444f53ae84d6c8f28b97c55590fb8d4bc54c669f6d383d3ea8364742c4398aa96d",
          "sha256": "f693dd0c5e7406976cc7ae480c4e16d128eaf303a8512a0055175083a32b73f4",
          "sha1": "17998df7078a89be450a296b915020b36a02bb2e",
          "md5": "3aaf6f3294e2f24d3f1ddd8489ab34d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-saveable-1.2.0-rc02-sources.jar",
          "url": "runtime-saveable-1.2.0-rc02-sources.jar",
          "size": 10792,
          "sha512": "2a4fd28cfd1e8bc9572cecab3dcc25560efcbf690e104e3b1e7039bd4d9c3bfc28f96e1d996cc2da2fb846b0f279de63a83d9e801867fa275b164a59645c606f",
          "sha256": "a498d31ee590d7b8b4a31021134e3793d6287a08fc0444c99b80020beea432ae",
          "sha1": "dfdc3070b43a1cb2939cc13498dd40988a8d3d93",
          "md5": "55cf532a33cf4313df6415a1342a26a3"
        }
      ]
    }
  ]
}