{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe-testing",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-testing-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-testing-1.0.0-alpha01.aar",
          "size": 76306,
          "sha512": "82c84c099205672bf8266daedcd6b9c058e8d0221fc0d766708b0de9d90e7324b5c00da1b32a2e5e74e52df71094f64e0b86af79b9264a516106b55226262f47",
          "sha256": "476ab3f3b83e46cdc8c783e75829feecd5720af34a7ccef62560796ab366c073",
          "sha1": "8cf42a9851be4242e0f50ff0d8d1b90cdb803768",
          "md5": "fd1466c76fe066556765b5d1875afef5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-testing-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-testing-1.0.0-alpha01.aar",
          "size": 76306,
          "sha512": "82c84c099205672bf8266daedcd6b9c058e8d0221fc0d766708b0de9d90e7324b5c00da1b32a2e5e74e52df71094f64e0b86af79b9264a516106b55226262f47",
          "sha256": "476ab3f3b83e46cdc8c783e75829feecd5720af34a7ccef62560796ab366c073",
          "sha1": "8cf42a9851be4242e0f50ff0d8d1b90cdb803768",
          "md5": "fd1466c76fe066556765b5d1875afef5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-camera2-pipe-testing-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-testing-1.0.0-alpha01-sources.jar",
          "size": 17538,
          "sha512": "a1ac2cdf0db4c419d860d2bd301c1ec12dc21b7a5ba4a55a9f4b31f6d817f1a6b213f28788b0aebf3bb14589b95b4ce02741fd182e7742364caaabdbca15d55e",
          "sha256": "d5a7b48df550bf75f6de01a5b3ab36d1cf4f31e22204b84ca7db0d2f6ec21168",
          "sha1": "508b139522589c0c15825947e9d794c2890ab4aa",
          "md5": "1562d3402629e98e88d9534584c04820"
        }
      ]
    }
  ]
}