{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material3",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha01.aar",
          "url": "compose-material3-1.0.0-alpha01.aar",
          "size": 66920,
          "sha512": "e15787377382584421b7ba3aefbfce972cd771017c2366272a5672ca5c68f4cc2043656f38babc941528511e4ff273c647223ff9e42f7c5209080c95eb6ea206",
          "sha256": "8bf02b9baf3bdc8c3487316aca1d0532bb8bd67805a884650a81bf7700550aa3",
          "sha1": "0cbc442d699565baaf4371896c9deefa39215c28",
          "md5": "1def5d8ec3f008029b7fdddd583bccef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha01.aar",
          "url": "compose-material3-1.0.0-alpha01.aar",
          "size": 66920,
          "sha512": "e15787377382584421b7ba3aefbfce972cd771017c2366272a5672ca5c68f4cc2043656f38babc941528511e4ff273c647223ff9e42f7c5209080c95eb6ea206",
          "sha256": "8bf02b9baf3bdc8c3487316aca1d0532bb8bd67805a884650a81bf7700550aa3",
          "sha1": "0cbc442d699565baaf4371896c9deefa39215c28",
          "md5": "1def5d8ec3f008029b7fdddd583bccef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.2.0-alpha07"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha01-sources.jar",
          "url": "compose-material3-1.0.0-alpha01-sources.jar",
          "size": 21847,
          "sha512": "3672644db0c0d750d9a857cf973af053a0727a648f310b0cb09139cb598ae33394cb0d3ab7d99e014620a5884833f65bc797273356f851ae44fc48bf0a5488e4",
          "sha256": "34a2e8e2eb8c7b1cdf9d41928feee53a40be41f7cb33fa6f00165e62e286add1",
          "sha1": "d89d1bef6d437f70c14502775d4b383cee8a7e77",
          "md5": "a78e517f1b599c4edee32a9bcbc5ed53"
        }
      ]
    }
  ]
}