{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.autofill",
    "module": "autofill",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7217131"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "autofill-1.2.0-alpha01.aar",
          "url": "autofill-1.2.0-alpha01.aar",
          "size": 37137,
          "sha512": "1dd67981a5dffe8bdbf5ecc47ee03c23c175b1646a04587f001c8d25bbecc849332b08b0ec2b8c345f3d42c270d07107b6ae14ff58de30979926fa321f06c163",
          "sha256": "32714ad0f1578ba44d78cb427ae6063e3fa2093a8b7d2498f64ad6dfc4d9ed7b",
          "sha1": "29b4ab011e338eb20f8e575426469893f85477c3",
          "md5": "1b79af33cbafdd677b13fd95ee228f2e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "autofill-1.2.0-alpha01.aar",
          "url": "autofill-1.2.0-alpha01.aar",
          "size": 37137,
          "sha512": "1dd67981a5dffe8bdbf5ecc47ee03c23c175b1646a04587f001c8d25bbecc849332b08b0ec2b8c345f3d42c270d07107b6ae14ff58de30979926fa321f06c163",
          "sha256": "32714ad0f1578ba44d78cb427ae6063e3fa2093a8b7d2498f64ad6dfc4d9ed7b",
          "sha1": "29b4ab011e338eb20f8e575426469893f85477c3",
          "md5": "1b79af33cbafdd677b13fd95ee228f2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "autofill-1.2.0-alpha01-sources.jar",
          "url": "autofill-1.2.0-alpha01-sources.jar",
          "size": 25986,
          "sha512": "7c922eb388d64fa284ffe28d1518a8fd8414201e41c796495273ae1c8a4860f72dca1aaea4b07b9e0c1d983c48bd9db87c114f61f7eda9322ea549a8b81bd6fa",
          "sha256": "0d4cdaa5bef792e39b523e2ef0e2285e97c170ad54579d129ba4f672fa0e5eaa",
          "sha1": "c5fb0f73ef83c30f02673b23571fd01847b8e66a",
          "md5": "a0cde6a1abc168006d29f6e2805f1fe0"
        }
      ]
    }
  ]
}
