{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.10.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14128725"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "material-ripple-metadata-1.10.0-alpha04.jar",
          "url": "material-ripple-1.10.0-alpha04.jar",
          "size": 14559,
          "sha512": "39780d6c60bfd02d07b956019b73798ea262cff4dd9e87fa2f6696abcd9bf584a1ee09c3fdf8d757b29840ab16c97a44d12fba18f6ec5a0c6ee5453aebe13cae",
          "sha256": "05a08117d393c53be325b59079712c0a43388b4822e569bea1a914c3398d6893",
          "sha1": "3c3ea4057c8ad00e469280dd11ca41a639b4775e",
          "md5": "fb262d9c3e1923d13ebb05e32bf21c4a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "material-ripple-kotlin-1.10.0-alpha04-sources.jar",
          "url": "material-ripple-1.10.0-alpha04-sources.jar",
          "size": 20384,
          "sha512": "963374037aa18d938cfa226e3b65d180c480a9fe7fb085b81b9c2ab9a1d31ca426a7ea959c3ad3001b1bb56ae1504d4e0675be938c31b1bcf9e66e268751e10d",
          "sha256": "69cb3dca99f6460d50adb7ef911998341cfcd88b3f063f157e370d3c242d6cf8",
          "sha1": "83a5b4687716a39e91cc7aa0ce7cf604c4f14423",
          "md5": "5537dc876aba7b6e45085f0c507b559d"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "files": [
        {
          "name": "material-ripple-1.10.0-alpha04-multiplatform-sources.jar",
          "url": "material-ripple-1.10.0-alpha04-multiplatform-sources.jar",
          "size": 31237,
          "sha512": "03732f7bdb873a63eadd78b57315f65c4115a83c4d92e718dbf7e7608e02c5b800d1606bb76531f632026d9a806ef91bc890b1b4efd67d6334b1526367bf9129",
          "sha256": "34d84a53e045d26c69d118c3d50214414f4012fae55df83534422f5f69da70d4",
          "sha1": "2138cbbebb6cbabdb31060fd324561893371900d",
          "md5": "e5a2d47dc23bb045c6adebe9485adbb0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material-ripple-1.10.0-alpha04-versionMetadata.json",
          "size": 3222,
          "sha512": "3c35ebf8d482c7d4e58f20541ecc1aa05b6bb43181eafd69185754452d3463a3d6c42d673cf65277ba5cc474ea0369f97f728d1e821e2d02dd73540667be3fc8",
          "sha256": "d3e7d97e8587777c5d40fd3926fbd5779a257c9bc6d03d9d2ecfb2021a0f090a",
          "sha1": "a85d78af58cc208aecf48dccad2fed29bf67ddc6",
          "md5": "dbca5ed5263eab0f270fe74d94d2df43"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-android/1.10.0-alpha04/material-ripple-android-1.10.0-alpha04.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-android",
        "version": "1.10.0-alpha04"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-android/1.10.0-alpha04/material-ripple-android-1.10.0-alpha04.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-android",
        "version": "1.10.0-alpha04"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-android/1.10.0-alpha04/material-ripple-android-1.10.0-alpha04.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-android",
        "version": "1.10.0-alpha04"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-jvmstubs/1.10.0-alpha04/material-ripple-jvmstubs-1.10.0-alpha04.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-jvmstubs",
        "version": "1.10.0-alpha04"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-jvmstubs/1.10.0-alpha04/material-ripple-jvmstubs-1.10.0-alpha04.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-jvmstubs",
        "version": "1.10.0-alpha04"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-ripple-jvmstubs/1.10.0-alpha04/material-ripple-jvmstubs-1.10.0-alpha04.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-jvmstubs",
        "version": "1.10.0-alpha04"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-ripple-linuxx64stubs/1.10.0-alpha04/material-ripple-linuxx64stubs-1.10.0-alpha04.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-linuxx64stubs",
        "version": "1.10.0-alpha04"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-ripple-linuxx64stubs/1.10.0-alpha04/material-ripple-linuxx64stubs-1.10.0-alpha04.module",
        "group": "androidx.compose.material",
        "module": "material-ripple-linuxx64stubs",
        "version": "1.10.0-alpha04"
      }
    }
  ]
}