{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-paging-rxjava2",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-paging-rxjava2-2.5.1.aar",
          "url": "room-paging-rxjava2-2.5.1.aar",
          "size": 8932,
          "sha512": "f16408fc8a526b0257740fe92325a8620b1f4a552fd5e1e3dac80cf489aa49f6a628a269c82b69cca219af2285a9087ce255bc954f5ca91cdccc977b4cb5b6d5",
          "sha256": "f1369b6c3e8ac9dec0eea33625233e6d3617a311c4d2493e1a950a364ffbdaff",
          "sha1": "39f70492d19a060c371e24cc6fadc64d35b531f5",
          "md5": "197e42205d50b19ee0d8fa1296eeef40"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-paging-rxjava2-2.5.1.aar",
          "url": "room-paging-rxjava2-2.5.1.aar",
          "size": 8932,
          "sha512": "f16408fc8a526b0257740fe92325a8620b1f4a552fd5e1e3dac80cf489aa49f6a628a269c82b69cca219af2285a9087ce255bc954f5ca91cdccc977b4cb5b6d5",
          "sha256": "f1369b6c3e8ac9dec0eea33625233e6d3617a311c4d2493e1a950a364ffbdaff",
          "sha1": "39f70492d19a060c371e24cc6fadc64d35b531f5",
          "md5": "197e42205d50b19ee0d8fa1296eeef40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-paging-rxjava2-2.5.1-sources.jar",
          "url": "room-paging-rxjava2-2.5.1-sources.jar",
          "size": 2386,
          "sha512": "93a0019cb1b2433834596e499fc939f0b19cbc71ec75b6c78582c8e4584d26462992c00385b04a732c64af6b3d8939015b777cc64c0f36fd97095a25f7147e7e",
          "sha256": "67977c44b3dc30cfa80a455ef63d81fd4484abf9df90dd48efdaaeec7f8a3397",
          "sha1": "0e37d6d4d29932358c507c2cbed04e6f54795005",
          "md5": "f963228310c5f69ccb51bcbbee7eca50"
        }
      ]
    }
  ]
}