{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler-hosted",
    "version": "1.2.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compiler-hosted-1.2.0-alpha07.jar",
          "url": "compiler-hosted-1.2.0-alpha07.jar",
          "size": 924885,
          "sha512": "d0f6b17aae846fa3c116987ea59f968d00c85818fc6c103d671ab818fedc69248226140c02838a46432b3b35d2e45bfb03723e94321ddf9544479fac31900504",
          "sha256": "4f12d0f7977faf886239ad41cfb2190d234313d97c8a2884ea4f3989e1e31352",
          "sha1": "657e847ec17e314a78c18e92d3f311b8b82b21dc",
          "md5": "223a04a842d027bef109d946961a44f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "compiler-hosted-1.2.0-alpha07.jar",
          "url": "compiler-hosted-1.2.0-alpha07.jar",
          "size": 924885,
          "sha512": "d0f6b17aae846fa3c116987ea59f968d00c85818fc6c103d671ab818fedc69248226140c02838a46432b3b35d2e45bfb03723e94321ddf9544479fac31900504",
          "sha256": "4f12d0f7977faf886239ad41cfb2190d234313d97c8a2884ea4f3989e1e31352",
          "sha1": "657e847ec17e314a78c18e92d3f311b8b82b21dc",
          "md5": "223a04a842d027bef109d946961a44f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-hosted-1.2.0-alpha07-sources.jar",
          "url": "compiler-hosted-1.2.0-alpha07-sources.jar",
          "size": 188329,
          "sha512": "d36c4444f8f4960cec9bb0cf6e26945d0c72e566c772ed5879bf0e30b9ca88b6227b5afb0c48dcc21abe3ddd3f3a045701d00c7affaf9ff2de96b49907f12af2",
          "sha256": "6e94a720c5aac571c2d1bed8ab29b2b662e30e0ea49492271f83000839394894",
          "sha1": "f9ac5cc8eeecb9cb7f166cd400dca2f47b6556cb",
          "md5": "ebc1d9374c241174ee0ead1dcad5d3b7"
        }
      ]
    }
  ]
}