{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-retain/1.10.0-alpha04/runtime-retain-1.10.0-alpha04.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-retain",
    "version": "1.10.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14128725"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-retain-wasm-js-1.10.0-alpha04.klib",
          "url": "runtime-retain-wasm-js-1.10.0-alpha04.klib",
          "size": 66198,
          "sha512": "c8878feabf4cca081e9a2789e6cd1310609299959966ed45913b2f9e27e1a2857d8e4bcc2197c288fb1199936fccb1f9e06ef41c63f2b83a1c281a0a1c2805f6",
          "sha256": "505b3d71475619b4fb758bda640112319a612e6a148139dd88852b23635acd84",
          "sha1": "e801c4aaef5d96c96f1b9aa1e53db8847ef74e24",
          "md5": "d369cd969e2245110f455823314a3e44"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-browser",
          "version": {
            "requires": "0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-retain-wasm-js-1.10.0-alpha04.klib",
          "url": "runtime-retain-wasm-js-1.10.0-alpha04.klib",
          "size": 66198,
          "sha512": "c8878feabf4cca081e9a2789e6cd1310609299959966ed45913b2f9e27e1a2857d8e4bcc2197c288fb1199936fccb1f9e06ef41c63f2b83a1c281a0a1c2805f6",
          "sha256": "505b3d71475619b4fb758bda640112319a612e6a148139dd88852b23635acd84",
          "sha1": "e801c4aaef5d96c96f1b9aa1e53db8847ef74e24",
          "md5": "d369cd969e2245110f455823314a3e44"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-retain-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-tracing",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.10.0-alpha04"
          },
          "reason": "runtime-retain is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-retain-wasm-js-1.10.0-alpha04-sources.jar",
          "url": "runtime-retain-wasm-js-1.10.0-alpha04-sources.jar",
          "size": 28355,
          "sha512": "5a4812e84a2b1ac9dfd6045c66752d6a74302f9c3c86934fe076449b44e3dff29e9a76bf13aa694d6010fd17b7a68f79cd3c098b0b4e3de9b9cd39b596e68e34",
          "sha256": "e2c58d0a6dde8277c67aeaaf370061084d700713c9f3a88cb76d8afde005167a",
          "sha1": "68a81920366e17c29db873ae0bfd28d42c0d42c4",
          "md5": "4c5d2350faff0dc68cb0e77ec0c64a13"
        }
      ]
    }
  ]
}