{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-manifest",
    "version": "1.1.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.1.0-alpha06.aar",
          "url": "ui-test-manifest-1.1.0-alpha06.aar",
          "size": 1799,
          "sha512": "626ddf45f839de8740d0db09be191d482a5bba68e89c28974d8d567d7397bec218854c84facf9494560dee132643bc511db02e6a12ed3aeedb70562462f51093",
          "sha256": "6a619e3ff391886c377dd0d920623a1331b602973f3a4ec4b30ad452a2719a94",
          "sha1": "2338e2aba24ea946b2f99d30182742ce36fe2c5a",
          "md5": "8a6b23d406a442ebb40f296f45eff63a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.1.0-alpha06.aar",
          "url": "ui-test-manifest-1.1.0-alpha06.aar",
          "size": 1799,
          "sha512": "626ddf45f839de8740d0db09be191d482a5bba68e89c28974d8d567d7397bec218854c84facf9494560dee132643bc511db02e6a12ed3aeedb70562462f51093",
          "sha256": "6a619e3ff391886c377dd0d920623a1331b602973f3a4ec4b30ad452a2719a94",
          "sha1": "2338e2aba24ea946b2f99d30182742ce36fe2c5a",
          "md5": "8a6b23d406a442ebb40f296f45eff63a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-manifest-1.1.0-alpha06-sources.jar",
          "url": "ui-test-manifest-1.1.0-alpha06-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
