{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-bundled/2.5.2/sqlite-bundled-2.5.2.module",
    "group": "androidx.sqlite",
    "module": "sqlite-bundled",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13624135"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-release.aar",
          "url": "sqlite-bundled-android-2.5.2.aar",
          "size": 3365857,
          "sha512": "fd7b1e9131eaa44a721fed4225b27e97ea2768686a2b4fc29e670975575684a804403599188c5caa222b4ab97d5e57f890ae62488b6e96028e86192278ca5865",
          "sha256": "2de1d07399683582437a8383ac74015f6b03efae26bcc0540bae29c1fab6d949",
          "sha1": "9dc13c3b472a972a616d4737438c632130fa01ec",
          "md5": "4274150159cc0743c1f0ec2dc0fc1af9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-release.aar",
          "url": "sqlite-bundled-android-2.5.2.aar",
          "size": 3365857,
          "sha512": "fd7b1e9131eaa44a721fed4225b27e97ea2768686a2b4fc29e670975575684a804403599188c5caa222b4ab97d5e57f890ae62488b6e96028e86192278ca5865",
          "sha256": "2de1d07399683582437a8383ac74015f6b03efae26bcc0540bae29c1fab6d949",
          "sha1": "9dc13c3b472a972a616d4737438c632130fa01ec",
          "md5": "4274150159cc0743c1f0ec2dc0fc1af9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "sqlite-bundled is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-bundled-android-2.5.2-sources.jar",
          "url": "sqlite-bundled-android-2.5.2-sources.jar",
          "size": 16501,
          "sha512": "81aa5c05c6585a0273b53d8f5244fe31112a70e0a633ed2046a529745054566ce77557d3e2cee87f36da00d86115ac3549f93374af8c09089aa9a3f33365f380",
          "sha256": "84f8abd467bb76a2480df245eb2745944401dd09ed6acc5a6a90f6aea4e0f08e",
          "sha1": "a13155f563aba4e8ab95d175d15fde2a773b334b",
          "md5": "998dc52da47dfbdec5ab658558eb22e7"
        }
      ]
    }
  ]
}