{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.7.0-alpha06/runtime-saveable-1.7.0-alpha06.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.7.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-desktop-1.7.0-alpha06.jar",
          "url": "runtime-saveable-desktop-1.7.0-alpha06.jar",
          "size": 54821,
          "sha512": "5d5b08d1d8489f9027b4b59f6ac92b9f0d563ceadecd99d40744cd7dadc9bfb2b7750b59c28f7b8986af3ed4e692b341e64e31f1cb4dd39ba3b4af33a2b1e784",
          "sha256": "57d992f1169e5f70ff2259340fbbe4c5fd721ac60497fc75b63ece45da257f52",
          "sha1": "25d2132523e8349969203732d0f6050c11f50d9e",
          "md5": "037b9d9fc77ef467b6fef5235c7ff605"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-desktop-1.7.0-alpha06.jar",
          "url": "runtime-saveable-desktop-1.7.0-alpha06.jar",
          "size": 54821,
          "sha512": "5d5b08d1d8489f9027b4b59f6ac92b9f0d563ceadecd99d40744cd7dadc9bfb2b7750b59c28f7b8986af3ed4e692b341e64e31f1cb4dd39ba3b4af33a2b1e784",
          "sha256": "57d992f1169e5f70ff2259340fbbe4c5fd721ac60497fc75b63ece45da257f52",
          "sha1": "25d2132523e8349969203732d0f6050c11f50d9e",
          "md5": "037b9d9fc77ef467b6fef5235c7ff605"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha06"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-desktop-1.7.0-alpha06-sources.jar",
          "url": "runtime-saveable-desktop-1.7.0-alpha06-sources.jar",
          "size": 11663,
          "sha512": "326baea73bb95d4df655daa5b2b8f44613671b930581886d54885fc55955ca5feb72aecdd55922847c444861600de704d9f04e896d1e857bafd328977fd60c35",
          "sha256": "c1730d3a69eb62ad819b12835591d0a8d7676de0b6d4257a38fa28daebbb8399",
          "sha1": "f4b8bdb1cd75cb3c61bc1a3996fe6eff4382e836",
          "md5": "084246caa2aa3053867c6bf8c5b79b6d"
        }
      ]
    }
  ]
}