{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-test-junit4/1.9.2/ui-test-junit4-1.9.2.module",
    "group": "androidx.compose.ui",
    "module": "ui-test-junit4",
    "version": "1.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "14122761"
    }
  },
  "variants": [
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-jvmstubs-1.9.2.jar",
          "url": "ui-test-junit4-jvmstubs-1.9.2.jar",
          "size": 12359,
          "sha512": "1b2a5abd547efa408f6faedf3b5beb78301abbe24469b478032ca3f99dfb60218cc8798db0b9c1e2dd543879d36ba7c9fdf9c5ce14e95d35ebbe33ffb5515c02",
          "sha256": "09826ed0804f4df455776c97948a049218fb4831d5497911e8ea7ead217fd6f5",
          "sha1": "3474df458341b50cffa7ae5225dfc6807e60369b",
          "md5": "856dce092476e970e11e22e9be17b9b3"
        }
      ]
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "com.google.truth",
          "module": "truth",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-jvmstubs-1.9.2.jar",
          "url": "ui-test-junit4-jvmstubs-1.9.2.jar",
          "size": 12359,
          "sha512": "1b2a5abd547efa408f6faedf3b5beb78301abbe24469b478032ca3f99dfb60218cc8798db0b9c1e2dd543879d36ba7c9fdf9c5ce14e95d35ebbe33ffb5515c02",
          "sha256": "09826ed0804f4df455776c97948a049218fb4831d5497911e8ea7ead217fd6f5",
          "sha1": "3474df458341b50cffa7ae5225dfc6807e60369b",
          "md5": "856dce092476e970e11e22e9be17b9b3"
        }
      ]
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.9.2"
          },
          "reason": "ui-test-junit4 is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-jvmstubs-1.9.2-sources.jar",
          "url": "ui-test-junit4-jvmstubs-1.9.2-sources.jar",
          "size": 11489,
          "sha512": "ead39894a998c40efddb47c31105c6400ef1a40b135a638be2a698ff2d681cc5e42e2ceeaa71b7716e67bdb5f9ace448bf68d8c61a3c52d006e0f31840062886",
          "sha256": "94bdb1b78ef029c40b0a56b9f650e2f66b4237508033bd93bdfe055a5484a666",
          "sha1": "8bda61a138f20365c703be1c9a850e72ca7a949f",
          "md5": "3e946c43d0f2334c8c0185d0a9f442ba"
        }
      ]
    }
  ]
}