{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigationevent/1.0.0-alpha07/navigationevent-1.0.0-alpha07.module",
    "group": "androidx.navigationevent",
    "module": "navigationevent",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13969651"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-iosArm64Main-1.0.0-alpha07.klib",
          "url": "navigationevent-iosarm64-1.0.0-alpha07.klib",
          "size": 56232,
          "sha512": "8d733ad1001f9d62ba8921451f020cf53fcc52a7b8118711210863fd4ec7a0a9aa80c768d092430f07682c2d5e5621480a263285b5c34de4404d535b7b6f2274",
          "sha256": "1eddd590969c332212b4a563f2c10d4f07c8a1ca7ea44ae834803270fd78c680",
          "sha1": "a79ed1092abef0e487c47c3715b0e1cc099abd45",
          "md5": "cd70634aad493e7dd5c3595e8194d3e0"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        }
      ],
      "files": [
        {
          "name": "navigationevent-iosarm64-1.0.0-alpha07-sources.jar",
          "url": "navigationevent-iosarm64-1.0.0-alpha07-sources.jar",
          "size": 33887,
          "sha512": "7370fbf1ae539ed60e28770fa4aeabc6962f4f8ffe328204fe54a673e486add86376823aa4d89ce5ebbdb30b565c339b8674f14b04bc211a7aa806800e4233b1",
          "sha256": "ff3d7339674c936520cc84e56744f16fc499f803c02c0e345e43fcf82b1e301a",
          "sha1": "2619cb8af3bc73baa1d10102ce67fd5776ee5c0e",
          "md5": "822738892b5cb9ae094b9f5e38429fbc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-testing",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "navigationevent is in atomic group androidx.navigationevent"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "navigationevent-iosarm64-1.0.0-alpha07-metadata.jar",
          "url": "navigationevent-iosarm64-1.0.0-alpha07-metadata.jar",
          "size": 6710,
          "sha512": "782e466304d8496a5f26db6c602e4fb0b592cd975f78a104ccc4b34c4245c33817a04c014dd161815b13f45e1e02a18fe525b4178bbe604066ffdf456d5bcf97",
          "sha256": "31a26d943ab6813626e7b2078f567643919b2fd86ed78d0aa58d809a1c416f93",
          "sha1": "9c0cc568c7a1d8ad110c1de4a46863420476dd86",
          "md5": "d8deed7bcbc5dca3737013dba2e71a07"
        }
      ]
    }
  ]
}