{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/1.3.0-alpha07/savedstate-1.3.0-alpha07.module",
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12961777"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-macosX64Main-1.3.0-alpha07.klib",
          "url": "savedstate-macosx64-1.3.0-alpha07.klib",
          "size": 88954,
          "sha512": "2cfd8e87014ef1082f61a8e35efc8cde7b9f72082c29dba38fc89cb627e1e9e8ba6b83884922f3e5e8a986971b992dfdfa6b1c374eb80f41b5b3af72ab824bff",
          "sha256": "6082003241c45d80c00b25a92227487b5c7849ebd29bbc3c53018e7cebdc3a1d",
          "sha1": "33cf21f6abdb61af81ce75dbfc7515754c7dad92",
          "md5": "5f124e8f4ef1f553ebc47dec48c32565"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-macosx64-1.3.0-alpha07-sources.jar",
          "url": "savedstate-macosx64-1.3.0-alpha07-sources.jar",
          "size": 36818,
          "sha512": "e8dc1174b13a5465cb31f3953ad731c2cb61933d400711bea8137f0f81e1a4e765ff8cd299c7799aa65b513e09f4ff2b33710e06cfc28f2a228aeeb1b7efe249",
          "sha256": "72c537906d318042da29db644a374d47166be66cfb5acfdcd744e6e97f799b1b",
          "sha1": "3664a433f7c221bc4a7c42571ac7c057efa73a87",
          "md5": "412f044bb2cf217ce00cbfea8a35dab0"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-macosx64-1.3.0-alpha07-metadata.jar",
          "url": "savedstate-macosx64-1.3.0-alpha07-metadata.jar",
          "size": 7960,
          "sha512": "3d4b101934615d57b863b7b6e61e9b80af46fb7d4d5d15e142377c4506cfe586d2a7e72fc5bf4261f0ab28345e6d60b0e4de8608c2aacbdcb93106ae02375690",
          "sha256": "da7ed036dc63bacf7963b38c587d69b8a45d8118fe57d51fafec235f2fa14f27",
          "sha1": "a092d90a6646e0d54486a95e15ae2d0666c015f2",
          "md5": "7c314c01343f1bda72ed2cb241baae27"
        }
      ]
    }
  ]
}