{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.2.0-rc01.aar",
          "url": "ui-graphics-1.2.0-rc01.aar",
          "size": 1394577,
          "sha512": "53a878b521d3d46d53fcaa759af71eded35b76db39104e1dc4df87af77cb94c2669b7fdc947012519052720720518c15d569e6ec7bdd0288dbd02c7ff35dd11b",
          "sha256": "0d4e5b3adbc8f512331d1cda3d090da02264cafe1f0b1f4b29cc7af887f0467d",
          "sha1": "605ec79f83157c6091d6b4342759845bba5449ae",
          "md5": "66613760ba110a91e5a4a064fdc7ceb8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.2.0-rc01.aar",
          "url": "ui-graphics-1.2.0-rc01.aar",
          "size": 1394577,
          "sha512": "53a878b521d3d46d53fcaa759af71eded35b76db39104e1dc4df87af77cb94c2669b7fdc947012519052720720518c15d569e6ec7bdd0288dbd02c7ff35dd11b",
          "sha256": "0d4e5b3adbc8f512331d1cda3d090da02264cafe1f0b1f4b29cc7af887f0467d",
          "sha1": "605ec79f83157c6091d6b4342759845bba5449ae",
          "md5": "66613760ba110a91e5a4a064fdc7ceb8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-1.2.0-rc01-sources.jar",
          "url": "ui-graphics-1.2.0-rc01-sources.jar",
          "size": 159036,
          "sha512": "fd24a48d169101ac01d80d0feaa1c5253b64fa53857c92e2453a7f7fc8cb0e3e987c1e4038982dcc4be0ff23a866ee442b8d222abebd71f8f32383592995a451",
          "sha256": "f27ffd53aeed2ec1eb0fe93e3a89a0a31db6796422ebf0a1735638446be6c97c",
          "sha1": "189e02b9e64ea1accc5b2de0d34383aaa1708329",
          "md5": "bd8f2a92f27726dd975dbe3415e5886e"
        }
      ]
    }
  ]
}