{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3/1.4.0-alpha11/material3-1.4.0-alpha11.module",
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.4.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13248195"
    }
  },
  "variants": [
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-alpha11"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-alpha11"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.4.0-alpha11"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-jvmstubs-1.4.0-alpha11.jar",
          "url": "material3-jvmstubs-1.4.0-alpha11.jar",
          "size": 5510870,
          "sha512": "df243416bbaef0f9912d601d12aaddec32f8ea184881d793c21a487d5173d858fbe9e69dc0bd7e670e99a811f55849420faa18c00eb395636fc263eb1aaab122",
          "sha256": "580ed7ba67e02e52406586469b045c94a8c8dbb9b32d23a8f028d672fc15f67c",
          "sha1": "2f085d104161c981caf69cd903183b89b6e58c3d",
          "md5": "601ca5403d04f22764dc73049617ea0f"
        }
      ]
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-alpha11"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-alpha11"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.4.0-alpha11"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "material3-jvmstubs-1.4.0-alpha11.jar",
          "url": "material3-jvmstubs-1.4.0-alpha11.jar",
          "size": 5510870,
          "sha512": "df243416bbaef0f9912d601d12aaddec32f8ea184881d793c21a487d5173d858fbe9e69dc0bd7e670e99a811f55849420faa18c00eb395636fc263eb1aaab122",
          "sha256": "580ed7ba67e02e52406586469b045c94a8c8dbb9b32d23a8f028d672fc15f67c",
          "sha1": "2f085d104161c981caf69cd903183b89b6e58c3d",
          "md5": "601ca5403d04f22764dc73049617ea0f"
        }
      ]
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-alpha11"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-alpha11"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.4.0-alpha11"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-jvmstubs-1.4.0-alpha11-sources.jar",
          "url": "material3-jvmstubs-1.4.0-alpha11-sources.jar",
          "size": 697711,
          "sha512": "4e5ae8f98a7b67527a71820483f6740333fb7ad0a063c173e11c6308be9c1f54e0da21018a2638e54c3bf716c78a809301c6a5e08e1e84dc10704dc77e6fd758",
          "sha256": "f6108d14f298c7726dce2f4bd874d52d4c34773df893af065f1d099feaf73813",
          "sha1": "5bff78f497c96bc0badec41d4a64a41179a39d39",
          "md5": "6ed4cf315a3d7a6713ab778a4b2322ff"
        }
      ]
    }
  ]
}