{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-testing",
    "version": "1.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13699310"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-testing-1.5.0-beta01-sources.jar",
          "url": "window-testing-1.5.0-beta01-sources.jar",
          "size": 25824,
          "sha512": "fb53faeac61c69b7210401acd8a371945542a767fa887ab4ab572ecd2a5f606a1d61fb08fe2ff8ba35b5f5af0d85f3c3c1e1953b1f7ed6d6764d79e3d9a3ceba",
          "sha256": "c7365da3e294be44e21f140ca2f5c11547dc03117650e277fbb5cb0ac028abd2",
          "sha1": "39da00560a547a97af5bfefd32f1ed114dcdac0e",
          "md5": "26226a48ad0364510e2587455c09e1d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-testing-1.5.0-beta01.aar",
          "url": "window-testing-1.5.0-beta01.aar",
          "size": 46064,
          "sha512": "6c5af373e5e7b4409cdd9cbf6171e4266b9eb9baa63aa462032ff4613a2e84cef94a24baed8b41a0599e0807a3b1718a82c8f73f1f2dec110619239fecbab1b6",
          "sha256": "3642bb740aa141cb91f85d8422ae4e99631105c62ab64d36d6fdc71d9fac55f0",
          "sha1": "fbc5f651a22f26117efdb3e3ee8a30f48d21f88d",
          "md5": "beb56af9f1921638a062d378e58e50c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-testing-1.5.0-beta01.aar",
          "url": "window-testing-1.5.0-beta01.aar",
          "size": 46064,
          "sha512": "6c5af373e5e7b4409cdd9cbf6171e4266b9eb9baa63aa462032ff4613a2e84cef94a24baed8b41a0599e0807a3b1718a82c8f73f1f2dec110619239fecbab1b6",
          "sha256": "3642bb740aa141cb91f85d8422ae4e99631105c62ab64d36d6fdc71d9fac55f0",
          "sha1": "fbc5f651a22f26117efdb3e3ee8a30f48d21f88d",
          "md5": "beb56af9f1921638a062d378e58e50c3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-testing is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-testing-1.5.0-beta01-versionMetadata.json",
          "url": "window-testing-1.5.0-beta01-versionMetadata.json",
          "size": 6038,
          "sha512": "3389fba585227278b7cfdb1f4072c6faa2f32128f43acfe06ade668d7b45753b7a7845144639269b230584478c70b94425dd6b9ec624561296297c1227452ec7",
          "sha256": "b4eea8ee957628cead81af19e8e9c539588ed66ca8b74eb33ae958aa2af8f6ca",
          "sha1": "90f0488e8e153aedca5e9b9a85b45fe81a3c8c3d",
          "md5": "e07a3438f6303bff96fa3f88e54d29c7"
        }
      ]
    }
  ]
}