{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.10.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14219255"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.10.0-alpha05-sources.jar",
          "url": "lifecycle-livedata-core-2.10.0-alpha05-sources.jar",
          "size": 12361,
          "sha512": "a86c62426d848b859088e1931ed974dd0cd5b467251ed46f7bcdb01776ee66aee419996546c8ffa50d378a76533d87e97f7d93452e32e45a8c0cc2562e5fbdc9",
          "sha256": "2a7e7f5ac6c3716d214cbeb2b6459c3d9de74e4fa169f99c198210626c701cba",
          "sha1": "b27b638e9048333080231acaabe4df0a6be0c6ef",
          "md5": "a2c22224955708f953531a3d48f97bf0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.10.0-alpha05.aar",
          "url": "lifecycle-livedata-core-2.10.0-alpha05.aar",
          "size": 34364,
          "sha512": "658b721af70f4072321510f2c71c8147247b32c9eb196cad358a7fca30c153001c62d22f60357a8f77faae75352a20a240aeb6b45308847ca1ce23f56c378a4b",
          "sha256": "e809dfba59f462aedd47c2cbb9f744f5faca2c72438d60c116fc253077910353",
          "sha1": "3897ee2d3dd2f720b12ef6a22738580b5437c91b",
          "md5": "08520138aff3fa1bfbff804b6f4a208f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.10.0-alpha05.aar",
          "url": "lifecycle-livedata-core-2.10.0-alpha05.aar",
          "size": 34364,
          "sha512": "658b721af70f4072321510f2c71c8147247b32c9eb196cad358a7fca30c153001c62d22f60357a8f77faae75352a20a240aeb6b45308847ca1ce23f56c378a4b",
          "sha256": "e809dfba59f462aedd47c2cbb9f744f5faca2c72438d60c116fc253077910353",
          "sha1": "3897ee2d3dd2f720b12ef6a22738580b5437c91b",
          "md5": "08520138aff3fa1bfbff804b6f4a208f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-navigation3",
          "version": {
            "requires": "2.10.0-alpha05"
          },
          "reason": "lifecycle-livedata-core is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.10.0-alpha05-versionMetadata.json",
          "url": "lifecycle-livedata-core-2.10.0-alpha05-versionMetadata.json",
          "size": 1478,
          "sha512": "1761adc34d5b70f622fe16126c562500a7598dfacb99adef90b422ec60dadce9a0e7b102c761e53fc4ffa456097e94e0f0d06b73578bc52b32927c0066dc2d95",
          "sha256": "bffc890c75aafe9adf105af2d499cbd59143de01772112c7b31a43cc3c0f6659",
          "sha1": "fcf0173ec1d18e336aedb73447316b905ada5b56",
          "md5": "3e2420dfc5d1704d1147147ff80c773e"
        }
      ]
    }
  ]
}