{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-unit-samples",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-unit-samples-1.2.0-alpha03.aar",
          "url": "ui-unit-samples-1.2.0-alpha03.aar",
          "size": 4385,
          "sha512": "0c17c3171166ca34fb86e2e8cc81baac98d9a2f3ae68dc9d25d206723f957167510fc2cef1f4929bb4071abfd4304e2002098897ae25a1ca8ef62fbec128258c",
          "sha256": "69dd2cd5895a480365e30275c3eb338c50cd0e96b8fb9236777fddd6943065c0",
          "sha1": "2bc971e1df1c1f20c10b2a21edaca648f2f86ec9",
          "md5": "49fc675c019a6b5b95f1faeb2a58b2c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "ui-unit-samples-1.2.0-alpha03.aar",
          "url": "ui-unit-samples-1.2.0-alpha03.aar",
          "size": 4385,
          "sha512": "0c17c3171166ca34fb86e2e8cc81baac98d9a2f3ae68dc9d25d206723f957167510fc2cef1f4929bb4071abfd4304e2002098897ae25a1ca8ef62fbec128258c",
          "sha256": "69dd2cd5895a480365e30275c3eb338c50cd0e96b8fb9236777fddd6943065c0",
          "sha1": "2bc971e1df1c1f20c10b2a21edaca648f2f86ec9",
          "md5": "49fc675c019a6b5b95f1faeb2a58b2c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-unit-samples-1.2.0-alpha03-sources.jar",
          "url": "ui-unit-samples-1.2.0-alpha03-sources.jar",
          "size": 1579,
          "sha512": "1bad171b700e4c0f17114e21bbd79eb1d30fe5e87025f2839c66c2818cd4f829f322f168834381538e2bcef000f72c8201df942bc7ecac83e4fa4ad6718873c8",
          "sha256": "12a5c233a99eb05cfadefcaffba76bebc8e220cb694db3c44fa26025c7123879",
          "sha1": "76735f3cf03b3f8cce1953cad579d5637d748173",
          "md5": "1bb4d2b42176226bd4d07ebcf124c2c3"
        }
      ]
    }
  ]
}
