{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220518001855+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.6.0-alpha05.aar",
          "url": "appcompat-resources-1.6.0-alpha05.aar",
          "size": 67506,
          "sha512": "6d0489b65579488cfd02870874c7cad6fbd7b272c4f69f954dd8d670a3dc3ab3f349fd3ccb17d308ef5acf03e5387bcf35a97f931d5ca1a7ce53320854be8ae5",
          "sha256": "12b2d5cb59ac1fd0f5655b3991f822231075cc5cb45cbb0fd297101d65eece7b",
          "sha1": "1056849fc94fb0d6820a6d6efa80cb9eb2388907",
          "md5": "7422626206cf41e454d4d647d09c9a2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.6.0-alpha05.aar",
          "url": "appcompat-resources-1.6.0-alpha05.aar",
          "size": 67506,
          "sha512": "6d0489b65579488cfd02870874c7cad6fbd7b272c4f69f954dd8d670a3dc3ab3f349fd3ccb17d308ef5acf03e5387bcf35a97f931d5ca1a7ce53320854be8ae5",
          "sha256": "12b2d5cb59ac1fd0f5655b3991f822231075cc5cb45cbb0fd297101d65eece7b",
          "sha1": "1056849fc94fb0d6820a6d6efa80cb9eb2388907",
          "md5": "7422626206cf41e454d4d647d09c9a2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.6.0-alpha05-sources.jar",
          "url": "appcompat-resources-1.6.0-alpha05-sources.jar",
          "size": 41078,
          "sha512": "b490b7d90e77fef59da1a4c4bbced46f42054e3f7af4402bb31c22a86cd781f23d411a3f066fab4e50d7b358f7bc093c2ff0a19d23f17f2f4d637faaad4a5ba9",
          "sha256": "fec905dd620354c86d3d2eacae24607a045fb00f8046719aec7583cf75422159",
          "sha1": "fb65e13b11cb4391567e748e9ab7f27a64601039",
          "md5": "2d834f6b94cb1c13e1c1364a07ddcae9"
        }
      ]
    }
  ]
}