{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-alpha08.aar",
          "url": "tracing-perfetto-1.0.0-alpha08.aar",
          "size": 22873,
          "sha512": "57434b3612db962e42092140f5e3837ddfb0c3e9fae08a3a34efebcde513e18735971cfe0acb689c7931182e1d6904d56751142dd5fb3a3e3fd8f21e60dee7c5",
          "sha256": "afd7fedb0221a2f5ad12d4709e6db1e3cc9f110ad23d0ead42fff5a860966004",
          "sha1": "ed797f709edc5ebe581455115a5988efed582831",
          "md5": "0942f4f702f9e3151b34911935f36ffc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-common",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-alpha08.aar",
          "url": "tracing-perfetto-1.0.0-alpha08.aar",
          "size": 22873,
          "sha512": "57434b3612db962e42092140f5e3837ddfb0c3e9fae08a3a34efebcde513e18735971cfe0acb689c7931182e1d6904d56751142dd5fb3a3e3fd8f21e60dee7c5",
          "sha256": "afd7fedb0221a2f5ad12d4709e6db1e3cc9f110ad23d0ead42fff5a860966004",
          "sha1": "ed797f709edc5ebe581455115a5988efed582831",
          "md5": "0942f4f702f9e3151b34911935f36ffc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-alpha08-sources.jar",
          "url": "tracing-perfetto-1.0.0-alpha08-sources.jar",
          "size": 12034,
          "sha512": "6572f3a7f8886cf9423ddcc978b54b5457dc2de1ebaa4e85113d008258a67dc810ccb603465d867ef9fe4b155b788e674fce4aaca54eba934a9355f234f3e0f5",
          "sha256": "684832938eb28b34e9ef35c0d17c97cc2d68d4361394f3a91f4689842abf400f",
          "sha1": "fcce0e1e908eb3a4a0db4d0ec345e144caa2fcc6",
          "md5": "febeb5acacb6772a307ca47332de4917"
        }
      ]
    }
  ]
}