{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-views",
    "version": "1.4.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-1.4.0-beta02.aar",
          "url": "emoji2-views-1.4.0-beta02.aar",
          "size": 13997,
          "sha512": "93bce49e7e2c2c95b9fc1b271f4aeea99e9ed36562b8ee2dec05f13d4e49203ae0160efbd39b07acc03a0cec4162ed8ef4f9766198396ff56d4b69ef7b38f042",
          "sha256": "6ba585276de10fbab00cf647dfacc8ed2dcb88817e4498b5c8aa506a2ad851b2",
          "sha1": "8c89cb97f61e09ecae60949b72f427450195a475",
          "md5": "7505e6022f3d43af63279a2b6360f9a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-1.4.0-beta02.aar",
          "url": "emoji2-views-1.4.0-beta02.aar",
          "size": 13997,
          "sha512": "93bce49e7e2c2c95b9fc1b271f4aeea99e9ed36562b8ee2dec05f13d4e49203ae0160efbd39b07acc03a0cec4162ed8ef4f9766198396ff56d4b69ef7b38f042",
          "sha256": "6ba585276de10fbab00cf647dfacc8ed2dcb88817e4498b5c8aa506a2ad851b2",
          "sha1": "8c89cb97f61e09ecae60949b72f427450195a475",
          "md5": "7505e6022f3d43af63279a2b6360f9a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta02"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-1.4.0-beta02-sources.jar",
          "url": "emoji2-views-1.4.0-beta02-sources.jar",
          "size": 11199,
          "sha512": "30cffdcd272d80feb1d0637fdb2a3f11ced8f02df2a4c8b02fb9f35fcad74ccf581a95d5f5571f0a44358e2b17bc5557da6edc74b013099ca07a6535bc8331ad",
          "sha256": "77ff753b82443e4584d84a0e80d9e49830f15ea3a28059c39955077d51f3f3b5",
          "sha1": "c21c54f48b0506f6f5a3758489b655aebdf357a2",
          "md5": "73fc0b7505391d49dac1a2db83dbd1ca"
        }
      ]
    }
  ]
}