{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/1.3.0-alpha08/savedstate-1.3.0-alpha08.module",
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.3.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13022914"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-desktop-1.3.0-alpha08.jar",
          "url": "savedstate-desktop-1.3.0-alpha08.jar",
          "size": 79884,
          "sha512": "5c788cc4aa7997a3ed721be2877d27aacfa69e117e18907e9c75efd0615d1298cc24052d15f4cd358e7563c1be5e9b0d7aad63ddd88882d1f02c407725e640c0",
          "sha256": "b5898887d1fbb33dbec66492f208e58ac51cc329c1467a07168f97136203582c",
          "sha1": "9416372b9440f11e60b473626421e4418f782990",
          "md5": "cb7cc13acc1781cb4faae7b277729dff"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-desktop-1.3.0-alpha08.jar",
          "url": "savedstate-desktop-1.3.0-alpha08.jar",
          "size": 79884,
          "sha512": "5c788cc4aa7997a3ed721be2877d27aacfa69e117e18907e9c75efd0615d1298cc24052d15f4cd358e7563c1be5e9b0d7aad63ddd88882d1f02c407725e640c0",
          "sha256": "b5898887d1fbb33dbec66492f208e58ac51cc329c1467a07168f97136203582c",
          "sha1": "9416372b9440f11e60b473626421e4418f782990",
          "md5": "cb7cc13acc1781cb4faae7b277729dff"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-desktop-1.3.0-alpha08-sources.jar",
          "url": "savedstate-desktop-1.3.0-alpha08-sources.jar",
          "size": 36684,
          "sha512": "8146a66b99da6bf2d70b9ca825eebddf9c73861dd4e4f75df1d1f91c3c759a2c1e4a7354861c16280414304a86b6432e08f6c5a3722bd1dc033a975e191ddaff",
          "sha256": "6e14c90719dfffa73a0a853ef53b52bf147e48c02b964fe14451af5116ba8968",
          "sha1": "7ed725ec2b9bba9e2b9f055f8f7301d30d3beedb",
          "md5": "a3db4cdc7b7e544b9740d3255851bda2"
        }
      ]
    }
  ]
}