{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource",
    "version": "1.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "media3-datasource-1.4.0-alpha02.aar",
          "url": "media3-datasource-1.4.0-alpha02.aar",
          "size": 161796,
          "sha512": "fda4760de83985418aa66b8a777c6223e20029d07686c24c900af7a98357847148a157a7b9895701a733551a8f4bd78e114619949ef02bdb88f908a38c87f822",
          "sha256": "3d143cad8f896b544884cdd7047babe1a5556fa790c8e0edf476809ea8d1484a",
          "sha1": "ae4327ef3aef88826972d2ad29d55113df8269cd",
          "md5": "e3d5646dcf0ded3a40d895df61e0c224"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-1.4.0-alpha02.aar",
          "url": "media3-datasource-1.4.0-alpha02.aar",
          "size": 161796,
          "sha512": "fda4760de83985418aa66b8a777c6223e20029d07686c24c900af7a98357847148a157a7b9895701a733551a8f4bd78e114619949ef02bdb88f908a38c87f822",
          "sha256": "3d143cad8f896b544884cdd7047babe1a5556fa790c8e0edf476809ea8d1484a",
          "sha1": "ae4327ef3aef88826972d2ad29d55113df8269cd",
          "md5": "e3d5646dcf0ded3a40d895df61e0c224"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-1.4.0-alpha02-sources.jar",
          "url": "media3-datasource-1.4.0-alpha02-sources.jar",
          "size": 133098,
          "sha512": "02df1618335fc5caf12c0d01b3915aab80dd4fcbf57b2293b2788aecb39baa5803878c8bdbf85c8d500e435d35bbeae903560694c1ae878fd9bbd615c51c9e94",
          "sha256": "90a11116e36dc38e66b7f363e20fddd4aaa15cbfe0fdf4a1c8598cdae5873a65",
          "sha1": "00a065b2ce4e2f445532709f6db9e0fef555c648",
          "md5": "29c209b89223d038126b3ff697a70eb0"
        }
      ]
    }
  ]
}
