{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3-adaptive-navigation-suite-samples",
    "version": "1.3.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0-beta03"
          },
          "reason": "material3-adaptive-navigation-suite-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.0-beta03"
          },
          "reason": "material3-adaptive-navigation-suite-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.0-beta03"
          },
          "reason": "material3-adaptive-navigation-suite-samples is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-adaptive-navigation-suite-samples-1.3.0-beta03-sources.jar",
          "url": "material3-adaptive-navigation-suite-samples-1.3.0-beta03-sources.jar",
          "size": 2784,
          "sha512": "34466b7b811ebe0f8cd63b7066a8bc930c3fb7de1e629f8fb409498d8231bcbf1db0fd4d0b7b5742edbf3dfce7490cf04086fa415b42d547a3c19f13076f878c",
          "sha256": "d6897c73204274682b997d4d6af9b0212cd2e371d2bd4e2320f5a3eba1522783",
          "sha1": "851cf34f7003a9630ed0c111e9a0dc5877bf34a2",
          "md5": "e9471f3ee418a8c74716bcae79469ce1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0-beta03"
          },
          "reason": "material3-adaptive-navigation-suite-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.0-beta03"
          },
          "reason": "material3-adaptive-navigation-suite-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.0-beta03"
          },
          "reason": "material3-adaptive-navigation-suite-samples is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-adaptive-navigation-suite-samples-1.3.0-beta03.aar",
          "url": "material3-adaptive-navigation-suite-samples-1.3.0-beta03.aar",
          "size": 41555,
          "sha512": "51dcaff3755fff33c32056246504f9218c543975d548bcbd1da317745790535a8eaad6d70c791fbf64422c0c9473136d0be5151f3c9679e6bc756bf5263c1d40",
          "sha256": "1a975c466c664798ce0775d7af36565425da70377f2cee786b3ee0110049ba40",
          "sha1": "7ab4a6a54948315f33925265489d83791f7c25a7",
          "md5": "ef603cf3ae77e7f29c5e416fb0eced77"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-rc01"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.0-beta03"
          }
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive",
          "version": {
            "requires": "1.0.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-rc01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0-beta03"
          },
          "reason": "material3-adaptive-navigation-suite-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.3.0-beta03"
          },
          "reason": "material3-adaptive-navigation-suite-samples is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.3.0-beta03"
          },
          "reason": "material3-adaptive-navigation-suite-samples is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-adaptive-navigation-suite-samples-1.3.0-beta03.aar",
          "url": "material3-adaptive-navigation-suite-samples-1.3.0-beta03.aar",
          "size": 41555,
          "sha512": "51dcaff3755fff33c32056246504f9218c543975d548bcbd1da317745790535a8eaad6d70c791fbf64422c0c9473136d0be5151f3c9679e6bc756bf5263c1d40",
          "sha256": "1a975c466c664798ce0775d7af36565425da70377f2cee786b3ee0110049ba40",
          "sha1": "7ab4a6a54948315f33925265489d83791f7c25a7",
          "md5": "ef603cf3ae77e7f29c5e416fb0eced77"
        }
      ]
    }
  ]
}