{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-samples",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "window-samples-1.1.0-beta01.aar",
          "url": "window-samples-1.1.0-beta01.aar",
          "size": 10951,
          "sha512": "38cd65f7d8906287bb7bcb810d25db7ff0eee060feefbc5d35f7685e91d6b20952f99aa765260d8b72b9985774ed941bbe6d789a4a0b7ceddf0ee1fe3d1e7626",
          "sha256": "1b94f29291bee658780d87971f05d48124227c78fcd1bbef22bfad9789cdf611",
          "sha1": "3c7bbf9503e30944f12458b72febfaff622e1c1e",
          "md5": "761f35596fdddb79e7cec79bee2e9643"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "window-samples-1.1.0-beta01.aar",
          "url": "window-samples-1.1.0-beta01.aar",
          "size": 10951,
          "sha512": "38cd65f7d8906287bb7bcb810d25db7ff0eee060feefbc5d35f7685e91d6b20952f99aa765260d8b72b9985774ed941bbe6d789a4a0b7ceddf0ee1fe3d1e7626",
          "sha256": "1b94f29291bee658780d87971f05d48124227c78fcd1bbef22bfad9789cdf611",
          "sha1": "3c7bbf9503e30944f12458b72febfaff622e1c1e",
          "md5": "761f35596fdddb79e7cec79bee2e9643"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "window-samples-1.1.0-beta01-sources.jar",
          "url": "window-samples-1.1.0-beta01-sources.jar",
          "size": 2426,
          "sha512": "4c1c3eb0ec28041b882c76d64662fa9508ace690603c4864bbd615ba63121da149d3f184e88dc945e51c2f44d74fb2d21d7e4d85bc209c1e158694b6f96a9546",
          "sha256": "8d1db5df1f223df99b9549e9f02f6ecd25ea681912395f667d323d345332e376",
          "sha1": "5bc566fea88775aacfc777cf1614435f0c2d10b3",
          "md5": "3dd61be806b5598f013af9037fce7ec3"
        }
      ]
    }
  ]
}