{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-graphics-samples",
    "version": "1.9.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13569180"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.9.0-alpha04-sources.jar",
          "url": "animation-graphics-samples-1.9.0-alpha04-sources.jar",
          "size": 6286,
          "sha512": "25c2ac65c9316d536e531124bddb0140ad29fe1b5fb6fe437cf3c7a57328d9725e22423bbc09cb217e9c401b520ba0ed75012c149c848f8c626050411019b4e2",
          "sha256": "d41253d43b24d905582b45e06e9ad947d29bcbe87f458d02c430983b185f0bc4",
          "sha1": "6e6cc9c839ddcfea9605dbf93316980f39a0639f",
          "md5": "e734f65c449a1faa090c1f4df91cda39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.9.0-alpha04.aar",
          "url": "animation-graphics-samples-1.9.0-alpha04.aar",
          "size": 10346,
          "sha512": "bb7bf3fda593d48adec90a4bc1cd6086f50ec968c12a47b575e34e21f457f505e1161bc0421f6269e697b758851d52434c5a65430e868aa44c678177d542a273",
          "sha256": "bfb79943b052b8ce01aa14c0ba207bd7c8c6fb733b70d4b87be55ead4a1a812e",
          "sha1": "6d922e159b851c0728fb1c9321973296836b699c",
          "md5": "dab5d032ba0c9206392076276eb4f207"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "animation-graphics-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "animation-graphics-samples-1.9.0-alpha04.aar",
          "url": "animation-graphics-samples-1.9.0-alpha04.aar",
          "size": 10346,
          "sha512": "bb7bf3fda593d48adec90a4bc1cd6086f50ec968c12a47b575e34e21f457f505e1161bc0421f6269e697b758851d52434c5a65430e868aa44c678177d542a273",
          "sha256": "bfb79943b052b8ce01aa14c0ba207bd7c8c6fb733b70d4b87be55ead4a1a812e",
          "sha1": "6d922e159b851c0728fb1c9321973296836b699c",
          "md5": "dab5d032ba0c9206392076276eb4f207"
        }
      ]
    }
  ]
}