{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-viewbinding-samples",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-samples-1.1.0-beta01.aar",
          "url": "ui-viewbinding-samples-1.1.0-beta01.aar",
          "size": 9721,
          "sha512": "9f020a2c370a139387225db2b91474fd0a9854fd3ef7b0d1c3c6ddd508667bed81321da028edb22ed5018ff315d159568ae5647c51152e2d57f9089de29e0b32",
          "sha256": "6242ebe53ba364d70ee072b3a3a54bc7ab41ba065dd56c755b55def3990c702f",
          "sha1": "ef12a8b62754e0c8236dbc329513903aa23f41ad",
          "md5": "44ebdd4a27bc1f1ec24a986b1f8beb22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.1.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ui-viewbinding-samples-1.1.0-beta01.aar",
          "url": "ui-viewbinding-samples-1.1.0-beta01.aar",
          "size": 9721,
          "sha512": "9f020a2c370a139387225db2b91474fd0a9854fd3ef7b0d1c3c6ddd508667bed81321da028edb22ed5018ff315d159568ae5647c51152e2d57f9089de29e0b32",
          "sha256": "6242ebe53ba364d70ee072b3a3a54bc7ab41ba065dd56c755b55def3990c702f",
          "sha1": "ef12a8b62754e0c8236dbc329513903aa23f41ad",
          "md5": "44ebdd4a27bc1f1ec24a986b1f8beb22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-viewbinding-samples-1.1.0-beta01-sources.jar",
          "url": "ui-viewbinding-samples-1.1.0-beta01-sources.jar",
          "size": 1517,
          "sha512": "8a312b184765944e6cdd2a19f32ef47de77d2124ebdebdeef7eadcf37f208bf2ea3e9d28f3762b5ee24263d9ab10cb5024ea4a095a56cda122998fffe59b94a2",
          "sha256": "a1e23ebca5ce3ac9f020ac001520017c0221eb8305544092b8a807fe48c82e0f",
          "sha1": "4a0578956b7cccf0d6a316c2e370305974b55c58",
          "md5": "4e0cb348f1b27b827ae8b187ebe50959"
        }
      ]
    }
  ]
}
