{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-manifest",
    "version": "1.0.0-beta08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.0.0-beta08.aar",
          "url": "ui-test-manifest-1.0.0-beta08.aar",
          "size": 1797,
          "sha512": "e8be2b8239d7f022f0ec5211aea31a81b62f1513ef14450b06f09b045a1b236c7b45066fe3a97758af3d1eb5c7bce28581d3306549abffeee7c84eedcacad65d",
          "sha256": "79831b2639c4b991a9527ffff87e09392eb4d0dc22f5b75588e3db829f7c4b19",
          "sha1": "29d4c42e9b28e4aa37ef7beb5e4cc5dfb64c4f28",
          "md5": "6b06a5a2c4dba3dc1bcbd1b4ca6a0787"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.0.0-beta08.aar",
          "url": "ui-test-manifest-1.0.0-beta08.aar",
          "size": 1797,
          "sha512": "e8be2b8239d7f022f0ec5211aea31a81b62f1513ef14450b06f09b045a1b236c7b45066fe3a97758af3d1eb5c7bce28581d3306549abffeee7c84eedcacad65d",
          "sha256": "79831b2639c4b991a9527ffff87e09392eb4d0dc22f5b75588e3db829f7c4b19",
          "sha1": "29d4c42e9b28e4aa37ef7beb5e4cc5dfb64c4f28",
          "md5": "6b06a5a2c4dba3dc1bcbd1b4ca6a0787"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-manifest-1.0.0-beta08-sources.jar",
          "url": "ui-test-manifest-1.0.0-beta08-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
