{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials-samples",
    "version": "1.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13759744"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0-alpha04"
          },
          "reason": "credentials-samples is in atomic group androidx.credentials"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha04"
          },
          "reason": "credentials-samples is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-samples-1.6.0-alpha04-sources.jar",
          "url": "credentials-samples-1.6.0-alpha04-sources.jar",
          "size": 7239,
          "sha512": "1ee633d1013b2183cef418dffdb9500b3a44d99e3c99793423a362924671ee4de542342eee40de11f1a2df2b629127d11c52848cedb23b23d0c70a012e95f920",
          "sha256": "96cd83931877cd1a45ca054fb691d132a2bea0e396cdacdf8662c6f48a88b458",
          "sha1": "a0b5f12eb38243c4331f41ab2fede931b1d6e4ad",
          "md5": "5eb1bb8e4567872e48582c79164f4b22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0-alpha04"
          },
          "reason": "credentials-samples is in atomic group androidx.credentials"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha04"
          },
          "reason": "credentials-samples is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-samples-1.6.0-alpha04.aar",
          "url": "credentials-samples-1.6.0-alpha04.aar",
          "size": 17105,
          "sha512": "472e24727dc2814991502e254379679b422ea5d3707a3e2ce255f944e0920b11d21183f1917e26c7ac078959f30ff702615a931939d2b0a1ed2e1e372069fbf8",
          "sha256": "0f5eabc35373f2d5f818fa1d7fac70c9a2921bf0946722b7c4ebcc78ec40b0ed",
          "sha1": "dc80ccbec3b0800cf649c53cbc36fb0fec874bac",
          "md5": "7f6cc5c721deadc6c2a327bb491ee72a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0-alpha04"
          },
          "reason": "credentials-samples is in atomic group androidx.credentials"
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha04"
          },
          "reason": "credentials-samples is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-samples-1.6.0-alpha04.aar",
          "url": "credentials-samples-1.6.0-alpha04.aar",
          "size": 17105,
          "sha512": "472e24727dc2814991502e254379679b422ea5d3707a3e2ce255f944e0920b11d21183f1917e26c7ac078959f30ff702615a931939d2b0a1ed2e1e372069fbf8",
          "sha256": "0f5eabc35373f2d5f818fa1d7fac70c9a2921bf0946722b7c4ebcc78ec40b0ed",
          "sha1": "dc80ccbec3b0800cf649c53cbc36fb0fec874bac",
          "md5": "7f6cc5c721deadc6c2a327bb491ee72a"
        }
      ]
    }
  ]
}