{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-samples",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runtime-samples-1.0.5.aar",
          "url": "runtime-samples-1.0.5.aar",
          "size": 159890,
          "sha512": "8eea47dd56e7f7110c203f0687783c47cbb9250e868ab9b1a4dc37b71faa17b2b1642274009991c7848d784128af9b768bf8ce419d2ba950c5e7507f3699a415",
          "sha256": "d064721050d1a46780ad86f09ecc2121b7105fc597ea41d58e36395f447b863c",
          "sha1": "cc7e5091d52f404715a5a929a071d1d6157a085e",
          "md5": "4ce00d453e1aedeebdce8c885787f5cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-samples-1.0.5.aar",
          "url": "runtime-samples-1.0.5.aar",
          "size": 159890,
          "sha512": "8eea47dd56e7f7110c203f0687783c47cbb9250e868ab9b1a4dc37b71faa17b2b1642274009991c7848d784128af9b768bf8ce419d2ba950c5e7507f3699a415",
          "sha256": "d064721050d1a46780ad86f09ecc2121b7105fc597ea41d58e36395f447b863c",
          "sha1": "cc7e5091d52f404715a5a929a071d1d6157a085e",
          "md5": "4ce00d453e1aedeebdce8c885787f5cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-samples-1.0.5-sources.jar",
          "url": "runtime-samples-1.0.5-sources.jar",
          "size": 16114,
          "sha512": "8f8d9ec50de088a06a0b0a9649d1a623fb372c7672afa5a088a167d668334830d1f6315438928e99b5447fe47b0c55c607b38b320f475314f882e462a9b9373d",
          "sha256": "d707439c7f9818588518e84e33b0be9640279ffe0557e20b53c9ee4cadee69a5",
          "sha1": "11ecbecf261b6e21206500e6928170881859b937",
          "md5": "ca5c9449a26a3ee61ee50e67fae231f3"
        }
      ]
    }
  ]
}
