{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation-experimental",
    "version": "1.2.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotation-experimental-1.2.0-beta01.aar",
          "url": "annotation-experimental-1.2.0-beta01.aar",
          "size": 33997,
          "sha512": "3ed03ef69eb08da275bf839938061cab37591ccc214aa328acc5f4de1510f72c99106ba751a73972fef4a567586e9e1d87dec0131a31ba544debb5a0406b9589",
          "sha256": "e80a626d5090d772902740f44a7b751a989082fa8db7a0f3db9a95826b03be8c",
          "sha1": "79051b63f34cc34a8a1c462b688ae8bdc768c5a2",
          "md5": "a17141a7ded0c550bd4abd6da16c12bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.2.0-beta01.aar",
          "url": "annotation-experimental-1.2.0-beta01.aar",
          "size": 33997,
          "sha512": "3ed03ef69eb08da275bf839938061cab37591ccc214aa328acc5f4de1510f72c99106ba751a73972fef4a567586e9e1d87dec0131a31ba544debb5a0406b9589",
          "sha256": "e80a626d5090d772902740f44a7b751a989082fa8db7a0f3db9a95826b03be8c",
          "sha1": "79051b63f34cc34a8a1c462b688ae8bdc768c5a2",
          "md5": "a17141a7ded0c550bd4abd6da16c12bf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.2.0-beta01-sources.jar",
          "url": "annotation-experimental-1.2.0-beta01-sources.jar",
          "size": 5453,
          "sha512": "2d5eb1ef30bf9c1f75bb6f7c71aad25f662544b9c54ee4a6301d8fd249c2748c2de7dd866b796717b7e42dace7cb1a3e41073dc1f8849859c37c327bc26aa24a",
          "sha256": "55f54ee78ea50e0e423d1c99ff211a64e9d5c40d57105349024dddc9e3b174a7",
          "sha1": "a5ae3f8e0e1ce7e1656fe9623c0b631e8ad06f91",
          "md5": "b7fbf8fc1d95182a4657ea188f6b0c97"
        }
      ]
    }
  ]
}
