{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable-samples",
    "version": "1.7.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-samples-1.7.0-alpha07.aar",
          "url": "runtime-saveable-samples-1.7.0-alpha07.aar",
          "size": 56607,
          "sha512": "0e74dd1543b18f43cb05b969c7149c88f1463bd2a2797534f40d8a8569d8bde8e0a7ffe660d4749c03f5be7664cdf7fcfa696481426202e4b1f2fcf2b6c78a8d",
          "sha256": "eb7b8db774fcad3ebaabc0d76079b5317b2c1ec828433f59862859bfe9da1113",
          "sha1": "31f7b2e899c521a66062ef83d9928909836e4ddd",
          "md5": "d7fc91d12eb5164a2b11aa0be6daa8ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha07"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-samples-1.7.0-alpha07.aar",
          "url": "runtime-saveable-samples-1.7.0-alpha07.aar",
          "size": 56607,
          "sha512": "0e74dd1543b18f43cb05b969c7149c88f1463bd2a2797534f40d8a8569d8bde8e0a7ffe660d4749c03f5be7664cdf7fcfa696481426202e4b1f2fcf2b6c78a8d",
          "sha256": "eb7b8db774fcad3ebaabc0d76079b5317b2c1ec828433f59862859bfe9da1113",
          "sha1": "31f7b2e899c521a66062ef83d9928909836e4ddd",
          "md5": "d7fc91d12eb5164a2b11aa0be6daa8ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0-alpha07"
          },
          "reason": "runtime-saveable-samples is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-samples-1.7.0-alpha07-sources.jar",
          "url": "runtime-saveable-samples-1.7.0-alpha07-sources.jar",
          "size": 4242,
          "sha512": "e5f63bc82457d1c674a170db0a329465d93b190448a285c5ab6ba21ac4dcafed89579d908c2adf5f2cc8da805f8e2c734fae396cd0d337cab26479675d8413a9",
          "sha256": "798fb6b311ed459c2028126a3deb7596b2742d8a0694db5fc93e236aa2a1316b",
          "sha1": "f455c0e1f32983bec40d871459943835e3d10c96",
          "md5": "54da7c450cadd9706f836a217bfa469f"
        }
      ]
    }
  ]
}