{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-rxjava3",
    "version": "1.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13699310"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-rxjava3-1.5.0-beta01-sources.jar",
          "url": "window-rxjava3-1.5.0-beta01-sources.jar",
          "size": 5783,
          "sha512": "17cc8126d4cf84dce543b2a613a3bbeebb9b70c09f7246b761821cc456e47f151830177dfa1ccd0353a46c21b2b7cb442afef1ac8b0f0ab45df52c304e13c98e",
          "sha256": "89897742134845f55e0696ee79bb31a64b1d032f349020ddbc756bbd3e245b4b",
          "sha1": "24863147b1da5905cd996a9a55e2318b7fad5fa7",
          "md5": "e379713126be6bacf6249bd916def301"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx3",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-rxjava3-1.5.0-beta01.aar",
          "url": "window-rxjava3-1.5.0-beta01.aar",
          "size": 7540,
          "sha512": "416cf550dee6aa94350a7993cb2cf5aeadc7efde0b35521a227aceb3a9bf8a831d8cfe3d2b5cc381cce4e3a8f090dc5e460482731ef25ca9a92fb596bcc21c18",
          "sha256": "8622c5f125db60a66ddd8ffcf4f05d7da29f1f7ba28892b9fbe78fc9d3c6c172",
          "sha1": "3c8f2819e5e06ed249406fae9286bda63ed0a3eb",
          "md5": "8db1c97547fba7a2d9f470f379227734"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx3",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-rxjava3-1.5.0-beta01.aar",
          "url": "window-rxjava3-1.5.0-beta01.aar",
          "size": 7540,
          "sha512": "416cf550dee6aa94350a7993cb2cf5aeadc7efde0b35521a227aceb3a9bf8a831d8cfe3d2b5cc381cce4e3a8f090dc5e460482731ef25ca9a92fb596bcc21c18",
          "sha256": "8622c5f125db60a66ddd8ffcf4f05d7da29f1f7ba28892b9fbe78fc9d3c6c172",
          "sha1": "3c8f2819e5e06ed249406fae9286bda63ed0a3eb",
          "md5": "8db1c97547fba7a2d9f470f379227734"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "window-rxjava3 is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-rxjava3-1.5.0-beta01-versionMetadata.json",
          "url": "window-rxjava3-1.5.0-beta01-versionMetadata.json",
          "size": 592,
          "sha512": "2213501c5d4d2d834729ea3c2bd595b27523b60d3ffa821055a87fadefc29e1ac41825e8e6ff57bb1bee16d86bda22b530bc2801ed05205863c958fbe0e4d514",
          "sha256": "c16f28081231c82789cc6e945904c1ed6f7208710b0a8ad41cac1c660d944980",
          "sha1": "c7db8327f224716348997f741c0071862fea8517",
          "md5": "a1650e3d1a59fa4909d6c9e98d8e8073"
        }
      ]
    }
  ]
}