{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.pdf",
    "module": "pdf-document-service",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13092615"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "pdf-document-service is in atomic group androidx.pdf"
        },
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer-fragment",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "pdf-document-service is in atomic group androidx.pdf"
        }
      ],
      "files": [
        {
          "name": "pdf-document-service-1.0.0-alpha07-sources.jar",
          "url": "pdf-document-service-1.0.0-alpha07-sources.jar",
          "size": 27863,
          "sha512": "b0d7150fa2493ba25671ab128c9af7c28651db6191d24e8d31ec619d7ec9465237b2c0e903a0f468c187be2f3c058a9193d04e633e7f899b3401ba84d14ab693",
          "sha256": "3dbdb8e0ae018069b41b41a1706e51ae9ab0ba9b27c8c816554cb3a2239b9386",
          "sha1": "e88c1f7dcbf6c3d5290684fbc16784a4bd27c390",
          "md5": "5f913b40c888081345b72c12d51f124b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "pdf-document-service is in atomic group androidx.pdf"
        },
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer-fragment",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "pdf-document-service is in atomic group androidx.pdf"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "pdf-document-service-1.0.0-alpha07.aar",
          "url": "pdf-document-service-1.0.0-alpha07.aar",
          "size": 92860,
          "sha512": "8baf5aa324f24924387cde81da8ff7b19b52d3bc24fe57cd8a77e05a0e49dfe77699cdabc26e174a69390eb76654f7ea7668516d1016480a4f52794b3d3fca60",
          "sha256": "756e366a27780671a3c3614c3eb5e96e60957808537065ad42cdbbdcf3d48d0d",
          "sha1": "4b2735d564c35dbc7dc34bdd408e8f98617ead3a",
          "md5": "7056589d3fc17b09a29f1da265fac36f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer",
          "version": {
            "requires": "1.0.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "pdf-document-service is in atomic group androidx.pdf"
        },
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer-fragment",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "pdf-document-service is in atomic group androidx.pdf"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "pdf-document-service-1.0.0-alpha07.aar",
          "url": "pdf-document-service-1.0.0-alpha07.aar",
          "size": 92860,
          "sha512": "8baf5aa324f24924387cde81da8ff7b19b52d3bc24fe57cd8a77e05a0e49dfe77699cdabc26e174a69390eb76654f7ea7668516d1016480a4f52794b3d3fca60",
          "sha256": "756e366a27780671a3c3614c3eb5e96e60957808537065ad42cdbbdcf3d48d0d",
          "sha1": "4b2735d564c35dbc7dc34bdd408e8f98617ead3a",
          "md5": "7056589d3fc17b09a29f1da265fac36f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "pdf-document-service is in atomic group androidx.pdf"
        },
        {
          "group": "androidx.pdf",
          "module": "pdf-viewer-fragment",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "pdf-document-service is in atomic group androidx.pdf"
        }
      ],
      "files": [
        {
          "name": "pdf-document-service-1.0.0-alpha07-versionMetadata.json",
          "url": "pdf-document-service-1.0.0-alpha07-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}