{
  "formatVersion": "1.1",
  "component": {
    "url": "../../savedstate/1.4.0-alpha02/savedstate-1.4.0-alpha02.module",
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13895212"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-wasm-js-1.4.0-alpha02.klib",
          "url": "savedstate-wasm-js-1.4.0-alpha02.klib",
          "size": 103067,
          "sha512": "55241284b2fa245f9ff3ab615b5c0186b48f8b183a0b34b21fdbf599b7df11ce528f82f1d561e44a9d08bf30c3843e85c010613660138bdd42449cce81eee9fc",
          "sha256": "e2f8e7df8754ada5876b1113392e5eb6277aecd48877fd82e91a6d74107c03d6",
          "sha1": "dc5025f7eae376fc30a7c9ae7c7cab0020db77f2",
          "md5": "0555bbed3e623466baccafad50741b50"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-wasm-js",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-wasm-js-1.4.0-alpha02.klib",
          "url": "savedstate-wasm-js-1.4.0-alpha02.klib",
          "size": 103067,
          "sha512": "55241284b2fa245f9ff3ab615b5c0186b48f8b183a0b34b21fdbf599b7df11ce528f82f1d561e44a9d08bf30c3843e85c010613660138bdd42449cce81eee9fc",
          "sha256": "e2f8e7df8754ada5876b1113392e5eb6277aecd48877fd82e91a6d74107c03d6",
          "sha1": "dc5025f7eae376fc30a7c9ae7c7cab0020db77f2",
          "md5": "0555bbed3e623466baccafad50741b50"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "savedstate is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-wasm-js-1.4.0-alpha02-sources.jar",
          "url": "savedstate-wasm-js-1.4.0-alpha02-sources.jar",
          "size": 45902,
          "sha512": "bff321cde24a197f02d1c99eeba363e53bf46efa41b86f9bc0344806356c611fcf19b44c3ab09d1f564ec18c144bf55e473907cd6b225a5ca37d9a4c3f51bf29",
          "sha256": "a9cc31f29a11113b192f14e0e3320a60ca3f340a44fc57d20f442d777e092693",
          "sha1": "2d3e6c537f09b9c09ce557d0cf5ee03f6a6351e4",
          "md5": "bfc43bb555388f2c33f668a7703a0d97"
        }
      ]
    }
  ]
}