{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles-testing",
    "version": "1.5.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12958867"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-testing-1.5.0-alpha07-sources.jar",
          "url": "tiles-testing-1.5.0-alpha07-sources.jar",
          "size": 6956,
          "sha512": "acfbdc01535da38dc0aaa63acd8a56fe8bb3da2747dbd6e0e4ec9caca02f023f79731f8300bc2a907e820c04ffab43f2fe493d56db2914aaf85f6f12f27c5f67",
          "sha256": "49ac7bd2730888767950d23d941f244a169260912401f3a44780df7b43f83239",
          "sha1": "8043ddb447cf0400f4bca03df9d1894febdeb267",
          "md5": "314fafd6a8f976f605b4933e3d9cb2e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha07"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-testing-1.5.0-alpha07.aar",
          "url": "tiles-testing-1.5.0-alpha07.aar",
          "size": 9554,
          "sha512": "0fd45e90b6a302589187f58dcbcdc52bba3c930952aacc2d218d46ea9f080f4aa7c61eeb44902a8d70cdac9108d87e36d6dbe625f9f99c1cc528442ac176d66c",
          "sha256": "9275c9ef19ee79a72e9d39f100d5c917f94c46e6a94b1af672d0d292bdbc936f",
          "sha1": "4af7405cad2d942561658e2c7cc775a2c82aa9e1",
          "md5": "352338ca572730a9916365aa46d68ca1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha07"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha07"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.robolectric",
          "module": "robolectric",
          "version": {
            "requires": "4.14"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-testing-1.5.0-alpha07.aar",
          "url": "tiles-testing-1.5.0-alpha07.aar",
          "size": 9554,
          "sha512": "0fd45e90b6a302589187f58dcbcdc52bba3c930952aacc2d218d46ea9f080f4aa7c61eeb44902a8d70cdac9108d87e36d6dbe625f9f99c1cc528442ac176d66c",
          "sha256": "9275c9ef19ee79a72e9d39f100d5c917f94c46e6a94b1af672d0d292bdbc936f",
          "sha1": "4af7405cad2d942561658e2c7cc775a2c82aa9e1",
          "md5": "352338ca572730a9916365aa46d68ca1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.5.0-alpha07"
          },
          "reason": "tiles-testing is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-testing-1.5.0-alpha07-versionMetadata.json",
          "url": "tiles-testing-1.5.0-alpha07-versionMetadata.json",
          "size": 785,
          "sha512": "01823a51f27a1e8d0649dd974727f2bb17a4ba1f8a635089081cf769767a3b866396a5635789e405c0b773e55f0200985a2afb7f2f254149127d3f746b66babb",
          "sha256": "1c9c5e34471985f9d39c289cc5633689a02e4420e01adcaa26576c326c23bd49",
          "sha1": "5352917425753112082232e6fc62ee3b86f6a9a3",
          "md5": "cc7cdba24975754a1eed96c2ab05deff"
        }
      ]
    }
  ]
}