{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-framework/2.5.0-alpha08/sqlite-framework-2.5.0-alpha08.module",
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.5.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework.klib",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha08.klib",
          "size": 26411,
          "sha512": "b1a6b19558fd0748f43a982169fa5a6652bb30521cc0d151925fc17220709908919b49e58c236325bdc09cd78d7f392430457ec16c7d4c1afc923f93c602c8b8",
          "sha256": "9345b44dc110d5c507c26bd2040d3fd5f6cb55832e26cebea98e567446bbc58c",
          "sha1": "882e649aa2a47a6f64a0dc0e68298359bef1765e",
          "md5": "329afbbf27cc3b11f64d4a0a103e0836"
        },
        {
          "name": "sqlite-framework-cinterop-sqlite3.klib",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha08-cinterop-sqlite3.klib",
          "size": 67003,
          "sha512": "623e7ded03c60c7718d9fb8a14e803ee10d61ea80448cfe58b2c3474049e4cbddf366cfc2e3baa2c24b5996a7106c52bd3ceaeb703eaa7e7b6441a6b790b1914",
          "sha256": "8f033e4f21b252bdffbed3bfca73a8fac96b03283ea72d91c1879dac7ab55673",
          "sha1": "2f240efc7d7568d5f6c7c4940d13a9c03b1826d7",
          "md5": "e771f3639e6a09512824dd85e623d802"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-macosarm64-2.5.0-alpha08-sources.jar",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha08-sources.jar",
          "size": 10553,
          "sha512": "454676d8094c4005e298b80988618f01b41c8652ca4ce6b5dc8b3f4563f53b3812f0efb142b9ede13a416baefc040105b1336f26e85ae4d84f7657bd0c5aed76",
          "sha256": "d80a2f621c8afa5e0f3301c5caf3f93f422ead1af2df32b533cae25d2a2b3530",
          "sha1": "e46feae1e866a14543fbad899b7b047ad1df2457",
          "md5": "294299af010fc75d367fc145f51169cd"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.5.0-alpha08"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-macosarm64-2.5.0-alpha08-metadata.jar",
          "url": "sqlite-framework-macosarm64-2.5.0-alpha08-metadata.jar",
          "size": 4410,
          "sha512": "8a1dad28d8f0d29f274c988e1a7148c09ed9d4ecd45478639880bcba187912e129f9facb6125401ea05111d74fb0cc233d54f3a3f2ede532995fc33a73eb6dd5",
          "sha256": "009b67f8ad4ce8bfb48d7315e4883cd1b39e82bd9caece95a12ba6b7da46e4c3",
          "sha1": "b8eff1a3305e8d209805c9f38543d55f90f938e7",
          "md5": "edd9c586c0f4762042a6f92d03946e16"
        }
      ]
    }
  ]
}