{
  "formatVersion": "1.1",
  "component": {
    "url": "../../foundation/1.8.0-beta01/foundation-1.8.0-beta01.module",
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.8.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12962786"
    }
  },
  "variants": [
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-linuxx64StubsMain-1.8.0-beta01.klib",
          "url": "foundation-linuxx64stubs-1.8.0-beta01.klib",
          "size": 2577204,
          "sha512": "1eeea4091ead447b7bf6e145d272e5f16bb31594b9178bf8e2d7734f29467f82cd60574b1986c287c8632220bd131ffe61127f61026dc0b88b5f78db9b98a85a",
          "sha256": "6eae4794b165335f95e8e76f6199352663eef1b1edfa60ba44ef97a90056272c",
          "sha1": "12640e5d6cffd4e5b5c643e3dadf519e35710036",
          "md5": "7149362b0673b5778b0e90f3ecc0bfab"
        }
      ]
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-lint",
          "version": {
            "requires": "1.8.0-beta01"
          },
          "reason": "foundation is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-linuxx64stubs-1.8.0-beta01-sources.jar",
          "url": "foundation-linuxx64stubs-1.8.0-beta01-sources.jar",
          "size": 831736,
          "sha512": "ff7cad473d9458c9f12f7476734fe400a2df0367773abe8b00d7c2e5bd1259c99b7f05d8301d6574dc45418336122b9972be9bf53f7e216930328ef808d6d09b",
          "sha256": "8f26a04adc76c34cddbcc2a33fbbb19d9f6236026a89674aaf5853fe36453378",
          "sha1": "861146fa3e18ab875e6eba44dcf14a76164ffb51",
          "md5": "e9acfa0ac9f49fe2e9aadf7a973f3556"
        }
      ]
    }
  ]
}