{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-rxjava3",
    "version": "1.0.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7123292"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava3-1.0.0-alpha12.aar",
          "url": "runtime-rxjava3-1.0.0-alpha12.aar",
          "size": 25664,
          "sha512": "02deb307e6b6e5b988d614b7e6ce41658474d6de2e69baebefc23c358e9dbfaeaf6f8592b81b5b189650c74aec0ab4f4d8ebfab71753be4c0a687d045aaeefcb",
          "sha256": "c97f229385f37183b84632b2c3441c55aa62b7cb3be1afe0db549b7c01029184",
          "sha1": "80073f39fe30cf063a163fcc122bcf28101063ca",
          "md5": "a62f2d6a3e8940b5f33498bfc8d9bffc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-alpha12"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-rxjava3-1.0.0-alpha12.aar",
          "url": "runtime-rxjava3-1.0.0-alpha12.aar",
          "size": 25664,
          "sha512": "02deb307e6b6e5b988d614b7e6ce41658474d6de2e69baebefc23c358e9dbfaeaf6f8592b81b5b189650c74aec0ab4f4d8ebfab71753be4c0a687d045aaeefcb",
          "sha256": "c97f229385f37183b84632b2c3441c55aa62b7cb3be1afe0db549b7c01029184",
          "sha1": "80073f39fe30cf063a163fcc122bcf28101063ca",
          "md5": "a62f2d6a3e8940b5f33498bfc8d9bffc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-rxjava3-1.0.0-alpha12-sources.jar",
          "url": "runtime-rxjava3-1.0.0-alpha12-sources.jar",
          "size": 2234,
          "sha512": "cb08a0d39fde12fe624d93f2e09c94cbe881f8b113df257744acc349138b04c6e7f6e8344cc659d878da9e4d0aeab34a58fd05d8be09eaaa18a8249e3336e372",
          "sha256": "e2d577605af518c7ef2b1dd8f91739602d6562ced82bdcd13cb6347c9f9cae54",
          "sha1": "6a81e97b8e1b3320b53e65ef75b07d2793bc99f4",
          "md5": "5b6eba3aa3b922dfd848803b0ea1a746"
        }
      ]
    }
  ]
}
