{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-lifecycle",
    "version": "1.0.0-rc05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7270731"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc05"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.0.0-rc05.aar",
          "url": "camera-lifecycle-1.0.0-rc05.aar",
          "size": 17170,
          "sha512": "a76138b9571c2b16275425bcb7dcc09d5e09a9f9d028b7eb1a948eb2238a547320f0c69be4801922aa1f3a23ec4069923e2567275f410d9ca57509ce9644867d",
          "sha256": "eeb3f4e55791b83e5ecba70e48d46f1ba8fcd0fae4fc53c0b200b3d25dd49927",
          "sha1": "24f7ff46ed5c5cfe068a960536761e9449a33932",
          "md5": "4ef231d59332f5ff6105441b2e29e0c4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc05"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "camera-lifecycle-1.0.0-rc05.aar",
          "url": "camera-lifecycle-1.0.0-rc05.aar",
          "size": 17170,
          "sha512": "a76138b9571c2b16275425bcb7dcc09d5e09a9f9d028b7eb1a948eb2238a547320f0c69be4801922aa1f3a23ec4069923e2567275f410d9ca57509ce9644867d",
          "sha256": "eeb3f4e55791b83e5ecba70e48d46f1ba8fcd0fae4fc53c0b200b3d25dd49927",
          "sha1": "24f7ff46ed5c5cfe068a960536761e9449a33932",
          "md5": "4ef231d59332f5ff6105441b2e29e0c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-lifecycle-1.0.0-rc05-sources.jar",
          "url": "camera-lifecycle-1.0.0-rc05-sources.jar",
          "size": 16559,
          "sha512": "565352004d25a1b5db3a00182898738688b235f4430dbd87b7b283a77a5d348ede3d79986a8a5d349d2e5cea1a599ca954f65b954b2a268f0a8c4cc9448f182c",
          "sha256": "6a79829b84bee8f2ce838821214ffabe34ebda25997ff46820c0d5ff54e34d45",
          "sha1": "f71daf6982e489ab25e2bdafbe4bd4e6155fd6f0",
          "md5": "0969033a4b3c351138cdaa1291adb550"
        }
      ]
    }
  ]
}
