{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3-samples",
    "version": "1.0.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "material3-samples-1.0.0-alpha15.aar",
          "url": "material3-samples-1.0.0-alpha15.aar",
          "size": 844727,
          "sha512": "9d51414101412e81bf7bde75f7812a4a70612a69d0946ab14b4005c426bf2b879d297de4f83975b678cf4792d9e2effb06082786b97100cd4e7c0051db0bfa3f",
          "sha256": "f194687249297b8ac1a0addfee0989cc86ad5c6b57f64a5c165a2c325817429c",
          "sha1": "127423c39723303750f5b831fc84b4e1d970dc85",
          "md5": "72f6d61ed669e11bc2d407b9d039beb7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.0-rc02"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.0.0-alpha15"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "material3-samples-1.0.0-alpha15.aar",
          "url": "material3-samples-1.0.0-alpha15.aar",
          "size": 844727,
          "sha512": "9d51414101412e81bf7bde75f7812a4a70612a69d0946ab14b4005c426bf2b879d297de4f83975b678cf4792d9e2effb06082786b97100cd4e7c0051db0bfa3f",
          "sha256": "f194687249297b8ac1a0addfee0989cc86ad5c6b57f64a5c165a2c325817429c",
          "sha1": "127423c39723303750f5b831fc84b4e1d970dc85",
          "md5": "72f6d61ed669e11bc2d407b9d039beb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-samples-1.0.0-alpha15-sources.jar",
          "url": "material3-samples-1.0.0-alpha15-sources.jar",
          "size": 32990,
          "sha512": "6e54d8ac37c3c81a6964a152ceb0f95e8e6882f6d092e4015efff4b9004531ebe943abf7ff5f177d60e1d4691d12c3adfcad6ff97ee6659644e53345d82413e7",
          "sha256": "76cd1442a1b4d117f4b17ebc6030db5119d4457f203803400eb7263a167f21d7",
          "sha1": "b759cb0cb3ad7e268e248e55711654408d8fc898",
          "md5": "27ff30c347cfa9032035e2b629949e68"
        }
      ]
    }
  ]
}