{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate-samples",
    "version": "2.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13943607"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-samples-2.9.3-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-samples-2.9.3-sources.jar",
          "size": 5593,
          "sha512": "dd0f37b2e8fed03d02d9c5e877884ac96df5f2a3ce667e81136d125efff42bfa5ba7bb3761ade2b1d0305a06e2c9e733fb6b3952467dc5abb2243a77cb5eaddc",
          "sha256": "db875f4851cbc4a6c89085aa0acc8b9517c9df7ad2c987da1c9111c2121247bb",
          "sha1": "f0e6ff50f158c97ed29349cdb28ca5b372205f46",
          "md5": "1d2700ef8f867b9eb49a77117a301aeb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-samples-2.9.3.aar",
          "url": "lifecycle-viewmodel-savedstate-samples-2.9.3.aar",
          "size": 34249,
          "sha512": "189246fd7bf0c71c1660f9dc0fd43e0b1dd63276abd52d8381c68b431ee16f4c7d976d72cc5422f8762be4833e6955deddc4c85e38e908d670ec04427f30c145",
          "sha256": "26dd2b891bcd2671cec411f425b677e83b353e32031e2b564a67d831d41939d0",
          "sha1": "599026175a27c4bd2db4ec681122fad8a730f8d5",
          "md5": "9f266d3fc74f6aa68e0f64bf15682e4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.3"
          },
          "reason": "lifecycle-viewmodel-savedstate-samples is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-samples-2.9.3.aar",
          "url": "lifecycle-viewmodel-savedstate-samples-2.9.3.aar",
          "size": 34249,
          "sha512": "189246fd7bf0c71c1660f9dc0fd43e0b1dd63276abd52d8381c68b431ee16f4c7d976d72cc5422f8762be4833e6955deddc4c85e38e908d670ec04427f30c145",
          "sha256": "26dd2b891bcd2671cec411f425b677e83b353e32031e2b564a67d831d41939d0",
          "sha1": "599026175a27c4bd2db4ec681122fad8a730f8d5",
          "md5": "9f266d3fc74f6aa68e0f64bf15682e4e"
        }
      ]
    }
  ]
}