{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13828034"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-metadata-1.5.0-alpha01.jar",
          "url": "material3-1.5.0-alpha01.jar",
          "size": 286416,
          "sha512": "f0f08d76eecaf0c764d67fdfbbdf2b9dc02c68ab513352471882ae73d7d70a2dea314ab9b3833bef2df33fc05e4a459bf138c0e3da238926e4d95b51657989e1",
          "sha256": "e18b3cc897c83c4b4c45c3c61025711030cf2845d5c8a16577e7102a3900bfab",
          "sha1": "4f7a5fcc486e360ecea65f40fe2687948b2e0b04",
          "md5": "d992d034589218aea67d61266c3752a1"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-kotlin-1.5.0-alpha01-sources.jar",
          "url": "material3-1.5.0-alpha01-sources.jar",
          "size": 738974,
          "sha512": "bd95833629002c44694f3b64fe3cc91210e7294dcbe73be87359823691d2fa8a98bbb1808f1b4a19174c4f3688b08b5ebdfea70f9b453d30f312dc2a35f96225",
          "sha256": "649d66095c18fac537ebab2637504506f14ba7d9569f8c1917fbb7a144c5297f",
          "sha1": "dab34e9abbd2f42a931f111a136257560d4a7241",
          "md5": "3da211f829703a5425a4bd908f239be6"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-1.5.0-alpha01-multiplatform-sources.jar",
          "url": "material3-1.5.0-alpha01-multiplatform-sources.jar",
          "size": 797169,
          "sha512": "ba7f8ff11cffa5553b74384def9cb24720b9479a31e01708d2f12d03d2db50aab7c59463cf40b8c93c9f98960f8451b08335464d2b1c32786cc8961f8d98fa6b",
          "sha256": "3e1f53bba0eb8b646c6b2e1919796c49ab26c026b1fc06e86cad4e933637f318",
          "sha1": "3a9a39bfff990c1d21d66fc8f3433aba14c75a7d",
          "md5": "95251a79a79a5ecd8a51d96b6c710700"
        },
        {
          "name": "material3-1.5.0-alpha01-samples-sources.jar",
          "url": "material3-1.5.0-alpha01-samples-sources.jar",
          "size": 89925,
          "sha512": "a1e3b2bbd676d69a166e0e575be1905f45a53efefacf14dc6449aeb59ab0afc8c05f4a17c1a5c77a02e79c3fa6fddb962249da32473d0aff44cb54e5fdf496df",
          "sha256": "3aefcb40899f3c8aef154009929a1fabdcc22db3084a8d82f4bea311f34c9d2d",
          "sha1": "4a84975fba6e35c4255a1315ec309e5435a9d30c",
          "md5": "6c2eea8da6f85ebfa9fabdcca0068bf6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material3-1.5.0-alpha01-versionMetadata.json",
          "size": 589053,
          "sha512": "b27451542d03deb29eed047f59564b0b8e274deb444bc6574a9e9f133415d0204d1de751c6e3bca8bcf7f633e60af85437d42c68d343a279dca9faf1d3c23a54",
          "sha256": "e4fd6c29bc7cdbf3525c25e27723e5e6544005de3997bd72c85b45cf5182e0c5",
          "sha1": "05c317f6e251675d59a56cbcaf371498786678cf",
          "md5": "e9b2e5a63917a770422cb433e3096c3f"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-android/1.5.0-alpha01/material3-android-1.5.0-alpha01.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.5.0-alpha01"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-android/1.5.0-alpha01/material3-android-1.5.0-alpha01.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.5.0-alpha01"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-android/1.5.0-alpha01/material3-android-1.5.0-alpha01.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.5.0-alpha01"
      }
    },
    {
      "name": "jvmStubsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-jvmstubs/1.5.0-alpha01/material3-jvmstubs-1.5.0-alpha01.module",
        "group": "androidx.compose.material3",
        "module": "material3-jvmstubs",
        "version": "1.5.0-alpha01"
      }
    },
    {
      "name": "jvmStubsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-jvmstubs/1.5.0-alpha01/material3-jvmstubs-1.5.0-alpha01.module",
        "group": "androidx.compose.material3",
        "module": "material3-jvmstubs",
        "version": "1.5.0-alpha01"
      }
    },
    {
      "name": "jvmStubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-jvmstubs/1.5.0-alpha01/material3-jvmstubs-1.5.0-alpha01.module",
        "group": "androidx.compose.material3",
        "module": "material3-jvmstubs",
        "version": "1.5.0-alpha01"
      }
    },
    {
      "name": "linuxx64StubsApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-linuxx64stubs/1.5.0-alpha01/material3-linuxx64stubs-1.5.0-alpha01.module",
        "group": "androidx.compose.material3",
        "module": "material3-linuxx64stubs",
        "version": "1.5.0-alpha01"
      }
    },
    {
      "name": "linuxx64StubsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material3-linuxx64stubs/1.5.0-alpha01/material3-linuxx64stubs-1.5.0-alpha01.module",
        "group": "androidx.compose.material3",
        "module": "material3-linuxx64stubs",
        "version": "1.5.0-alpha01"
      }
    }
  ]
}