{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-dynamic-features-fragment",
    "version": "2.4.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.4.0-alpha04"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.4.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-fragment-2.4.0-alpha04.aar",
          "url": "navigation-dynamic-features-fragment-2.4.0-alpha04.aar",
          "size": 96358,
          "sha512": "0ecc4daf8dbdb9b1e23694be43d878116be83fa418097b457429f3805beef2fa80e729af05ac7af800bc591bd763ee33036246b383296b0993257b4594ef1447",
          "sha256": "35dc9df83021634f65817f5974366bebc68426c845b9844c3f2b3db6a38e0016",
          "sha1": "65190e74c91183333656af28583e244b4d9280c9",
          "md5": "aa7526a07a3be4270c69d3eca659d502"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.4.0-alpha04"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.4.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-dynamic-features-fragment-2.4.0-alpha04.aar",
          "url": "navigation-dynamic-features-fragment-2.4.0-alpha04.aar",
          "size": 96358,
          "sha512": "0ecc4daf8dbdb9b1e23694be43d878116be83fa418097b457429f3805beef2fa80e729af05ac7af800bc591bd763ee33036246b383296b0993257b4594ef1447",
          "sha256": "35dc9df83021634f65817f5974366bebc68426c845b9844c3f2b3db6a38e0016",
          "sha1": "65190e74c91183333656af28583e244b4d9280c9",
          "md5": "aa7526a07a3be4270c69d3eca659d502"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-dynamic-features-fragment-2.4.0-alpha04-sources.jar",
          "url": "navigation-dynamic-features-fragment-2.4.0-alpha04-sources.jar",
          "size": 10621,
          "sha512": "5f888969a2f90fec76ddca1f450dd1eff82b43414a838c252249101598631ff2c3129f48006e5bdf0e1e57318cddf4fe3df108e9e96a4d3cfe43ff8b9a9e0a64",
          "sha256": "2f8bef65767c80f98d2219e00d9051b64528145e4a3243e2c231ae06781a9477",
          "sha1": "440443c644cef27590d715945423661c150ce7de",
          "md5": "768e03ba2d337992afe00258709605c6"
        }
      ]
    }
  ]
}
