{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.ink",
    "module": "ink-geometry",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0",
      "buildId:": "14202175"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-geometry-metadata-1.0.0-alpha07.jar",
          "url": "ink-geometry-1.0.0-alpha07.jar",
          "size": 4773,
          "sha512": "39e17e65e7df92036538a3f7f9454f08878e8e02434e9ca4f036d0191929dfa613f159be2587a3988aa10776112825a036c081bd4302302f2799b9efa6cae0b7",
          "sha256": "3259581ae9630100fc2c3a638c43cee6a82201890e4c704e3e7ea451933acc47",
          "sha1": "5aa5be1208af7eaa038cf75a3173063c042bbc55",
          "md5": "c22ffe3202b092a5f07373717e6d3c59"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-geometry-kotlin-1.0.0-alpha07-sources.jar",
          "url": "ink-geometry-1.0.0-alpha07-sources.jar",
          "size": 4376,
          "sha512": "f44773b837128b3a535925e970be4b142ec5d18ffc8e4d2b51db237d797ec5e4ee7705bac21d31e747c07e6f84156f48004f1cb1316f1f795aff291bcf4ca5a9",
          "sha256": "3a0fca327951717b8fd368e1bfe191c4cb8e1a79a4795698e860964feb389433",
          "sha1": "da14c120badcc879f2ea734ffac3122e167c08eb",
          "md5": "aad84decd2a31998acf2d7cdec895024"
        }
      ]
    },
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-geometry-1.0.0-alpha07-multiplatform-sources.jar",
          "url": "ink-geometry-1.0.0-alpha07-multiplatform-sources.jar",
          "size": 71390,
          "sha512": "23bee3a126ad7062e85e6bf1fd8c3c0f1c540a1c5040127193ad5a0c6206b81594b9ace9b713c118193cc88906c22abe28f89ea4e59a77c8fd1e6c0226705442",
          "sha256": "431f392bb1578212f8b1809ff1dbb44f83eb9d72e0bb1199d87de7053ba553c4",
          "sha1": "4d363b70fbb0237bf2a395dd3f19defa32739964",
          "md5": "ec88440254b97774a830b53110fc19bb"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha07"
          },
          "reason": "ink-geometry is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ink-geometry-1.0.0-alpha07-versionMetadata.json",
          "size": 30752,
          "sha512": "0465c6f4e2b4f9119a4bd4339fca904d1a049afb02b260135fae4b4af3e8fcf5cd402c1d3f5bf36f236171002b980063f2ca5c2bd88c7bff3cc30b2342a2629c",
          "sha256": "39380e76682138bf951e019ae2dc727268d2fc6d555e34a6d2e6447cd4bae2f0",
          "sha1": "0c4caa4acda68ce586d65b2e4865b57d5ea5f9f6",
          "md5": "c21065c1e153f9e4c1f1064ad98d799f"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-geometry-android/1.0.0-alpha07/ink-geometry-android-1.0.0-alpha07.module",
        "group": "androidx.ink",
        "module": "ink-geometry-android",
        "version": "1.0.0-alpha07"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-geometry-android/1.0.0-alpha07/ink-geometry-android-1.0.0-alpha07.module",
        "group": "androidx.ink",
        "module": "ink-geometry-android",
        "version": "1.0.0-alpha07"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-geometry-android/1.0.0-alpha07/ink-geometry-android-1.0.0-alpha07.module",
        "group": "androidx.ink",
        "module": "ink-geometry-android",
        "version": "1.0.0-alpha07"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-geometry-jvm/1.0.0-alpha07/ink-geometry-jvm-1.0.0-alpha07.module",
        "group": "androidx.ink",
        "module": "ink-geometry-jvm",
        "version": "1.0.0-alpha07"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-geometry-jvm/1.0.0-alpha07/ink-geometry-jvm-1.0.0-alpha07.module",
        "group": "androidx.ink",
        "module": "ink-geometry-jvm",
        "version": "1.0.0-alpha07"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ink-geometry-jvm/1.0.0-alpha07/ink-geometry-jvm-1.0.0-alpha07.module",
        "group": "androidx.ink",
        "module": "ink-geometry-jvm",
        "version": "1.0.0-alpha07"
      }
    }
  ]
}