{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-style",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-style-1.2.0-alpha02.aar",
          "url": "watchface-style-1.2.0-alpha02.aar",
          "size": 178468,
          "sha512": "8dd25faed352a7f503e97aac5ddae18c82216f8c3bf4a3337dc27e6e2a168c81967e5a2ab8f68ec792692182cd055c78568c32900e45aaa1c7a7b9872a30e157",
          "sha256": "5163514c559cc8fb7502709e28fbf0cbc8cfc9647c7e8b3f01d0f7ca1b261b67",
          "sha1": "29678ccea9721611e4c16e193140fbd4157b981a",
          "md5": "5d930fc1a701000a9aed88c8b489df48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "watchface-style-1.2.0-alpha02.aar",
          "url": "watchface-style-1.2.0-alpha02.aar",
          "size": 178468,
          "sha512": "8dd25faed352a7f503e97aac5ddae18c82216f8c3bf4a3337dc27e6e2a168c81967e5a2ab8f68ec792692182cd055c78568c32900e45aaa1c7a7b9872a30e157",
          "sha256": "5163514c559cc8fb7502709e28fbf0cbc8cfc9647c7e8b3f01d0f7ca1b261b67",
          "sha1": "29678ccea9721611e4c16e193140fbd4157b981a",
          "md5": "5d930fc1a701000a9aed88c8b489df48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "watchface-style-1.2.0-alpha02-sources.jar",
          "url": "watchface-style-1.2.0-alpha02-sources.jar",
          "size": 27182,
          "sha512": "5eed71c54cb2cac022a852b4e4fefe1427cd8f78c708d0bdfcac629783dc2e51aa67fc24220b5363c5872bca1b1bbfd7b2bb965995cfc2a6e5b3969fc16f04a2",
          "sha256": "2b81f5e39ade05614f3ef5337192988f67145d8e1c5fdafaaa0f8a21b180afe9",
          "sha1": "4da859569d7f3fc14a5b73500903a8c2322ace1a",
          "md5": "699b09311804b98e320e0cbe5241d0ed"
        }
      ]
    }
  ]
}