{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel/2.9.0-beta01/lifecycle-viewmodel-2.9.0-beta01.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel",
    "version": "2.9.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13310178"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-iosX64Main-2.9.0-beta01.klib",
          "url": "lifecycle-viewmodel-iosx64-2.9.0-beta01.klib",
          "size": 55810,
          "sha512": "ae81d62b2f109f72bd70b6535fd15d2ae0f5cd78ae259bf7b0863fcda950e19eb0b98d927b7c270882c1808ba6b490a96ce11d532b4d4eaa9b1394b3c315579e",
          "sha256": "4c23e6d4d7d5446c8a410fa58624481d8e50a716b71d0c99f34ab776ec776054",
          "sha1": "0a9a78a3478f99140d58078ca30b8ab25d735b09",
          "md5": "3d125f1420f663f38a0df46fdf20c991"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-iosx64-2.9.0-beta01-sources.jar",
          "url": "lifecycle-viewmodel-iosx64-2.9.0-beta01-sources.jar",
          "size": 36334,
          "sha512": "925b973f88ce84498bd1db64eedab7066a0309c73cc8da63f51ed0f6db690a969a4c16b2a7f503f516861756510e588d1515d2a5cc981d52febb599872ed6388",
          "sha256": "05bc8cc9870d6d8efcd6aee445559d1cd1a97319b9c9ae73440c927b9ab22e38",
          "sha1": "871eb5f77bfa57fa9f94f8f50427f3f433136a6f",
          "md5": "66cd2081ea615e9c90cc8cc980f8f0b6"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-beta01"
          },
          "reason": "lifecycle-viewmodel is in atomic group androidx.lifecycle"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-iosx64-2.9.0-beta01-metadata.jar",
          "url": "lifecycle-viewmodel-iosx64-2.9.0-beta01-metadata.jar",
          "size": 6857,
          "sha512": "9548dce8c6ae21da5ed2ee9d4403f9e09dafa4da03394c8fe24b588a4e45c9f85b2b35bc054b7b98bfbfcc26195a3fde563fea8ea6bcd4ec1cfc38a24b5b455a",
          "sha256": "98c5a35c2545d31eed3b9f0a1e25eba3b7771682bd677fa82afe52d00615faa1",
          "sha1": "e0de01a018af57f311ab7b942d73b31bf5c8c1ce",
          "md5": "06a1d3a395dca854011017f46e4d45f7"
        }
      ]
    }
  ]
}