{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.health.connect",
    "module": "connect-testing",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "connect-testing-1.0.0-alpha01-sources.jar",
          "url": "connect-testing-1.0.0-alpha01-sources.jar",
          "size": 19057,
          "sha512": "986d50e62088e8e5f055b2f66fbda18684bca71a406f7a6204da969d7afb227af7c3a4868574e0dc69b3691f28b399e4be5c586c7e35aadf9d6f1715c424b05f",
          "sha256": "541120e5674e45a918b91cc8ad48d9a3b03ee5e2f9d8fcfe9791e49f95665791",
          "sha1": "7512521c4152c896fc1a91fd7a7c0f6fe8418a28",
          "md5": "4235afcddca4ac563833b27ec54dbec2"
        },
        {
          "name": "connect-testing-1.0.0-alpha01-samples-sources.jar",
          "url": "connect-testing-1.0.0-alpha01-samples-sources.jar",
          "size": 8861,
          "sha512": "6f0e61ed223e2564b2985ba77c721ffbe2f8366edc9a9ddb1bf2f6690f31be70800a27a2a10b9f118c9391820b25061bb44f1403445c6a30623c6f73ae33aaf4",
          "sha256": "6e907d362175d2c8815a83bc703a850e1bb7af9f080422432e48c6b4d72969ab",
          "sha1": "b8555a1d3e31451a88779a6455f95e846dd35e7b",
          "md5": "df503dcf18b5488b2b6d008295e31639"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "connect-testing-1.0.0-alpha01.aar",
          "url": "connect-testing-1.0.0-alpha01.aar",
          "size": 43855,
          "sha512": "96a66c9677d08d34661c763d1d3a161cf9e9ae65f932ca0a378784343aa1bc1a7f6ab7deb3251dda4a8bc7621c962dfb0450b145db6cee5e346e8678b2d67779",
          "sha256": "413c33aa7b0fe4008d71798c5db1915fc7e69efbcb04d8636df9be40f043faad",
          "sha1": "2a2bc22d1e7a7cbbec057c60c623397f15936f66",
          "md5": "43a4516e421e7cd19482c9c7bf788797"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.1.0-alpha08"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client-proto",
          "version": {
            "requires": "1.1.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "connect-testing-1.0.0-alpha01.aar",
          "url": "connect-testing-1.0.0-alpha01.aar",
          "size": 43855,
          "sha512": "96a66c9677d08d34661c763d1d3a161cf9e9ae65f932ca0a378784343aa1bc1a7f6ab7deb3251dda4a8bc7621c962dfb0450b145db6cee5e346e8678b2d67779",
          "sha256": "413c33aa7b0fe4008d71798c5db1915fc7e69efbcb04d8636df9be40f043faad",
          "sha1": "2a2bc22d1e7a7cbbec057c60c623397f15936f66",
          "md5": "43a4516e421e7cd19482c9c7bf788797"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "connect-testing-1.0.0-alpha01-versionMetadata.json",
          "url": "connect-testing-1.0.0-alpha01-versionMetadata.json",
          "size": 10192,
          "sha512": "31f5c31e7421250134e74a6a94808d4ed06836222e781c65e8ce387e91faf1c53fbf773233abbc2d252fefaaf2073776942395563c87db8e27ecb90cca24552a",
          "sha256": "628d5d4826b0c3d3e148db1199313a8b3633701150543273a78f6c5ee93080ce",
          "sha1": "c565c8156303b75da80a017ca6b2a9ec39f93047",
          "md5": "444ddd8ad00102bab0a7cfa85471f4bc"
        }
      ]
    }
  ]
}