{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear-watchface-style",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7321851"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear-watchface-data",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "wear-watchface-style-1.0.0-alpha13.aar",
          "url": "wear-watchface-style-1.0.0-alpha13.aar",
          "size": 80489,
          "sha512": "18f16fd8f7ebe10ee1a67b382ea8560b5b1ed9a9616d1714e58e4af393b2452ed9d504088a42d65ef8efa8e8cd0b28610b77b253e892fb38b331bf40b990fd91",
          "sha256": "5d951c9bd09a0aaa2fa9677cf9c4002558b4c109f19281ac62d8e344d54624a7",
          "sha1": "2f03b7a6bd0658e68581c30a9c22b509873b5e4d",
          "md5": "dd9552f3ca240dfdf76e6b033b50c690"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear-watchface-data",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.32"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-watchface-style-1.0.0-alpha13.aar",
          "url": "wear-watchface-style-1.0.0-alpha13.aar",
          "size": 80489,
          "sha512": "18f16fd8f7ebe10ee1a67b382ea8560b5b1ed9a9616d1714e58e4af393b2452ed9d504088a42d65ef8efa8e8cd0b28610b77b253e892fb38b331bf40b990fd91",
          "sha256": "5d951c9bd09a0aaa2fa9677cf9c4002558b4c109f19281ac62d8e344d54624a7",
          "sha1": "2f03b7a6bd0658e68581c30a9c22b509873b5e4d",
          "md5": "dd9552f3ca240dfdf76e6b033b50c690"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-watchface-style-1.0.0-alpha13-sources.jar",
          "url": "wear-watchface-style-1.0.0-alpha13-sources.jar",
          "size": 11686,
          "sha512": "31120ac5944eeb0c5493d64c1f1ffa6fb6025933cfdcb01a44fa4e9437b4cea3104f0a99749987c899862463ba8de3e40e51bd4784df052755ebbeeaeb160f95",
          "sha256": "c75fe91dd9c31e7c5f96077f4e856603c0d9f0c1cd267c5b25eb3ca7c8ff8869",
          "sha1": "c928774bce9aedd50b7d9ddc648f8fcbb0e67fc9",
          "md5": "450eab207fbf285cf2213aee274e451b"
        }
      ]
    }
  ]
}
