{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-text",
    "version": "1.0.0-beta08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-beta08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-beta08"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.0.0-beta08.aar",
          "url": "ui-text-1.0.0-beta08.aar",
          "size": 445943,
          "sha512": "79c2256e6327ce5a2b8965aae868e80d1fbbb943eeae250acc5d51d1c14b60966846c91497c92ff7c164a56a196492c9a08e5833f25739cba54ca5b7ef294c55",
          "sha256": "13cd70b64696c1048c750d4c712f899eecf1e0d5e4e1186cf13c6fd7dffecf3a",
          "sha1": "47d3482b4fc3e57af6f02f0005d84807c70d937a",
          "md5": "60670fe6b38f92adc376d7711e61e0c0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.0.0-beta08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.0-beta08"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.0-beta08"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.0-beta08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0-beta08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-rc02"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-1.0.0-beta08.aar",
          "url": "ui-text-1.0.0-beta08.aar",
          "size": 445943,
          "sha512": "79c2256e6327ce5a2b8965aae868e80d1fbbb943eeae250acc5d51d1c14b60966846c91497c92ff7c164a56a196492c9a08e5833f25739cba54ca5b7ef294c55",
          "sha256": "13cd70b64696c1048c750d4c712f899eecf1e0d5e4e1186cf13c6fd7dffecf3a",
          "sha1": "47d3482b4fc3e57af6f02f0005d84807c70d937a",
          "md5": "60670fe6b38f92adc376d7711e61e0c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-text-1.0.0-beta08-sources.jar",
          "url": "ui-text-1.0.0-beta08-sources.jar",
          "size": 171482,
          "sha512": "46078fbcc708f34e5d29462757c60fc2889cca552dbd82b44b3e14b3e2ae827c3a82b37e39a95cddfc71d6204e2d95bf331e7fac07a420c0db49003005b7deed",
          "sha256": "93771dfc878c5fadc1c4895c73769d41d3dd05f646764fd1f3d28d99130d7422",
          "sha1": "8c35eb0f9e970128787bd1a07bd272f5b2825746",
          "md5": "7efbf3189a5924ff9b8a11200ee22b4d"
        }
      ]
    }
  ]
}
