{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-ktx",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-ktx-1.3.0-alpha01.aar",
          "url": "tracing-ktx-1.3.0-alpha01.aar",
          "size": 6013,
          "sha512": "21d345ddce3a5399cc09305fc5d87261306677f511f3ada804788f1156ef109aeee21db850599ea0062f8dc35ea192ac78338f05e54201beda2cae5835a48ed7",
          "sha256": "03ecdb97ed849ceefd3de26891fd8fd9aa660a533d81f9a0f896adc025c44b7d",
          "sha1": "75926b530243aa3d5d3ac8e08fddc0dbb037f672",
          "md5": "ee028f9090bbf38da4bf65516787cea2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-ktx-1.3.0-alpha01.aar",
          "url": "tracing-ktx-1.3.0-alpha01.aar",
          "size": 6013,
          "sha512": "21d345ddce3a5399cc09305fc5d87261306677f511f3ada804788f1156ef109aeee21db850599ea0062f8dc35ea192ac78338f05e54201beda2cae5835a48ed7",
          "sha256": "03ecdb97ed849ceefd3de26891fd8fd9aa660a533d81f9a0f896adc025c44b7d",
          "sha1": "75926b530243aa3d5d3ac8e08fddc0dbb037f672",
          "md5": "ee028f9090bbf38da4bf65516787cea2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-ktx-1.3.0-alpha01-sources.jar",
          "url": "tracing-ktx-1.3.0-alpha01-sources.jar",
          "size": 1656,
          "sha512": "b24e54a7e3aa29abb281c89aa34fa9fe492063958b6c92778f8719415a88223e3075d82c03cc6c2a5c91e3e3d14b0d845c97eaf69a04b17b8b5c5e8ed57347e9",
          "sha256": "610a5837e1efa2ad4dc940f1b308bd020d2d6d2b02fcebdf27b0b7b23f5e0a5a",
          "sha1": "1c3ce12844007242d296d73e1188d076784b5183",
          "md5": "40b9479530f86f54fa37bd49d94d2b28"
        }
      ]
    }
  ]
}