{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lifecycle-viewmodel-savedstate/2.9.0-alpha06/lifecycle-viewmodel-savedstate-2.9.0-alpha06.module",
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.9.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate.klib",
          "url": "lifecycle-viewmodel-savedstate-linuxx64-2.9.0-alpha06.klib",
          "size": 10020,
          "sha512": "7c9a6a9a864e3e407351169660803bd0e6fcd5b4504b311d6e716c272fb6f7ebc27aa97f3c9fe6f654edba9ff904ae6bff03e4d9714d1b5b8d24d10ad1179257",
          "sha256": "836cd6ea995c11c89ca5e5069a160b8671b4413ea5f3162f118b393ecdcbefc0",
          "sha1": "22fcad46de6555f674cef2e42d9b26be0b0c8e38",
          "md5": "f81c5a388858921e25dbc46d2e3f2c37"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-compiler",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-reactivestreams-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "lifecycle-viewmodel-savedstate is in atomic group androidx.lifecycle"
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-linuxx64-2.9.0-alpha06-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-linuxx64-2.9.0-alpha06-sources.jar",
          "size": 5497,
          "sha512": "066f9132dee144ee8d349e7c4eb3827c97d1889f5f4d8326c532c244529db3dba0ea203eb54c2baef9721f3925f5b68d08e736f3b9c3831250510a795f1218c6",
          "sha256": "f41be1cd040b6db8be293748c4f40f2301a4cabfe7944070a766eafe96d3dd5e",
          "sha1": "672b5221dbbb842eb847f7ffa287623f8dba92d2",
          "md5": "efbf44526c3113228df9458040643fbe"
        }
      ]
    }
  ]
}