{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate-ktx",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha03-sources.jar",
          "url": "savedstate-ktx-1.3.0-alpha03-sources.jar",
          "size": 4426,
          "sha512": "470b68b1ba0bbefe5afcf0a072635a72e5080f040860d900c972c9797c1ab4c2402ad6a622477ea916ecc6ece19b0290e15a391f7f1a0ea00c612b1da3ea6d82",
          "sha256": "b1e8d78600a68fb3c0029793146ac07ea0335819f813554e85c568caa35cb5e4",
          "sha1": "d281a4d66d1b5ed25c21373dedb46a67918618d9",
          "md5": "c7dd8c25948273de8256385c8a05e3d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha03.aar",
          "url": "savedstate-ktx-1.3.0-alpha03.aar",
          "size": 5595,
          "sha512": "14890fded4597be3af60c21f4ca41f6d137a722025800713a2a4b84696ddf963453f5e28a550080ebfd0366fd23dd04e1151bebe5e913f99ab2c7adc6827b152",
          "sha256": "4c8f8feedab717d1cdd989d8b0d3127984a0896615b49f152db1f243f85d5515",
          "sha1": "077b583d3122c86e186c8ef99e0f5acf1ede3a5c",
          "md5": "af72d9c6c5139547e7e4e11ea52b7a9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha03.aar",
          "url": "savedstate-ktx-1.3.0-alpha03.aar",
          "size": 5595,
          "sha512": "14890fded4597be3af60c21f4ca41f6d137a722025800713a2a4b84696ddf963453f5e28a550080ebfd0366fd23dd04e1151bebe5e913f99ab2c7adc6827b152",
          "sha256": "4c8f8feedab717d1cdd989d8b0d3127984a0896615b49f152db1f243f85d5515",
          "sha1": "077b583d3122c86e186c8ef99e0f5acf1ede3a5c",
          "md5": "af72d9c6c5139547e7e4e11ea52b7a9e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.3.0-alpha03-versionMetadata.json",
          "url": "savedstate-ktx-1.3.0-alpha03-versionMetadata.json",
          "size": 191,
          "sha512": "225072cf1e54fc7479700f5339019ceafe1f9e4d514a8893a626190d42dfb31b35804c73597292ee864e5f3034bc73b4c5806109ed130eb268c531948a4be4b7",
          "sha256": "ff1847220d3c526a133e4f76baed2060de09a72ac96f5b8e1fef2ab1d21ba85e",
          "sha1": "a1a2692ed79fa0caa20fafeb33e56bd48993f6de",
          "md5": "57c4eed7a9c15485d30d344fdc944a0a"
        }
      ]
    }
  ]
}