{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-core",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.19.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha01.jar",
          "url": "tools-core-1.0.0-alpha01.jar",
          "size": 206332,
          "sha512": "d5cd346387bb3fd369c50a2dadf9fcba3bd246131babe59d1d211efdd209a53ceb7bfabdb290378ae3e46001834e1baa8578676e9b0e54fe0be76692fb28818b",
          "sha256": "dc0d809d07dc6fe5c89a55fe6f4e376ba3051a12d05fba7ef8180bb311cc44ef",
          "sha1": "e85fc405f0f7cf73eab001a532e2851f1d83140d",
          "md5": "86461ef84bbfd2f63654959c28dd443f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.19.4"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha01.jar",
          "url": "tools-core-1.0.0-alpha01.jar",
          "size": 206332,
          "sha512": "d5cd346387bb3fd369c50a2dadf9fcba3bd246131babe59d1d211efdd209a53ceb7bfabdb290378ae3e46001834e1baa8578676e9b0e54fe0be76692fb28818b",
          "sha256": "dc0d809d07dc6fe5c89a55fe6f4e376ba3051a12d05fba7ef8180bb311cc44ef",
          "sha1": "e85fc405f0f7cf73eab001a532e2851f1d83140d",
          "md5": "86461ef84bbfd2f63654959c28dd443f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-core-1.0.0-alpha01-sources.jar",
          "url": "tools-core-1.0.0-alpha01-sources.jar",
          "size": 35110,
          "sha512": "783acf632610475e3c500d71e1260be4f06307e79563b85f3ec008f946d9caf956cf1ef154d785b5e8c45bbfe65037fb4848196e27405f218cda8cb0f2f3747d",
          "sha256": "67d97562b8c3c1b307f869ccec94aca22327115db0cf6ff8957965003e1877cf",
          "sha1": "97258c64898bf5cfdf189d226a8a00be5e616ac7",
          "md5": "04cc128682dabbe5b72c0e423c2f1f6d"
        }
      ]
    }
  ]
}