{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core-samples",
    "version": "1.6.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.6.0-beta01.aar",
          "url": "animation-core-samples-1.6.0-beta01.aar",
          "size": 188140,
          "sha512": "65d94deab2b6e55e51b008d20ff81b553d022527d9e2a5c31a34de3a8a56bae865118b26da023c1d5de50f1d9608a4c072b751d5b942d127e1768d4c817d6802",
          "sha256": "3cb31757ca4ad627b903c192af80bf75dda50e4f356adac218c2928e611edb4f",
          "sha1": "802602eba39958f8158d18fc42153cd7c2dc4efa",
          "md5": "de9738b1b7e9fedd354ccfe8d9799339"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-beta01"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-beta01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.6.0-beta01.aar",
          "url": "animation-core-samples-1.6.0-beta01.aar",
          "size": 188140,
          "sha512": "65d94deab2b6e55e51b008d20ff81b553d022527d9e2a5c31a34de3a8a56bae865118b26da023c1d5de50f1d9608a4c072b751d5b942d127e1768d4c817d6802",
          "sha256": "3cb31757ca4ad627b903c192af80bf75dda50e4f356adac218c2928e611edb4f",
          "sha1": "802602eba39958f8158d18fc42153cd7c2dc4efa",
          "md5": "de9738b1b7e9fedd354ccfe8d9799339"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.6.0-beta01"
          },
          "reason": "animation-core-samples is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-core-samples-1.6.0-beta01-sources.jar",
          "url": "animation-core-samples-1.6.0-beta01-sources.jar",
          "size": 18899,
          "sha512": "f636f50e54cc0784823718c5b026c7d5b52f66be04a4fe051b4dba636078f8e139a8e61d59fe98af852ee5d0e578921ca50774064da1a0cf844789afd131d1e3",
          "sha256": "62387e00e443b95faef3983bd0d4ca292f18080785d5c6d6d328aac0bdcf35d0",
          "sha1": "b76d91827def4ed1fc06b1fc6888711db1fe0881",
          "md5": "47aa1d5380614d293e34b8b857f3efa8"
        }
      ]
    }
  ]
}