{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ink-authoring/1.0.0-alpha06/ink-authoring-1.0.0-alpha06.module",
    "group": "androidx.ink",
    "module": "ink-authoring",
    "version": "1.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13895212"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-authoring.aar",
          "url": "ink-authoring-android-1.0.0-alpha06.aar",
          "size": 196666,
          "sha512": "6db2813cc3aff07c4fe6819091a1bad43aca43272ae5302d745b43783f822c0ae879bab3e9bf1af456f01d314ebceb932f31554308ddf0da4cc6beebc7cca217",
          "sha256": "1b1b190ca03bc31cbd91ffd26aa43a298f55340f6ed46f58af891a3c528769fa",
          "sha1": "956500506ff4f69abdcf3f642ffe59a56d409085",
          "md5": "493f4a881ba85be0577dab91185d74ca"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.16.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0-rc01"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.7"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-core",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-idling-resource",
          "version": {
            "requires": "3.5.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-authoring.aar",
          "url": "ink-authoring-android-1.0.0-alpha06.aar",
          "size": 196666,
          "sha512": "6db2813cc3aff07c4fe6819091a1bad43aca43272ae5302d745b43783f822c0ae879bab3e9bf1af456f01d314ebceb932f31554308ddf0da4cc6beebc7cca217",
          "sha256": "1b1b190ca03bc31cbd91ffd26aa43a298f55340f6ed46f58af891a3c528769fa",
          "sha1": "956500506ff4f69abdcf3f642ffe59a56d409085",
          "md5": "493f4a881ba85be0577dab91185d74ca"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.ink",
          "module": "ink-authoring-compose",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-brush-compose",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-geometry-compose",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-nativeloader",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-storage",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-strokes",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        },
        {
          "group": "androidx.ink",
          "module": "ink-rendering",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ink-authoring is in atomic group androidx.ink"
        }
      ],
      "files": [
        {
          "name": "ink-authoring-android-1.0.0-alpha06-sources.jar",
          "url": "ink-authoring-android-1.0.0-alpha06-sources.jar",
          "size": 90265,
          "sha512": "8e93eea3d2d8f101dc2224870dd920b385cc80db89cd7c8412eb28e38e0e6af39d42cb7f643e2538b69e7c8d74a69a0554669a88145e70c63f603c4f3d077672",
          "sha256": "fdbdfdf7ebfc42e5d6cf7099ded4f76d3675657b8d61cd2eb75756c2db48cf23",
          "sha1": "943cf779269e4e3a92cc09f6aa6601e2bcb566cc",
          "md5": "f83a2e7d53d73226e1aa9c7b900c951d"
        }
      ]
    }
  ]
}