{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appsearch",
    "module": "appsearch",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7322716"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "appsearch-1.0.0-alpha01.aar",
          "url": "appsearch-1.0.0-alpha01.aar",
          "size": 96058,
          "sha512": "8f294ff8f8d4572823b73f2f723f87476b9a52a3f6e4cc3aff775ffa765f3caa204edef382d9a48ef1cb403bfc1bcf036faa6f98ff77e22eab00edd17df85a86",
          "sha256": "c89e080be587d8f7498cb8e96c739a8fe5eab9b5fc583083b8abcd3cdeb044d2",
          "sha1": "ec846cafe09e7a1493446e9875ba3cd6117e4730",
          "md5": "eda5aa820461151dce290ffd918c4ac8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.2"
          }
        }
      ],
      "files": [
        {
          "name": "appsearch-1.0.0-alpha01.aar",
          "url": "appsearch-1.0.0-alpha01.aar",
          "size": 96058,
          "sha512": "8f294ff8f8d4572823b73f2f723f87476b9a52a3f6e4cc3aff775ffa765f3caa204edef382d9a48ef1cb403bfc1bcf036faa6f98ff77e22eab00edd17df85a86",
          "sha256": "c89e080be587d8f7498cb8e96c739a8fe5eab9b5fc583083b8abcd3cdeb044d2",
          "sha1": "ec846cafe09e7a1493446e9875ba3cd6117e4730",
          "md5": "eda5aa820461151dce290ffd918c4ac8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appsearch-1.0.0-alpha01-sources.jar",
          "url": "appsearch-1.0.0-alpha01-sources.jar",
          "size": 77318,
          "sha512": "c415f9ff0c9515c387cd688e7061a65b64425da98c58d5b28f315fdcddbd9f2196a710f7bbeb54b933793354f9ff5af5cd41862d2b8536657134c6e0dc45bb19",
          "sha256": "2203100409bfdecb66c6c2cb1489953f1726d28b99007a8b70d5716a681ef2ad",
          "sha1": "1dabd7039b5cb567b55658a801bfc6351caa414a",
          "md5": "8a6bd8eaf73c31a816c49351ec270a69"
        }
      ]
    }
  ]
}
