{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-navigation-compose-samples",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-samples-1.1.0-alpha01.aar",
          "url": "hilt-navigation-compose-samples-1.1.0-alpha01.aar",
          "size": 17025,
          "sha512": "6d4e3721326e211e4b5d9697a1b7879cd0fe7de38d40fa544fb0b0172817fc5ef15f4109a49e18f10a2a297a7e2bfb40f2ee4ed4795ac8fec9dbe6cae2a7878d",
          "sha256": "c187ae8904b6b9eeaba8c98c94ce1ebf611ed2a772c8770f98d3cd8644133287",
          "sha1": "c3045f51755afa9495abdb3ad78fd20fb78a74bf",
          "md5": "a834fe1644cadf5198de36d5cc6dff50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation-compose",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-samples-1.1.0-alpha01.aar",
          "url": "hilt-navigation-compose-samples-1.1.0-alpha01.aar",
          "size": 17025,
          "sha512": "6d4e3721326e211e4b5d9697a1b7879cd0fe7de38d40fa544fb0b0172817fc5ef15f4109a49e18f10a2a297a7e2bfb40f2ee4ed4795ac8fec9dbe6cae2a7878d",
          "sha256": "c187ae8904b6b9eeaba8c98c94ce1ebf611ed2a772c8770f98d3cd8644133287",
          "sha1": "c3045f51755afa9495abdb3ad78fd20fb78a74bf",
          "md5": "a834fe1644cadf5198de36d5cc6dff50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-samples-1.1.0-alpha01-sources.jar",
          "url": "hilt-navigation-compose-samples-1.1.0-alpha01-sources.jar",
          "size": 1898,
          "sha512": "fe6c7dce7abd4d3c1eb75b865777613251f022ac2300881e66f992ec95f78f1a89dc4a85c701be052fd3e797def5c972fb594d91659416f4b2783c5cea7a619e",
          "sha256": "bd73f7cf3cda2b0c1874fbbb1ea062cdb94ba53026a24deb811f9a23c00835a9",
          "sha1": "d3d99092893551b9ed5b1fa4ef8e87adc2897978",
          "md5": "81391181170bdfb31859a4bb5a752d01"
        }
      ]
    }
  ]
}